### ISSUE TITLE
Agenda for Public Core Meeting - 2016-05-26 15:00 UTC

### ISSUE THREAD

**Issue by bcoca** [ansible/community#107]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

**Comment by bcoca** [comment]
lxc connection plugin
https://github.com/ansible/ansible/pull/13145

**Comment by tannerjcghtester1** [comment]
Allowing numeric variable names with set_fact https://github.com/ansible/ansible/issues/16008

**Comment by bcoca** [comment]
Define a framework for getting detailed action feedback from modules (see azure/docker 'actions')

**Comment by bcoca** [comment]
Define 'facts' and create rules to deal with different types of 'info gathering' modules.

**Comment by chouseknecht** [comment]
docker_network module: 

https://github.com/ansible/ansible-modules-core/pull/3728

**Comment by Mic92** [comment]
my irc name is "Mic92" as well
