### ISSUE TITLE
Agenda for Public Core Meeting - 2016-06-07 19:00 UTC

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/community#108]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

**Comment by MichaelBaydoun** [comment]
When creating IAM roles using the IAM module, there is currently no support for trust policies.  Specifying a trust policy is required for cross account role assumption, users of cognito, lambda, etcetera.  https://github.com/ansible/ansible-modules-core/issues/2468

https://github.com/ansible/ansible-modules-core/pull/3264 adds the capability but was closed by submitter in frustration over time delay in merging and dealing with bot.

**Comment by abadger** [comment]
Discuss https://github.com/ansible/ansible-modules-core/issues/3256 What should be done about the name parameter in the cron module.  Requested by  @Leibniz137  It seems like name probably should be required and Ansible only manage cron jobs that have the name/comment string.  However currently the code doesn't require the name and it's unclear why that changed.
