### ISSUE TITLE
Agenda for Public Core Meeting - 2016-06-09 15:00 UTC

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#109]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

**Comment by nitzmahone** [comment]
(bumped from Tuesday's meeting)

Discuss ansible/ansible-modules-core#3256 What should be done about the name parameter in the cron module. Requested by @Leibniz137 It seems like name probably should be required and Ansible only manage cron jobs that have the name/comment string. However currently the code doesn't require the name and it's unclear why that changed.

**Comment by underyx** [comment]
I'd like to discuss whether it makes sense to merge https://github.com/ansible/ansible-modules-core/pull/901 (was briefly merged and then reverted last weekend).

**Comment by robinro** [comment]
I have two topics to discuss:

1. To review/merge: In 2.2 currently git with depth but without version specified does not update repos. This is the documentation-example usage case for ansible-pull
    Fix: https://github.com/ansible/ansible-modules-core/pull/3794
    Test: https://github.com/ansible/ansible/pull/16055 

    The git module is a bit of a mess and there are still some holes in the support of `depth`, see also https://github.com/ansible/ansible-modules-core/issues/3817 (not yet fixed). Maybe one can do a git refactor sprint? I'd be happy to take part if time allows, but am pretty busy the next weeks/months.

2. To discuss: Add `check_mode: yes/no` to tasks. Replaces `always_run` (then `check_mode: no`,  see also https://github.com/ansible/proposals/blob/master/rename_always_run.md by @resmo) and introduces `check_mode: yes` to run a single task in check mode even if this is not requested on the command line.
    PR: https://github.com/ansible/ansible/pull/16056
    Issue: https://github.com/ansible/ansible/issues/12498
    Historical Discussion: https://github.com/ansible/ansible/pull/7439

**Comment by quinot** [comment]
I'd like to touch base on ansible/ansible#11810 (multiple interpreter support): I would like to make sure that there is no pending issue left that prevents merging it.

**Comment by dagwieers** [comment]
A change to the unarchive module (ansible/ansible-modules-core#3575) causes a lot of opened issues related to `extra_opts` and `exclude` options not working. I opened a pull request (ansible/ansible-modules-core#3767) to make a better fix than (ansible/ansible-modules-core#3575) which resulted in some discussion (related to python2 and python3), but in the meantime people keep on complaining.

So I would propose we revert the original commit first (so it works again for the majority of people) and then look for a proper implementation.

Opened issues on unarchive will show a handful: https://github.com/ansible/ansible-modules-core/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20unarchive

**Comment by abadger** [comment]
@dagwieers Why don't we fix the PR?  IIRC the final comments from me are that codecs.escape_decode() seems to work but the PR was never updated to use that instead of string_escape.

**Comment by dagwieers** [comment]
@abadger It wasn't clear to me that we had a final solution, if I had known I wouldn't have it allowed to linger like this (with the frustration of having to tell people that it is in a known broken state).

Let me go back and redo my proposal. Thanks for the update !
