### ISSUE TITLE
Agenda for Public Core Meeting - 2016-07-07 15:00 UTC

### ISSUE THREAD

**Issue by willthames** [ansible/community#111]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

**Comment by willthames** [comment]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

**Comment by willthames** [comment]
* ansible/ansible-modules-core#3025
* ansible/ansible#12904
* ansible/proposals#7

**Comment by jimi-c** [comment]
Topic: Ansible 2.1.1 RC2 (planning release today)
^ if there's a critical bug please bring it up in today's meeting.

**Comment by gundalow** [comment]
A few callback plugins that it would be good to get some feedback on

* https://github.com/ansible/ansible/pull/16491 @to-m callback and strategy plugins for use with integration (and other) 'test' playbooks

And from @dagwieers:

* https://github.com/ansible/ansible/pull/15938
* https://github.com/ansible/ansible/pull/14978
* https://github.com/ansible/ansible/pull/14332

**Comment by Shrews** [comment]
https://github.com/ansible/ansible-modules-core/pull/4051
https://github.com/ansible/ansible/pull/16458  (merged)

**Comment by jimi-c** [comment]
<pre>
[11:35] <zodbot> Meeting ended Thu Jul  7 16:35:20 2016 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[11:35] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2016-07-07/ansible_core_public_meeting.2016-07-07-15.05.html
[11:35] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2016-07-07/ansible_core_public_meeting.2016-07-07-15.05.txt
[11:35] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2016-07-07/ansible_core_public_meeting.2016-07-07-15.05.log.html
</pre>

**Comment by dagwieers** [comment]
Where can I move my PRs to be looked at the next meeting ?
- ansible/ansible#15938  --  _"pyformat" filter plugin to format python-style_
- ansible/ansible#14978  --  _"dense" callback plugin_
- ansible/ansible#14332  --  _"filetree" lookup plugin_
