### ISSUE TITLE
Adding a ‘fake’ loopback alias with the public/elastic IP address:

### ISSUE THREAD

**Issue by maheshwarirohit87** [ansible/community#113]
I have to automate the following command using ansible. I am facing difficulty in doing that. Need help.

- Adding a ‘fake’ loopback alias with the public/elastic IP address:

sudo cat >> /etc/sysconfig/network-scripts/ifcfg-lo\:0 << EOF
DEVICE=lo:0
IPADDR=`curl http://instance-data/latest/meta-data/public-ipv4`
NETMASK=255.255.255.255
ONBOOT=yes
NAME=loopback
EOF

- sudo systemctl restart network

- DNS configuration:

sudo  mv /etc/resolv.conf /etc/resolv.conf.ori
sudo cat >> /etc/resolv.conf << EOF
nameserver xx.xx.xx.xx
EOF

**Comment by gundalow** [comment]
Hi, 
Thanks for your interest in Ansible. 

For general questions please use the Ansible mailing list which can be found at

http://docs.ansible.com/ansible/community.html#i-ve-got-a-question
