### ISSUE TITLE
Planning for Contributor Conference Brooklyn

### ISSUE THREAD

**Issue by gregdek** [ansible/community#115]
It's in roughly nine weeks. Presumably October 10th.

**Comment by gregdek** [comment]
Next up: first draft of an etherpad.

**Comment by gregdek** [comment]
Done. Blog post goes out this week.

**Comment by gundalow** [comment]
Did something get added to etherpad?

**Comment by robynbergeron** [comment]
https://public.etherpad-mozilla.org/p/ansible-summit-october-2016 <-- etherpad here

**Comment by gregdek** [comment]
Blog and email are out.

**Comment by gregdek** [comment]
Next step: refine the session schedule on the etherpad.

**Comment by gregdek** [comment]
Next step: send out a final note to the community for comment next week, and then slot the schedule.

**Comment by gregdek** [comment]
@robynbergeron will work on recap, and then we will close.
