### ISSUE TITLE
Need clearer IRC hailing processes

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#119]
There was a spam-ish bot on IRC the evening of aug. 11 -- I got pinged as the person with ops who had been idle the least amount of time. Would be good to have some sort of obvious place to report or send email or ping someone, and have that documented.

**Comment by gregdek** [comment]
Best place to document is in the topic of the channel. Could be as simple as "Issues? Notify irc@ansible.com".

**Comment by robynbergeron** [comment]
You are, as always, correct... and this is now super obvious to me, lol.

**Comment by gregdek** [comment]
I'm going to close this since we've had several such issues since, and the answer is almost always "someone pings someone with op" and it seems to work very quickly.
