### ISSUE TITLE
Add some basic info to README.md in ansible/community repo

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#12]
Should probably have more than a blank page here. :)

**Comment by robynbergeron** [comment]
Okay. I've started this, working in a fork in my own repo:
https://github.com/robynbergeron/community/blob/master/README.md

Before submitting a PR, though, wanted to share a few thoughts I've had while writing.

Having some back-and-forth in my head about organization of this stuff. Because:
1. We want to have this space because of the reasons that a README.md exists: What is this repository all about, what are the goals, how do I file an issue, etc.
2. We also want some of the things that will presumably live in this space to be easily findable / easy to navigate to. Things like meeting logs, or other future content that may or may not live in this space ("Ansible Best Tools", #5 could be an example).

Also thinking about how to make this space as easy as possible for contributors to contribute to, particularly if we envision things like the aforementioned Ansible Best Tools living here, or other similar content possibilities (newsletter? or who knows what?). Some of those items are great for non-coder contributors to get started with, and I have been reminded WHILE DOING THIS STUFF, as one of those people myself, that doing pull requests can be sort of painful to remember how to do when you don't do them often, even through the web interface.

Is some of this better suited as a wiki page? Even though we know what wiki stands for? (Where information kills itself :D) Even if it's just: Main page, with links to Meetings wiki page with dates / times / link to where / how agenda is set, + link to logs space; $otheransible community thing (again, Best Tools page? or whatever else?), etc, and a strong suggestion to push most content back into docs?

Or: Could readme.md be the above content, and much of *this* readme.md as I've drafted could go into contributing.md? That doesn't seem quite right to me, but not sure.

**Comment by robynbergeron** [comment]
Also, how does https://groups.google.com/d/msg/ansible-devel/7LESbiIE2MY/lqi04fIEAwAJ
(docs/proposal in ansible/ansible) relate here?

**Comment by gregdek** [comment]
I think what I want this to be is "(a) a place to show what we're doing transparently, and (b) a place to ask/provide community help in a structured way where no other repos make sense ." And I think what you've got is pretty close to that.

For ansibull stuff, we just redirect to ansibull.

**Comment by robynbergeron** [comment]
Okay -- PR exists for this as part of #20, because I can't git right. :)

**Comment by robynbergeron** [comment]
#20 is merged, closing this.
