### ISSUE TITLE
Agenda for Public Core Meeting - 2016-09-29 15:00

### ISSUE THREAD

**Issue by gundalow** [ansible/community#126]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your GitHub username, add that as well.

When closing this ticket please create the next one with label `meeting_agenda`

**Comment by dminca** [comment]
I propose for discussion **Ansible compatibility with Manjaro Linux (Arch distros)**, specifically issue https://github.com/ansible/ansible-modules-core/issues/4996

**Comment by ericsysmin** [comment]
How do I join this? It's my first meeting

**Comment by grastogi23** [comment]
I would like to add this to the agenda 
https://github.com/ansible/ansible/pull/17535

**Comment by sgujic** [comment]
Hi, 

I have few questions regarding https://github.com/ansible/ansible-modules-core/issues/4857. 

I plan to help in writing this module but want to get more informations.

My irc username is: crawler

Regards,
Sinisa

**Comment by dminca** [comment]
@ericsysmin details are here https://github.com/ansible/community/blob/master/MEETINGS.md

**Comment by gundalow** [comment]
From @privateip https://github.com/ansible/ansible/pull/17753 We really need this for 2.2

**Comment by Shaps** [comment]
Hi, 

Would be nice to have a way to tell ansibot to label non-bug issues with a specific label

**Comment by gundalow** [comment]
Meeting has finished.

Agenda for next week is https://github.com/ansible/community/issues/127
