### ISSUE TITLE
Standing Agenda, Public Core Meeting Meeting

### ISSUE THREAD

**Issue by gundalow** [ansible/community#132]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by abadger** [comment]
This is carry over from before: https://github.com/ansible/ansible/pull/17768

**Comment by gundalow** [comment]
~~Discussion around how to track and report Python3 status so other people can help~~
@gundalow will setup a Google Spreadsheet and drive it from the Testing Working Group

**Comment by stevekuznetsov** [comment]
Discussion around the API that users can expect with `stdout` callback plugins:
 - can they control `std{out,err}` completely?
 - what can we do about things like https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/helpers.py#L196-L200

Discussion around how to more correctly use the Ansible `Display`:
 - should it be a global object?
 - It cannot remain in `__main__` for Python3 compatibility.
 - why is the following code used? It doesn't make a global if one doesn't exist, it makes a local copy everywhere:

    ```py
    try:
        from __main__ import display
    except ImportError:
        from ansible.utils.display import Display
        display = Display()
    ```

Discussion around how to best make CLI actions programatically reusable -- break out logic that parses user input from the command line entirely and ensure that a user consuming the Ansible CLI to issue actions can generate the correct set of options the need to e.g. run a playbook.

**Comment by samdoran** [comment]
I'd like to discuss changing the examples format in existing modules to use multi-line YAML instead of key value pair shorthand.

I have a [branch](https://github.com/samdoran/ansible-modules-core/commits/examples-syntax-fix) where I've done most of the work for core modules but would like to discuss before submitting the PRs.

**Comment by stevekuznetsov** [comment]
I would like to further discuss publishing versioned documentation on the docs.ansible.com domain. It's seemingly published from devel and very misleading.

**Comment by gundalow** [comment]
I'd like to float the idea of Ansible detecting passing invalid modes to `file:` (etc)
Not sure if by the time we parse that if we can tell if it's a number and if the leading zero has been dropped.

**Comment by Shaps** [comment]
I'd like to discuss https://github.com/ansible/ansible/issues/18325. It seems a good idea to me to add the `SSH_CONTROL_PATH_DIRECTORY`, and remove the hardcoded value

**Comment by gundalow** [comment]
https://github.com/ansible/ansible-modules-core/pull/5388 MySQL Security issue
from WouterOosterveld as something that should go into 2.2

**Comment by abadger** [comment]
Ticket rotated. new ticket: https://github.com/ansible/community/issues/140
