### ISSUE TITLE
Standing Agenda, Public Core Meeting Meeting - November 2016

### ISSUE THREAD

**Issue by abadger** [ansible/community#140]
#Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by abadger** [comment]
From previous agenda ticket, @gundalow: 

I'd like to float the idea of Ansible detecting passing invalid modes to file: (etc)
Not sure if by the time we parse that if we can tell if it's a number and if the leading zero has been dropped.

**Comment by abadger** [comment]
From previous agenda ticket, @gundalow:

https://github.com/ansible/ansible-modules-core/pull/5388 MySQL Security issue
from WouterOosterveld as something that should go into 2.2

Current status: jmainguy and WouterOosterveld are discussing in the ticket.

**Comment by abadger** [comment]
How long to deprecate before removal: https://github.com/ansible/community/issues/139

**Comment by gundalow** [comment]
Fix YAML source and lint it

We already have yamllint (with some rules disabled), do we want to formalise that more?

https://github.com/ansible/ansible/pull/15470

cc @adrienverge @mattclay

**Comment by gundalow** [comment]
Proposal: ansible-config
https://github.com/ansible/proposals/issues/35

**Comment by tannerjcghtestuser4** [comment]
https://github.com/ansible/ansible/pull/18439

**Comment by gundalow** [comment]
Module examples
> < agaffney> I've found 57 instances throughout the source tree of with_(items|dict|indexed_items) and a bare variable

We happy to clear all of those out?
Do we need to add in detection for them?

**Comment by Shaps** [comment]
Discuss implementation of #18501

**Comment by gundalow** [comment]
https://github.com/ansible/community/issues/143
Provides a document with lifecycle of the various releases

Discussed during 2016-11-17 Core meeting
We currently have
* http://docs.ansible.com/ansible/dev_guide/developing_releases.html
*

**Comment by gundalow** [comment]
No Public Core Meeting on Thursday 24th November

**Comment by gundalow** [comment]
From discussion in networktocode.
Can we provide better messages regarding missing dependencies. On a number of occasions users have been confused when told package foo isn't installed when it is. The actual issue being they are running in a virtual env

**Comment by gundalow** [comment]
More details about upcoming repo merge 
Important to review for those looking to contribute to module development https://groups.google.com/forum/#!topic/ansible-project/9WpXraBSLz8

**Comment by jctanner** [comment]
Inability to find modules in subdirectories of "library" has been gaining more and more attention

https://github.com/ansible/ansible/issues/15432

We need to decide if we'll accept a patch or not and then give guidance in the issue or close it.

**Comment by gundalow** [comment]
It's now December so closing this

I've carried over 
1) Can we provide better messages regarding missing dependencies. On a number of occasions users have been confused when told package foo isn't installed when it is. The actual issue being they are running in a virtual env
2) Inability to find modules in subdirectories of "library" has been gaining more and more attention


**MEETING CLOSED**

December's Agenda https://github.com/ansible/community/issues/147
