### ISSUE TITLE
Provides a document with lifecycle of the various releases

### ISSUE THREAD

**Issue by mscherer** [ansible/community#143]
I participated last week at the Centos interlock meeting, which was a meeting between various Centos SIG members and the Centos team. One of the discussion item was to see how we can package Ansible, since there is several SIG providing project using it such as PaaS-SIG with https://github.com/openshift/openshift-ansible/, Storage SIG with https://github.com/gluster/gdeploy and https://github.com/ceph/ceph-ansible , and even used somewhere in RDO.

However, not all of them use the same version of Ansible. Ansible-ceph is for now stuck on 1.9, Openshift-ansible is following Ansible release quite closely (and so is on 2.2), etc.

And so, trying to see if 1.9 was still maintained/supported on irc, I got different answers, and so would propose that we publish a document that would explain for how long will each versions be updated and why ( similar to https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle )

**Comment by dagwieers** [comment]
It would be nice if we could reach out to these projects to see if they can become part of the RC testing team (or something like that). If they are better involved in release candidate testing, maybe they wouldn't be left behind on older releases ?

**Comment by mscherer** [comment]
Yeah, I did pushed for that, so we would get feedback on our RC. I would even push for having tests on a git HEAD snapshot or some workflow (ie, ansible-openshift do test on stable version, then once that's done, a non blocking test for RC/git HEAD would permit for us to detect regression (or see what is broken in the future version).

**Comment by dmsimard** [comment]
It would be great to at least have a formal page with their versions and their status.

For example, [OpenStack](https://www.openstack.org/) does it [this way](https://releases.openstack.org/#release-series):
![alt text](http://i.imgur.com/tdUWYRt.png)

It was only now (to my knowledge) made more or less official that Ansible 1.9.x and Ansible 2.0.x were no longer supported:
https://groups.google.com/forum/#!topic/ansible-devel/6-6FdxZ94kc

> As you've likely heard, Computest.nl reported a security vulnerability to the Ansible Core engineering team and Red Hat Security.  The Ansible Core team has been working hard to fix the issues and has released Release Candidates to the 2.1.x branch and the 2.2.x branches (and devel of course for future releases).
> Traditionally we've only supported the last two major, stable versions although we've often back-ported security fixes beyond the supported versions.  Because of the difficulty of back-porting these fixes we (Ansible Core team and Red Hat) have decided that only versions 2.1.x and newer will get the updates. Ansible 2.0 and older will no longer receive updates.

**Comment by gregdek** [comment]
This is more a product thing that a community thing. cc: @calfonso and @mckerrj for help/advice here.

**Comment by gregdek** [comment]
I do note that we have something in the topic of the IRC channel, to wit:

#ansible Ansible - !search $topic - http://docs.ansible.com * latest releases: 2.3.1.0 / 2.2.3.0 / 2.1.6.0 * 2.3.1 and 2.1.6 FINAL released - https://groups.google.com/forum/#!topic/ansible-announce/i3hsJKuVusQ

...but I dunno if that constitutes anything official.s

**Comment by mckerrj** [comment]
Yes, we've reached out to a number of teams to start testing. I believe other groups have moved up, but we are working with them on these.
