### ISSUE TITLE
Standing Agenda, Public Core Meeting Meeting - December 2016

### ISSUE THREAD

**Issue by gundalow** [ansible/community#147]
#Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by gundalow** [comment]
Carry over from https://github.com/ansible/community/issues/140

From discussion in networktocode.
Can we provide better messages regarding missing dependencies. On a number of occasions users have been confused when told package foo isn't installed when it is. The actual issue being they are running in a virtual env

Can we have a few failure message that returns some extra state, e.g
`self.dependency_fail('junos-eznc >= 1.2.2 is required but does not appear to be installed. It can be installed using 'pip install junos-eznc')`

Would return something along the lines of
`'msg:' 'ERROR: unos-eznc >= 1.2.2 is required but does not appear to be installed. It can be installed using 'pip install junos-eznc'. You are running inside sys.executable`

If agreed we need to update the existing modules (and inventory scripts) as well as developing_modules.html

<b>Update</b> Discussed 29-Nov-2016 No definite conclusion but:
* adding the information sounds good but talk to bcoca about whether we can add it controller-side.
* we'd need to think more about an AnsibleModule method... might want to expand it to make conditional_importing better in general.

**Comment by gundalow** [comment]
Carry over from https://github.com/ansible/community/issues/140

Inability to find modules in subdirectories of "library" has been gaining more and more attention

https://github.com/ansible/ansible/issues/15432

We need to decide if we'll accept a patch or not and then give guidance in the issue or close it.

**Comment by rouge8** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19017

**Comment by megamisan** [comment]
Re-migrated ansible/ansible#19016

**Comment by gunzy83** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19020

**Comment by naslanidis** [comment]
Unfortunately when I migrated he first time the original was deleted so I've had to create a new PR. https://github.com/ansible/ansible/pull/19021

**Comment by bjoernalbers** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19027

**Comment by kevensen** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19029

**Comment by veger** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19042 [postgresql module] and https://github.com/ansible/ansible/pull/19043 [elasticache module]

**Comment by ganeshnalawade** [comment]
Re-migrated PR's
https://github.com/ansible/ansible/pull/19046
https://github.com/ansible/ansible/pull/19038

https://github.com/ansible/ansible/pull/19045

**Comment by aperigault** [comment]
Re-migrated PR #19049

**Comment by robinro** [comment]
One more re-migrated: https://github.com/ansible/ansible/pull/19057

**Comment by robinro** [comment]
How about 3-for-1? 🎁 
I got 2 more small test PRs waiting:
https://github.com/ansible/ansible/pull/18500
https://github.com/ansible/ansible/pull/17898

**Comment by Fale** [comment]
Rebased on the new import:

* https://github.com/ansible/ansible/pull/18823
* https://github.com/ansible/ansible/pull/18824
* https://github.com/ansible/ansible/pull/18825
* https://github.com/ansible/ansible/pull/18826
* https://github.com/ansible/ansible/pull/18827
* https://github.com/ansible/ansible/pull/18828
* https://github.com/ansible/ansible/pull/18829
* https://github.com/ansible/ansible/pull/18830
* https://github.com/ansible/ansible/pull/18831
* https://github.com/ansible/ansible/pull/18832
* https://github.com/ansible/ansible/pull/18834
* https://github.com/ansible/ansible/pull/18836
* https://github.com/ansible/ansible/pull/18837
* https://github.com/ansible/ansible/pull/18840

Re-moved from the old repo:
* https://github.com/ansible/ansible/pull/19053
* https://github.com/ansible/ansible/pull/19054
* https://github.com/ansible/ansible/pull/19055
* https://github.com/ansible/ansible/pull/19056
* https://github.com/ansible/ansible/pull/19058
* https://github.com/ansible/ansible/pull/19059
* https://github.com/ansible/ansible/pull/19060
* https://github.com/ansible/ansible/pull/19061
* https://github.com/ansible/ansible/pull/19062
* https://github.com/ansible/ansible/pull/19063

**Comment by ilpianista** [comment]
Re-moved ansible/ansible#19070

**Comment by gundalow** [comment]
From @dagwieers
> [13:48] <dag-> BTW can we introduce a Regression issue/PR type ?
> [13:49] <dag-> this type of issue/PR could be looked at when evaluating the stable-branch(es)

**Comment by vaygr** [comment]
Re-migrated: https://github.com/ansible/ansible/pull/19072

**Comment by imuchnik** [comment]
Re-migrated https://github.com/ansible/ansible/pull/19096

**Comment by abadger** [comment]
From @dagwieers to make master an alais for devel in the git repo:  https://github.com/ansible/proposals/issues/43

**Comment by akatch** [comment]
Community thoughts on adding a documentation bot to the `#ansible` IRC channel
- `raktajino`

**Comment by nitzmahone** [comment]
Discuss module file layout/category metadata: https://github.com/ansible/proposals/issues/46

**Comment by mattclay** [comment]
Discuss optional static type checking and type hints in Ansible: https://github.com/ansible/proposals/issues/44

**Comment by gundalow** [comment]
No more meetings in December.

Next Public Core meeting will be 3rd of Jan.

New Agenda https://github.com/ansible/community/issues/148
