### ISSUE TITLE
Standing Agenda, Public Core Meeting Meeting - February 2017

### ISSUE THREAD

**Issue by abadger** [ansible/community#150]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by abadger** [comment]
Re-migrated ansible/ansible#19016
* From 12/13 meeting: currently waiting for JMainguy to have a chance to look.
* From 2/2 meeting: Waiting on one documentation change from submitter then ready to merge

**Comment by abadger** [comment]
Re-moved ansible/ansible#19070 win_file: fix error when creating an existing dir
* nitzmahone has this on his list.

**Comment by abadger** [comment]
ansible/ansible#15432 "Ansible 2.0 no longer finds modules in library subdirectories"
* [Decision:](https://github.com/ansible/community/issues/148#issuecomment-270201815) to document ANSIBLE_LIBRARY as the official way to achieve this functionality.
* abadger: Documentation is part of this PR: ansible/ansible#20913

**Comment by abadger** [comment]
Discuss extending the module "shipit" workflow to non-modules, such as:
- lib/ansible/plugins
- lib/ansible/module_utils
- contrib/inventory

** Update 12 Jan 2017 Meeting **
* All approved.  We'll start with contrib/inventory as most of those are community maintained as it is.  * * Will come up with a list of dynamic inventory proposed metadata for next week.

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/19500 Update assemble to allow alternate source of files
* jan 5 meeting: Discussion lead to question of whether an alternate source of files is desirable for assemble.  itdependsnetworks  was pro and bcoca was con.
  * Everyone was okay with the subset of giving assemble a way to customize sorting (but haven't figured out implementation that is limited to this).
* 2 Feb meeting: Submitter doesn't want to truncate this particular PR to only be about sorting so we need to decide on the features that are present in the PR.  We talked briefly about whether template includes can do the work that assemble src_files does and seemed like it could.  We think we've gotten all the input we can so we started voting among the committers to decide whether to accept or reject:
  * -1 bcoca, abadger
  * +0 ryansb jctanner
  * +1 alikins
Right now the decision could be weighted by which committers were attending the meeting so we'll ask for more votes next meeting before making a decision.

**Comment by abadger** [comment]
feature proposal: https://github.com/ansible/ansible/pull/19707  (enhanced rolling updates)
* Jan 10 meeting: bcoca was for a sorting and grouping of hosts independent of serial.
  * Some flaws in the implementation were pointed out.
  * more discussion happening in ticket.  To be discussed more in this meeting if the ticket discussion gets stuck.
* Jan 31 meeting: podlesh has some examples of use case that don't seem to be solvable by merely enhancing sorting and grouping  independent of serial.  bcoca and jimi-c not present.  Will discuss at meeting feb 6

**Comment by abadger** [comment]
From @jtyr: https://github.com/ansible/ansible/pull/19283  hosts module (for /etc/hosts)
* 2 Feb meeting: All issues that are solvable by code resolved.
  * Need to make a decision on whether this overlaps too much with existing modules/roles.  Will discuss and probably call for a vote on Tuesday (7-Feb) meeting

**Comment by abadger** [comment]
From  luto: https://github.com/ansible/ansible/pull/19297 Fix for wildcards inside of a path for fileglob lookup (ie: ```with_fileglob: "/tmp/*/some.conf"```)
* 24 Jan Meeting:  bcoca had two observations which need to be considered as the code is reviewed:
  * (1) bcoca: dwim code always needs careful consideration because it can break a lot of things and isn't always obvious why it's doing things.
    * Submitter (rupran) says: "what it basically does is factor out a part of path_dwim_relative_stack (leaving the functionality untouched) to use it in with_fileglob"
  * (2) bcoca: lookups should use same function, once you start diverting them they become unpredictable but just on consistency with lookups, not happy to duplicate and modify functionality

**Comment by abadger** [comment]
From bcoca: Decide which are valid directives on include (for execution or inheritance) and what to do when we decide they are not.  This issue deals with one case, but i think we should deal with it in general https://github.com/ansible/ansible/issues/20440

**Comment by abadger** [comment]
From rfleschenberg versioned docs
Summarizing [previous discussion](https://github.com/ansible/community/issues/148#issuecomment-274906303)
* Versioning approved.  dharmabumstead and gundalow working on proposal here https://public.etherpad-mozilla.org/p/ansible-versioned_docs

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/20058 Add systemd-nspawn connection driver

* 31 Jan: reviewed by abadger, waiting on submitter to fix up

**Comment by bcoca** [comment]
define and document proposals process i.e https://github.com/ansible/proposals/issues/50 was created and 'agreed' to immediately, w/o giving time for community feedback, which is happening now after implementation.

**Comment by jtyr** [comment]
@bcoca Yeah, such process would be really useful because I'm not happy about the result of the Proposal #50 at all ;o(

**Comment by bcoca** [comment]
@jtyr this is not a revision on that decision (I suggest you open your own agenda item for that) but on the process that should be followed on proposals and the time needed to allow for community feedback.

**Comment by mattclay** [comment]
https://github.com/ansible/ansible/pull/13206

This PR was discussed at length internally and we couldn't come to an agreement one way or another, so putting it on the agenda for wider discussion. I'll try to summarize some of the key points of the discussion here:

- environment variables are not a secure place for secrets, use a file with proper permissions
- standard practice on many CI systems is to expose credentials in environment variables
- having the feature would encourage misuse (use in situations other than CI systems)
- if the feature is supported, a runtime warning should be given which can't be disabled
- the feature isn't needed (see work-around provided in the PR comments)
- lack of the feature may increase chances of logging the password (bash -x), CI artifacts

Apologies if I missed any key points from the discussion, it ran over the course of ~1 hour.

**Comment by abadger** [comment]
Minuites for today's meeting: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-07/ansible_core_meeting.2017-02-07-19.00.html

**Comment by thaumos** [comment]
I'd like to discuss [ansible/ansible#19264](https://github.com/ansible/ansible/pull/19264).

**Comment by albertomurillo** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/20834
my irc nick is `albertom`

**Comment by jtyr** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/20703

**Comment by gundalow** [comment]
2017-02-09

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-09/ansible_core_meeting.2017-02-09-15.00.html
https://meetbot.fedoraproject.org/ansible-meeting/2017-02-09/ansible_core_meeting.2017-02-09-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-09/ansible_core_meeting.2017-02-09-15.00.log.html

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/issues/18453

How do we:
1. Update the requirements in documentation
2. Prevent future desync between setup.py and docs

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/21299

**Comment by gundalow** [comment]
2017-02-14

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-14/ansible_core_meeting.2017-02-14-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-02-14/ansible_core_meeting.2017-02-14-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-14/ansible_core_meeting.2017-02-14-19.00.log.html

**Comment by dagwieers** [comment]
Can we merge **wait_for_connection** action plugin ? #20011

**Comment by ryansb** [comment]
Facts modules not using `ansible_fact` argument to `exit_json` https://github.com/ansible/ansible/pull/19910#issuecomment-278496104

**Comment by dagwieers** [comment]
How to get this going: ansible/community#152 ?

**Comment by gundalow** [comment]
**2017-02-16**

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-16/ansible_core_meeting.2017-02-16-15.00.html
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-02-16/ansible_core_meeting.2017-02-16-15.00.log.html

**Comment by enunez-cyberark** [comment]
I would like to discuss [ansible/ansible/21764](https://github.com/ansible/ansible/pull/21764)

IRC nickname is enunez-cyberark

**Comment by jhawkesworth** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/20405, specifically to see if we can reach an agreement about the copy action plugin behavior.  Would adding an optional 'check_method' parameter be acceptable.  Or is there a better way to solve this problem?

**Comment by gundalow** [comment]
Ansible Core 2.1.5RC1 and 2.2.2RC1 are available for testing
https://groups.google.com/forum/#!topic/ansible-devel/VnHIVtzuyzs

**Comment by ryansb** [comment]
I'd like to discuss https://github.com/ansible/proposals/issues/14 

IRC nick == ryansb

**Comment by mikedlr** [comment]
I would like to discuss 
* merging [aws_api_gateway](https://github.com/ansible/ansible/pull/20230)
* * status - more or less ready for an initial merge / somewhat limited functionality
* merging [lambda_policy](https://github.com/ansible/ansible/pull/20890)
* * status - had initial feedback ; about to start making fixes
* * interested in comments on [other related models](https://github.com/pjodouin/ansible-lambda/tree/master/modules)
* improving other aws modules in particular
* * getting RDS module to use boto3 / support SSD

**Comment by dagwieers** [comment]
I would like to discuss what the process is when
- Original module author not responding to PRs (i.e. authors possibly left community)
- Assign new module maintainers to an existing module

**Comment by dagwieers** [comment]
I think a new discussion is in order on how to tackle the "modules are used for adding, changing, removing and giving information about an object".

Discussion triggered by: https://github.com/ansible/ansible/pull/20399#pullrequestreview-18432297

We have modules that allow state=list (or state=info), other (sets of) modules have _facts variants and here the contributor was requested to leave it out and assume that an undefined "state" means not making changes but returning information.

**Comment by dagwieers** [comment]
Related to https://github.com/ansible/ansible/pull/21874 we disabled the standard expanduser/expandvars in a lot of internal module_utils functions. And it appeared that (at least) none of the integration tests rely on this specific expanding of user/vars of paths. Since we usually expand directly as part of processing parameters, it seems we don't actually need this on different levels (and in the case of unarchive in this specific case it was undesirable and potentially a security problem).

The question being: can we get rid of these expanduser/expandvars calls here ? And if so, what's the process to get it done.

**Comment by abadger** [comment]
Update to the metadata format: https://github.com/ansible/proposals/issues/54

Want to update the metadata format prior to 2.3 to get rid of some warts that have been identified post-implementation.

**Comment by gundalow** [comment]
Open items have been moved to March's agenda https://github.com/ansible/community/issues/156
Windows Community is up and running, please see https://github.com/ansible/community/issues/153
