### ISSUE TITLE
Document IRC Meeting Duties

### ISSUE THREAD

**Issue by abadger** [ansible/community#151]
Need to document IRC meeting duties and then figure out some way to assign them out.  Here's what I could come up with as I wrapped up today's meeting:

IRC Meeting duties:

== Overall notes ==

* We keep each item as a separate comment on the standing agenda ticket.
* As items are worked on, we update status by adding more status information to each comment.
* When an item is complete, we use <strike></strike> to cross it off and add a short message about the resolution.

== Roles ==
* Anyone => Anyone that has commit in the ansible/proposals repository
* Meeting leader

== Before meeting ==

* [Anyone] Go through items on the agenda.  Cross off things that were resolved over the course of the week so they don't take meeting time
* [Meeting leader] Go through items and decide if there's things that should either be sure to be discussed or cannot be discussed.  This lets you switch between topics and manage the meeting time more effectively.

== During Meeting ==

* [Meeting leader] Start the meeting on time :-)
* [Meeting leader] Chair people and ping people wh9o haven't shown up

* [Anyone chaired] Use #info, #agreed, and #action to record important information
* [Meeting leader] Keep the discussion flowing by summarizing main points, identifying points of conflict, and keeping an eye out for ideas that can be turned into a proposal
* [Meeting leader] Keep track of time and ask if people want to keep discussing every once in a while.
* [Meeting leader] Try to end discussions with a decision or an action.  Discussions that don't have at least an #action probably won't see any progress until the next meeting time.

* [Meeting leader] End the meeting or make sure someone is #chair 'd that will end the meeting

== After meeting ==

* [Anyone] Add link to the html meeting Minutes to the agenda ticket
* [Anyone] Process items discussed
  * Add a summary of what was discussed/decided to each item.
  * If the item is completed, cross off all previous information and leave a short note about the resolution.

* [Anyone] Once a month, create a new agenda ticket
  * Create a new ticket.  copy and paste the initial meeting comment from the old ticket in.  Title it similarly.  Add the "meeting_agenda" label to the ticket.
  * Go through the old ticket and copy items which are unresolved to a new ticket.  CC submitters of the item.

**Comment by abadger** [comment]
@gundalow I think this might go somewhere in the dev_guide (for now..)  It's "Project Documentation" [in some ways like the Module Checklist, definitely akin to things that are about contributing to ansible itself.]

**Comment by gundalow** [comment]
Thanks for this write up. I'll give it some more thought tomorrow and add some notes.

**Comment by gregdek** [comment]
So I think this is probably a general "how to run a meeting document" somewhere in the new SIG infrastructure. "How to run a SIG" is probably a good thing to document.

**Comment by gregdek** [comment]
We'll cover this in #164, in fact.
