### ISSUE TITLE
Ansible-Windows meetings, action-plan and cleanups

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#152]
I would like to have a weekly meeting wrt. everything specific to Windows, so that people with an interest in Ansible-Windows are more involved or can track overall progress. (I listed a few of them that are very active recently below)

Things I have roughly listed before:
- Cleaning up the existing Windows modules, so that they all
    - have integration tests
    - ~conform to a certain standard (i.e. using Get-AnsibleParam, -type, Expand-Environment)~
    - are idempotent, implement check-mode ansible/ansible#20781 and diff support where possible
- Select a reference Windows module ansible/ansible#20505
- Improve the existing documentation ansible/ansible#16243 ansible/ansible#17311 ansible/ansible#19623 ansible/ansible#20696 ansible/ansible#21128
   - compare feature-completeness between win_ modules and their python variant
- Improvements to ConfigureRemoteingForAnsible.ps1 ansible/ansible#10509 ansible/ansible#14387 ansible/ansible#17378
- Decide what to do wrt. group policies (not sure what the use-cases are here)
- Decide what to do with functional lists of registry keys (i.e. some have been proposed as modules https://github.com/ansible/ansible/pull/20992#issuecomment-277385149)
- List the missing functionality and status:
    - ~Pipelining support~ ansible/ansible#21510
    - ~Become support~ ansible/ansible#21510
    - Missing modules nice-to-have: 
- Implement native newline sequence for win_template ansible/ansible#21846
- Issue/PR triage (lots of bugs are waiting for feedback or PRs for review)
    - Open PRs: 
        - [Repository ansible/ansible](https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Awindows)
        - [Repository ansible/ansible-modules-core](https://github.com/ansible/ansible-modules-core/pulls?q=is%3Aopen+is%3Apr+label%3Awindows)
        - [Repository ansible/ansible-modules-extras](https://github.com/ansible/ansible-modules-extras/pulls?q=is%3Aopen+is%3Apr+label%3Awindows)
    - Open issues:
        - [Repository ansible/ansible](https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Awindows)
        - [Repository ansible/ansible-modules-core](https://github.com/ansible/ansible-modules-core/issues?q=is%3Aopen+is%3Aissue+label%3Awindows)
        - [Repository ansible/ansible-modules-extras](https://github.com/ansible/ansible-modules-extras/issues?q=is%3Aopen+is%3Aissue+label%3Awindows)
- Running Ansible on Windows (WSL) as control master
- Using SSH as a transport for Windows

cc: @nitzmahone @jhawkesworth @trondhindenes @jborean93 @JimFicarra @cchurch @daBONDi

**Comment by nitzmahone** [comment]
@jhawkesworth, @trondhindenes and I had sorta agreed we needed to start doing this after a contributor conference awhile back, but I dropped the ball on officially organizing it. Would be good to have more interactive/democratic planning of the roadmaps and stuff, especially if others are willing to sign to do stuff.

Timezones are definitely an issue... Monday or Tuesday @ 1600 UTC is probably the sanest time to hit the most people in this group (except @jborean93, unless he's a serious night-owl). Need to make sure we pick a day where we're not clobbering other IRC meetings (or where they're likely to run long and prevent us from meeting).

**Comment by jborean93** [comment]
I'm definitely not that much of a night owl unfortunately, happy to help contribute any way I can/share some ideas.

**Comment by gundalow** [comment]
Just found this tool which may help. Not sure what timezone everyone is in. 

https://www.timeanddate.com/worldclock/meetingtime.html?day=14&month=2&year=2017&p1=47&p2=202&p3=16&iv=0

What hours do people work?

**Comment by jborean93** [comment]
I'm usually 8-5 give or take depending on the day in GMT+10

**Comment by gundalow** [comment]
We also have `#ansible-meeting-2` registered on Freenode,  which also has meetingbot running,  so you can run meeting there. 
So you could overlap with Network Meeting if that's a better time, or possibly Testing Working Group. 

May be best not to overlap with the Core meetings.

**Comment by trondhindenes** [comment]
I'd be up for this. I'm on Europe-time but wouldn't mind doing the meeting during the US folks' business hrs.

**Comment by jhawkesworth** [comment]
I can't commit to a regular meeting at the moment due to stuff.
I'm on UTC although I'm largely restricted to doing ansible things out of hours but will try and take part if I'm awake.

I had some (fairly incoherent) thoughts about other stuff that we might want to talk about and put them on this etherpad here. https://public.etherpad-mozilla.org/p/Ansible_Windows_Community_Plan - feel free to comment or add stuff there.

**Comment by gundalow** [comment]
How to setup a meeting
* Pick time
* Create agenda issue & add `meeting_agenda` label
* Update Google Calendar and update https://raw.githubusercontent.com/ansible/community/master/ansible_community_meetings.ics (ask @mattclay for help)
* Update https://github.com/ansible/community/blob/master/MEETINGS.md
* Announce on -devel -project and https://github.com/ansible/community/issues/150

Use `#info`, `#action` a lot in the meeting

**Comment by JimFicarra** [comment]
Thank you for considering me as part of this effort!  I am very interested in participating, however  I will need to clear my participation with my employer before I can commit.

**Comment by daBONDi** [comment]
When the next meeting will happening ? could not find anything on the calender?
I'm also quite interested in helping out..

**Comment by jhawkesworth** [comment]
@daBONDi - I don't think anything has been scheduled yet.
If you have time to help out, there are lots of modules and module changes that could do with being reviewed and tested.  Search on this page https://ansible.sivel.net/pr/byfile.html for anything with 'win_' and click through to the pull requests to see if there's anything you are interested in trying out.  There's some generic advice here on testing pull requests - http://docs.ansible.com/ansible/dev_guide/developing_test_pr.html - many thanks for any time you can spare.  Jon

**Comment by gundalow** [comment]
@fdaBONDi where in the world are you? Also are you on Freenode IRC, if so, what's your name there.

**Comment by dagwieers** [comment]
@jhawkesworth Now that @ansibot is doing a lot of work for us, this link is probably easier to use: https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Awindows

**Comment by daBONDi** [comment]
@gundalow will stick on "#ansible" in Freenode , mostly evenings arround ~20:00 UTC

**Comment by dagwieers** [comment]
@nitzmahone Can you communicate date/time for these meetings ? As discussed in the core meeting, maybe use a different day/time every other week so all timezones are represented.

There's still a lot to do to improve Windows support for v2.3. Time to get things listed and prioritized !

**Comment by nitzmahone** [comment]
Yep, scheduled. I've got some travel for an Ansible event next week, so we're starting the following week. 

https://github.com/ansible/community/blob/master/MEETINGS.md#tuesdays
https://github.com/ansible/community/blob/master/MEETINGS.md#fridays

We can do one more adhoc sometime this week or Monday next week if we want to talk 2.3 stuff...
