### ISSUE TITLE
How to developt a configuration for Juniper Router

### ISSUE THREAD

**Issue by minhdatvnpt** [ansible/community#155]
Hi all,
  I'm a newbie on this sector, 
I want to use ansible (run on Ubunto platform) to mange and configurate Juniper Router.
But now I have some troubles about creat the playbook to configure Juniper Router.
I know the infrastructure of playbook, but I can't image about a playbook's juniper router configuration.
Some one can address and give me a example!
Thanks advance!

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
