### ISSUE TITLE
Public Core Meeting Meeting - March 2017

### ISSUE THREAD

**Issue by gundalow** [ansible/community#156]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by gundalow** [comment]
Discuss extending the module "shipit" workflow to non-modules, such as:
- lib/ansible/plugins
- lib/ansible/module_utils
- contrib/inventory

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277025899

**Update 12 Jan 2017 Meeting**
* All approved.  We'll start with contrib/inventory as most of those are community maintained as it is.
  * Will come up with a list of dynamic inventory proposed metadata for next week. 
  * bcoca created spreadsheet; will update us on status.

**Update 9th Feb 2017 Meeting**
For contrib/inventory
* Spreadsheet exists
* bcoca to speak with @abadger  to find out how we add python metadata to config files
* bcoca to organise meeting (internally?) to vote and get metadata agreed

**Feb 21 Meeting**
* For dyn inventory config files, abadger proposes that the config files use the asociated script's metadata.
  * Note: There are both yml and ini config files.  Need to make sure both are handled by the metadata code.
  * ryansb  will rename the one outlier, consul.ini to consul_io.ini to match with the script consul_io.py. (code will look for both file names for backwards compat)

**Comment by gundalow** [comment]
From  luto: https://github.com/ansible/ansible/pull/19297 Fix for wildcards inside of a path for fileglob lookup (ie: ```with_fileglob: "/tmp/*/some.conf"```)

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277029768

* 24 Jan Meeting:  bcoca had two observations which need to be considered as the code is reviewed:
  * (1) bcoca: dwim code always needs careful consideration because it can break a lot of things and isn't always obvious why it's doing things.
    * Submitter (rupran) says: "what it basically does is factor out a part of path_dwim_relative_stack (leaving the functionality untouched) to use it in with_fileglob"
  * (2) bcoca: lookups should use same function, once you start diverting them they become unpredictable but just on consistency with lookups, not happy to duplicate and modify functionality
* 9 Feb: @bcoca to review
* 21 Feb: Still on @bcoca's radar to review

**Comment by gundalow** [comment]
From bcoca: Decide which are valid directives on include (for execution or inheritance) and what to do when we decide they are not.  This issue deals with one case, but i think we should deal with it in general https://github.com/ansible/ansible/issues/20440

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277030715
also document once decided so users KNOW what to expect

* 9 Feb Lots of discussion; https://meetbot.fedoraproject.org/ansible-meeting/2017-02-09/ansible_core_meeting.2017-02-09-15.00.log.html
  * Need to document, need to add tests to defend that order

**Comment by gundalow** [comment]
From rfleschenberg versioned docs

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277058347

Summarizing [previous discussion](https://github.com/ansible/community/issues/148#issuecomment-274906303)
* Versioning approved.  dharmabumstead and gundalow working on proposal here https://public.etherpad-mozilla.org/p/ansible-versioned_docs

**Comment by gundalow** [comment]
Define and document proposals process i.e https://github.com/ansible/proposals/issues/50 was created and 'agreed' to immediately, w/o giving time for community feedback, which is happening now after implementation.

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277304534

We might need to review/update this:
https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

**7 Feb Meeting**

Discussed at the meeting.  Many problems with the meta-proposal for creating proposals were discussed.  Minimum timeframes were proposed but no agreement could be come to.  Proposal documenting the new proposal process was asked for.

**14 Feb Meeting**

* ACTION: `allanice001` has kindly offered to raise a PR to update `proposals_process_proposal.md`
 * In the future we can look at moving this under docs.ansible.com/ansible/NEWDIR/process_proposal.html , Details about our release process, proposal process, etc will go there, rather than under dev_guide. Need to bikeshed a name. This is something for after Ansible 2.3 is released.

**Comment by gundalow** [comment]
https://github.com/ansible/proposals/issues/14 Proposal: Module Rename Lifecycle
from ryansb
Migrated from https://github.com/ansible/community/issues/150#issuecomment-282010701

**Comment by gundalow** [comment]
I think a new discussion is in order on how to tackle the "modules are used for adding, changing, removing and giving information about an object".

Discussion triggered by: https://github.com/ansible/ansible/pull/20399#pullrequestreview-18432297

We have modules that allow state=list (or state=info), other (sets of) modules have _facts or _stat variants and here the contributor was requested to leave it out and assume that an undefined "state" means returning information, rather than making changes.

Migrated from: https://github.com/ansible/community/issues/150#issuecomment-282733423

**Comment by gundalow** [comment]
Related to https://github.com/ansible/ansible/pull/21874 we disabled the standard expanduser/expandvars in a lot of internal module_utils functions. And it appeared that (at least) none of the integration tests rely on this specific expanding of user/vars of paths. Since we usually expand directly as part of processing parameters, it seems we don't actually need this on different levels (and in the case of unarchive in this specific case it was undesirable and potentially a security problem). (dag)

The question being: can we get rid of these expanduser/expandvars calls here ? And if so, what's the process to get it done.

Migrated from https://github.com/ansible/community/issues/150#issuecomment-282736510

**Comment by gundalow** [comment]
Update to the metadata format: https://github.com/ansible/proposals/issues/54

Want to update the metadata format prior to 2.3 to get rid of some warts that have been identified post-implementation. (Toshio)

Migrated from https://github.com/ansible/community/issues/150#issuecomment-283077592

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/13758 moved README.md to README.rst

Should we also do this for CHANGELOG.md, having headings and TOC would make that a lot more readable

**Comment by abadger** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-03-07/core_team_meeting.2017-03-07-19.11.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-03-07/core_team_meeting.2017-03-07-19.11.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-03-07/core_team_meeting.2017-03-07-19.11.log.html

**Comment by bcoca** [comment]
How should paths work?
https://github.com/ansible/ansible/pull/22546

**Comment by bcoca** [comment]
do we call them directives, attributes, keywords, etc?
https://github.com/ansible/ansible/pull/22524

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/58

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/22796

**Comment by bcoca** [comment]
expand doc fields
https://github.com/ansible/proposals/issues/58

**Comment by bcoca** [comment]
from open floor, by jtanner:
core/extras repo leftover open ticket handling
meeting notes 2017-03-21:
Proposal 1: Migrate Issues from the module repos to the ansible/ansible repo ( +1 x3, -1 x1 = +2)
Proposal 2: Add Comment to PRs that an interested party needs to use the tool to migrate them to ansible/ansible and then lock (+1 x4 = 4)

**Comment by allanice001** [comment]
For review: https://github.com/ansible/proposals/pull/59

**Comment by gregdek** [comment]
Issues: +1 to close after new automated notice to migrate.
PRs: +1 to the proposal.

**Comment by bcoca** [comment]
** 2017-03-23:**
[12:55] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-03-23/core-team-meeting.2017-03-23-15.01.html
[12:55] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-03-23/core-team-meeting.2017-03-23-15.01.txt
[12:55] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-03-23/core-team-meeting.2017-03-23-15.01.log.html

**Comment by gundalow** [comment]
Ansible 2.3 RC2 has been releases, Please test and report issues via https://github.com/ansible/ansible/issues/new
https://groups.google.com/forum/#!topic/ansible-devel/cmYsumCc4kA

**Comment by sivel** [comment]
As a comment to the markdown to reStructuredText, it was mentioned in the meeting that all files should be converted.  This should not apply to the `ticket_stubs`, as they are meant for copy/paste into comment fields, and GitHub doesn't support rst comments, only markdown.  The same likely goes for the ticket templates.

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/issues/16832

**Comment by bcoca** [comment]
Now that we support docs for many more plugin types, should we require all new plugins of those types to have docs included?

**Comment by gundalow** [comment]
Ansible 2.3 RC3 has been released https://groups.google.com/forum/#!topic/ansible-devel/X8sYLl-ZuTY

We welcome your feedback, after all, we can only fix what we know is broken. If you spot any issues please raise via https://github.com/ansible/ansible/issues/new

Thanks again for your help

**Comment by mattclay** [comment]
https://github.com/ansible/ansible/pull/9563 (Adding nested dictionary lookups) - Do we want to accept this PR?

NOTE: Tests were passing until more strict checks were added recently. Docs will need to be updated to reference the 2.4 release instead of 2.2.

**Comment by bmildren** [comment]
Hi all, I'm trying to find how to progress this PR past community review, and it was suggested I add it here as an item to discuss.. https://github.com/ansible/ansible/pull/19872

(my irc handle is productiondba)

**Comment by gundalow** [comment]
As we are in April we've rolled over to a new agenda.

Any open items have been carried over

https://github.com/ansible/community/issues/159
