### ISSUE TITLE
Unable to use the module to query Vmware host

### ISSUE THREAD

**Issue by alstarian** [ansible/community#157]
Hi Guys,

For the most part I have got anisble almost working to talk to my Esxi host. I have created my playbook to use the module "vmware_get_facts" but when I run my "ansible-playbook vmware.yml" file I get the error 

**"FAILED! => {"changed": false, "failed": true, "msg": "pyvmomi is required for this module"}
 [WARNING]: Could not create retry file '/etc/ansible/playbooks/vmware.retry'.         [Errno 13] Permission denied: u'/etc/ansible/playbooks/vmware.retry'"**

My python version is 2.7 and I have installed the PyVmomi module using pip install pyvmomi and then pip install --upgrade pyvmomi, however i still get the error which says the module isnt installed? (wierd).
I have gotten past all the authentication errors but sadly stuck on this...

Any ideas?!

-A

**Comment by jctanner** [comment]
@alstarian this repository is for tracking community related items like proposals and workflows. Please file an issue in https://github.com/ansible/ansible/issues or on the ansible-project mailing list if you have technical problems with ansible.
