### ISSUE TITLE
Getting issue

### ISSUE THREAD

**Issue by psantosh12** [ansible/community#158]
Hello All,

Issue: 
{"changed": false, "failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE"}

I have created one AWS instance using ansible code and stored in one variable. I am trying to install softwares in that newly provided instance but giving the above issue.

Please help me to resolve the issue.

Note:  I am able to connect that new instance 

Regards,
Santosh

**Comment by psantosh12** [comment]
I have ran the playbook using -vvv option and provided detailed error

Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<52.64.160.24> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.64.160.24> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o StrictHostKeyChecking=no -o 'IdentityFile="/home/ubuntu/My_Code/vmhostkey.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/tmp/%h-%p-%r 52.64.160.24 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ncoehnqztxinutpuewuujbnsoehazdbo; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [52.64.160.24]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "setup"
    },
    "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"

**Comment by jctanner** [comment]
@psantosh12 issues for ansible need to be filed in https://github.com/ansible/ansible 

This repo is for tracking community meeting agenda items.

**Comment by psantosh12** [comment]
What is the solution for that error
