### ISSUE TITLE
Public Core Meeting Meeting - April, May 2017

### ISSUE THREAD

**Issue by gundalow** [ansible/community#159]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by gundalow** [comment]
Discuss extending the module "shipit" workflow to non-modules, such as:
- lib/ansible/plugins
- lib/ansible/module_utils
- contrib/inventory

Migrated from
* https://github.com/ansible/community/issues/150#issuecomment-277025899
* https://github.com/ansible/community/issues/156#issuecomment-283631658

**Update 12 Jan 2017 Meeting**
* All approved.  We'll start with contrib/inventory as most of those are community maintained as it is.
  * Will come up with a list of dynamic inventory proposed metadata for next week. 
  * bcoca created spreadsheet; will update us on status.

**Update 9th Feb 2017 Meeting**
For contrib/inventory
* Spreadsheet exists
* bcoca to speak with @abadger  to find out how we add python metadata to config files
* bcoca to organise meeting (internally?) to vote and get metadata agreed

**Feb 21 Meeting**
* For dyn inventory config files, abadger proposes that the config files use the asociated script's metadata.
  * Note: There are both yml and ini config files.  Need to make sure both are handled by the metadata code.
  * ~~ryansb  will rename the one outlier, consul.ini to consul_io.ini to match with the script consul_io.py. (code will look for both file names for backwards compat)~~ Completed
 
**Mar 2 Meeting**
* Nothing new to discuss while we wait on module metadata to be reworked.

**Mar 14**
* Metadata rework is done.

**2017-03-23**
 jtanner to evaluate and write bot workflow for non-module shipits
tracked in https://github.com/ansible/ansibullbot/issues/437
need more info on what 'rework is done' means

**Comment by gundalow** [comment]
From  luto: https://github.com/ansible/ansible/pull/19297 Fix for wildcards inside of a path for fileglob lookup (ie: ```with_fileglob: "/tmp/*/some.conf"```)

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277029768

* 24 Jan Meeting:  bcoca had two observations which need to be considered as the code is reviewed:
  * (1) bcoca: dwim code always needs careful consideration because it can break a lot of things and isn't always obvious why it's doing things.
    * Submitter (rupran) says: "what it basically does is factor out a part of path_dwim_relative_stack (leaving the functionality untouched) to use it in with_fileglob"
  * (2) bcoca: lookups should use same function, once you start diverting them they become unpredictable but just on consistency with lookups, not happy to duplicate and modify functionality
* 9 Feb: @bcoca to review
* 21 Feb: Still on @bcoca's radar to review
* 2 Mar:  Still on @bcoca's radar to review
* 7 Mar: Recently rebased.  Still on bcoca's radar.

**Comment by gundalow** [comment]
Define and document proposals process i.e https://github.com/ansible/proposals/issues/50 was created and 'agreed' to immediately, w/o giving time for community feedback, which is happening now after implementation.

Migrated from https://github.com/ansible/community/issues/150#issuecomment-277304534

We might need to review/update this:
https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

**7 Feb Meeting**

Discussed at the meeting.  Many problems with the meta-proposal for creating proposals were discussed.  Minimum timeframes were proposed but no agreement could be come to.  Proposal documenting the new proposal process was asked for.

**14 Feb Meeting**

* ACTION: `allanice001` has kindly offered to raise a PR to update `proposals_process_proposal.md`
 * In the future we can look at moving this under docs.ansible.com/ansible/NEWDIR/process_proposal.html , Details about our release process, proposal process, etc will go there, rather than under dev_guide. Need to bikeshed a name. This is something for after Ansible 2.3 is released.

**2 Mar Meeting**

* No updates from `allanice001`. Still waiting on PR to update proposal.

**2017-03-23**
reviewed: https://github.com/ansible/proposals/pull/59
no consensus, some feedback (see meeting notes) to be posted on ticket.

**Comment by gundalow** [comment]
How should paths work?
https://github.com/ansible/ansible/pull/22546

**Comment by gundalow** [comment]
expand doc fields
https://github.com/ansible/proposals/issues/58

**2017-03-21:**
types +1 as long as they are strict list
config: @bcoca to provide more examples as it seems to overlap with existing `options`

**2017-03-23:**
new proposal seems close to consensus, some details to discuss:
- priorities
- shared docs (fragments?)
- field naming (bikeshed away)

Ticket is open to updates/discussion and once those are done it will be brought back for final approval

**Comment by gundalow** [comment]
From bcoca

Now that we support docs for many more plugin types, should we require all new plugins of those types to have docs included?

**2017-03-30**

* All new plugins should have docs
* Should be enforced by CI
* We should *not* just add placeholder docs to existing to make them pass - will be difficult to know what requires work.
* Therefore CI requires skip-list

**Comment by gundalow** [comment]
From @mattclay 

ansible/ansible#9563 (Adding nested dictionary lookups) - Do we want to accept this PR?

NOTE: Tests were passing until more strict checks were added recently. Docs will need to be updated to reference the 2.4 release instead of 2.2.

**Comment by gundalow** [comment]
From @bmildren 

Hi all, I'm trying to find how to progress this PR past community review, and it was suggested I add it here as an item to discuss.. https://github.com/ansible/ansible/pull/19872

(my irc handle is productiondba)

**Comment by gundalow** [comment]
Ansible 2.3.0 FINAL has been released. Thank you for all your help with this release
https://groups.google.com/forum/#!topic/ansible-project/aKnggI-Y8dk

**Comment by nitzmahone** [comment]
Revisit frequency/timing of core meetings- participation and efficacy feels pretty low lately.

**Comment by thaumos** [comment]
2017-04-25 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-04-25/ansible_core_team_meeting.2017-04-25-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-04-25/ansible_core_team_meeting.2017-04-25-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-04-25/ansible_core_team_meeting.2017-04-25-19.00.log.html

**Comment by gundalow** [comment]
Module option validation.

I've recently seen a few modules that:

* Ensure an int is within a specific range
* Ensure a option is an IPv4 (or IPv6) address

Should `class AnsibleModule` in `basic.py` be updated to support these?

**Comment by azaghal** [comment]
I would like to get some feedback for a [dconf](https://github.com/ansible/ansible/pull/23015) module. Since I have some obligations on next Tuesday, if this could be discussed during meeting on Thursday, 2017-05-11, that would be great.

Before I continue making changes to the proposed pull request, I would like to get feedback on what would be acceptable in order to merge it so I would not spend effort going into wrong direction.

Problem is as follows:

- `dconf` is configuration database used by a lot of Gnome and/or GTK+ applications. A module that wraps around it makes it possible to automate provisioning of configuration for such applications.
- In order to change settings via `dconf`, it is necessary to have a running D-Bus user session. Session is provided by running `dbus-daemon` binary.
- In order to ensure integrity and avoid accidental overwrites of settings, one should not run multiple D-Bus user sessions.
- Connection to D-Bus session is specified via environment variable `DBUS_SESSION_BUS_ADDRESS`.
- Detecting a running D-Bus user session address is a non-trivial matter due to lack of standardisation in D-Bus itself, and across distributions. If you are running `systemd`, the address should be predictable. If running something else, not so much. For example, on Gentoo this is a random string.
- D-Bus user session (`dbus-daemon`) can be launched in different ways based on D-Bus version present. If you're lucky (running D-Bus 1.8.0+), you can use `dbus-run-session` to wrap your command, and it will kill off the `dbus-daemon` once your command exits. If not, you need to launch the daemon and make sure to kill it off after you're done.
- Current implementation in the pull request will try its best to find a running session, and if that fails it will run its own. Code will also clean-up after itself as needed, supporting both the `dbus-run-session` and spawning of its own daemon.
- Problem is that this means the `dconf` module is behaving like a process manager, at least for D-Bus user session. This might not be desirable behaviour for publicly available Ansible module. As pointed out on IRC by `sivel`, a module should not manage daemon processes.
- Alternative would be to rely and require user to take care of spawning D-Bus user session and providing the address. However, this reduces usability, and pushes burden with all the listed things onto module user (and good luck someone would read up on how D-Bus daemon is spawned and killed - I know I didn't until somebody told me in the pull request review :).

**Comment by sivel** [comment]
https://github.com/ansible/ansible/pull/22929

**Comment by alikins** [comment]
I plan on discussion a merge of the facts cleanup fairly soon. This is the facts cleanup based on the 2.4 roadmap (see https://github.com/ansible/ansible/pull/23012 and https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst)

**Comment by thaumos** [comment]
2017-05-09 Meeting

12:55 <@zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-09/ansible_core_meeting.2017-05-09-19.00.html
12:55 <@zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-09/ansible_core_meeting.2017-05-09-19.00.txt
12:55 <@zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-09/ansible_core_meeting.2017-05-09-19.00.log.html

**Comment by gundalow** [comment]
Ansible `2.2.3 FINAL` released, `2.1.6rc1` and `2.3.1rc1` available for testing

All of these releases address at least one CVE (listed below). Users of 2.2.x should upgrade to 2.2.3 as soon as possible. The CVE impacting 2.1.x and 2.3.0 is MODERATE in nature, however users should look to upgrade as soon as the final releases are done. 
https://groups.google.com/forum/#!topic/ansible-devel/etlpnJDerY0

**Comment by thaumos** [comment]
https://github.com/ansible/ansible/pull/24463

**Comment by thaumos** [comment]
2017-05-11 Meeting 

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-11/ansible_core_meeting.2017-05-11-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-11/ansible_core_meeting.2017-05-11-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-11/ansible_core_meeting.2017-05-11-15.00.log.html

**Comment by azaghal** [comment]
**aka branko on IRC**

Would like to discuss https://github.com/ansible/ansible/pull/23015 once again (`dconf` module) since in the current form module might be a bit useless even to me.

**Comment by gundalow** [comment]
Is `DOCUMENTATION = r'''` the correct way"? If so we need to update our docs. Ditto. For `RETURNS` and `EXAMPLES`.

**Comment by bcoca** [comment]
@gundalow `r` ??? that looks really wrong

**Comment by thaumos** [comment]
https://github.com/ansible/ansible/pull/23038, proposal to have backported to 2.3

**Comment by thaumos** [comment]
2017-05-15 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-16/ansible_core_meeting.2017-05-16-19.00.html
12:40 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-16/ansible_core_meeting.2017-05-16-19.00.txt
12:40 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-16/ansible_core_meeting.2017-05-16-19.00.log.html

**Comment by gundalow** [comment]
**Ansible Contributor Summit 4 (Part of AnsibleFest 2017 London)**

We are happy to announce our fourth Ansible Contributors Summit!
AnsibleFest London (http://www.ansible.com/ansiblefest) will be on Thursday 22nd June, and the Contributor Summit will be held on Wednesday 21st June, from 9:30am to 4pm (time subject to change).

Contributors Summit is a day-long working session with the core team and key contributors to discuss important issues affecting the Ansible community. You can participate in person or online

Proposed topics: https://public.etherpad-mozilla.org/p/ansible-summit-june-2017

See https://groups.google.com/forum/#!topic/ansible-devel/stUITiM6hMs for more info

**Comment by thaumos** [comment]
https://github.com/ansible/ansible/pull/24751

**Comment by thaumos** [comment]
2017-05-18 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-18/ansible_core_meeting.2017-05-18-15.00.html
09:00 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-18/ansible_core_meeting.2017-05-18-15.00.txt
09:00 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-18/ansible_core_meeting.2017-05-18-15.00.log.html

**Comment by thaumos** [comment]
2017-05-23 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-23/ansible_core_meeting.2017-05-23-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-23/ansible_core_meeting.2017-05-23-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-23/ansible_core_meeting.2017-05-23-19.01.log.html

**Comment by Akasurde** [comment]
Need suggestion about Yum module - [ansible/ansible #24822](https://github.com/ansible/ansible/pull/24822)

**Comment by bcoca** [comment]
vote on https://github.com/ansible/ansible/pull/24867

**Comment by bcoca** [comment]
do we allow 'none/null' values on required parameters?

https://github.com/ansible/ansible/pull/24871

**Comment by thaumos** [comment]
2017-05-25 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-25/ansible_core_meeting.2017-05-25-15.00.html
08:58 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-25/ansible_core_meeting.2017-05-25-15.00.txt
08:58 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-25/ansible_core_meeting.2017-05-25-15.00.log.html

**Comment by willthames** [comment]
`when:` conditions are warning even for variables composed of other variables - this is most unexpected.

https://github.com/ansible/ansible/issues/25053

I almost certainly won't be able to make the meetings (1am and 5am my time) but @bcoca is aware of my thoughts.

My helpful proposal that should catch 99% of problems but not cause issues for lots of users (i.e. it should be an improvement, but not necessarily perfect) is:

```
'{{' in condition and '}}' in condition or '{%' in condition and '%}' in condition
```

**Comment by mikedlr** [comment]
The apt package installing module is a bit inefficient and could do with proper refactoring.  There was a new patch to handle multi-architecture.  I tried to make a [unit test](https://github.com/mikedlr/ansible/commit/25dbdacbe8ad83b62d370c321d7d6afdc22cab7c) for it and it turned up a few of obvious deficiencies.  For example the following:

- there's a huge section of code hidden inside a try which makes exception handling very unpredictable
- the dpkg installation function is too big and complex
- every .deb which is examined requires three external calls to dpkg (in turn calling dpkg-deb) and so it's needlessly inefficient and complex.

I've made more detailed comments in my review in [the pull request for the apt module](https://github.com/ansible/ansible/pull/24846).

This is a core maintained module so it would be good if someone could look at it and see if they'd be interested in taking on fixing it.  @evgeni who wrote the patch is willing to help but doesn't think he can drive this.  I can help with making the unit tests but don't really know the module or debian packaging so well.  @gundalow suggested taking this up in the core meeting and will be willing to talk about it if I'm not available.

**Comment by willthames** [comment]
What constitutes authorship for a module? What criteria should there be to be added to the authors list? What responsibilities (if any) does being added to the authors list bring?

**Comment by jctanner** [comment]
Meeting ended Tue May 30 20:49:18 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
4:49 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-30/ansible_core_team_meeting.2017-05-30-19.00.html
4:49 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-05-30/ansible_core_team_meeting.2017-05-30-19.00.txt
4:49 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-05-30/ansible_core_team_meeting.2017-05-30-19.00.log.html

**Comment by chriskarel** [comment]
I'd like to bring up PR #24580 https://github.com/ansible/ansible/pull/24580

I believe the PR is complete, and even has some additional unit tests.  But it hasn't been approved enough to get included.  One of the module maintainers recommended bringing it up in this meeting.

**Comment by gundalow** [comment]
https://github.com/ansible/proposals/issues/65 Allow documenting option deprecation

**Comment by erasmix** [comment]
I would like to discuss [PR#21857](https://github.com/ansible/ansible/pull/21857) and [PR#21764](https://github.com/ansible/ansible/pull/21764) on the next Core Meeting

**Comment by pilou-** [comment]
I would like to request reviews for [PR#23862](https://github.com/ansible/ansible/pull/23862).

**Comment by dagwieers** [comment]
We need guidance on ordered dictionaries for Windows modules. I prefer a common solution. https://github.com/ansible/ansible/issues/25265#issuecomment-306209518

**Comment by dagwieers** [comment]
Would like to discuss:
- The purpose of `connection: local`  --  ansible/ansible#24083
- Allowing host-lists (rather than dicts) in YAML inventories  --  ansible/ansible#22567

**Comment by cyberark-bizdev** [comment]
I would like to discuss [PR#21857](https://github.com/ansible/ansible/pull/21857)

@erasmix will be attending
@cyberark-bizdev will be in standby for discussion

**Comment by azaghal** [comment]
I would like to discuss if there is anything else I could do to have the following pull requests merged:

- https://github.com/ansible/ansible/pull/24576
- https://github.com/ansible/ansible/pull/23015
- https://github.com/ansible/ansible/pull/22956

**Comment by thaumos** [comment]
Please use https://github.com/ansible/community/issues/162 going forward.

**Comment by gundalow** [comment]
Rolled over to June's agenda, please use https://github.com/ansible/community/issues/162
