### ISSUE TITLE
Find maintainer for Ceph modules

### ISSUE THREAD

**Issue by gregdek** [ansible/community#16]
We've got some unmaintained Ceph modules, and it seems like we should be able to get some help from our Red Hat friends.

**Comment by robynbergeron** [comment]
We actually don't have any unmaintained Ceph modules, we just have modules that prospectively could have Ceph functionality in them :) In any case -- pinged Sebastien Han to see if he could lend a hand giving some eyeballs from the Ceph angle, and hopefully this will move along.

**Comment by gregdek** [comment]
Conversation ongoing.

**Comment by gregdek** [comment]
Looks like Sebastien is looking into it, so we can close here
