### ISSUE TITLE
Prohibit feature branches in the ansible/ansible repositories

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#160]
From time to time I see new feature branches being pushed from 'origin'.
This is problematic because these feature branches accumulate at everybody's working space.
And they are not being cleaned up ever (unless people do it themselves).

So it's best to create feature branches *only* in your personal clone, and allow people to collaborate there on these branches, rather than forcing them on everyone.

```
[dag@moria ansible.git]$ git pull --rebase
X11 forwarding request failed on channel 0
remote: Counting objects: 402, done.
remote: Total 402 (delta 218), reused 218 (delta 218), pack-reused 183
Receiving objects: 100% (402/402), 178.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (273/273), completed with 143 local objects.
From github.com:ansible/ansible
   99d3289..822fcc5  devel      -> origin/devel
 * [new branch]      issue_23579_memory -> origin/issue_23579_memory
   5f0be9d..d94ac76  stable-2.3 -> origin/stable-2.3
```

These are the ones that still exist upstream, but I have a lot of them accumulated on my local system that are just stale: https://github.com/ansible/ansible/branches/all

I had more than **200** feature branches from origin, after pruning the stale ones there's only 17 left.
```
[dag@moria ansible.git]$ git branch -a | grep remotes/origin | grep -vE 'stable|release|devel' | wc -l
271
[dag@moria ansible.git]$ git remote prune origin
Pruning origin
URL: git@github.com:ansible/ansible.git
 * [pruned] origin/abort-play-abort-playbook
 * [pruned] origin/action-boolean
[dag@moria ansible.git]$ git branch -a | grep remotes/origin | grep -vE 'stable|release|devel' | wc -l
17
```

**Comment by gregdek** [comment]
Discussed in the contributors conference. Do you feel like we came to any sort of conclusion? Do we need to drill down more on this?

**Comment by dagwieers** [comment]
@gregdek This was not discussed at the contributor conference AFAICT.

We discussed about protecting branches so direct commits would not be allowed. However not adding feature branches to the main repository was not discussed (and I am sorry I did not put it on the agenda, I didn't think of adding these open issues)

**Comment by gregdek** [comment]
Since this is, essentially, a proposal for how core should work, I wonder if it's more appropriately filed as a Proposal to be discussed at an upcoming core team meeting.

**Comment by bcoca** [comment]
we have our personal repos for 'feature branches', I don't see a need to polute the main repo

**Comment by gregdek** [comment]
@bcoca I think that's exactly what @dagwieers is saying, right? That that's what *should* be done, but not everyone's doing it, and so feature branches are showing up in the main repo when they shouldn't?

"So it's best to create feature branches only in your personal clone, and allow people to collaborate there on these branches, rather than forcing them on everyone."

Do we all basically agree on this? And if so, do we need some kind of policy, or should we just delete feature branches in the main repo, or what?

**Comment by bcoca** [comment]
@gregdek, yes, I'm agreeing with @dagwieers , but I already avoid creating these. I don't even use the 'revert' button in github as it creates these branches also.

The decision would have to be made by core team, I'm +1 to this rule, but I don't speak for all.

**Comment by gregdek** [comment]
@mckerrj Assigning to you for a policy decision here.

**Comment by jimi-c** [comment]
Discussed in our internal team meeting, and since I'm primarily the main offender here I'll start being a good bye and submitting PRs like everyone else.

Thanks!

**Comment by mckerrj** [comment]
And no feature branches please. :)

**Comment by dagwieers** [comment]
@jimi-c It's not so much about doing PRs instead (although that is a good practice too ;-)). Feature branches in your own space can be merged directly without PRs too. In any case, thanks !
