### ISSUE TITLE
Turn on wikis for SIGs

### ISSUE THREAD

**Issue by gregdek** [ansible/community#166]
At least one SIG, the Windows SIG, wants wikis. We'll figure out how to give them that.

**Comment by dagwieers** [comment]
The sooner the better, we are dragging this on for 1.5 month now.
Let's use this as a test-case and see what we can learn from it.

**Comment by gregdek** [comment]
Wiki is open for business!

**Comment by dagwieers** [comment]
Thanks ! I have started to move things over, it will take some time to find how to organize ourselves now.
