### ISSUE TITLE
Create Ambassadors working group

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#168]
The Ambassadors (https://github.com/ansible/ambassadors) wiki content is best placed inside the [Community repository](https://github.com/ansible/community) as a separate Working Group. It could become part of the existing Community Working Group, or as a separate entity. (@gregdek ?)

If it becomes part of this repository and Wiki, it will be easier to find as we will be promoting this repository a lot more within the community.

cc:  @gregdek @geerlingguy @tonk @bbaassssiiee @danvaida

**Comment by gregdek** [comment]
Yep, on it.

**Comment by dagwieers** [comment]
So what do we call it ?
Or will this become the Community Working Group ?

Still unclear to me.

**Comment by gregdek** [comment]
Well, the ambassadors group was originally for meetup attendees and speakers. We could call it the "meetups working group" as that's (a) quite specific, (b) underserved at the moment, and (c) very much in keeping with the original purpose.

**Comment by gregdek** [comment]
We could have a generic "marketing working group" that covers lots of things, but... dunno, unclear.

@robynbergeron as former head of Fedora Marketing SIG, advice plx :)

**Comment by dagwieers** [comment]
We opted for a "Promo" SIG in the CentOS project, as Marketing really sounded as if we're trying to sell something in a hideous way ;-)

**Comment by gundalow** [comment]
Once we've got the new Working Groups setup it would be good to ping all the existing Meetups to tell them about the various new Working Groups we've got + link to how to setup new ones. Feel like we are around a month away from that, as I'd want all the Working Groups to have a good list of "Here is how *you* can help".

**Comment by bbaassssiiee** [comment]
Hi

Ansible Ambassador has a great appeal to me. Marketing/promo/working group all have quite other connotations. The ambassador stands for openness and for the community. Our Benelux meetup f.i. is one of the few low-key places where peers meet over beers to talk without shoptalk and marketing bs. Why not keep the ansible ambassador? Meetup master, standup steward, co-organizer,  community guy/girl, working group worker. These terms all lack the class of the Ansible Ambassador. Like going back to the boy scouts.

Kindest regards,

Bas Meijer
@bbaassssiiee

**Comment by danvaida** [comment]
+1 on what Bas said. Thanks for finding the right words :)

**Comment by gregdek** [comment]
Got it. :)

So let's keep Ambassadors as the name of the Working Group.

What functions should it serve?

Promoting meetups, sharing content for meetups, etc., should definitely be one of them. Others?

For instance: we're thinking it's time to put together a community newsletter of "cool stuff that has happened in Ansible-land, neat youtube videos, talks, blog posts, etc."  Should that be an ambassador thing or a separate thing?

**Comment by bbaassssiiee** [comment]
Meetups, of course, and maybe also offer curated lists of content, like good slidedecks, peer-reviewed roles and other examples and demo's. A code of conduct should include to be inclusive, to embrace the openness of the community, and to share content, view point, and constructive critisism in code reviews. Avoiding certificates and licensed training, lock-in is for other cfgmgt vendors.

**Comment by tonk** [comment]
Just my two cents,

I do agree that the name should be kept. Ansible Ambassador does have a
special ring to it.

But I also think that the repo on Github deserves more love. At this
point it's just lying around, doing nothing.

Some things I would like to see in there would be:
	- A list of speakers you can contact for presentations
	  (or via telepresence)
	- Good slidedecks (with explanations, nut just nice pictures)
	- Announcements of events
	- Announcements of planned code and design changes

But one of the things I would love more would be an increase in speed
with the pull-requests and issues of the Ansible code on Github.

Maybe this is not the point in time or the place to start this
discussion, but I think it should be started somewhere, soon.
I hear of people leaving or planning to leave the community because of
the pace things are resolved on Github and that would be a very bad
situation.

Cheers,
	TonK

**Comment by dagwieers** [comment]
There was never a request to change the name for the Ambassador concept, or push through some other change from an ivory tower. The original request was to consolidate the information from the current ambassador repository into the community repository. In whatever form makes the most sense. The main thread here is what is needed to make this a success.

Secondly, the concept of Working Groups is to advance a specific area of Ansible (community, development, ...) by bringing together a group of people with the same focus to *actively* work on that common area. So from that perspective, the Ansible Ambassadors initiative could be part of the Community Working Group or a Promo Working Group.

It doesn't have to be, but it all depends on the critical mass and what is needed to make advancements. So allow me to be blunt here, if there is no plan to have regular meetings or action plans, if there's no group of people to actively lead this, there is no need for a dedicated Working Group. If I look at the Ambassador repository, there is value in the content, but there is little activity for the two years. So I don't really see what a dedicated Ambassadors Working Group will bring to the table at the moment, and don't see a good reason to make it its own Working Group.

So to end with a metaphor, I would hate to see a rush to claim new land now, with no farmers to develop that land and end up with wasteland. I would rather start small as part of a Community Working Group and when the critical mass is there, split it off because there is real value in doing so.

Does that make sense ?

**Comment by dagwieers** [comment]
@tonk More activity means more people willing to drive this activity. For the Windows Working Group we are trying to address these issues, both by having Ansible Sprints and growing the community. But this requires dedication and effort.

So the autonomy that Working Groups bring to the table could be an enabler here, but only if people are interested to lead such efforts. Granted, it is easier to focus on e.g. Windows, then it is to focus on specific modules that do not really fit a specific area. But a focus could be added by e.g. doing a Ansible Unix sprint (targeting all Unix system modules and advancing issues/PRs in that area for say, a month).

**Comment by tonk** [comment]
I really do agree with the things tht Dag says and I'm willing to spent
time and effort to get things going again. I'm not glued to the spot
where the Ambassador site is right now, I do agree that a spot where
more people are willing to participate would be good. For the people and
for the content. At this moment in time the (in my opinion valuable
content) is just lying around.

I'm still planning a meetup, but due to time constraints, things with
higher priority (getting married) and all kinds of other things that
need attention first, organizing things just fell of the grid. And now
we are entering the holiday season, so things could come to a grinding
halt. And I fear most of us have similar problems.

But I still stand by my initial sentence: I am willing to spent time and
effert to get things going again.

**Comment by gundalow** [comment]
Hi, I'm on the Core Engineering team and the new co-owner of the London UK Meetup.

I'm run the Network & Testing Working Groups.

I agree with the comments from @bbaassssiiee and @tonk 

Sharing expertise between meetups is a good thing. 

After the Contributors Summit in London last week (as part of AnsibleFest) we have some ideas of better organising the various working groups. Once this is done we can publicise these which will help the issue & PR backlogs for those specific areas.

@tonk Congratulations :)

**Comment by gregdek** [comment]
@tonk congrats indeed!

**Comment by tonk** [comment]
> Op 6 jul. 2017 om 18:06 heeft Greg DeKoenigsberg <notifications@github.com> het volgende geschreven:
> 
> @tonk congrats indeed!
> 
Thank you very much.

**Comment by robynbergeron** [comment]
Labelling for discussion in Community WG meeting today.

**Comment by robynbergeron** [comment]
Notes from meeting. @gregdek continues to have the ball on this one. ⚾️ 🏀 ⚽️ 🏈 🏉 🍙 

10:36 < dag> gregdek: let's draw a plan, and take it from there
10:36 < gundalow> So regarding publicising I'm running London Meetup, every meeting I'm going to be promoting the 
                  different Working Groups
10:36 <@gregdek> Ohhhhh, love it
10:36 <@rbergeron> okay. so: want to sit and think on this one for a week?
10:37 <@rbergeron> "draw the plan in the issue over the next week"?
10:37 < dag> rbergeron: or ask around and bring people together to draw that plan
10:37 < dag> I heard Wiki's are great for this :p
10:37 <@gregdek> So how do we plan the plan? :)
10:37 <@gregdek> Here's what I'm inclined to do:
10:38 <@gregdek> Tell the world "we're thinking about an Ambassador WG."
10:38 <@rbergeron> dag: well, only if we have a working group :) (or we put the ideas in the community wg wiki?)
10:38 <@gregdek> "Here's what it might do. Here's who it might serve."
10:38 < dag> what do we expect from this working group
10:38 < dag> like gundalow says, use the meetups to talk about the community
10:38 <@gregdek> And ask people to comment, either in an issue or on a wiki page or something.
10:38 < dag> and get more people closer involved
10:39 < dag> ok, sounds good

**Comment by gregdek** [comment]
OK, so this ticket has lots of info, so I'm going to rename it and drop a bunch more stuff in it.

New name: "create Ambassadors working group".

List of stuff to do:

- [ ] Create Ambassadors working group, including wiki
- [ ] Pull in legacy content from https://github.com/ansible/ambassadors
- [ ] Set up structure for canned content
- [ ] Write the 10m noob deck 
- [ ] Set up structure for outreach to non ansible meetups
- [ ] Set up remote speaker bureau
- [ ] Invite meetup leaders to join Ambassadors working group

Some of these may just "get done", some of them may turn into separate tickets

**Comment by gregdek** [comment]
Advice for small/medium/large:

Small: create an event "chat about Ansible" and locate it at a coffeeshop or library or someplace like that. Cap attendance at 10, just in case you accidentally overrun the place. No agenda, just hang out and share Ansible stories. If you end up with a waiting list, that's a sign to move up to medium.

Medium: find a place with a projector and do a simple talk, like "Ansible 101" (it's on our plate to put together a standard deck for this.) Can be pretty much any company's office, and you can solicit on the group: "hey members, can anyone host this?" Look for someone to sponsor pizza/snacks/drinks, and if you can't find anyone, we're happy to cover it. Cap attendance at 50, and if that ends up with a waiting list, move to large.

Large: solicit actively for multiple co-organizers and multiple sponsors. Solicit membership for content on a regular basis. Consider dividing tasks between organizers.

**Comment by gregdek** [comment]
OK. The Ambassadors WG is set up. Going to close this and move some tasks to new tickets.
