### ISSUE TITLE
Consolidate Community on docs.ansible.com/ansible/community

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#169]
Currently the root-directory of the Community repository has a couple of files that probably could live elsewhere. The reason for cleaning this up is so that people find the things they are looking for quicker.

So we leave the most important stuff in the root, and reference the others from the README.

- CONTRIBUTING.md  --  *I would move this content to the Wiki and reference it from the README.md*
- LICENSE  --  *Leave in place*
- MEETINGS.md  --  *I would move this content to the Wiki and reference it from the README.md*
- PR-FLOW.md	 --  *This may be obsolete (ansibullbot?) or may move to **group-community**.*
- README.md  --  *Leave in place*
- ansible_community_meetings.ics  --  *Unfortunately we cannot move/rename this one, ever*

**Comment by gundalow** [comment]
Myself and @gregdek have been talking about this.

We have a lot of community documentation that's spread over:
* github.com/ansible/ansible
* github.com/ansible/community
* github.com/ansible/proposals
* github.com/ansible/ansibullbot
* docs.ansible.com/ansible/community
* docs.ansible.com/ansible/dev_guide
* ansible.com/community
* + other places

We know that:
* A lot of these docs need love
* There is a lot of duplicated/contradictory and wrong information
* Need consolidating and linking together

Therefore we've agreed to move all the main content to `docs.ansible.com/ansible/community` (`docs/docsite/rst/community`)

This will allow it to:
* Be in one place and easily linkable from relevant existing user & dev_guide
* Benefit from our Technical Author review process
* Look a lot better
* Be searchable

To clarify, we are *not* talking about moving the Working Group areas or Wiki. We are talking about moving the static & process documentation)

**What should move**
The following docs should be migrated
  * All docs from github.com/ansible/community/index.rst
    * CONTRIBUTING.md point -> docs/community/index.rst
    * CODING_GUIDELINES.md -> possibly delete or dev_guide
    * MODULE_GUIDELINES.md -> docs/community/maintainers.rst
    * ROADMAP.rst -> docs/community/roadmaps.rst
  * From docs.ansible.com/ansible/
    * committer_guidelines.html -> docs/community/commiters.rst
    * community.html -> docs/community/index.rst
  * From ansible/community
    * README.md -> Simplify
    * CONTRIBUTING.md -> Delete
    * MEETINGS.md -> docs/community/meetings.rst
    * PR-FLOW.md -> DELETE
    * commiters/merge_workflow.md
    * commiters/triage.md -> Delete?
  * From ansible/ansibullbot
    * ISSUE_HELP.md -> pr_and_issue_workflow.rst


**Proposed New Structure**
* **www.ansible.com/community**
  * Should still exist
  * "DISCUSS" LINK: docs/community/contact.rst
* **docs/community/index.rst**
  * Almost no content apart from "Thank you", just points to other pages
  * Should also link to Marketing site
    * https://www.ansible.com/events
* **docs/community/development_process.rst**
  * Flow chart from
    * Do i need to raise a PR LINK: sivel's prbyfile LINK: How to review
    * Should this be a proposal -LINK: docs/community/proposal_process.rst
    * PR
    * Raise PR
    * Bot labels
    * Human triage
    * Move bot help here
    * Getting reviews (maintainers, topic maintainers)
      * How to get more reviewers
    * shipit label
    * merge
    * Backport?
    * Changelog
       * devel
      * stable-x.y/CHANGELOG.md - ALL CHANGES
    * Releases
* **docs/community/reporting_bugs_and_features.rst**
  * What is a bug
  * Has it already been filed
  * Is there a PR in flight
  * What's a feature
  * Feature vs proposal LINK docs/community/proposal_process.rst
* **docs/community/roadmaps/index.rst**
  * What are roadmaps and how do we use them
  * ROADMAP_2.3.rst
  * ROADMAP_2.4.rst
  * FutureDirection.rst
* **docs/community/triage_process.rst**
  * Publish internal notes?
* **docs/community/how_can_I_help.rst**
  * Types of help
  * Become a user
  * LINK: docs/community/development_process.rst
  * Improve Docs
  * Link to Working Groups + there how to help pages
  * Review PRs
    * LINK: sivel/prbyfiles
* **docs/community/maintainers.rst**
  * What is a maintainer LINK: docs/community/development_process.rst
  * Responsibilities
  * Adding
  * Stepping down
  * Orphaned modules
* **docs/community/communication.rst**
  * How to communicate & which methods are best for what
  * Email
  * List of IRC Channels
  * Meetings
* **docs/community/special_interest_groups.rst**
  * ansible-container
  * AWS
  * Testing
  * Network
  * Windows
  * How can I set one up - make this very light weight
* **docs/community/other_tools_and_programs.rst**
  * Links to other things from willthames, sivels, etc
  * Other tools https://github.com/ansible/community/issues/5 
  * How can I get my tool on here LINK: IRC Meetings

**Comment by bcoca** [comment]
@gundalow +1

**Comment by gundalow** [comment]
ansibullbot & PR workflow may need a little more thought, need to discuss with Tanner

**Comment by dagwieers** [comment]
@gundalow Whoaw, that seems much better than what I was looking for ;-) I have nothing to add to that.

**Comment by gregdek** [comment]
So basically we'll start moving these over bit by bit and removing the pages from ansible/community as we go. Might be worth breaking these up into individual issues... will noodle on it. Anyway, it's on my list. :)

**Comment by gundalow** [comment]
@dagwieers It's been something I've been thinking about for a while, finally wrote it down

**Comment by gundalow** [comment]
Changed issue title to represent the bigger project

When doing this it's important for the first pass to only move and reorder content into the new location. Avoid the urge to rewrite.

Once the content is in the new location, in smaller files these can be attacked individual. We've found this process worked well when updating `dev_guide`

**Comment by gregdek** [comment]
OK, time to tackle this one next, since it's blocking a bunch of stuff. And as per @gundalow, going to resist the urge to rewrite. :)

**Comment by docschick** [comment]
I'd like @dharmabumstead to weigh in here as well, since I want him to be more community-facing and be the point person for all things docs related to Ansible Core. Love the ideas you have going @gundalow, but has @dharmabumstead had a chance to review or weigh in here at all?

**Comment by gregdek** [comment]
He can have commit rights as far as I'm concerned. It's going to be an ongoing process.

**Comment by gregdek** [comment]
Well, and these things are all landing in the docs tree anyway as PRs, so he will obviously have review rights.

**Comment by gregdek** [comment]
OK, so I'm going to call the cavalry in here. I can't figure out how to get the docs stuff updated, because I basically can't even figure out how to build it, and I'm taking way too much time on this relative to other things I could be doing better.

@gundalow @dharmabumstead is this the kind of thing where we could grab a couple of hours to do a sprint here? Just get on bluejeans one day, screenshare, and knock some of this stuff out?

**Comment by dharmabumstead** [comment]
Yes. I will touch base with @gundalow to coordinate how we want to do this.

**Comment by dharmabumstead** [comment]
https://github.com/dharmabumstead/ansible/tree/community-content-1

**Comment by gregdek** [comment]
@dharmabumstead is there a PR of this? Was this merged?

**Comment by dharmabumstead** [comment]
A work branch was created last week (see above) and initial structure set up, but no PR yet.

**Comment by gregdek** [comment]
OK. So the first step is to make sure that all extant content, from everywhere we can find, exists in the new devel structure. Thanks to @dharmabumstead, we have that new structure in place in devel now, so I'll be filling it up according to @gundalow's recommendations. That will take place over several PRs, each with review from @gundalow and @dharmabumstead.

Once that's done, we will re-review the whole thing for "good-enough-ness", and when we're ok with it we will ask for a backport to production.

Once *that's* done, then, and only then, we will clean up the old pages on ansible/community.

**Comment by gregdek** [comment]
[ ] **rst/community/index.rst** 
  * Almost no content apart from "Thank you", just points to other pages
  * Should also link to Marketing site
    * https://www.ansible.com/events
[ ] **rst/community/development_process.rst**
  * Flow chart from
    * Do i need to raise a PR LINK: sivel's prbyfile LINK: How to review
    * Should this be a proposal -LINK: docs/community/proposal_process.rst
    * PR
    * Raise PR
    * Bot labels
    * Human triage
    * Move bot help here
    * Getting reviews (maintainers, topic maintainers)
      * How to get more reviewers
    * shipit label
    * merge
    * Backport?
    * Changelog
       * devel
      * stable-x.y/CHANGELOG.md - ALL CHANGES
    * Releases
[ ] **rst/community/reporting_bugs_and_features.rst**
  * What is a bug
  * Has it already been filed
  * Is there a PR in flight
  * What's a feature
  * Feature vs proposal LINK docs/community/proposal_process.rst
[ ] **rst/community/roadmaps/index.rst**
  * What are roadmaps and how do we use them
  * ROADMAP_2.3.rst
  * ROADMAP_2.4.rst
  * FutureDirection.rst
[ ] **rst/community/triage_process.rst**
  * Publish internal notes?
[ ] **docs/community/how_can_I_help.rst**
  * Types of help
  * Become a user
  * LINK: docs/community/development_process.rst
  * Improve Docs
  * Link to Working Groups + there how to help pages
  * Review PRs
    * LINK: sivel/prbyfiles
[ ] **rst/community/maintainers.rst**
  * What is a maintainer LINK: docs/community/development_process.rst
  * Responsibilities
  * Adding
  * Stepping down
  * Orphaned modules
[ ] **rst/community/communication.rst**
  * How to communicate & which methods are best for what
  * Email
  * List of IRC Channels
  * Meetings
[ ] **rst/community/special_interest_groups.rst**
  * Limited content, it just links to gh/ansible/community
  * ansible-container
  * AWS
  * Testing
  * Network
  * Windows
  * How can I set one up - make this very light weight
[ ] **rst/community/other_tools_and_programs.rst**
  * Links to other things from willthames, sivels, etc
  * Other tools https://github.com/ansible/community/issues/5 
  * How can I get my tool on here LINK: IRC Meetings
[ ] **www.ansible.com/community** (existing page)
  * Should still exist
  * "DISCUSS" LINK: docs/community/contact.rst

**Comment by pilou-** [comment]
I have made some updates (labels, bot commands, workflows, what is a maintainer from the bot point of view) to [ISSUE_HELP.md](https://github.com/ansible/ansibullbot/commits/master/ISSUE_HELP.md). It seems some parts of `ISSUE_HELP.md` will be moved/refactored into **rst/community/development_process.rst** :) Is there another working branch ?

In the future, where will the link contained in the automatically added pull-request comment ([this one](https://github.com/ansible/ansible/pull/27637#issuecomment-319717129)) point to ?

**Comment by gregdek** [comment]
@pilou- no working branches. Basically we'll move everything in its own branch, one commit/one file at a time, to the devel branch of docs. Once they're all moved, we'll treat the docs site as authoritative and start to prune other content from the repo.

**Comment by gregdek** [comment]
Open question: ISSUE_HELP.md is a comprehensive document, and really does document the full bot workflow -- which is, practically speaking, the development workflow. Wondering if development_process.rst shouldn't just point to ISSUE_HELP.md for most of the "ansibot" content, and have wording like "the Ansibot drives the triage process, the process changes and improves, go to ISSUE_HELP.md for the current triage process."

**Comment by pilou-** [comment]
The behavior of the bot is often updated, it seems http://docs.ansible.com/ansible/latest/community/index.html is using `devel` branch of Ansible Git repository but how often is it updated  ?

**Comment by gregdek** [comment]
I know it's @gundalow's intention to basically backport the community pages as often as necessary, and perhaps even to just build them directly from the devel branch.

Anyway, this issue is now waiting for approval from @dharmabumstead and @gundalow. If they agree it's good enough to go live, they will supersede the current community.html document with the community/ tree, and we'll be ready to close this issue.

**Comment by gundalow** [comment]
Another idea is that we redirect http://docs.ansible.com/ansible/*latest*/community/ to http://docs.ansible.com/ansible/*devel*/community/ so we don't have to backport

`http://docs.ansible.com/ansible/latest/` Is the latest `stable-x.y` branch
`http://docs.ansible.com/ansible/devel/` Is the `devel` branch (Not currently live)

See https://github.com/ansible/proposals/issues/60 for more info

**Comment by dharmabumstead** [comment]
Thanks Greg!

In the future, it'd probably be easier to leave the PRs open so we can use
Github's edit-in-place and review features before merging.

FYI, I've created a branch for this so we can do some smoothing/editing. I
will do a PR after my first pass is finished and leave it open so we can
iterate over it:

https://github.com/dharmabumstead/ansible/tree/community-docs-edit-pass-1

I hope to have the first pass done and PR opened by tomorrow night.

Thanks!

**Comment by dharmabumstead** [comment]
https://github.com/ansible/ansible/pull/28368

**Comment by gregdek** [comment]
Live. Whew!

**Comment by gundalow** [comment]
Yay live
Boo lots of other stuff left to do, see my epic list
Also for everything that's been moved to the new docs location we need to delete from this repo

**Comment by gregdek** [comment]
Right, the old docs need to be migrated:

What should move
The following docs should be migrated

All docs from github.com/ansible/community/index.rst
CONTRIBUTING.md point -> docs/community/index.rst
CODING_GUIDELINES.md -> possibly delete or dev_guide
MODULE_GUIDELINES.md -> docs/community/maintainers.rst
ROADMAP.rst -> docs/community/roadmaps.rst
From docs.ansible.com/ansible/
committer_guidelines.html -> docs/community/commiters.rst
community.html -> docs/community/index.rst
From ansible/community
README.md -> Simplify
CONTRIBUTING.md -> Delete
MEETINGS.md -> docs/community/meetings.rst
PR-FLOW.md -> DELETE
commiters/merge_workflow.md
commiters/triage.md -> Delete?
From ansible/ansibullbot
ISSUE_HELP.md -> pr_and_issue_workflow.rst

**Comment by gregdek** [comment]
OK, waiting on review of a couple of PRs, but then I think the cleanup is done. @gundalow if you can confirm, we can close. (And honestly, if you find issues at this point, this omnibus issue probably isn't helping us track anymore.)

**Comment by gregdek** [comment]
As I said in October, this omnibus issue is no longer useful for tracking the issues we surfaced. From what I can tell, the vast majority of these things have been fixed; those that haven't can be opened separately.
