### ISSUE TITLE
Simple guidelines for Working Groups

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#170]
So we now have a list of Working Groups with group information in the [community repository](https://github.com/ansible/community). Next thing to do is improve the quality of the information to help interested readers to join.

- [Community Working Group](https://github.com/ansible/community/tree/master/group-community)  --  @gregdek @robynbergeron 
- [Network Working Group](https://github.com/ansible/community/tree/master/group-network)  --  @privateip 
- [Testing Working Group](https://github.com/ansible/community/tree/master/group-testing)  --  @mattclay @gundalow
- [Windows Working Group](https://github.com/ansible/community/tree/master/group-windows)  --  @nitzmahone @jborean93

The [wiki link](https://github.com/ansible/community/wiki) is optional, if you do not want to use the wiki, that's fine too.

What other Working Groups already exist ? Documentation ? Promo (Ambassadors) ?
And what additional Working Groups would be useful/feasible to create ? VMware ? Cloud ? Solaris ? ...

**Comment by gregdek** [comment]
We've got the AWS working group as well, already created and running sort-of afaict. 

I'll reboot Ambassadors as a working group per #168.

I think what's needed to close this issue is an answer to the question "how do I start my own working group?" Which is probably by submitting a PR with the new working group. Maybe we even have template working group documentation to start from.

**Comment by gundalow** [comment]
I wonder if:
* How to start a working group 
* how to setup (name, chanserver, ops, document it)
* host IRC meeting

should be in one document

**Comment by gregdek** [comment]
Yes. Starting a working group should subsume all of these things, because you really shouldn't be doing those things in the absence of a working group.

**Comment by gregdek** [comment]
Since this is kind of an omnibus issue, I'm going to change the name here and assign it to myself to bang out quickly.

**Comment by gregdek** [comment]
OK, friends, take a look:

https://github.com/ansible/community/pull/180

**Comment by gregdek** [comment]
Closed by #180.
