### ISSUE TITLE
Update Google Calendar with new Windows meeting timing

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#174]
So the Windows meeting has moved to Tuesdays at 20:00 UTC, but nobody seems to be able to update the Google calendar.

Maybe that access should be shared with the Community Working Group ?

**Comment by robynbergeron** [comment]
@dagwieers just the existing Tuesday meeting (which looks to be every other tuesday)? And the Friday meeting stays the same?

**Comment by robynbergeron** [comment]
re: sharing access with the community group -- I am not sure offhand if that is possible (in a technical sense). A bigger concern is whether or not -- as we, um, undergo further assimilation by our corporate overlords -- that calendar in general will be migrated as part of general consolidation anyhow, which may or may not mean that wider access will continue to be possible (if it is anyhow at the moment), and also, if it will mean people have to resubscribe or not, etc. 

@gregdek i know you were talking to the IT humans about some of this stuff -- can you maybe add this to your list of things to find out? 

More broadly -- my biggest concern is making sure that adding to / fixing the calendar isn't a bottleneck for people in working groups or starting new things, and if we can't share access I'd rather get rid of it or find an alternative solution that we can link to github auth or .. something? I know it's "convenient" to folks to have access to a downloadable calendar but that convenience isn't very awesome if the community isn't enabled to touch it and set meetings for when they'd like. And I'd rather be on the side of "everyone can edit a bulletpoint list with times, and we all know how to fix our own calendars" vs. having a bottleneck where not everyone can have access. 

$.02 :)

FWIW I did look at calendaring in Fedora thinking that that might be an option (Fedocal, https://apps.fedoraproject.org/calendar/ ) but I'm pretty sure we (a) aren't at the point of wanting to run our own version, (b) borrowing from them may mean having to deal with FAS and I don't think we want to get into that territory either. 

So i guess:
1: Alternative suggestions welcome if anyone has ideas, would be neat if it worked with github auth somehow and isn't a service that is going to go out of business in the next year :D
2: If @gregdek can determine the future of that calendar's existence as that domain gets subjected to the assimilation, that would be great (inc. what the sharing possibilities are)
3: If whomever has access to the calendar as it is can fix the situation for the moment based on @dagwieers original request, I will give you a cookie at some point in the future. Or a hug. :D

**Comment by robynbergeron** [comment]
(ps. @dagwieers i am pretty sure that is not entirely the answer you were hoping for at the moment, but I'm also trying to bear in mind that "fixing it" for the moment and finding out later when we have 20 SIGs going and more people dependent on the calendar that we have to change it would suck even more than it does at the moment. :hotdog: )

**Comment by dagwieers** [comment]
@robynbergeron All existing meetings will be replaced by "every Tuesday at 20:00 UTC".

PS I updated the ICS manually, so maybe we could get away with a simply YAML file, and a small tool to convert it to an ICS file. You can import the URL to the ICS to a Google Calendar, and in theory no one needs access to that Google Calendar.

**Comment by dagwieers** [comment]
There's always someone who preceded us: https://pypi.python.org/pypi/yaml2ical/0.2.0

**Comment by mattclay** [comment]
I've updated the Google Calendar.
