### ISSUE TITLE
News Working Group

### ISSUE THREAD

**Issue by gregdek** [ansible/community#175]
Hey @robynbergeron we've been batting this idea around for a while now. Should we just get started with it?

**Comment by robynbergeron** [comment]
Yes. I think so :) It looks like (based on discussions in #168 re: ambassadors, marketing, sig naming, etc.) that calling it the newsletter working group is just dandy. 

@gregdek Do we want to wait on merging #180 -- and then I can "test out" the Working Group Guidelines in creating this new Newsletter working group? :)

**Comment by gregdek** [comment]
OK, we've got a working group created per the other ticket. :) And since that also tested the Working Group Guidelines, I'm considering this one closed as well.
