### ISSUE TITLE
Pause Module in Ansible Tower With Human Intervention

### ISSUE THREAD

**Issue by Ankur1106** [ansible/community#179]
Hello All,

We have a scenario where we have to include pause between tasks for manual interventions . We are using Ansible tower 3.1.3  to run our playbook. I have tried to use pause module but with ansible tower the keyboard interactions (ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort) doesn't work and it pauses for the defined time like 2mins, 5mins etc.  
Is there any other way to achieve this through tower? We want the next task should start or abort if we get a prompt  for the same.?

Regards,
Ankur

**Comment by dagwieers** [comment]
The ansible/community repo is not about product support, it is about community collaboration.
Please contact Ansible support instead.
