### ISSUE TITLE
Fix "commiters" directory in ansible/community to correct spelling

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#181]
Once #169 is sorted out this will probably go away anyhow -- but in the meantime....

Anyone interested in creating a PR for fixing https://github.com/ansible/community/tree/master/commiters to change "commiters" to "committers" would be my hero or at least would save my eyes from continuous bleeding every time I see that typo :) :face_with_head_bandage:

**Comment by dagwieers** [comment]
Haha, I noticed that as well, but refrained myself from potentially breaking whatever that could be using it.
So I am allowed to change it ?

**Comment by robynbergeron** [comment]
Looks like you are :) I think nothing will get broken by fixing it -- my worry in doing it myself was that my infrequent git usage might result in like, actual breakage of bigger things :D thanks @dagwieers :hugs:
