### ISSUE TITLE
Sprint at EuroPython 2017 (July 15-16)

### ISSUE THREAD

**Issue by robinro** [ansible/community#183]
I'll be at the EuroPython 2017 conference and there are two days of sprints.
Is anyone of you going to be there and interested in (co-)organising an ansible-sprint or joining one?
It'll probably be nice to have someone with commit rights there, which I don't have.

I saw @ioggstream is giving an ansible training session.

I'm open to work on pretty much anything. There are some long-term refactorings for the git module that I might tackle or look into performance measurement and optimizations.

**Comment by gundalow** [comment]
I will not be there in person, however I'm in the same time zone & I've got commit rights. I should be available online most of that weekend. 

Feel free to use `#ansible-devel` during that time to discuss anything with a wider audience, and poke me to commit.

**Comment by robinro** [comment]
Sounds good, thanks @gundalow.
Let's see whether people interested for this sprint show up.

**Comment by ioggstream** [comment]
I'm in: maybe it's the occasion to have a couple of things merged.

If anybody is interested in reviewing the course:

  - it's here https://github.com/ioggstream/python-course/tree/ansible-101-v2
  - it's based on jupyter so you can run ansible quite simply.

@robinro Thx++!

**Comment by gundalow** [comment]
You may want to mention this on he two email lists, IRC (at a few different times) and in the IRC meetings

**Comment by gundalow** [comment]
@robinro @ioggstream How's this looking?

**Comment by robinro** [comment]
@gundalow The training session by @ioggstream is tomorrow (12.07.). I'll see whether people there are interested in a sprint and then announce via the conference group/blackboard so everyone is reached who can be there in person.
I'd focus on bug-cleanup starting with the modules I maintain or with whatever people use and complain about.

**Comment by gundalow** [comment]
Sounds great. I should be around this weekend if stuff needs merging.

Could you please mention the various Working Groups that now exist, would be great to promote them a bit more 
https://github.com/ansible/community/#communication

Thank in advance :)

**Comment by robinro** [comment]
@gundalow Can you be in IRC tomorrow (Fri, Jul 14) 08:00 - 09:00 UTC? We'll do a short session and there are some old PRs that want to be merged.

There'll probably be more Saturday/Sunday.

**Comment by gundalow** [comment]
@robinro Yup, I should be able to be around.

To speed up the process if you can ensure no `stale_ci` labels are on the PRs, if there are they will need closing and re-opening (if the PR creator is there) otherwise please ping links in `#ansible-devel` asking for CI to be rerun.

**Comment by robinro** [comment]
There is an etherpad with some issues to work on: https://public.etherpad-mozilla.org/p/ansible-sprint-europython-2017

**Comment by robinro** [comment]
Thanks everyone for attending and @gundalow for helping to get stuff merged.
Some more issues/PRs started here will be opened/reviewed/merged in the coming days and weeks.
