### ISSUE TITLE
Create IRC channels for all extant WGs 

### ISSUE THREAD

**Issue by gregdek** [ansible/community#184]
Create IRC channels for all extant groups, if they don't already exist:

AWS
Community
Network
Testing
VMWare
Windows

...and get the meetbot into all of them.

**Comment by gundalow** [comment]
aws, vmware and windows already exist

Just created network

Testing does NOT want a dedicated channel as per https://github.com/ansible/community/tree/master/group-testing
> #ansible-devel IRC channel on Freenode.net. As testing related to all aspects (and other Working Groups) we use the main #ansible-devel

**Comment by gundalow** [comment]
```

**Comment by gregdek** [comment]
Sounds good. Thanks @gundalow! 

Re: adding the bot, that'll have to wait a bit; bots are limited to 150 channels, and the Fedora bot we're using is at that limit. I'll file a separate issue for that.
