### ISSUE TITLE
News WG creation request

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#185]
WORKING GROUP NAME: News

WORKING GROUP PURPOSE:
The Ansible News Working Group sources, curates, and promotes existing Ansible-related content, and encourages the creation of Ansible-related content across a variety of mediums. Initial curation and promotion goals are an Ansible Weekly Newsletter; future work may include "Ansible Magazine" (online site, Ansible-community created / edited); Ansible Developer Newsletter (less frequent, info that is relevant to contributors).

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
IRC: rbergeron / GitHub: @robynbergeron
IRC: gregdek / GitHub: @gregdek 

**

Alternate suggestion for WG Name: Moos. Because it rhymes with News. 🐮 
(Though perhaps this does not translate well in other languages. I also wonder if "la bonne moovelle" - as opposed to 'la bonne nouvelle' is a possible french pun. I don't know! I think this is all magic related to a newsletter name to be decided in the working group once we have it. 🐄 )

**Comment by gregdek** [comment]
I know we've been talking about Ansible Magazine. Is this the same, related, different?

**Comment by robynbergeron** [comment]
Related / different, I suppose?

The Ansible Magazine idea is akin to [Fedora Magazine](https://fedoramagazine.org/)  -- where would content is created and edited (or in some cases, republished with permission) by members of the Ansible Community, similar to how it is done in Fedora. (2-3 articles a week, etc, largely "end user" facing and not so much targeted at contributors.)

The Newsletter Idea -- at least, to begin -- is more of a traditional community-related news newsletter published weekly or every-other-week including things like:

1: Links to interesting blog posts from the past week or two
2: Links to other interesting content (videos, podcasts, whatever)
3: Could include things like "interesting tool of the week"
4: Could include things like "look at this happy tweet from this person"
5: Likely includes an "events" section including "upcoming meetups in the next 2 weeks," conferences with Ansible content in the immediate future, CFPs, stuff like that. 

Newsletter would likely be a flat-text format or possibly flat-text but could opt into "full html email" if we wanted to.

They are related in that "Ansible Weekly News" or whatever it would be called would probably be a likely candidate each week to get turned into an Ansible Magazine post; I suspect until then, we can probably turn it into a blog post on ansible.com (which gets sticky because I don't know how much access we can dole out for that, but that's a driver for creating a magazine-type site as well). 

So:

Could this be a "content" working group? Sure. Could we do a newsletter group and sort out the things and then get to magazine in a month or two? I think that seems more feasible.

There is lots of content around Ansible out there that people create like, in huge volumes, and I think it's worth having a newsletter that highlights all of that magical stuff; having a magazine with more specific / edited content that the Ansible Community creates itself I think will have a better chance of gaining contributors if we're already starting to do a good job of highlighting and appreciating other content out there in the community as well. 

I don't want to dive too much in specifics / decisions in requesting a group since I think lots of those specifics would be decided by a group :) 

All that said -- the "weekly news" or whatever we'd call it is probably the first option; i know other folks have discussed figuring out how to have more of a contributor / developer focused newsletter / awareness type of thing, probably for a smaller audience, and that's a thing the newsletter group could also do, but .. you know. One thing at a time :D

**Comment by robynbergeron** [comment]
Examples of other nice newsletters include: 

[KubeWeekly](https://kubeweekly.com/)
[Docker Weekly](https://goto.docker.com/Docker-Weekly_6212017.html)

@lhawthorn and I and some of our other fine colleagues used to put together the newsletter at our former place of employment, and I think it's a thing that can easily be translated into a community-contributable type of effort via the wiki or etc. and where we can figure out how to take suggestions from folks for content / links via issues or something to that effect.

**Comment by gregdek** [comment]
What do you think about "News" for the WG name? That gives us something less squishy than "content" and also leaves open the option for both newsletter and magazine down the line.

**Comment by robynbergeron** [comment]
Sure! Sounds delightful.

**Comment by robynbergeron** [comment]
@gregdek so: should I edit the issue above to reflect that stuff? I guess I will do that. If not I guess you can undo that 😁

**Comment by robynbergeron** [comment]
I have now updated the request and issue to reflect being a request for the News Working Group.

Moo. :cowboy_hat_face:

**Comment by gregdek** [comment]
Done! Join me on #ansible-news so we can discuss next steps!
