### ISSUE TITLE
TODO list for News WG

### ISSUE THREAD

**Issue by gregdek** [ansible/community#190]
We've got our first News Working Group meeting coming up -- we should get all of Robyn's notes into a wiki or a page or something so we can start working on our TODO list!

**Comment by robynbergeron** [comment]
Well, I made #210 (content suggestions) and #211 (newsletter "decisions"). Will link into the wiki "ideas" section in copious spare time. 😄

**Comment by gundalow** [comment]
Replaced by https://github.com/ansible/community/issues/546
