### ISSUE TITLE
Contributors Summit London 2017: Finish off

### ISSUE THREAD

**Issue by gundalow** [ansible/community#193]
Review & Retrospective
* Videos need to go online
* Minutes need to go online
* Actions need writing up
* What went well/what didn't

Use to help https://github.com/ansible/community/issues/192

**Comment by gregdek** [comment]
I sent out a summary of this event as part of the invite for SF Contributor Summit, and we didn't really have the time to do the others of these properly -- and I don't think anyone is going to comb through the video for these sessions, so I'm going to close this one.
