### ISSUE TITLE
Windows Working Group agenda - Jul-Dec 2017

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#195]
The Windows Working Group is focused on improving Ansible's management of Windows hosts. The group meets every week on Tuesdays at 20:00 UTC (see [calendar](https://calendar.google.com/calendar/embed?src=ansible.com_pafenslko0e2bqjgujp8f7s0do%40group.calendar.google.com&ctx=UTC)) 

More information related to the Windows Working Group is available at:
 https://github.com/ansible/community/tree/master/group-windows

**Feel free to add your questions to this ticket to be discussed during the upcoming meeting.**

*(Migrated from the previous agenda at #153, actionable items are available at [Windows: action plan](https://github.com/ansible/community/wiki/Windows:-action-list))*

**Comment by dagwieers** [comment]
Review and merge: ansible/ansible#23119

**Comment by dagwieers** [comment]
(@jhawkesworth) Reminder to ask how others are debugging while we are in the (temporary) position of not being able to use ANSIBLE_KEEP_REMOTE_FILES=1 for windows modules at the moment.

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-289038975*

**Comment by dagwieers** [comment]
(@dagwieers) Review and decide: ansible/ansible#21898

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-300023131*

**Comment by dagwieers** [comment]
[New windows modules](https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Awindows+label%3Anew_module) waiting for review/feedback:
- win_wait_for: ansible/ansible#26556
- win_xml: ansible/ansible#26404
- win_secedit: ansible/ansible#26332
- win_group_member: ansible/ansible#26307
- win_user_right: ansible/ansible#26276
- win_certificate: ansible/ansible#25837
- win_pagefile: ansible/ansible#25605
- win_domain_user: ansible/ansible#24075
- ~win_secedit: ansible/ansible#22775~

Once merged, please add to [CHANGELOG.md](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md) !

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-301128352*

**Comment by dagwieers** [comment]
(@jborean93) Implement ansible/proposals#63 in Shippable CI.

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-302923532*

**Comment by dagwieers** [comment]
Effort to have [integration tests for all Windows modules](https://github.com/ansible/community/wiki/Windows%3A-progress-tracker#missing-integration-tests). Please review and merge:
- **win_iis_webapppool**  --  @jborean93   --  https://github.com/ansible/ansible/pull/25869
- **win_iis_website**  --  @jborean93   --  https://github.com/ansible/ansible/pull/25902
- **win_unzip**  --  @dagwieers  --  https://github.com/ansible/ansible/pull/25335

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-306452743*

**Comment by dagwieers** [comment]
(@dagwieers) Using httptester (docker) for Windows win_get_url and win_uri testing.

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-307416056*

**Comment by dagwieers** [comment]
(@dagwieers) Investigate and recover from "Connection refused" errors in WinRM. ansible/ansible#25532

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-307416504*

**Comment by dagwieers** [comment]
(@jborean93) List new/missing facts from **win_setup** and make a plan.

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-312738930*

**Comment by nitzmahone** [comment]
Discuss perf changes being made to Windows CI (windows/ci/smoketest, elimination of group1/2/3)

**Comment by dagwieers** [comment]
Can we get ansible/ansible#26533 merged ?

**Comment by dagwieers** [comment]
Can we get https://github.com/ansible/ansible/pull/26612 merged ?

**Comment by dagwieers** [comment]
Can we get https://github.com/ansible/ansible/pull/26512 merged ?

**Comment by dagwieers** [comment]
Maybe it is time to think about what we still want to achieve before [the v2.4 release](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst). For example, it would be nice to finish integration tests for all modules that will ship in v2.4. Or have [Windows coverage](https://codecov.io/gh/ansible/ansible/tree/devel/lib/ansible/modules/windows) support. Or finish organizing the Windows/DSC documentation, etc.

What is achievable in the remaining time ?
And what can we communicate to the community if we need help ?

**Comment by dagwieers** [comment]
In a few months Windows Subsystem for Linux will become fully supported. At that time we need to re-clarify our position on running Ansible on WSL. Will we actively test it in Shippable as a supported configuration ? Will it be best-effort or community-supported ? Do we consider WSL as just another Linux, or does it need special care ?

https://blogs.msdn.microsoft.com/commandline/2017/07/28/windows-subsystem-for-linux-out-of-beta/

**Comment by nitzmahone** [comment]
Realized I thought of this a couple weeks ago and didn't include it on the review, but do we want to rename `win_group_member` to `win_group_membership` to be consistent with some other things (eg `win_domain_membership`), since the resource we're editing is a membership, not a member...

**Comment by andrewsaraceni** [comment]
@nitzmahone @jborean93 I can put in a PR for the rename if that's helpful (unless you're already taking care of it).

**Comment by nitzmahone** [comment]
@andrewsaraceni sure, go for it! If you do, please also rename in CHANGELOG... Thanks!

**Comment by andrewsaraceni** [comment]
Thanks @nitzmahone, just submitted PR https://github.com/ansible/ansible/pull/27614 for this - let me know if you see anything I missed.

**Comment by jborean93** [comment]
Would like a consensus for the variable we set when checking if `--diff` has been set. Currently I use `$diff_mode` but others are using `$diff_support`. This will make it easier to check if a parameter support diff if we use one variable.

See https://github.com/ansible/ansible/pull/26468#discussion_r131549379 for more details.

**Comment by gundalow** [comment]
**Ansible Contributor Summit 5 (Part of AnsibleFest 2017 San Francisco)**

When: 2017-09-06:
Notes: https://public.etherpad-mozilla.org/p/ansible-summit-september-2017
Event will be in person + online (Video + IRC)

Agenda is open for topics for the next Contributors Summit

Please add (and vote `+1`) for any topics.

**Comment by gundalow** [comment]
**NOTE:** meetings are canceled for the week Aug 21st to 25th due to 'all hands' meeting for the core team. We will resume normal schedule after that.

**Comment by dagwieers** [comment]
I have some "old" new stuff to discuss:
- win_reboot: post_reboot_delay parameter and async/check-mode fixes
  https://github.com/ansible/ansible/pull/28448
- pywinrm: Fix to retry on "Connection refused" (example)
  https://github.com/diyan/pywinrm/pull/174
- win_shortcut: Fix for env variables/UNC paths
  https://github.com/ansible/ansible/pull/27089
- win_get_url: Add use_proxy, headers and timeout
  https://github.com/ansible/ansible/pull/26612
- wait_for_connection: Remove transport_test for WinRM
  https://github.com/ansible/ansible/pull/28450

**Comment by jhawkesworth** [comment]
Could we spend some time seeing if there are any more modules that can make it in before the freeze?

Also re SID lookup utils, now that the .psm1 has been merged is anyone looking at getting the modules to use it?  See https://github.com/ansible/ansible/pull/19219#issuecomment-325727518

**Comment by jborean93** [comment]
@jhawkesworth I was going to have a look at using them in win_owner/acl/... but it will probably be a 2.5 thing.

**Comment by gundalow** [comment]
**NOTE:** meetings are canceled for the week September 4th through 8th due to AnsibleFest San Francisco. We will resume normal schedule after that.

**Comment by dagwieers** [comment]
I implemented something I wanted to do before and was discussed once before, allow modules to update system facts (managed by **setup.ps1**). I believe this is what Ansible should be doing, if we know e.g. the system requires a reboot, there's no need to keep the existing system facts wrong.

Now, I don't know if my implementation for **reboot_required** vs **ansible_reboot_pending** is perfect, as I don't know if we want to consider both the same thing in this case, and what else there is to consider. I'll let the experts here decide that, but the general idea still holds (and we probably want to update other Windows modules to do the same thing).

- Windows: Introduce Set-Fact and set reboot_pending https://github.com/ansible/ansible/pull/29170

**Comment by nitzmahone** [comment]
discuss options for fixing https://github.com/ansible/ansible/issues/23019 (basically, breaking change or no?)

**Comment by jborean93** [comment]
Discuss https://github.com/ansible/ansible/pull/28995 and see if we want to split the module up into smaller pieces or keep it as one.

**Comment by dagwieers** [comment]
Tonight, at 19:00 UTC (one hour before the Windows Working Group meeting) we plan [a second Windows Sprint](https://github.com/ansible/community/wiki/Windows:-sprints#sprint-2). During this Sprint we will review a series of open issues and take actions to get them resolved. **Everybody is welcome**. If you have an open issue that requires some attention, feel free to bring it up.

**Comment by jhawkesworth** [comment]
I can't make 3 Oct meeting but would appreciate any thoughts anyone has about this WIP PR
https://github.com/ansible/ansible/pull/31231  Possibly may need me to explain what I was thinking though, so leave it if its too obscure to understand as it is.

Also, for info, but related to the above, I had some very rought thoughts about re-organising the windows docs which I put here: https://github.com/ansible/community/wiki/Windows--ideas-for-documentation-new-structure - I have parked this at the moment as I know jborean93 is working on windows docs,

**Comment by jhawkesworth** [comment]
I'd like to discuss the implications of this https://stackoverflow.com/questions/5260125/whats-the-better-cleaner-way-to-ignore-output-in-powershell  and in particular the final answer which appears to show that 
sending things to the pipe is slow, rather than actually whether you use a [void] cast or a send output to Out-Null.
I just did a quick grep and found 60 occurrences of Out-Null in the modules in 20 modules.
If testing showed any actual speed advantage, would a PR to reduce the use of pipelining across modules be acceptable?

**Comment by jborean93** [comment]
Looking at https://github.com/ansible/ansible/pull/31289, do we want to load the registry hive under a unique name and map it to a custom key in powershell like `HKAN` (or something like that). Or do we want to keep the current behaviour where it is always mapped to `HKLM:\ANSIBLE` and people just prepend that to their path.

The former makes it seem like we are loading a hive under a new key but in reality it is still being loaded under either HKLM or HKU so it really depends on whether we want to make it more like the native tools or take a step further.

**Comment by jborean93** [comment]
The win_dsc PR https://github.com/ansible/ansible/pull/31556 fixes a few things with that module but also breaks compatibility with 2 things

* Dict type (`CimInstance`) in 2.4 need to be defined as a string, this PR changes it so it is a normal dict in YAML

Before:
```
- win_dsc:
    resource_name: xWebSite
    Ensure: Present
    Name: Ansible DSC Test
    State: Started
    PhysicalPath: C:\inetpub\wwwroot
    BindingInfo: |
      MSFT_xWebBindingInformation
      {
          Port = 8443
          Protocol = HTTPS
          HostName = *
      },
      MSFT_xWebBindingInformation
      {
          Port = 8888
          Protocol = HTTP
          HostName = *
      }
```

After:
```
- win_dsc:
    resource_name: xWebSite
    Ensure: Present
    Name: Ansible DSC Test
    State: Started
    PhysicalPath: C:\inetpub\wwwroot
    BindingInfo:
    - Protocol: https
      Port: 8443
      HostName: '*'
    - Protocol: http
      Port: 8888
      HostName: '*'
```

I can potentially add in backwards compatibility now that @trondhindenes has let me know how it was done before but strings can be quick finicky and was hoping to avoid it https://github.com/ansible/ansible/issues/31003#issuecomment-337077872

* The `attributes` and `dsc_attributes` have been removed as they were the same and there is even a third copy being set on the root `result` object. I didn't want to remove them all but was hoping to get rid of them before too many people start using the module

I was hoping to get a consensus from people around whether we should make these breaking changes or if we should try and keep compatibility. It is a preview module and was only added in the previous version and I think these are changes for the best but will go with what the crowd thinks.

**Comment by pablodav** [comment]
Hello, 

I was just curious about this: is it possible to support actual python modules in windows? 

There are cases with modules like: git, docker_* and others like that that probably there is no difference or little difference between windows and linux, so could make sense to use same module on win/linux?

**Comment by jhawkesworth** [comment]
I'd like to discuss whether its worth considering making a distinction between paths and command lines, following the discussion https://github.com/ansible/ansible/pull/32469
as @jborean93 observes originally the path type just enabled expansion of envrionment variables but then was later modified to validate paths.  However in the case above the module parameter isn't simply a path to a file, but a command line (i.e. a path to an .exe plus optional command line args), so maybe over time the module parameter name aliased and then changed to 'command_line' (or something better).

Also perhaps having a 'expand' module parameter type might be a nice thing, which just expands any env vars.  Suggestions for a better name welcome.

**Comment by dagwieers** [comment]
@ar7z1 and I want to discuss how to manage firewall rules with overlapping profiles (https://github.com/ansible/ansible/issues/32478#issuecomment-342502306) in the next meeting.

**Comment by jhawkesworth** [comment]
Just want to check everyone ok before I delete the following wiki pages which I think are now superceeded by the detailed windows guide documentation.

https://github.com/ansible/community/wiki/Windows%3A-documentation
https://github.com/ansible/community/wiki/Windows--ideas-for-documentation-new-structure
https://github.com/ansible/community/wiki/Windows-Paths---prescriptive-style

**Comment by jborean93** [comment]
Quickly talk about the `win_stat` PR https://github.com/ansible/ansible/pull/33005 and the behaviour of some of the return values. Are the names of `hlnk_targets` and `lnk_type` fine, they are not used in `stat` so I had to set my own names here. Also currently `stat` does not set `islnk: True` when the file has other hard link references. I went the route of setting `islnk: True` in these cases as `hlnk_targets` and `lnk_type` are set accordingly in these cases but was hoping for a consensus before moving ahead.

**Comment by dagwieers** [comment]
I discovered an issue with the use of **win_get_url** where the default **timeout** parameter (at 10 seconds) behaves differently on Unix as on Windows. On Windows it appears to mean the complete download needs to finish within that timeframe, whereas on Unix this is related to the connection timeout, not the *operation* timeout.

A default operation timeout of 10 seconds is problematic, and breaks existing playbooks (on larger files).

**Comment by marqelme** [comment]
Please decide if following Pull Requests are ready to get merged or if something is missing / needs to be changed:
win_disk_management
https://github.com/ansible/ansible/pull/27634
win_disk_facts
https://github.com/ansible/ansible/pull/32935

**Comment by pablodav** [comment]
How do you setup windows environment for development? 

Could be useful for new developers to have some reference in: 
https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_general_windows.html#windows-integration-testing

Something like vagrant and molecule? https://github.com/metacloud/molecule/issues/607#issuecomment-347284381

**Comment by dagwieers** [comment]
@pablodav This is not a support forum, but the agenda of a meeting. You can open an issue related to new functionality (or documentation), or create a PR with suggested changes. Also look at: ansible/ansible#33515

**Comment by quorten** [comment]
PR #26934 looks like it is ready for merging.  The Windows Working Group should see if this should get merged or closed.  From my testing, the change is required for proper IPv6 Windows support.  It would be great if winrm IPv6 support could be functional for the Ansible 2.5 release.

**Comment by jhawkesworth** [comment]
I suggest we postpone further meetings until 2018.

**Comment by jborean93** [comment]
That's probably a sensible idea, both @nitzmahone and I will be away next week so should probably postpone until the 9th.

**Comment by gundalow** [comment]
The 2.5 freeze dates (merge deadlines) have been pushed out by a week.

Please see updated dates 
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst

To see whats change please see https://github.com/ansible/ansible/commit/1826c27e6841eb313dc3a05dc7f19c96e42c7fbf

**Comment by dagwieers** [comment]
----
**This agenda has been migrated to a new location: #294**
----
