### ISSUE TITLE
Bot for WG IRC channels

### ISSUE THREAD

**Issue by gregdek** [ansible/community#197]
We're leaning on our wonderful friends on the Fedora Infrastructure team to provide bots for our IRC channels, but we're currently constrained by the number of channels a bot can serve; zodbot is pushing the limit of 150 channels across various projects.

The Fedora team is going to resolve this somehow, so this is just a place holder to make sure we are informed when that happens, and then we'll ask to have the bot set up in the various WG channels.

Will assign to @puiterwijk for tracking purposes when he accepts the invite to join the ansible/community org. :)

**Comment by robynbergeron** [comment]
Adding the infra label, unless someone feels it should be bucketed elsewhere :)

**Comment by gregdek** [comment]
Also adding cwg so can review it weekly

**Comment by puiterwijk** [comment]
The channel limit should now be lifted.
Just let me know which channels you'd like the bot to join.

**Comment by gregdek** [comment]
Thanks @puiterwijk!
