### ISSUE TITLE
Add Maintainers to organisation to allow issue/PR assignment

### ISSUE THREAD

**Issue by robinro** [ansible/community#200]
It would be nice to have a read-only group in the ansible organisation on github.

People in this group can be assigned to issues/PRs without having commit rights on the repo.

This would be especially interesting for maintainers. It can replace the "cc" mentions of ansibulbot and make better use of assignees/reviewers on PRs and makes managing issues/PRs easier for module maintainers.

Details on the permissions are at:
https://help.github.com/articles/repository-permission-levels-for-an-organization/

This is inspired by the setup of coala:
http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-1-meet-the-community-and-get-an-invitation-to-the-organization

There every interested contributor can add themselves to the read-only group.

For ansible I would start with all maintainers by syncing a group  with the MAINTAINERS/BOTMETA/OWNERS files. One can think about adding contributors in a second step.

**Comment by robinro** [comment]
Doing this would also allow to make use of github's OWNERS feature: https://github.com/blog/2392-introducing-code-owners

**Comment by gregdek** [comment]
Hmmm.

This would mean a lot of changes, potentially, but worth exploring. The question is, how much will it cost to switch to this new workflow and maintain it?

@jctanner thoughts?

**Comment by gregdek** [comment]
Pinging @jctanner again and also @mckerrj for discussion at a future core team meeting.

**Comment by robinro** [comment]
As a more general comment I think to make the project more attractive to contributors its best to use as much of the github functionality as possible and put as little as possible logic in ansibot.
If features are missing one could also talk to github about it.

Please let me know if this gets discussed in a meeting. I'll try to be there.

**Comment by lwm** [comment]
FYI: AFAIK, this is happening. I co-help in the Linode WG and now have organisation access.
