### ISSUE TITLE
List language specific IRC channels in the README

### ISSUE THREAD

**Issue by Spredzy** [ansible/community#205]
There are language-specific IRC channels on Freenode:

  * French: #ansible-fr
  * Spanish: #ansible-es 

Not sure if they are "official" or not, but if so, it would be nice to have them listed on https://github.com/ansible/community so more users/contributors can be aware of those.

**Comment by gregdek** [comment]
@Spredzy sure. Submit a PR and I'll merge.

**Comment by gregdek** [comment]
Never mind, I just did it. :)
