### ISSUE TITLE
Windows community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#208]
[![Github windows issues](https://img.shields.io/github/issues/ansible/ansible/windows.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:windows) [![Github windows PRs](https://img.shields.io/github/issues-pr/ansible/ansible/windows.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:windows) [![Windows agenda](https://img.shields.io/github/issues/detail/last-update/ansible/community/420.svg?label=agenda+update)](https://github.com/ansible/community/issues/420) [![Windows pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/208.svg?label=pinboard+update)](https://github.com/ansible/community/issues/208)

We have quite some Windows contributors on Github and Windows users on IRC that may not know it yet, but may want to join the Windows Working Group or the upcoming weekly meetings. More information about the Windows Working Group and WWG meetings is available from: https://github.com/ansible/community/wiki/Windows

You can add yourself to the Working Group by adding yourself as a member to the list. In case you want to discuss an issue or a PR during the Windows WG meeting, add it to [the meeting agenda](https://github.com/ansible/community/issues?q=is:open+label:meeting_agenda+label:windows) and join the meeting !

**Update:** Cleaned up Github mentions

**Comment by dagwieers** [comment]
List is too long for Github notifications, extending the list here:
cc: @tklaus @breathe @abarnas @deliciousfudge @brianlloyd @mrcrilly @whereismyjetpack @wenottingham @perzizzle @kstrauser @sgargan @woop @martinaders @cipress @cwacekINV @vkhramtsov @wozz @kworr @mircopatroncini @DamonOverboe @bennojoy @TimothyVandenbrande @chrishoffman

**Comment by dagwieers** [comment]
Existing pull-request contributors:
cc: @steve-dave @richardcs @andrewsaraceni @tiwood @mmasztalerczuk @LiranNis @virtuald @kamranayub @russdaygh @lnomine @nwchandler @smikulcik @barneysowood @jondelmil  @ptemplier @McBadass @tivrobo @strangeman @alex3305 @jswetzen @moriyoshi @h0nIg

**Comment by deekayen** [comment]
This is sort of sudden and doesn't really detail what sort of what commitment is involved.

**Comment by dagwieers** [comment]
@deekayen The Windows Working Group is now working and meeting for a few months already, so I guess "sudden" is in the eye of the beholder :-) We had a public sprint 2 weeks ago. But not everyone who collaborated in the past is aware we are organising us in different ways now that allows anyone to become part of, and stay involved with certain developments.

The only commitment in a community project is what one commits to herself. When working with volunteers I don't think we can ask for a commitment from anyone. People come and go. But as a community we can try to communicate better, provide easier and more dependable processes, have regular introspective meetings, so that *if* someone commits to something the community and processes are there to reach those goals.

That's why that, if you look at the [Windows WG info page](https://github.com/ansible/community/tree/master/group-windows) and [wiki](https://github.com/ansible/community/wiki/Windows], you'll see we have spent some time on laying out how we are organized and what we are planning for. And people that are interested can bring up stuff they are interested in and help out where we need help. The more people willing to lend a hand, the more and faster we can get things done, and focus on newer ideas too.

**Comment by Cryptophobia** [comment]
Interesting. How do we join? I would be happy to help but don't know if I can commit my time to attending all of the meetings.

I can help make ConfigureRemotingForAnsible.ps1 a module for the Powershell Gallery.

**Comment by dagwieers** [comment]
@Cryptophobia You can stay connected by subscribing to [the Windows meeting agenda ticket](https://github.com/ansible/community/issues?q=is:open+label:meeting_agenda+label:windows), joining the meetings when you can and/or read the meeting logs afterwards.

There is also a dedicated #ansible-windows IRC channel and if you look on [the Wiki](https://github.com/ansible/community/wiki/Windows), the Windows section has a lot of items we discussed, planned and are implementing. It's easy to start helping out if you look at the progress tracker.

If you have a topic (PR, new idea, question) to discuss, you can add it to the meeting agenda and join the meeting. The next meeting is planned on Tuesday 2017-07-25 at 20:00 UTC and will take place at the #ansible-windows IRC channel.

**Comment by jhawkesworth** [comment]
Hello past and present windows modules contributors and bug reporters.

There is a second Windows sprint for Tuesday 19th September 2017 19:00 UTC 
https://groups.google.com/forum/#!topic/ansible-project/3v7f4iXnntQ

If you have time please join us to help tackle the backlog and share experience regarding windows module development and testing.

Many thanks,

Jon

cc @h0nIg @elventear @petemounce @smadam813 @SamLiu79 @if-meaton @TimothyVandenbrande @ar7z1 @angstwad @chrishoffman @brianlloyd @cchurch @joshludwig @blakfeld @rndmh3ro @defionscode @daBONDi @schwartzmx

cc: @bielawb @dupondje @wil @lordmuffin @tjsampson @absolutejam @basictheprogram @supertom @andrewsaraceni @cptchips @dlazz @ITGuyOU @Novex @virtuald @DepthDeluxe @andmos @tomkitchen @deekayen @anguswilliams @johnnysheppard-isode @JimFicarra @anryko @Fale @JimFicarra @sherlockmatt @ilpianista @pwae @Newbe36524 @resmo @Rajeshkumar90 @qwazerty @chrisvire @bpleines @matthodge @ilpianista

cc: @jswetzen @Ssawa @adbertram @jlehtniemi-broadsoft @stylersnico @Jookadin @mss @Cryptophobia @mholiv @mingqiancoding @tklaus @breathe @abarnas @deliciousfudge @mrcrilly @whereismyjetpack @wenottingham @perzizzle @kstrauser @sgargan @woop @martinaders @cipress @cwacekINV @vkhramtsov @wozz @kworr @mircopatroncini @DamonOverboe @bennojoy @Shaps

cc: @steve-dave @richardcs @andrewsaraceni @tiwood @mmasztalerczuk @LiranNis @virtuald @kamranayub @russdaygh @lnomine @nwchandler @smikulcik @barneysowood @jondelmil @ptemplier @McBadass @tivrobo @strangeman @alex3305 @moriyoshi

**Comment by dagwieers** [comment]
The past year we made a lot of progress on the Windows front, to the point that we can say that Windows support has grown up (without bragging).

- [Totalling 80+ Windows modules](http://docs.ansible.com/ansible/devel/modules/list_of_windows_modules.html)
- Overhaul of module quality and near 100% integration tests (77 and counting)
- [Improved Windows documentation](http://docs.ansible.com/ansible/devel/modules/list_of_windows_modules.html)
- [Major improvements in WinRM and privilege escalation (become-support)](http://docs.ansible.com/ansible/devel/user_guide/windows_dsc.html)
- [Much anticipated DSC support](http://docs.ansible.com/ansible/devel/user_guide/windows_dsc.html)

If you like to become part of this future development, please try out Ansible v2.5 (release candidates), join the Windows Working Group and participating in meetings and bring up issues and ideas.

Feel free to add your name to: https://github.com/ansible/community/tree/master/group-windows

Let us know how we can improve our communication and grow this community !

**Comment by dagwieers** [comment]
Another year has passed with even more progress on the Windows front.

- The upcoming Ansible v2.8 release will ship with [100+ Windows modules](http://docs.ansible.com/ansible/devel/modules/list_of_windows_modules.html)
- The [Chocolatey support](https://docs.ansible.com/ansible/devel/modules/win_chocolatey_module.html) was improved, and new Chocolatey modules were added
- [A long list of bugs](https://github.com/ansible/ansible/pulls?q=is:pr+is:closed+label:windows+sort:updated-desc+label:bug) have been fixed
- [A new framework for Windows modules](https://github.com/ansible/ansible/pull/44705) makes modules more robust and concise
- [An alternative Windows connection plugin (PSRP)](https://github.com/ansible/ansible/pull/41729) adds reliability and efficiency
- [The Windows Working Group wiki pages](https://github.com/ansible/community/wiki/Windows) have been revamped

The Windows Working Group is always looking for more members to help out with reviewing issues and PRs. If you are interested to help out, please add yourself to [the Windows Working Group wiki](https://github.com/ansible/community/wiki/Windows).
