### ISSUE TITLE
create a very basic CONTRIBUTING.md file

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#21]
Something simple, don't go diverging far off from the practice of putting most things in docs.ansible.com/ansible/community.html , because duplication / multiple sources of truth is bad. 

Add some simple "here's where issues are listed, here's our waffleboard" type stuff.

**Comment by robynbergeron** [comment]
Fork in my repo -- https://github.com/robynbergeron/community/blob/master/CONTRIBUTING.md -- mostly because pending comments / feedback in #12 

But sharing nonetheless for context / transparency.

**Comment by gregdek** [comment]
I think that's a good enough start. We can always add/change as needed. I would say shipit.

**Comment by robynbergeron** [comment]
Okay -- PR exists for this as part of #20, because git is hard and stuff. Sooooory!

**Comment by gregdek** [comment]
Merged, closing
