### ISSUE TITLE
Newsletter Content Suggestions

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#210]
There are many existing, open-source newsletters to look to for suggested content. A basic outline -- for a newsletter audience consisting of "users of Ansible" -- is listed below.

- Big News (releases, mostly.)
- News: Relevant / interesting blog posts, videos, news articles / reviews. 
- "Tweet of the week": find a fun tweet about Ansible, add it to the newsletter. 
- Events: Upcoming meetups. larger conferences with any Ansible content, CFPs of interest. 
- Community-related news: New modules, new contributor highlights and thank-yous; potential linking to "how to get started contributing" + selected "easy-fix" type issues; rotate through various WGs and provide a "what's up in the  $whatever working group" short but sweet synopsis."
- "haz news to suggest? do so here in $locationTBD" (see #211 for this dependency).

**Comment by lwm** [comment]
I enjoyed scrolling the 'call for participation' section of https://haskellweekly.news/issues/127.html. 

That pretty much lines up with the 'easy fix' tickets. Good idea.

**Comment by gundalow** [comment]
All done apart from "Tweet of the week", which has been added to #456
