### ISSUE TITLE
Newsletter "decisions"

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#211]
- [x] Agreement on audience for newsletter.
- [ ] Infrastructure for signing up / mass mailing: suggest using Ansible org's existing infrastructure, with explicit "no merging this list of folks with other lists" rules :)
- [ ] How / where to encourage submissions of suggested content
- [ ] Figure out who (and list publicly) the "editorial" team
- [ ] Decide on a basic framework / outline
- [ ] Decide on plain text vs. html email (basically, "plain text" or allow an option to choose; html email should not be the default IMO
- [ ] Decide on "where the editing actually happens" (wiki?)
- [ ] How to "vote" if no agreement on if something should be posted (or cross that bridge when we come to it)
- [ ] How long is too long
- [ ] Who is the person who would turn the draft into the thing that goes in the system that sends out the mail? Who is the backup? 
- [ ] Cross-post (or slightly-later post) to ansible.com blog or ansible-magazine (in future if we do that?) for tweeting / sharing / getting people to sign up
- [ ] Chicken & egg problem: How do we get enough folks to sign up for a "soon" newsletter so that we have more than 0 subscribers for the first issue? 
- [ ] What day do we send the newsletter out?
- [ ] Acceptable content guidelines 
- [ ] PIck a newsletter name. Kind of useful. 😁

**Comment by gregdek** [comment]
Audience: all Ansible enthusiasts

**Comment by robynbergeron** [comment]
Meeting notes. Containing the various tentative actions / decisions / issues to file regarding the above list. Will pare down into the actual actions in another comment, but wanted to paste these in before they vanished. 

11:00 <@rbergeron> It is meeting time. so:
11:01 <@rbergeron> Meeting Topic: News! And agenda: https://github.com/ansible/community/labels/news
11:02 <@rbergeron> So: I guess from oldest to newest... (news-est, lol) --
11:02 <@rbergeron> https://github.com/ansible/community/issues/89 -- Need a good way to advertise CFPs to the wider community
11:03 <@gregdek> Which is... a regular part of the newsletter?
11:03 <@rbergeron> I think that's basically still "in process" or may be covered by decisions made re: the newsletter, or other things (ambassadors, probably.)
11:03 <@gregdek> We can sort of run two tracks here: ambassadors gather, newsletter disseminates?
11:04 <@rbergeron> Maybe? I think that assumes an element of "if they want to" -- 
11:04 <@gregdek> Right.
11:04 <@rbergeron> and "they" existing and meeting :) 
11:04 <@gregdek> Well, it can be an optional thing, I suppose.
11:04 <@gregdek> Anyway, for now it's probably more "future ambassadors" than "news".
11:05 <@rbergeron> Well -- let's cover the other things and see. :)
11:05 <@gregdek> ok!
11:05 <@rbergeron> so: next is -- https://github.com/ansible/community/issues/190 -- TODO list for news WG.
11:06 <@rbergeron> I have nothing in the wiki thus far, because I suck -- but I do have 2 issues open, the next 2 to cover, that I think will provide the fodder for such things. I suppose they could have been under "ideas" in the wiki -- and i can probably list the issues there, but figured issues 
                   were better for feedback. Along with this meeting.
11:06 <@gregdek> yep.
11:06 <@gregdek> so let's move on to those.
11:07  * rbergeron adds a note to that issue to that effect and moves on
11:07 <@rbergeron> Next: https://github.com/ansible/community/issues/210 -- Newsletter content suggestions. 
11:08 <@rbergeron> This is the basic format that most folks seem to use, including what LH and I did at that other place we worked whose name i forget. :D
11:08 <@gregdek> LOL
11:08 <@gregdek> Yup, these all look great.
11:08 <@gregdek> The question is, how do we gather, and who gathers?
11:08 <@rbergeron> This is mostly just going to twitter and digging things up, at least to start; over time, I think suggestions will come in. 
11:08 <@gregdek> Honestly, we could use this hour every week to do exactly that, to start.
11:08 <@rbergeron> Well, those are questions in the "newsletter decisions" issue :)
11:09 <@gregdek> And just have a thing at the footer of the newsletter that says "news to share? send to x!"
11:09 <@gregdek> OK...
11:09 <@gregdek> ...I'll wait :)
11:09 <@gregdek> But I think these are good general categories.
11:09 <@rbergeron> Yes. Actually, I'll add that to the outline
11:10 <@gregdek> Oh, right.
11:10 <@gregdek> So we'll have an outline we'll fill out every n weeks?
11:10 <@gregdek> Useful.
11:11 <@rbergeron> so: Yeah. I think so. It's enough to get started. 
11:11 <@rbergeron> Next (where i think lots of the actual questions 210 inspires are actually listed): https://github.com/ansible/community/issues/211 -- Newsletter "decisions."
11:12 <@rbergeron> I think it's useful to probably noodle on if we have *more* questions or pointws on which to decide that may affect how stuff might be handled or other decisions. 
11:12 <@gregdek> Whoa... checkboxes!
11:13 <@rbergeron> This is basically the "all the crap i could think of, not actually in any order" list.
11:13 <@gregdek> I didn't know you could do that!
11:13 <@rbergeron> Yes, I just discovered this. (Not sure if you can like... point to where the checkbox proof / evidence / answer actually is, but :D)
11:14 <@gregdek> OK.
11:14 <@gregdek> Who's our audience?
11:14 <@gregdek> I think "all Ansible enthusiasts".
11:15 <@rbergeron> Sure. I basically had it as "users of ansible" but that's approximately the same, but with more positivity
11:15 <@rbergeron> ;)
11:15 <@rbergeron> Mostly -- ssince there have been mentions of "developer-focused newsletter" -- i wanted to delineate which was first.
11:16 <@gregdek> ok.
11:16 <@gregdek> Yeah, not developer focused for now.
11:16 <@rbergeron> i mean -- do we want to kind of leave this open for viewing / comment ofr a few days for ppl who can't be in this meeting right now? 
11:16 <@gregdek> User focused, with maybe some developer-y stuff. Broader is better to start, yeah?
11:16 <@rbergeron> and answer some of the obvious stuff?
11:16 <@rbergeron> yup.
11:17 <@gregdek> I mean, sure, we can, but I kinda feel like most of this will be people following our lead to start, and we can always change over time.
11:18 <@gregdek> And if we hit things that make us think "ooh, we should wait"... then we wait :)
11:18 <@rbergeron> so -- i think the ones around "using the existing ansible.com mail dissemination infra" -- we need to investigate a bit.
11:18 <@rbergeron> Like, if that's kosher with them.
11:19 <@rbergeron> and knowing what it can or can't do (for example, the plain text vs. html bits.)
11:19 <@rbergeron> (and really, we can always do a "want to see the pretty version? go to $webaddress)
11:21 <@rbergeron> Suggestions for content -- I think we could probably take that via issue, esp. if we have some sort of pre-populated template, which .. might be tricky, outside of "entirely separate repo to take those in"
11:21 <@gregdek> OK, so should that be a separate issue, then?
11:21 <@rbergeron> I think so, yes.
11:22 <@rbergeron> I'm basically going to probaby try to copypasta most of this meeting log into the issue so we nkow what issues to make, unless you want to make one right now, but i suspect we'll have a bunch
11:22 <@gregdek> OK, sounds good.
11:22 <@rbergeron> kk
11:23 <@rbergeron> thoughts on "how to submit content"?
11:23 <@gregdek> I'm ok with email tbh. It's simplest.
11:23 <@gregdek> People who don't have a gh account don't have to create it.
11:23 <@gregdek> We can auto-feed into issues if we really want to.
11:24 <@rbergeron> email to... who? a mailing list? that you dom't have to sign up for?
11:24 <@gregdek> Yeah, just an alias. news@ansible.com would be fine.
11:24 <@gregdek> That goes to either us, or a script, or something.
11:24 <@rbergeron> and can we alias that out to non-ansible employees?
11:24 <@gregdek> Oh, good question there.
11:24 <@rbergeron> (or to a news-issue bot?)
11:25 <@gregdek> Well, really, I just want to avoid making people have a Github account if they don't want one.
11:25 <@gregdek> A news-bot would be better.
11:25 <@gregdek> But not sure how to hook that up inside of the ansible domain.
11:25 <@gregdek> Although...
11:25 <@gregdek> ...well, there's a bunch of ways to do that.
11:25 <@rbergeron> okay, that sounds like .. an issue :)
11:25 <@gregdek> I could auto-forward to an address that would do the right thing.
11:25 <@gregdek> Yeah.
11:26 <@rbergeron> okay. moving on then --
11:26 <@rbergeron> figure out who is the editorial team and where to list them
11:26 <@rbergeron> I am goign to assume this is "anyone on the News WG" for now --
11:27 <@rbergeron> if we get to a point of "multiple newsletters and not all ppl edit them all" we can do that
11:27 <@rbergeron> basically, "news WG is the editorial team"
11:27 <@rbergeron> yes/no?
11:27 <@gregdek> I think so.
11:28 <@rbergeron> any lingering unsureness that you want to clarify?
11:28 <@gregdek> I don't think so? LOL
11:29 <@gregdek> I mean, yes.
11:29 <@rbergeron> kk
11:29 <@rbergeron> oh
11:29 <@rbergeron> okay
11:29 <@gregdek> News WG is the editorial team.
11:29 <@gregdek> NO I MEAN NO
11:29 <@gregdek> LO
11:29 <@gregdek> LOL
11:29 <@rbergeron> i'll move on.
11:29 <@rbergeron> :)
11:29 <@gregdek> I AM CERTAIN THAT NEWS WG IS THE EDITORIAL TEAM SORRY TO BE CONFUSING
11:29 <@rbergeron> decide on a basic outline -- i think we more or less did that in #210. 
11:29 <@rbergeron> yes?
11:30 <@rbergeron> yes. :) i'll answer that.
11:30 <@rbergeron> next: Decide on plain text vs. html email (basically, "plain text" or allow an option to choose; html email should not be the default IMO)
11:30 <@gregdek> html email is the debbil.
11:30 <@gregdek> Plain text.
11:30 <@gregdek> No option.
11:30 <@gregdek> :)
11:30 <@rbergeron> So: I think plain text is the norm / standard -- and should defiitely be at least an option. So if whatever infra we have for the above ticket investigating possibilities of using existing mailing stuff --
11:31 <@rbergeron> says "html only" -- back to the drawing board, but we should verify before we settle on that.
11:31 <@rbergeron> But otherwise: yes, plain text is the key thing.
11:31 <@rbergeron> Okay, next:
11:31 <@rbergeron>  Decide on "where the editing actually happens" (wiki?)
11:32 <@gregdek> wiki is ok.
11:32 <@gregdek> i mean, that's what it's for, after all.
11:32 <@rbergeron> along with information killing itself
11:32 <@rbergeron> :D
11:32 <@rbergeron> so: yes wiki. Okay, next:
11:32 <@rbergeron> How to "vote" if no agreement on if something should be posted (or cross that bridge when we come to it)
11:33 <@gregdek> not yet
11:33 <@rbergeron> I think this is "cross that bridge when we come to it" -- i think mostly we may want to decide "how old is too old" for a piece of content or whatever to be posted
11:33 <@gregdek> yup
11:33 <@rbergeron> Maybe having some basic "acceptable content guidelines" would solve a lot of that. 
11:34 <@rbergeron> I've added that as a note.
11:34 <@rbergeron> and okay, yup from me as well. So:
11:34 <@rbergeron> " How long is too long
11:34 <@rbergeron> "
11:35 <@rbergeron> -- there may be some "internet suggestions" on this -- I think we'll probably know. Like, 4 or 5 bullet points per section is probably ... about it. 
11:35 <@rbergeron> So I think we should again just go with the flow or have some set of guidelines. 
11:35 <@rbergeron> so -- yeah, i think this is probably in the "cross that bridge if we come to it"
11:36 <@gregdek> yep. agree.
11:36 <@rbergeron> (too much content is probably a "maybe weekly is better" point)
11:36 <@gregdek> yes.
11:36 <@rbergeron> Who is the person who would turn the draft into the thing that goes in the system that sends out the mail? Who is the backup?
11:36 <@gregdek> and there's nothing that prevents us from moving back and forth.
11:36 <@gregdek> well, for now it's you or me, one is lead, one is backup.
11:36 <@gregdek> And ultimately always will be.
11:37 <@gregdek> The editing can happen by literally anyone, but those last steps are probably us.
11:37 <@rbergeron> (and since we both travel simultaneously sometimes, who is the backup-backup that isn't us? can we describe "how to send this to $human with access and with appropriate instructions"?
11:37 <@rbergeron> )
11:37 <@gregdek> Because they involve internal systems. (Unless we decide otherwise of course)
11:37 <@gregdek> I kinda think we don't have to worry about that.
11:37 <@gregdek> If we're both too busy to copypasta and click send, something is on fire. That should be 15m.
11:38 <@rbergeron> yup. 
11:38 <@rbergeron> okay.
11:38 <@gregdek> And if it doesn't go out that week because something is on fire, so be it :)
11:38 <@rbergeron> so, next: Cross-post (or slightly-later post) to ansible.com blog or ansible-magazine (in future if we do that?) for tweeting / sharing / getting people to sign up
11:38 <@gregdek> ANSIBLE WEEKLY NUMBER 7: SHIT'S ON FIRE YO
11:38 <@rbergeron> this is mostly: how do we feel about doing that? I think it would be useful at least to amass more subscribers
11:38 <@gregdek> Hm.
11:38 <@gregdek> Yeah, again, copypasta.
11:39 <@rbergeron> esp. if it's "you want this sooner?"
11:39 <@gregdek> I mean, tbh, we should basically ask Gretchen/Carrie/team to just "do that".
11:39 <@rbergeron> Well, making blogs pretty (ie: not a youtube limk but instead embed the video)
11:39 <@rbergeron> is more than copypasta :)
11:39 <@rbergeron> yeah
11:39 <@gregdek> Oh, yeah.
11:39 <@gregdek> Well, again:
11:39 <@rbergeron> yeah, agreed.
11:39 <@gregdek> That's what their team is good at.
11:39 <@gregdek> If we can give them the content, I'm sure they will be DELIGHTED to make it purty.
11:39 <@rbergeron> And i htink if / when we get ansible magazine up that will be a nice thing for there. 
11:39 <@rbergeron> as well.
11:40 <@rbergeron> so that sounds like a yes, but we should probably give some context around "how we think it might look when converted" 
11:40 <@gregdek> Yeah.
11:41 <@rbergeron> LH and i used to only post the full video embed for 1 or 2 of the 3 or 4 videos we'd link to.
11:41 <@rbergeron> Just so it wasn't busy. 
11:41 <@gregdek> Although I kinda think they'll be better at that than we are...
11:41 <@gregdek> ...but yeah, if we have specific guidelines...
11:41 <@gregdek> ...we can use 'em.
11:41 <@rbergeron> okay.
11:41 <@gregdek> I really trust Rob for good layout tho.
11:41 <@rbergeron> Will note in ... ticket-y things
11:41 <@gregdek> kk :)
11:41 <@rbergeron> Chicken & egg problem: How do we get enough folks to sign up for a "soon" newsletter so that we have more than 0 subscribers for the first issue?
11:42 <@rbergeron> Like, do we want to encourage folks during fest? Do we want to do little giveaways at events in the near future in exchange for signing up? Anything? Just expect ppl to show up?
11:42 <@rbergeron> and be like
11:42 <@rbergeron> I REALLY WANT THIS AWESOME COMMENTARY?
11:43 <@rbergeron> oh god. we should have "Ask Ansibull" question of the week at the top of the letter
11:43 <@gregdek> hmmmmmmmmm
11:43 <@gregdek> hmm
11:43 <@gregdek> hm
11:43 <@gregdek> mmmmaybe?
11:44 <@rbergeron> Ansible MOOSLETTER
11:44 <@gregdek> So I think for the first few, we just send to ansible-users with "this is special to ansible-users, to sign up, please go here"
11:44 <@rbergeron> kk --
11:44 <@rbergeron> (also, oh, newsletter title)
11:45 <@rbergeron> will add that in. Annnnnd
11:45 <@rbergeron>  What day do we send the newsletter out?
11:45 <@gregdek> ¯\_(ツ)_/¯
11:45 <@rbergeron> I think tuesdays seem to be ... a reasonable day. Though then we'd probably want to hae this meeting on Monday. Which would be a bad idea often.
11:46 <@gregdek> Ugggggh.
11:46 <@rbergeron> So maybe Tuesday meeting, wednesday mail
11:46 <@gregdek> Yeah.
11:46 <@rbergeron> Friday mail is usually unread because it's the weekend on other parts of the planet
11:46 <@rbergeron> Okay. Will mote that -- we can move this around when ... it's time to do that. 
11:46 <@rbergeron> since next week is travel week for me and i am selfish also
11:46 <@rbergeron> :)
11:47 <@gregdek> :)
11:47 <@rbergeron> I think we covered the "content guidelines would be useful" point and i'll add that in to a ticket or stub that out somewhere
11:47 <@rbergeron> ... last is
11:47 <@rbergeron>  PIck a newsletter name. Kind of useful. �
11:47 <@gregdek> oh god
11:47 <@gregdek> see, this...
11:47 <@gregdek> ...this is where we go completely off the rails.
11:48 <@gregdek> ..."Ansible News"?
11:48 <@gregdek> I suppose that's too sensible?
11:48 <@rbergeron> Ansible MOos
11:48 <@gregdek> The moos-letter
11:48 <@rbergeron> which is terribull
11:48 <@gregdek> I mean, don't we kind of have to?
11:48  * rbergeron raises an eyebrow
11:49 <@gregdek> I DUNNO I'M ASKING
11:49 <@rbergeron> ohhhh
11:49 <@rbergeron> oh, sorry, i thought youtyped "we kind of don't have to"
11:49 <@rbergeron> yes we have to. just on principle and opportunity for fun if nothing else
11:50 <@rbergeron> a little bit of personality actually makes things readable and nice vs. "i could have gotten these links myself by googling"
11:50 <@gregdek> ok. :)
11:50 <@gregdek> SO...
11:50 <@gregdek> "Ansible Moos-Letter"?
11:50 <@rbergeron> The bullpen
11:50 <@rbergeron> The Bullhorn
11:50 <@gregdek> ugh
11:50 <@rbergeron> umm
11:50 <@gregdek> Too punny?
11:50 <@gregdek> The Bullhorn
11:50 <@rbergeron> "the hot dog news letter"
11:50 <@gregdek> Kinda has a nice ring to it
11:51 <@rbergeron> I have no idea how internationally translatea-bull that word is 
11:51 <@rbergeron> Or if there's a cute ascii bullhorn 
11:51 <@rbergeron> or if there's a cute cowsay play on it that could be applied
11:52 <@gregdek> Yeah.
11:52 <@gregdek> It's tempting to pun in ways that would lose non-English speakers in a hurry.
11:52 <@gregdek> Should we... put it to a community vote? :)
11:53 <@gregdek> It's a good way to announce that it's coming, generate some interest...
11:53 <@gregdek> ...and give folks a little bit of ownership in it?
11:53 <@rbergeron> yup. 
11:53 <@rbergeron> I think so :)
11:53 <@gregdek> FUN
11:53  * rbergeron unwraps the new bikeshed and hopes people like it, since we'll use it for voting and bikeshedding
11:54 <@gregdek> twitter poll? "potential ansible newsletter title #1: the bullpen! like or share to upvote"
11:54 <@gregdek> Or just survey monkey?
11:55 <@rbergeron> well twitter is usually "click one" -- we could do both and use best judgement possibly or combine all the numbers
11:55 <@rbergeron> ... but we'd probably want to have a "where to sign up for when we do decide and write it" link to go along :)
11:55 <@rbergeron> we literally dont need the name until the moment we ship the thing
11:56 <@gregdek> yep.
11:56 <@gregdek> maybe "subscribe and get a vote"?
11:56 <@rbergeron> so let's figure out the "use the mail infrastructure" bit
11:56 <@gregdek> yeah, ok.
11:57 <@rbergeron> (we'll probably need to figure out some sort of "opt-out blah blah blah" stuff too)
11:57 <@rbergeron> and be sure it works :)
11:58 <@gregdek> Yup.
11:58 <@rbergeron> ohh, yeah i guess maybe a web page where you can sign up
11:58 <@gregdek> OK, so "figure out infra" looks like the critical path thing.
11:58 <@rbergeron> not a mail address to mail to sign up
11:58 <@rbergeron> i gues
11:58 <@gregdek> Because that's probably going to tackle a bunch of these.
11:58 <@rbergeron> is how that would work
11:58 <@rbergeron> yup.
11:58 <@gregdek> Well, I mean, "give us your email" is a thing we do a billion times a day, I imagine.
11:59 <@rbergeron> you can have all my email if you want it
11:59 <@rbergeron> :)
12:00 <@gregdek> LOL
12:01 <@gregdek> OK, so by next time, we'll have infra sorted out.
12:01 <@gregdek> Should just be a quick internal email -- you or me?
12:02 <@rbergeron> if it's me, i literally won't get to it for a while, and i think it may be easier for you to pop over during some future office visit to chat through things if meeded than it is for me
12:02 <@gregdek> ok.
12:02 <@rbergeron> I have multiple articles to edit on deadlines for ppl and ... making all the tickets
12:02 <@gregdek> I'll kick things off with an email.
12:02 <@rbergeron> and... piles. piles everywhere
12:03 <@rbergeron> but apparently not a lunch plan after all so that means i can work more
12:03 <@rbergeron> lol
12:03 <@gregdek> :/
12:03 <@rbergeron> okay, well -- looks like that's about it for meeting time :D
12:03 <@gregdek> ok :)
12:04 <@gregdek> #endmeeting
12:04 <@gregdek> :)

**Comment by dagwieers** [comment]
I missed that meeting, but here are my 2 cents...

Not sure what "enthusiasts" entails, but I think it could be useful to consider 2 different audiences: contributors and users.

Obviously you could create one newsletter that addresses both users and contributors, but: you may loose either's attention because it appears too simple / too advanced.

When I suggested to do a newsletter, the aim was to build a community of contributors. Currently maintainers or occasional  contributors do not build a relation with others. That is what I wanted to see changed.

Personally I think there are plenty of resources for the users, but what's missing is information about what the development communities are doing, etc. The more technical stuff, and that's what we should be focussing on. That's also something you'd get the existing community interested.

So communicate things like:

- New changes that affect module-writing
- Workflows and Ansibot
- Test infrastructure changes
- How to make your modules better (integration tests, unit tests, coverage)
- Changes to core, other domains (networking, windows, vmware, ...)
- Roadmaps, progress on larger cleanups
- Information about Working Groups
- Announce events (conferences, sprints, meetups, ...)

Besides, if you do this cleverly, you can write stuff that can be added to the documentation, or you can focus on a piece of the existing documentation to build an article on. In both cases it's a win.

**Comment by bcoca** [comment]
I think @dagwieers raises good points, we do have -devel channels specifically for contributors, but we have not been very good about communicating all the things on the list above through them.

Just to add my 2c, i think roadmaps, events and changes to core/domains do require wider distribution unless they are specifically targeted at contributors (like those that affect module writing or contributors' summit).

**Comment by gundalow** [comment]
We are doing this!

**Comment by gundalow** [comment]
Pull items from:
* Changes impacting Committers/Contributors #346
* Changes impacting Collection Contributors and maintainers ansible-collections/overview#45

**Comment by gundalow** [comment]
We've had 18 editions of The Bullhorn so far. Closing this as now tracked by https://github.com/ansible/community/issues/546
