### ISSUE TITLE
Add WG meeting icals to Google Calendar

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#217]
*I know this was requested earlier (as part of some other issue ticket, but couldn't find it).*

AFAIK only @mattclay can add items to the Google calendar listing Ansible meetings. Could we have all ical calendars of WG meetings from https://github.com/ansible/community/tree/master/meetings/ical imported so they are automatically updated when the .ics files change in Github ?

I don't know if this would work (i.e. do imported ical calendars exposed as part of a shared calendar ?), but it's worth a try. If this does not work, please add the various missing WG meeting calendars to the Google calendar instead. Thanks !

**Comment by gregdek** [comment]
So... um... 

Hm.

Ok, I've validated that if I add the *raw* versions of the *individual* iCals to my own calendar, they show up just fine. And I kinda think... that's just what we should tell people to do.

Which means, on the newfangled community/communication.rst page on the docs site, we should link to the individual raw files with instructions on how to add them (just use this URL to add and they should show up).

@dagwieers I guess your issue is that, if those ics files change, the calendar application won't know about the changes without being informed. But wouldn't the same be true if they imported a "master" iCal that had all the calendar entries?

**Comment by dagwieers** [comment]
I would expect it to work :-) But the proof of the pudding... let's see how this goes.
So the only action needed, is to import new URLs  for new Working Groups.
From that point onwards Working Groups should be able to update their own ical.

Thanks !

**Comment by mattclay** [comment]
I think the best thing we can do at this point is stop using the old [interactive calendar](https://calendar.google.com/calendar/embed?src=ansible.com_pafenslko0e2bqjgujp8f7s0do%40group.calendar.google.com&ctz=UTC) (which we can no longer update) and direct people to import the ICS files they care about. At least with Google Calendar it will automatically update as changes are made as long as the import was done by URL.

The old interactive calendar is no longer maintained. Although it could be replaced, doing so would require manual updates to keep it in sync with ICS changes in the repository.

**Comment by gregdek** [comment]
@mattclay are we still referencing the old interactive calendar? I thought we'd basically moved to the individual ICS files already.

**Comment by gregdek** [comment]
Anyway, I think the decision here is made: move to the individual ICS files and then clean up references to the old calendars as needed.

**Comment by gregdek** [comment]
I just removed what I believe is the last reference to the old calendar from community/meetings.

**Comment by dagwieers** [comment]
Ok, with "imported" I actually meant "added as URL" so that changes to the ICS files would automatically affect people who are using this calendar. Since the current infrastructure cannot deal with one-time events like AnsibleFest's or Ansible Automates, or code freezes etc.

There's still some need for a calendar with those events IMO

**Comment by gregdek** [comment]
Is a generic "events of interest" ICS enough?

**Comment by dagwieers** [comment]
The problem is that the tool we're using to generate ical calendars only supports recurring events. #196 
Unless that tool has been improved since...

**Comment by gregdek** [comment]
Maybe, let's move discussion to #196
