### ISSUE TITLE
Create OpenStack Working Group (note: not-quite-standard WG request)

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#219]
WORKING GROUP NAME:  OpenStack

WORKING GROUP PURPOSE: Facilitate cross-community work with the OpenStack Community.

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
- IRC: rbergeron / GitHub: @robynbergeron
- Sorry, just one for now; depending a bit upon process in OpenStack-land in conjunction with this. 

For context: Also starting an Ansible SIG in OpenStack; these two groups (this one, and the openstack one) will basically be the same group, pointing to one another as appropriate, reviewing items from both community's intended work queues. The Ansible SIG in openstack is actually the first SIG in that community, so ... working through a bit of being a guinea pig over there.

Right now: I just need wiki space, label, directory; want to hold off on irc channels, etc. until the likely members sort out where those things will likely live and how / who maintains them. Largely making this request in advance of having all the details for transparency. :)

For reference: 
- https://wiki.openstack.org/wiki/OpenStack_SIGs#Ansible
- http://lists.openstack.org/pipermail/openstack-sigs/2017-August/000032.html

**Comment by robynbergeron** [comment]
Leaving as CWG until I wrap this up and turn it into owg. :)

**Comment by jamescassell** [comment]
Does the OpenStack WG have IRC meetings, or should issues for discussion be raised at another meeting, such as core?

**Comment by dagwieers** [comment]
There is no real OpenStack WG AFAIK.
Care to start one? I can set you off quickly as we did for others.

**Comment by dagwieers** [comment]
Alright, so most of the OpenStack and issues and PRs were already labeled, I now finished it off.
I also created the initial Wiki page for OpenStack. See https://github.com/ansible/community/wiki/OpenStack

We may want to call out on a pinboard to the existing and past contributors to engage them in a discussion ? cc @gundalow

**Comment by jamescassell** [comment]
What would be required to start the WG?  I see that there is already team_openstack that ansibot knows about...

**Comment by dagwieers** [comment]
This is what I usually do:
- Create a label and label all past and open issues and PRs
- Create the wiki page with badges and some basic info
- Create a $team in BOTMETA.yml (which already existed in this case)
- Create a pinboard, cc every past and present contributor and post a message

Then wait a few days to see the response, and update the $team in BOTMETA.yml.

Sometimes we already can tell who is very active or an authority in Ansible, in other cases people step forward and take active roles.

**Comment by dagwieers** [comment]
I am going to close this ticket. We now have [a Wiki space](https://github.com/ansible/community/wiki/OpenStack) and [a pinboard](https://github.com/ansible/community/issues/447) for collaboration. Now we need members and actions!
