### ISSUE TITLE
create a label explicitly for greg/robyn tasks

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#22]
Considering making a label to be used as a secondary label for things that only Greg / Robyn can do for the time being. This is stuff like "pay bills / do expenses", meetup-related tasks, etc. 

This is mostly because we don't necessarily want to have to assign everything to one or the other of us (particularly when it's in backlog and either of us could do it) immediately; and because we want contributors to be able to easily find things they can do. 

Since we're often the ones who create these greg-or-robyn items, it seems like it would be easier for us to label those explicitly, rather than labeling everything else as "adopt me" if it's adoptable (because then we have a combo of unlabeled + adoptme things, even though often unlabeled things are adoptable, particularly if we don't religiously triage / label incoming issues.

**Comment by robynbergeron** [comment]
Also: I suggest "batmobile" as the label. Only because right now we know that at least greg and robyn are in that car, but the car could have more passengers in the future :)

Only half-jokingly :) (But willing to consider other things)

**Comment by robynbergeron** [comment]
Also: 

Yes, we could delineate along the lines of "backlog" vs. "ready" (ie: things can only be adopted from the ready column, not the backlog column) -- and maybe we keep our things in backlog until one of us self-assigns it and we put it in-progress. 

Arguments against that: backlog is sort of a capacity-management strategy; normally it would be a way to constrain how much a team is working on -- backlog can't move over until time is freed up to do things.

In a contribution environment, that's kind of a weird thing; by definition, when a new contributor wants to contribute by working on a specific task, the capacity of the overall team increases, in a sense. 

It almost seems like "adopt me" type things would be in backlog; someone could indicate they want to adopt or ask questions, and once they or we collectively scope out the further plan in the issue and when they think it might be done, it goes into Ready; once they start *actually doing work* (and showing it / linking to it in the issue), it goes to in progress. 

Or maybe too philosophical for this early in the morning. :)

**Comment by gregdek** [comment]
So why would we create a separate tag here, versus just assigning it to one of us?

**Comment by gregdek** [comment]
Per irc convo:

 <•gregdek> Not sure why we wouldn't just assign it to one of us if we know up front that it belongs to one of us.
2:50 PM <•gregdek> i.e. if it's in that class -- i.e. the kind of thing only Robyn or Greg *could* do -- then we'd know that up front and assign it.
2:51 PM nitzmahone → •nitzmahone_
2:51 PM <•gregdek> And yes, that might mean Robyn and Greg reassigning things back and forth and that's fine. :)
2:51 PM nitzmahone_ → •nitzmahone  
2:51 PM <•gregdek> Which implies that if it's a task we think anyone can do, we leave it unassigned.
2:52 PM <•gregdek> (And then we are free to pick it up ourselves once we move it into in_progress).
