### ISSUE TITLE
Public Core Meeting Agenda - August 2017

### ISSUE THREAD

**Issue by thaumos** [ansible/community#220]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

**Comment by thaumos** [comment]
bcoca wants https://github.com/ansible/ansible/pull/18662 discussed

**Comment by thaumos** [comment]
@cyberark-bizdev wants https://github.com/ansible/ansible/pull/27519 reviewed

**Comment by thaumos** [comment]
@bcoca wants https://github.com/ansible/ansible/issues/27537 discussed

**Comment by thaumos** [comment]
@dagwieers wants to discuss

Can we reconsider the new `ansible_facts` namespace and shorten it to just `facts` ? Since we are in Ansible anyway, having to specify `ansible_facts` for every fact seems pretty redundant.

Could we also get rid of the `ansible_` prefix for each fact in the new namespace? Since we now have the `ansible_facts` namespace that pretty much defeats the purpose of having that prefix.

So in the end, I would prefer that
```python
ansible_os_distribution
```
becomes accessible as
```python
facts.os_distribution
```
rather than the existing implementation
```python
ansible_facts.ansible_os_distribution
```
This will be a lot more convenient writing playbooks then the current implementation.

**Comment by marc-sensenich** [comment]
I'd like to discuss adding the module from ansible/ansible#27636

**Comment by thaumos** [comment]
2017-08-03 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.html
09:23 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.txt
09:23 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.log.html

**Comment by thaumos** [comment]
2017-08-01 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-01/ansible_meeting.2017-08-01-19.00.html
12:58 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-01/ansible_meeting.2017-08-01-19.00.txt
12:58 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-01/ansible_meeting.2017-08-01-19.00.log.html

**Comment by thaumos** [comment]
2017-08-03 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.html
09:23 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.txt
09:23 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-03/ansible_meeting.2017-08-03-15.00.log.html

**Comment by abadger** [comment]
Discuss whether we want to allow a PR to implement a stdout/stderr parameter for command: https://github.com/ansible/ansible/issues/14380 (and several associated PRs)  Can be done via piping in with the shell module but doing it in command makes quoting easier.

**Comment by dagwieers** [comment]
I would like to discuss merging ansible/ansible#25323 (new xml module). It has been re-licensed, re-worked, made python3-compatible and comes with a lot of integration tests out-of-the-box.

**Comment by abadger** [comment]
This issue is about the replace module https://github.com/ansible/ansible/issues/27779 but there's an overall question of what encoding strategy to take with modules.  SInce at least 1.7, our strategy has been utf-8 everywhere.  Recently i've merged a few patches that allow specifying an encoding parameter to choose one specific encoding other than utf-8 for what specific plugins read and write.  The issue submitter above asks about two other cases:

* Files that have mixed encodings (/etc/passwd with one line having utf-8 and a different line having latin-1, for instance)
* Files that aren't text.

**Comment by cyberark-bizdev** [comment]
Please add following PRs for discussion:

https://github.com/ansible/ansible/pull/21857
https://github.com/ansible/ansible/pull/27519

Either @cyberark_bizdev or @erasmix will be attending

**Comment by liquidat** [comment]
The link to the meeting agenda is broken, please fix that. Otherwise, new community members have no chance of attending.

**Comment by abadger** [comment]
@liquidat, which link?  I probably can fix it but I need to know what link
it is I need to change

**Comment by liquidat** [comment]
> @liquidat, which link?  I probably can fix it but I need to know what link it is I need to change

@thaumos It was the link in the original posting, the one pointing to the agenda. It was originally pointing at "https://github.com/ansible/community/blob/master/MEETINGS.md", and if I am not mistaken @dagwieers just changed it to the new, proper link. So everything is fine now.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/27897

**Comment by mikedlr** [comment]
I'd like some support to merge some of my PRs.  Maintaining and rebasing them unmerged is getting to be a pain and quite a few of them are "ready" to merge.  

Should be ready to merge 
1. https://github.com/ansible/ansible/pull/24951 - Lambda policy with tests
2. https://github.com/ansible/ansible/pull/24722 - Lambda integration tests 
3. https://github.com/ansible/ansible/pull/26059 - Lambda using new aws utils

Needs comments and reviews.
1. https://github.com/ansible/ansible/pull/26594 - rds.py utilities file
2. https://github.com/ansible/ansible/pull/27910 - or this version

Waiting for other merges above
1. new RDS modules need rds utility merge first
1.1. https://github.com/ansible/ansible/pull/26598 - new rds_instance_facts module
1.2. https://github.com/ansible/ansible/pull/26599 - new rds_snapshot_facts module
1.3. https://github.com/ansible/ansible/pull/26602 - new rds_instance module
1.4. https://github.com/ansible/ansible/pull/26604 - new rds_snapshot module 
1.5. https://github.com/ansible/ansible/pull/26606 - integration tests for RDS modules

Needs more from me then merge
1. https://github.com/ansible/community/pull/187 - community / needs AWS

**Comment by resmo** [comment]
Use apt-get as fallback for apt upgrade  https://github.com/ansible/ansible/pull/27962

**Comment by jtyr** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/24967.

**Comment by bcoca** [comment]
Meeting ended Thu Aug 10 15:55:47 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-10/ansible_core.2017-08-10-15.05.html
 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-10/ansible_core.2017-08-10-15.05.txt
 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-10/ansible_core.2017-08-10-15.05.log.html

**Comment by abadger** [comment]
Backwards incompatibility for status='preview'

Who decides whether a backwards incompatibility is okay for a module that is status='preview'?  Are there any project-wide rules we want to document regardless of who decides?

**Alternatives:**
* Leave it to the module maintainers (so the authors of the packet_device module) to discuss and decide
* Leave it to the domain experts (so the authors of modules that live inside of cloud/packet) to discuss and decide
* Decide on something(?) project-wide with case-by-case exceptions

Relates to: https://github.com/ansible/ansible/pull/23127

* **Decided**: Project wide rule: incompatibilities **must** be documented
* **Decided**: Incompatibilities mean that it's incompatible with a previous release of Ansible (if something has only existed in devel then it's fine to change).

**Comment by dagwieers** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/25089 for v2.4.

**Comment by gundalow** [comment]
**Ansible Contributor Summit 5 (Part of AnsibleFest 2017 San Francisco)**

When: 2017-09-06:
Notes: https://public.etherpad-mozilla.org/p/ansible-summit-september-2017
Event will be in person + online (Video + IRC)

Agenda is open for topics for the next Contributors Summit

Please add (and vote `+1`) for any topics.

**Comment by kustodian** [comment]
Modules `set_facts` and `include_vars` have misleading names and it would be a lot easier if they were renamed:
 * `set_facts` -> `set_host_vars`
 * `include_vars` -> `include_host_vars`
because they actually do set/include host variables. This would be very easy to do, because modules can have aliases, so the modules can be renamed and because of compatibility reasons aliases to old names could be added (and maybe in future those aliases removed).

I was talking about this with @bcoca a few weeks ago, he told me that he wants to do this.

**Comment by mkrizek** [comment]
https://github.com/ansible/ansible/pull/22206

**Comment by dagwieers** [comment]
I'd like to get the Core team's opinion on functionality we need: https://github.com/ansible/ansible/pull/26889

**Comment by bcoca** [comment]
Meeting ended Thu Aug 17 16:19:12 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-17/core_community_meeting.2017-08-17-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-17/core_community_meeting.2017-08-17-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-17/core_community_meeting.2017-08-17-15.02.log.html

**Comment by bcoca** [comment]
**Notice:** meetings are canceled for the week Aug 21st to 25th due to 'all hands' meeting for the core team. We will resume normal schedule after that.

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/26613  Digital Ocean module refactor is pulling code from modules (licensed GPLv3+) to module_utils.  We currently require those to be BSD licensed.  efforts to contact the authors are missing agreement from one person.  We need to figure out what options we have here.

**Comment by dagwieers** [comment]
Another pass at the **sleep** module: https://github.com/ansible/ansible/pull/26889
I added "Benefits vs Drawbacks" to hopefully help making a decision next meeting.

@bcoca Feel free to amend that issue with your list of drawbacks.

**Comment by dagwieers** [comment]
I would like to discuss new functionality needed by the **xml** module:
- Introduce new 'required_by' param_spec option https://github.com/ansible/ansible/pull/28662

**Comment by dagwieers** [comment]
Two items to raise that often come up during review (i.e. https://github.com/ansible/ansible/issues/20160 or https://github.com/ansible/ansible/pull/26675)

- From time to time new parameters are proposed with the unit as part of the parameter name, e.g. **expire_secs** in **win_toast** or **pre_reboot_delay_sec** in **win_reboot** and two sides of preferences. It would be nice to make a decision about this for the future we can add to the documentation.

- A common practice I have seen in modules is that the input parameters are put in the result output dictionary (usually at the start of the module). IMO there is no real value in returning the input parameters as return values again. (The user already has that information, why return it back to the user ?)

Can we come up with a guideline related to these to improve the documentation ?

**Comment by bcoca** [comment]
@dagwieers those shoudl only appear on certain verbosity levels, they should NOT be done by module authors as ansible does this automatically. This is done because the inputs can be variables, but the 'invocation information' would be the actual values.

**Comment by bcoca** [comment]
Meeting ended Tue Aug 29 20:00:25 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-29/ansible_public_core_meeting.2017-08-29-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-08-29/ansible_public_core_meeting.2017-08-29-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-08-29/ansible_public_core_meeting.2017-08-29-19.05.log.html

**Comment by dagwieers** [comment]
Reopening as there is no new agenda created.

**Comment by kustodian** [comment]
https://github.com/ansible/proposals/issues/69
