### ISSUE TITLE
Code of conduct contact address incorrect 

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#222]
http://docs.ansible.com/ansible/latest/community.html#community-code-of-conduct lists the contact address as greg@ansible.com ; I know that at some point we did obtain a codeofconduct@ansible.com address, and we should update the code of conduct with that address, as we expressed intention to do in #40 :)

(I also know we had some issue with redirecting that mail alias in the Great Crappy Mailbox Merge; not sure if that has been resolved, so we should resolve that mail alias issue before changing the address.)

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/28368 updates to use codeofconduct@ansible.com

**Comment by gundalow** [comment]
Re-openeing to ensure that the mailbox actually works, I've sent it a test email

**Comment by robynbergeron** [comment]
Actually - would it be terrible to do codeofconduct  (at) ansible (dot) com?

Wondering how much spam we might get by directly exposing the address...

**Comment by robynbergeron** [comment]
@gregdek lmk what your thoughts are on the email address / spam
possibility..

**Comment by gundalow** [comment]
We already have `security@ansible.com` in a few places. No idea how much spam that gets. I assume Google are good at filtering that out. Happy to change to whatever

**Comment by gregdek** [comment]
I suspect anything that's actually harvesting email addresses isn't fooled by (at) and (dot) anymore.
