### ISSUE TITLE
Containers  agenda item:  Support multiple containers per pod

### ISSUE THREAD

**Issue by chouseknecht** [ansible/community#225]
There is an open proposal for supporting multiple containers per pod. See [PR #639](https://github.com/ansible/ansible-container/pull/639/files).

During the next WG meeting, we should consider the following: 

- Should Ansible Container support multiple containers per pod?
- If so, does the proposed solution represent a good approach, or does it need modification?

**Comment by chouseknecht** [comment]
In the 8/14 container working group meeting the following it was decided:

- The proposal was accepted, and [PR #639](https://github.com/ansible/ansible-container/pull/639/files) has since been merged. 
- There is an implementation [PR #685](https://github.com/ansible/ansible-container/pull/685) ready for review. Both @j00bar and @marc-sensenich agreed to review.

**Comment by dagwieers** [comment]
@chouseknecht I noticed you're using the community issues for agenda-items, but the **meeting_agenda** label is not for individual items, but for complete WG agenda's. The reason for this label is to list the various meeting agenda's from the WG documentation. (As these agenda's are moving from time to time we cannot have a permanent link, so we link to them indirectly).

Could the Container WG also start using an Agenda ?

**Comment by chouseknecht** [comment]
Yeah, makes sense. My bad. Closing this, as it was previously resolved.
