### ISSUE TITLE
Collaboration on specific module development

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#226]
So I was wondering if there was an interest to create some Wiki space related to specific module collaboration. So apart from the very obvious "sets of modules" (e.g. windows, vmware, openstack) there are various modules that are just generic modules (e.g. hpilo, xml) supported by the community.

Creating a formal WG for individual modules is insane, but still it would be nice to have TODO lists and progress lists for some of these modules so those interested in these modules can collaborate.

So my proposal is to create some structure in the Wiki where this becomes possible (in an organized and structured way). I think the needs here are quite simple, maybe only a "Collaborators", "Plan" and "Progress" section  is needed. So a single page per module (or set of modules) is needed in its own name-space.

I would also allow for adding a link to this space from the module's documentation so anyone interested can find this space.

**Update:** So sometimes it takes time to get the concepts right the first time, here's a small introduction: https://github.com/ansible/ansible/issues/28481#issuecomment-324735364

**Comment by dagwieers** [comment]
I now implemented this to have a small community for the xml module:
https://github.com/ansible/community/wiki#module-communities

**Comment by gregdek** [comment]
Anyone should be free to add anything to the wiki for more or less any reason.

We'll still need a way to prune old content though.

**Comment by dagwieers** [comment]
It's not about *anyone can add freely to the wiki*, it's about ensuring that people know we are doing things like this and maybe actively help doing such things as a common practice, like if you see someone doing a good job on a module, guiding him to start sharing what he's doing with others.

A community is not a bunch of people doing whatever they like individually, I mean, we already have that on the Internet, right ? It's about finding ways to collaborate and sharing them.

**Comment by gregdek** [comment]
Well, that's sort of what a working group is, right?

I agree a working group per module is kind of heavyweight, but it's not *that* heavyweight. The dedicated IRC channel can certainly be optional.

How do you have a structure that is both distinct and well-advertised? 

Maybe the answer is that working groups are actually not structured correctly, and should be Wiki Space First.

**Comment by dagwieers** [comment]
Well, in this case we don't do meetings, issues/PRs are not specifically labeled, no IRC channel, actually there is nothing except a list of people and things to discuss/track. Not sure if a WG per module makes sense. And a "files" WG makes no sense either.

But an index of modules with such a Wiki page and the general practice of doing long-term maintenance on modules through such a Wiki page is important to build communities IMO.

Maybe the generated module docs could include a standard link to https://github.com/ansible/community/wiki/Module:-<module_name> (or it could check if it exists and then add a link to it). That could help people to collaborate on modules.

**Comment by gregdek** [comment]
Hmmm. Maybe.

Sort of just "notes on module X."

I mean, my big concern is that could turn into a dumping ground pretty quickly. I know that issues and PRs are not the greatest collaboration structure, but they are a structure that everyone understands. Having a separate "comment space here" for every module -- ok, but comments for what? What goes in the wiki space and what goes in an issue? 

I'm not opposed to the idea, I think it's interesting. I just want to make sure people understand how to use it.

**Comment by gregdek** [comment]
We could always ask the module maintainers to keep their little corner of the wiki clean, but that's another ask on a set of people who we already ask a lot of. :)

**Comment by dagwieers** [comment]
TBH The work of a maintainer should include:
- managing a roadmap for his module(s)
- tracking progress of open issues, functionality, caveats
- looking out for more maintainers and building that community
The fact that there is no link from the documentation to somewhere where a community can share information is unfortunate. That maintainers are not listed in the module documentation also does not help collaboration.

**Comment by dagwieers** [comment]
BTW In order to ensure the Wiki is not just a dumping ground, I added a note to the Wiki's footer a month ago.

*"This Wiki is used for collaboration and reporting, not documentation."*

Wouldn't mind if this can be improved while staying concise.

**Comment by dagwieers** [comment]
So we're doing it now for 2 examples, people are free to add more.
