### ISSUE TITLE
VMware Working Group - VMworld Hackathon's 2017

### ISSUE THREAD

**Issue by pdellaert** [ansible/community#229]
Soon VMworld US is on us and with it, a Hackathon is being organised. In September, the same will happen at VMworld EU.

For both VMworlds, teams have been created to be part of the Hackathons. The main goal is to have fun with same-minded people who want to learn, work and even expand or improve the Ansible VMware functionality.

You can get more information and subscribe here:
- **VMworld US**: 
  - https://blogs.vmware.com/code/2017/07/28/vmworld-hackathon-back/
  - Team 15: https://docs.google.com/spreadsheets/d/1M0sFAG2N9Zpa5H-e869eTmOaYiwuKKwlgCzP2k_wWCM/edit#gid=0
- **VMworld EU**: 
  - https://blogs.vmware.com/code/2017/08/10/vamonos-set-vmworld-europe-hackathon/
  - Team 4: https://docs.google.com/spreadsheets/d/1kAjZD5Y8ayz6OT7idrymREc9Y4E3BZhE63mfUVCbuO8/edit#gid=0

For both teams and Hackathon's we're still looking for cool ideas so any suggestion is welcome (we will be looking at fun stuff to do as well, of course).

**General info**
- General Ansible VMware working group info: https://github.com/ansible/community/tree/master/group-vmware
- Freenode IRC Channel: #ansible-vmware
- Current (2.3) Module documentation: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#vmware (the `vsphere_*` modules should be deprecated)

**VMworld US**
- A repository has been created which will hold the code: 
https://github.com/carlcapozza/SCVMWorld17
- A Slack channel has been created on the code.vmware.com slack: #hackathon-team15

cc @Akasurde @jctanner @dagwieers @chrrrles @cigamit @kassiansun @kbroughton @DMarby @dav1x @hryamzik @pchauncey @dahr @dariko @enrh @kaneda-fr @warthog9

**Comment by Kev-Johnson** [comment]
consider me signed up. I know *nothing* of Ansible, but I'm keen to learn - happy to throw some evenings between now and Barcelona into any kinds of beginners guides you may be able to recommend!

**Comment by thefluffysysop** [comment]
Hi Guys :) 
First time using Github

**Comment by pdellaert** [comment]
Welcome! :)

**Comment by vOrcunus** [comment]
Hi everyone, just signed up for the EU team and looking forward to start working with you :)

**Comment by pdellaert** [comment]
For the EU team, let's decide what we want to do, i've got two proposals:
1. Create a new Ansible module to deploy OVA's
or
2. Automate the deployment and use of vSphere Integrated Containers

(some details: https://dellaert.org/2017/09/04/vmworld-europe-hackathon-introducing-team-automation-for-all/ )

(1) is a bit more complicated, as it will require python and pyvmomi knowledge, if the team is lacking that, that's fine :).

(2) is a bit easier and is more focused on the actual use of Ansible

Personally, i'm a big fan of (2) for this team. I can make sure to do another writeup tomorrow on how to setup your environment in preparation of this (pretty simple) and to give some initial introduction/training on the use of Ansible.

(1) is of course fine as well (got some module dev behind my belt, so i can provide guidance as well)

**Comment by gregdek** [comment]
Hey @pdellaert any more action on this?

**Comment by pdellaert** [comment]
Nop, closing it :)
