### ISSUE TITLE
docs/proposals: I propose that we document that this is a thing

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#23]
I just backtracked from [this comment](https://github.com/ansible/community/issues/3#issuecomment-187854893) in #3 -- "create a proposal in docs/proposals" -- to seeing one in that directory from the lovely will thames -- and on backwards to the following mailing list thread:
https://groups.google.com/d/msg/ansible-devel/7LESbiIE2MY/lqi04fIEAwAJ

A-ha! Right, that's where this all came from, and I skimmed over that particular mail.

Since some of the things in #12 might or might not relate to this (I want to propose a new team or group that is doing something loosely related to the code, but not *in* the code -- ie: translations? or who knows what else? -- do I have to create a proposal in this directory?) -- curious what the scope of what types of proposals should be in here. Proposals for "i'm going to write a new module"? Should we have equivalent things in core / extras modules repos?

But never mind that question, because I have asked more explicitly for thoughts in #12. 

NOW THAT I SORT OF KNOW ABOUT IT KINDA, in that way that one finds out about things after going over a bunch of "how to contribute" and "ways to suggest new things" documentation, and then doing a bunch of work (ironically, with the goal of telling people "if you want to suggest $type of idea, go to $place!), and then finding out that half the things I was thinking may not be valid or correct now. 

So I propose that we document how to propose things in docs/proposals, and get that stuff in the community.html space as soon as humanly possible.

Which means we need to loosely tie off the remaining questions on the mailing list about things like "how does this get processed" and "what links back where?" and so forth as noted by House, and write something more permanent, even if it's a "this is an evolving process, feel free to improvise / poke us / ping if $unexpectedthing happens" note. 

And then write it.

**Comment by robynbergeron** [comment]
So:

Since I am the one doing the complaining... I will figure out the fix.

And will do so in a proposal in docs/proposals, and will pseudo-follow the proposal steps/stages I am proposing, and upon approval, will document the docs/proposal process. 

MINDBENDING.

**Comment by gregdek** [comment]
Ultimately, this should be a README+template in docs/proposals.

This TODO should be "create that README and figure out how to point people to it."

**Comment by gregdek** [comment]
Of course, the real issue is "how to we debate / add to such a proposal?" And we don't have a good answer to that yet. We need one, because people are asking.

**Comment by robynbergeron** [comment]
So the process i'll be proposing outlines how to debate / add to the proposal. 

And the plan is to use the proposed process as *the way* to debate / add to the proposal. 

If it doesn't work, well, we'll know that process probably isn't the best way to go about things :)

**Comment by mckerrj** [comment]
I think that works.  It's going to change so let's not over engineer up front.

**Comment by robynbergeron** [comment]
Okay, the PR for this now exists. Will mail the mailing list in short order with the guidance of "don't respond to the mail, comments / feedback should go in the PR"

https://github.com/ansible/ansible/pull/14802#

**Comment by gregdek** [comment]
Did we capture the actions from Friday's meeting, and should they go in here?

**Comment by gregdek** [comment]
Next steps:

1. Create the new repo for proposals (ansible/proposals); 
2. Move the current proposals to the new repo;
3. Update the proposal proposal as follows:

#info an artifact that is the proposal == the proposal file, submitted as a PR and immediately merged

#info a way of tracking discussions of that artifact == a single issue, referenced in the proposal file

#info a way of modifying the artifact == PRs to that file, merged or not at submitter's discretion and discussed in the issue

#info a way of putting the artifact into buckets == maybe issue tags?

#info a time/place to discuss == weekly proposal meeting.

**Comment by robynbergeron** [comment]
https://github.com/ansible/ansible/pull/14929 is waiting for someone to merge.

**Comment by robynbergeron** [comment]
Okay, @gregdek merged that for me. :D So now, per our meeting notes:

#action rbergeron to now move docs/proposals remains to ansible/proposals
#action rbergeron to recirculate this draft in its current form to mailing list
#action rbergeron to then take it to a public irc meeting for ... hugs

**Comment by robynbergeron** [comment]
okay, so: I pinged the core team to ask for help on this. Turns out moving a bunch of stuff to a separate repository is like, NOT SO SIMPLE, if you want to preserve history, and breaking the universe is not a thing i love doing.   Some random helper tips I found: 

https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

http://ariya.ofilabs.com/2014/07/extracting-parts-of-git-repository-and-keeping-the-history.html

Will update when i find out who might do such magical stuff.

**Comment by gregdek** [comment]
Decided not to keep history and just move over the new files.

**Comment by gregdek** [comment]
OK, moved:

https://github.com/ansible/proposals

Now the question is, when do we start discussing these proposals?

**Comment by gregdek** [comment]
Yeah, we have a lighter weight idea now. @robynbergeron will move forward with it.

**Comment by gregdek** [comment]
Goal is to discuss in Wednesday's meeting.

**Comment by gregdek** [comment]
So conclusion is, @robynbergeron will send out the link to ansible-devel, we'll entertain discussion, and then next week we'll ratify unless we get significant pushback.

**Comment by robynbergeron** [comment]
Note that https://github.com/ansible/proposals/issues/5 is the proposal proposal issue

**Comment by robynbergeron** [comment]
gregdek to ping jimi in a day or two to confirm times of Tue 1400 
                   UTC and Thu 1900 UTC

**Comment by gregdek** [comment]
Ratified and in the meeting agenda for the core team. Done!
