### ISSUE TITLE
Create wiki page for Ansible Contributor Summit organization process 

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#230]
Consolidate steps / process / best practices for organizing a Contributor Summit into a wiki page under ansible/community / community working group space. AKA: SOP (standard operating procedure). 

@gundalow you mentioned in today's CWG meeting you have related content that may be useful -- feel free to note it here as you see fit. (Maybe in a gist or something?)

**Comment by gundalow** [comment]
I think they ended up as part of https://github.com/ansible/community/tree/master/meetings
