### ISSUE TITLE
[Docs] Fix community workflow documentation 

### ISSUE THREAD

**Issue by gregdek** [ansible/community#234]
Now that we have a separate permanent workflow documentation page about to land for ansible/ansible, we need to review it to make sure it's correct (it's kind of correct now, but Ansibot has advanced a long way since we first wrote this doc.)

**Comment by gregdek** [comment]
OK, we spent the community working group session at Fest working on this. Here's the full readout of things that need to be done:

In this session, we are running down all of the docs issues with the new community docs, and will turn them into a ticket/tickets as appropriate.
First, the top-level sidebar link from docs.ansible.com ("Community Information and Contributing") is out of date and points to the old docs page instead of the new docs directory.  Note: broken in *both versions*, both stable and devel! (Once you get into the docs site, the sidebar is correct.)
Q#1: do we actually want the roadmap items to live in docs, as they do now apparently and are linked as such, or do we want to link directly to Github? (jason) (probably the right answer is point directly to Github)
Add to community maintainers section: how does one become a community maintainer? What is the process?
Is "ready_for_review" still a valid state? Should it be removed? (We should at least note that it's a legacy state)
"new_module" is actually pretty good, maybe? We should describe the process here, even if it's just "to speed up potential inclusion, you can always come to the meeting to advocate".
First four links go to the same page -- is that confusing? It's kind of confusing to me!
Reporting a bug: add more info about necessity of including component name, since that's how the bot determines who owns the issue
Reporting a bug: just re-read this generally, a lot of this text is from 3-4 years ago
"Reporting A Bug" is in caps and should be lower case
"how_can_I_help.html": "Become a module maintainer" should link to the "module maintainer guidelines" 
Rework "working group guidelines" to better documentation (maybe "creating a working group" is not actually helpful and we should point to existing working groups as well)
Link to Ansible development process isn't marked up correctly in the RST (yup)
Open Q: should we autoclose PRs that are in needs_revision for a long time? It doesn't hurt to close them, they can be reopened. (gdk will revisit with product management)
Module Maintainer Guidelines:
typo: "Thank you for being a maintainer of one Ansible’s community modules!"
Broken link: "[ansible/ansible](https://github.com/ansible/ansible) repository"
Broken link: "[contribution guidelines](https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md),"
...and others
Extras maintainers list should now point to BOTMETA
Either change or remove "A detailed explanation of the PR workflow can be seen here: https://github.com/ansible/community/blob/master/PR-FLOW.md" (or just point to Sam's page)
Fix "Change Maintainership" link
And add an explicit "orphaning" process (use "ignored"?)
Be more explicit about which modules are unmaintained / orphaned
If we have an explicit "orphaning" process, that can *also* be an "unresponsive" process as well
What are reasonable expectations for orphaning?
Change "tools and other resources" to point to the "other tools and programs" page
Other tools and programs doesn't contain ansibullbot info so that might need adding at the same time
Add: Ansible Doctor (https://github.com/ansible/ansible-doctor)
Ansible Inventory Grapher: https://github.com/ansible/ansible/pull/29065
Review from here: https://tannerjc.net/wiki/index.php?title=Ansible_Community_Projects
Add the Code of Conduct link to the index (http://docs.ansible.com/ansible/devel/community/code_of_conduct.html)
Is there anything in http://docs.ansible.com/ansible/devel/community.html that should be under http://docs.ansible.com/ansible/devel/community ? (should be sorted as part of the original port)

**Comment by gregdek** [comment]
I'll get a patch together for all this here in the next week or two.

**Comment by gregdek** [comment]
OK, progress started here. It's in the gregdek/ansible devel branch.

**Comment by gundalow** [comment]
Also https://github.com/ansible/ansible/projects/31
