### ISSUE TITLE
Make sure that docs.ansible.com/community always points to devel version

### ISSUE THREAD

**Issue by gregdek** [ansible/community#239]
There will never be meaningful "previous versions" of community documentation, since we always want this documentation to be current.

**Comment by gundalow** [comment]
+1000

I'd like to see the same logic applied to `dev_guide`, although the content may change all new feature always targets `devel` and given the efforts to improve the docs it would be a shame if people ended up looking at older docs

**Comment by gundalow** [comment]
Added to https://github.com/ansible/proposals/issues/60#issuecomment-329800297

**Comment by gundalow** [comment]
We will be moving contributor docs to docs.ansible.com/community (which will not be versioned).
