### ISSUE TITLE
Public Ansible Project Meeting Agenda - September 2017

### ISSUE THREAD

**Issue by thaumos** [ansible/community#240]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by thaumos** [comment]
@kustodian wanted to go over:

All file modules should have a sane default follow parameter

ansible/proposals#69

**Comment by thaumos** [comment]
@albertomurillo wanted to go over.

https://github.com/ansible/ansible/pull/28292

**Comment by thaumos** [comment]
12 September 2017 Meeting:

12:24 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-12/ansible_project_meeting.2017-09-12-19.00.html
12:24 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-09-12/ansible_project_meeting.2017-09-12-19.00.txt
12:24 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-12/ansible_project_meeting.2017-09-12-19.00.log.html

**Comment by thaumos** [comment]
14 September 2017 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-14/ansible_community_meeting.2017-09-14-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-09-14/ansible_community_meeting.2017-09-14-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-14/ansible_community_meeting.2017-09-14-15.00.log.html

**Comment by ssbarnea** [comment]
Proposal for ansible.cfg path expansion variable https://github.com/ansible/proposals/issues/73

**Comment by gundalow** [comment]
Declarative Intent proposal https://github.com/ansible/proposals/issues/70

**Comment by gundalow** [comment]
Aggregate (loops) proposal https://github.com/ansible/proposals/issues/71

**Comment by thaumos** [comment]
19 September 2017 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-19/ansible_project_meeting.2017-09-19-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-09-19/ansible_project_meeting.2017-09-19-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-19/ansible_project_meeting.2017-09-19-19.00.log.html

**Comment by jtyr** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/28375 on Thu 21th Sep.

**Comment by bcoca** [comment]
not much discussed 2 requests to review plugins.

https://github.com/ansible/community/tree/master/meetings".
Meeting ended Tue Sep 26 19:24:20 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-26/ansible_core_team.2017-09-26-19.04.html
 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-09-26/ansible_core_team.2017-09-26-19.04.txt
og: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-26/ansible_core_team.2017-09-26-19.04.log.html

**Comment by albertomurillo** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/29031 on sept 28

**Comment by dagwieers** [comment]
I would like to discuss ansible/proposals#74 and implementation https://github.com/ansible/ansible/pull/30957

**Comment by thaumos** [comment]
28 September 2017 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-28/ansible_dev_meeting.2017-09-28-15.00.html
08:58 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-09-28/ansible_dev_meeting.2017-09-28-15.00.txt
08:58 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-28/ansible_dev_meeting.2017-09-28-15.00.log.html

**Comment by bcoca** [comment]
what to do with `inventory_dir` when `add_hosts` in >= 2.4 
https://github.com/ansible/ansible/issues/30901

**Comment by dagwieers** [comment]
Beware that if we are rolling over agenda's every month, people wishing to track changes will have to re-subscribed to the new agenda (issue). So my preference is to only roll over the agenda when the number of (closed) comments become unmanageable.

In this case we could have repurposed this issue for October and maybe even November.

**Comment by thaumos** [comment]
@dag, yes that's what I do. This month was small enough to roll over.  I don't want issues to be long in the tooth either.  The threading on issues is not a good method for tracking this in my opinion, but it's what we use. 

When I roll over I copy every thing that rolls over and @ tag a user.  I didn't do it this time due to time restriction.  So that's my fault.
