### ISSUE TITLE
Sponsorship inquiry from North Bay Python

### ISSUE THREAD

**Issue by joshsimmons** [ansible/community#246]
Hello, Ansible community!

I'm helping to organize [North Bay Python](https://northbaypython.org), a nonprofit community conference being held an hour north of San Francisco on the weekend of December 2-3, 2017. It's a first year conference with a super experienced organizing team (eg. OSCON, Linux.conf.au, PyCon AU) and our goal is to put on a high quality event on a shoestring budget.

To do so, we need sponsorship and I'm wondering if the good folks behind Ansible might be able to help. A little about us:

We've woven inclusion and diversity into everything we do -- outreach, speaker mentorship and training, financial assistance, affordable tickets and lodging, and, of course, a code of conduct with enforcement procedures. Our sponsorship goal, so we could include things like childcare and open captioning, was $60K but it doesn't look like we'll hit that. Our current goal is $30K so we can at least clear costs and produce video recordings.

We expect 350-450 attendees, mostly from the SF Bay Area, though we are seeing interest from people as far north as Vancouver BC, as far south as San Diego, and as far east as Ohio. We expect many seasoned professionals from the tech industry to show up, but we are explicitly courting junior developers, students, and people who use Python in their work but may not describe themselves as developers, such as researchers and data scientists.

We are a member project of Software Freedom Conservancy so we are, truly, a nonprofit event and a percentage of sponsorship and ticket sales go to fund SFC programs :-)

It would mean the world to us, and the people we are helping into the industry, if you [joined us as a sponsor](https://2017.northbaypython.org/sponsors/become-a-sponsor).

Please let me know if you have any questions, or email us at sponsor@northbaypython.org. Thank you so much for the consideration <3

**Comment by gregdek** [comment]
I don't know if we successfully handled this or not, which is bad -- at any event, the date has passed. @joshsimmons apologies for not handling this issue in a timely way.
