### ISSUE TITLE
Network Working Group Meeting Agenda 2

### ISSUE THREAD

**Issue by gundalow** [ansible/community#247]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/tree/master/group-network for the schedule

All Core Networking issues (most recently updated at the top):
https://github.com/ansible/ansible/issues?q=is%3Aopen+label%3Anetworking+-label%3Aneeds_revision+sort%3Aupdated-desc

Network Working Group: https://github.com/ansible/community/tree/master/group-network

`#ansible-network` on Freenode IRC

**Comment by gundalow** [comment]
**Ansible 2.4.0 FINAL**

https://groups.google.com/forum/#!msg/ansible-announce/IrLR3pjNZnk/J8s-uC5EAgAJ
Lot of network improvements, especially to NXOS
Please do take a look
If you find any bugs please report them at https://github.com/ansible/ansible/issues/new

Thank you all for your help during this release.

**Comment by gundalow** [comment]
From @saichint ansible/ansible#29143 Integration Tests only: nxos_udld, nxos_udld_interface, nxos_vxlan_vtep_vni

Migrated from https://github.com/ansible/community/issues/110#issuecomment-329234544

**Comment by gundalow** [comment]
Proposals for 2.5 that we'd like your input on:
* https://github.com/ansible/proposals/issues/71 Hold off and redesign Aggregates
* https://github.com/ansible/proposals/issues/70 Hold off and redesign Declarative Intent

We welcome all of your input on this, making sure we implement something that's useful and easy to understand.

**Comment by gundalow** [comment]
From @Gelob https://github.com/ansible/ansible/issues/30250 Arista EOS module doesn't properly parse vrfs

Migrated from https://github.com/ansible/community/issues/110#issuecomment-330420196

**Comment by gundalow** [comment]
All,
If you could raise PRs to update the list of Network Group members on https://github.com/ansible/community/tree/master/group-network that would be very helpful given the large and growing community.
Add GitHub, real name, company/affiliation and IRC name (if different to GitHub)
Thanks in advance.

**Comment by gundalow** [comment]
From @caphrim007

https://github.com/ansible/ansible/pull/30577 This module allows users to manage partitions on a BIG-IP
~~https://github.com/ansible/ansible/pull/30584 Changes ignored and maintainers for the f5 modules.~~ MERGED

Migrated from https://github.com/ansible/community/issues/110#issuecomment-330675257

**Comment by privateip** [comment]
https://github.com/ansible/proposals/issues/76

**Comment by caphrim007** [comment]
* https://github.com/ansible/ansible/pull/30998

**Comment by eoprede** [comment]
https://github.com/ansible/ansible/pull/30767
This is 1 module out of roughly 20 that I am looking to contribute. 
My IRC name is Gesha24

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/31202
> Should we add cdp information to the lldp fact, since it is basically the same. We could add an attribute source in ansible_net_neighbors with value cdp/lldp ?

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#31401
This moves files from lenovo folder to cnos folder

**Comment by caphrim007** [comment]
* https://github.com/ansible/ansible/pull/30391

**Comment by amuraleedhar** [comment]
Please merge 
ansible/ansible#31507
ansible/ansible#31508
ansible/ansible#31509
ansible/ansible#31510
ansible/ansible#31512
This are util files, plugin files and doc file for enos modules

**Comment by amuraleedhar** [comment]
I am trying to add modules for enos of lenovo. I started on by creating a folder and adding __init__.py to it using Github Desktop. It seems I don't have permission to create this folder and file. I can add rest of the files using Web access of github but __init__.py has to be a zero size file which I think cannbot be pushed through web access. Please help

**Comment by amuraleedhar** [comment]
Updated my PRs to be merged List shown above

**Comment by calfonso** [comment]
We need to complete the conversation around aggregates https://github.com/ansible/proposals/issues/71 and decide if we are going down the loop route or not.

**Comment by gundalow** [comment]
Docs: Network getting started example https://github.com/ansible/ansible/pull/31807

**Comment by gundalow** [comment]
Meeting ended Wed Oct 18 17:04:59 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-network/2017-10-18/network_working_group.2017-10-18-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2017-10-18/network_working_group.2017-10-18-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2017-10-18/network_working_group.2017-10-18-16.00.log.html

**Comment by gundalow** [comment]
Review wanted on https://github.com/ansible/ansible/pull/31807 Docs: Network getting started example

**Comment by saichint** [comment]
I would like to to merge these 2 PRs.
https://github.com/ansible/ansible/pull/29143
https://github.com/ansible/ansible/pull/28933

**Comment by amuraleedhar** [comment]
I would like to to merge these 2 PRs.
ansible/ansible#31696
ansible/ansible#31401

**Comment by rahushen** [comment]
PRs:
ansible/ansible#29030 
ansible/ansible#28939

**Comment by gundalow** [comment]
Meeting ended Wed Oct 25 16:40:12 2017 UTC.
Minutes: https://meetbot.fedoraproject.org/ansible-network/2017-10-25/network_working_group.2017-10-25-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2017-10-25/network_working_group.2017-10-25-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2017-10-25/network_working_group.2017-10-25-16.00.log.html

**Comment by jmighion** [comment]
PR: https://github.com/ansible/ansible/pull/32172

**Comment by gundalow** [comment]
Meeting ended Wed Nov  1 16:46:43 2017 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-network/2017-11-01/network_working_group.2017-11-01-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2017-11-01/network_working_group.2017-11-01-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2017-11-01/network_working_group.2017-11-01-16.00.log.html

**Actions**

* ganeshrn to review 32172, merge and CP into 2.4
* EVERYBODY If you think anything is missing from https://github.com/ansible/ansible/issues?q=is%3Aopen%20label%3Anetworking%20milestone%3A2.5.0 please let us know in #ansible-network
* Gundalow to add facts discussion to internal team agenda

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#31696

**Comment by jmighion** [comment]
PR: https://github.com/ansible/ansible/pull/32602

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#31401. Rebasing done and conflicts are resolved

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#32782.

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#32895

**Comment by rahushen** [comment]
ansible/ansible#28939

**Comment by gundalow** [comment]
From Core discussions "Deprecate using jinja tests as filters"
* https://github.com/ansible/proposals/issues/83 Proposal
* https://github.com/ansible/ansible/pull/32361 WIP implementation

Comments welcome on the proposal

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#32966.
This contains fix for cli context issues for ENOS switches associated with network_cli

**Comment by gundalow** [comment]
nmap dynamic inventory https://github.com/ansible/ansible/pull/32857

**Comment by gundalow** [comment]
Now that https://github.com/ansible/ansible/pull/32825 is merged the Persistent Connection is terminated at the end of each play.

**Comment by gundalow** [comment]
network_cli developer documentation https://github.com/ansible/community/blob/master/group-network/network_dev_network_cli.rst

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#33081
This is enos_config.py module addition.

**Comment by mikewiebe** [comment]
Need to discuss the following PR's
* https://github.com/ansible/ansible/pull/31524 and impact to ISSU capability
* https://github.com/ansible/ansible/pull/33376
   * Would like to understand the history here of why it's being deprecated and impact to existing users.

**Comment by amuraleedhar** [comment]
Please merge ansible/ansible#33857

**Comment by samerd** [comment]
Hi,
Please merge all mlnxos modules:

- [ansible/ansible/#34285](https://github.com/ansible/ansible/pull/34285)
- [ansible/ansible/#34286](https://github.com/ansible/ansible/pull/34286)
- [ansible/ansible/#34287](https://github.com/ansible/ansible/pull/34287)
- [ansible/ansible/#34305](https://github.com/ansible/ansible/pull/34305)
- [ansible/ansible/#34307](https://github.com/ansible/ansible/pull/34307)
- [ansible/ansible/#34323](https://github.com/ansible/ansible/pull/34323)
- [ansible/ansible/#34326](https://github.com/ansible/ansible/pull/34326)
- [ansible/ansible/#34327](https://github.com/ansible/ansible/pull/34327)

I finished pushing all mlnxos_modules for this ansible version, (except maybe bug fixes)

Thanks,
Samer

**Comment by gundalow** [comment]
The 2.5 freeze dates (merge deadlines) have been pushed out by a week.

Please see updated dates 
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst

To see whats change please see https://github.com/ansible/ansible/commit/1826c27e6841eb313dc3a05dc7f19c96e42c7fbf

**Comment by amuraleedhar** [comment]
Please merge a bug fix in cnos.py module_util file.
ansible/ansible#34607
Some of Switch ports support break-out, such as there maybe "interface eth 1/87/1" for G8296 etc.
This fix address such changes in switch prompts.

**Comment by amuraleedhar** [comment]
Please merge a bug fix reported in backup functionality
ansible/ansible#34789
ansible/ansible#34793
In these fixes, I am adding code to create folder for backup in <rolepath>/backup with a config backup filename as <IP Address>config<time stamp>
Another review was to use load method instead on loadfp. I have accomplished this comment as with minimum changes.

**Comment by grastogi23** [comment]
Discuss use of VCR for acceptance test. https://pypi.python.org/pypi/vcrpy

**Comment by gundalow** [comment]
FortiOS and FortiGate
https://github.com/ansible/ansible/pull/33591#issuecomment-364775042
Would like feedback on this approach

**Comment by amuraleedhar** [comment]
Please merge this PR
ansible/ansible#36840 
These are changes in license information after review by Legal team of Lenovo

**Comment by amuraleedhar** [comment]
Please merge the following documentation / license PR
ansible/ansible#36851

**Comment by grastogi23** [comment]
https://github.com/ansible/ansible/pull/36468

**Comment by gundalow** [comment]
*Ansible 2.5.0 Release Candidate 2* is now available! Get it on PyPI: `pip install ansible==2.5.0rc2`, https://releases.ansible.com/ansible/, or GitHub. 
* This is likely to be the final Release Candidate, so please test, and raise issues on GitHub
* Lots of new network documentation http://docs.ansible.com/ansible/devel/network/
* No more `unable to open shell`!
* First class plugins for `connection: network_cli` and `connection: netconf`. `connection: local` will continue to work. Please read this the docs and see that platform specific notes for EOS, Junos and NXOS if you are use them.
* Loads of bug fixes. 
* Thank you to all that have tested and provided feedback and PRs so far, can't do this without you. 
* Happy automating!

**Comment by samerd** [comment]
[ansible/ansible#37310](https://github.com/ansible/ansible/pull/37310)
please review and merge if OK.
I have another bug fix that based on it

**Comment by Qalthos** [comment]
A proposal for eAPI connection type: https://github.com/ansible/proposals/issues/102

**Comment by calfonso** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-04-04/ansible_network_workgroup.2018-04-04-16.02.html

Log: https://meetbot.fedoraproject.org/ansible-network/2018-04-04/ansible_network_workgroup.2018-04-04-16.02.log.html

**Comment by ganeshrn** [comment]
Proposal on Netconf modules: https://github.com/ansible/proposals/issues/104

**Comment by ganeshrn** [comment]
Deprecation of `connection=local` and `provider` for Network modules.

**Comment by Qalthos** [comment]
Review HTTP connection proposal ansible/proposals#103

**Comment by calfonso** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-04-18/network_working_group.2018-04-18-16.00.html

Log: https://meetbot.fedoraproject.org/ansible-network/2018-04-18/network_working_group.2018-04-18-16.00.log.html

**Comment by brampling** [comment]
I have a customer looking for these which are waiting for review:

https://github.com/ansible/ansible/pull/37543
https://github.com/ansible/ansible/pull/37580
https://github.com/ansible/ansible/pull/37582
https://github.com/ansible/ansible/pull/37583
https://github.com/ansible/ansible/pull/37676
https://github.com/ansible/ansible/pull/37678

**Comment by brampling** [comment]
With respect to https://github.com/ansible/ansible/issues/39386#issuecomment-384773801

It's not very clear that the NIOS lookup plugins exist. Is there some way to indicate that in the documentation section for the NIOS net_tools modules?

**Comment by amuraleedhar** [comment]
Please review and merge 
ansible/ansible#39665
This is a bug fix on cnos util module. This has to be backported to 2.5 as well.

Thank You.

-Anil

**Comment by acozine** [comment]
Clarifying terminology for network-engine role. Background:
We've used the word “parser” to describe the file with the matching rules, the module that does the matching, and the combination of the two. We're working to clarify the usage and make the modules in network-engine easier to understand and use. See https://github.com/ansible-network/network-engine/issues/65.

**Comment by amuraleedhar** [comment]
Please review and merge
ansible/ansible#39955
Here I am modifiying cnos_facts, cnos_command to align with how it is done for other vendors. In addition to this I am adding cnos_config also. Here I am using persistent connection. Therefore all the three plugins are also introduced for this purpose viz. action, cliconf and terminal plugins. The documentation snippet in util is brought into each module documentation as they differ here.  module_util/cnos.py is added with all methods that are required for this.  Added unit test for each of them. In addition to that i have removed few errors from the ignore.txt as they have been addressed here

Please review and merge

Thank You.

-Anil

**Comment by amuraleedhar** [comment]
Please review and merge
ansible/ansible#40218
Starting with our recent CNOS release version 10.7, we have moved certain CLI keywords to match with Industry Standard CLI (ISCLI) keywords. For backward compatibility, old CLI keywords will continue to work for next one or two CNOS releases with a condition that “command acronyms” of old CLI keywords, cannot be used. For eg: Use “display version” instead of “disp ver”. This PR is to expand the acronymns if they are present in the python code

This has to be backported to 2.5 as well.

Thank You.

-Anil

**Comment by mikewiebe** [comment]
https://github.com/ansible/ansible/pull/40102

**Comment by amuraleedhar** [comment]
Please merge the PR 
ansible/ansible#40865

This is to fix the copy paste error in CNOS plugin files. Corrected typo ENOS to CNOS. There was few merge issue in some enos license text. This also fixed.

**Comment by mikewiebe** [comment]
I would like to discuss the following issue:

https://github.com/ansible/ansible/issues/40683

**Comment by caphrim007** [comment]
https://github.com/ansible/ansible/issues/40913

**Comment by amuraleedhar** [comment]
Please merge the PR
ansible/ansible#41121

This is to fix the copy paste error in CNOS facts . This issue came revealed when I ran a coverity scan.

**Comment by Qalthos** [comment]
> Meeting started Wed Jun 13 16:01:01 2018 UTC.
> Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-06-13/network_working_group.2018-06-13-16.01.html
> Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-06-13/network_working_group.2018-06-13-16.01.txt
> Log: https://meetbot.fedoraproject.org/ansible-network/2018-06-13/network_working_group.2018-06-13-16.01.log.html

**Comment by caphrim007** [comment]
* Discuss inclusion of 2.7 backport of Python's ipaddress.py module for usage in F5 modules. Backport is here https://raw.githubusercontent.com/phihag/ipaddress/master/ipaddress.py

Same license terms would be included as seen in Ansible's ismount code found here 
https://github.com/ansible/ansible/blob/6787fc70a643fb6e2bdd2c6a6202072d21db72ef/lib/ansible/module_utils/ismount.py#L7

F5 wants to do this for the following reason

* remove the netaddr dependency in several of its modules.

The reason for this is the current implementation in the modules places a dependency that must be met in Ansible (in the form of tests) and met by F5's customers (remembering to install `netaddr`). This second issue leads to more support requests, which are unnecessary, because this dependency can be removed.

The requested code to include, is provided natively in Python 3.x. This code would be used as a shim until such time as,

* Python 3.x is considered "normal" across the Ansible user community
* Python 3.x is considered "normal" across the F5 community which uses Ansible.
* Python 2.x development ceases https://www.python.org/dev/peps/pep-0373/

I think that based off of the pre-existing work in Ansible, and the known GPL-compatibility of the PSF and GPL3, that this should be a non-issue provided that the ipaddress.py code is clearly documented as such (and that that license does not extend beyond the ipaddress.py file.

There is existing work in Ansible's module utils to support rudimentary IP address work. F5 needs the enhanced library to support IP networks in addition to the existing IP addresses.

This module utility would only be included in F5's module_utils directory; not the larger network/common or its sub dirs. Other module authors using this module_util would assume the risk of it being removed per the bullets mentioned above.

**Comment by Qalthos** [comment]
> Meeting started Wed Jun 20 15:59:50 2018 UTC.
> Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-06-20/network_working_group.2018-06-20-15.59.html
> Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-06-20/network_working_group.2018-06-20-15.59.txt
> Log: https://meetbot.fedoraproject.org/ansible-network/2018-06-20/network_working_group.2018-06-20-15.59.log.html

**Comment by amuraleedhar** [comment]
Please merge 
ansible/ansible#41998

This is to add the expansion of CNOS CLI acronymns into Change Logs

**Comment by gundalow** [comment]
**Ansible 2.6.0 final is now available**
See 
From a network point view
**Connection Plugins**
* `httpapi` - New connection method that simplifies connections to platform-specific APIs such as Arista eAPI and Cisco NXAPI. This method replaces  connection: local with `connection: httpapi` and then specifying the specific platform via the `ansible_network_os` variable.

**Modules**

* `net_get` - downloads a large config file to target network device with SCP/SFTP
* `net_put` - copies a large config file to target network device with SCP/SFTP
* `netconf_get` - fetches the configuration and state data from remote NETCONF enabled network device/host
* `netconf_rpc` - executes generic NETCONF RPC commands that are defined by NETCONF standard as well as proprietary RPC-based NETCONF capabilities supported by the remote network device/host

**General**
* There will be an Ansible 2.6 blog post soon with more details and links in.
* Various updates have been made to https://docs.ansible.com/ansible/latest/network/
* For more information on the connection types see https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html
* For changelog and porting guide please see https://groups.google.com/forum/#!topic/ansible-devel/P5KPevGGlmE
Happy Automating!
As always please report any issues at https://github.com/ansible/ansible/issues/new/choose

**Comment by gundalow** [comment]
**2018-07-04**

**Summary of key points**

* Ansible 2.6.0 has been released, see https://github.com/ansible/community/issues/247#issuecomment-401423602 for more info
* Expect updates to 2.6.x every three weeks

**Team status update**

* Roadmap item: https://github.com/ansible/community/wiki/Network:Core-roadmap-2.7#plugins--cliconf-netconf-plugins-refactor-net_mod Completed cliconf plugin refactor for eos, ios and vyos
* Enhancements for net_get/net_put modules released in 2.6
* Working on net_config generic module
* Working on getting Zuul testing for the ansible/ansible repo. This will give us pre-commit integration testing on various network platforms. Right now we are building up the configuration, with the aim of getting this live early next week.


09:17 Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-07-04/ansible_network_working_group.2018-07-04-16.00.html
09:17 Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-07-04/ansible_network_working_group.2018-07-04-16.00.txt
09:17 Log: https://meetbot.fedoraproject.org/ansible-network/2018-07-04/ansible_network_working_group.2018-07-04-16.00.log.html

**Comment by fxfitz** [comment]
For the July 11th meeting, I would like to quickly discuss an open PR: https://github.com/ansible/ansible/pull/41985

**Comment by amuraleedhar** [comment]
Please merge PR ansible/ansible#42500

In this PR, I am moving the legacy code from Paramiko to use Persistent Connection of Ansible instead for cnos_vlan module. Along with this I am trying to take care of the new CLIs introuduced for CNOS. To take care of backward compatibility, I am introducing a fall back logic. And I have added UT codes for this module. Once this module passes through review process and get merged, I will replicate the paradigm for rest of 14 modules.

**Comment by gundalow** [comment]
**2018-07-04**

**Summary of key points**

* Ansible 2.6.1/2.5.6/2.4.6 are now available, which include security fixes, see https://groups.google.com/forum/#!topic/ansible-announce/4tUBKNcH5fU for more info
* Expect updates to 2.6.x every three weeks
* We suggest you subscribe to https://groups.google.com/forum/#!forum/ansible-announce to keep informed regarding releases
* AnsibleFest Austin Contributor Summit agenda, feel free to add items to https://etherpad.openstack.org/p/ansible-summit-october-2018 

**Team status update**

* Fixing ios integration tests and some internal network connection cleanup work
* Continue work on cliconf refactor, fix junos integration test failure and couple of bug fixes
* Updated on nios_test_container to support new nios modules tests, and bug fixes
* This week finished changes to net_get and net_put modules for idempotency and handling binary files
* Working on ios_linkagg, ios_vlan bugs.
* Got Zuul running on ansible-fork for VyOS. Need to ansible-test respect --changed so we only run the correct set of tests
* Working on net_config module and integration tests, link to the PR #42413.
* Fixing bgp issues on csr, looking at azure rm documentation. 

**Actions**

* gundalow to merge https://github.com/ansible/ansible/pull/41985
* Qalthos to do technical review of the conversion from Paramiko to persistent connection" on Persistence connection for cnos_vlan #42500

Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-07-11/ansible_network_working_group.2018-07-11-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-07-11/ansible_network_working_group.2018-07-11-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-07-11/ansible_network_working_group.2018-07-11-16.00.log.html

**Comment by samerd** [comment]
Please merge PR: ansible/ansible#42164

**Comment by ganeshrn** [comment]
Review and test PR https://github.com/ansible/ansible/pull/42847 for community supported platforms

**Comment by amuraleedhar** [comment]
Please merge PR ansible/ansible#43194
In this PR, I am moving the legacy code for ssh connectivity from Paramiko to persistent connection of Ansible for cnos_portchannel, cnos_vlag and cnos_interface module. Along with this I am trying to take care of the new CLIs introuduced for CNOS. And I have added UT codes for this module. This done exactly in line with PR#42500. This code has been tested on a CNOS Mars switch.

**Comment by Qalthos** [comment]
**2018-07-25**

**Team status update**

* nios and other networking bugs and nios new module integration tests.
* nxos cliconf plugin refactor PR ansible/ansible#43203
* nxos_facts refactor work
* nxos get_capabilities regex fix.
* nxos_logging bugs and adding new features - use-vrf & source-interface.
* merged setting command timeout per task feature, Added PR ansible/ansible#43078 to send timeout error message in output
* Adjustments to httpapi connection plugin to better support incoming httpapi plugins

**Actions**

* Qalthos to make sure per-task timeouts are documented
* Qalthos to merge PR ansible/ansible#43194

 Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-07-25/network_working_group.2018-07-25-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-07-25/network_working_group.2018-07-25-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-07-25/network_working_group.2018-07-25-16.00.log.html

**Comment by amuraleedhar** [comment]
Please merge PR ansible/ansible#43534
In this PR, I am moving the legacy code for ssh connectivity from Paramiko to persistent connection of Ansible for cnos_bgp, cnos_factory, cnos_reload, cnos_save,  and cnos_showrun module. Along with this I am trying to take care of the new CLIs introuduced for CNOS. And I have added UT codes for this module. This done exactly in line with PR#42500. This code has been tested on a CNOS Bacon switch.

**Comment by gundalow** [comment]
Contributors Summit, AnsibleFest Austin 2018
What would **you** like to see discussed at the Community Summit, this is your opportunity to to ask questions either related to Networking, or the Community in general, feel free to add any topics to:
https://etherpad.openstack.org/p/ansible-summit-october-2018

**Comment by samerd** [comment]
URGENT: unable to join meeting:
got this error:
[09:06] == Usermode change: +Ri
[09:06] == gateway/web/freenode/ip.209.116.155.178 is now your hidden host (set by syn.)
[09:06] == #ansible-network Cannot join channel (+r) - you need to be identified with services

please help

**Comment by mattclay** [comment]
@samerd Due to increases in spam in IRC, most of them now require you [register](https://freenode.net/kb/answer/registration).

**Comment by gundalow** [comment]
@samerd I've removed the requirement, please try and join again

**Comment by amuraleedhar** [comment]
Hi,

I have registered as Anil_Lenovo. Now how can I join the chat ?

-Anil

**Comment by gundalow** [comment]
## Ansible Contributor Summit 6 (Part of AnsibleFest 2018 Austin, Texas)

As part of http://www.ansible.com/ansiblefest

* AnsibleFest Austin will be on both Tuesday 2nd and Wednesday 3rd October 2018
* The Contributor Summit will also be over two days, on Monday 1st and Thursday 4th October, from 9:30am to 4pm (time subject to change).

### This is your event

Ansible succeeds because of its community, and this contributor summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the etherpad. For topics that other had added please vote by adding +1

https://etherpad.openstack.org/p/ansible-summit-october-2018 

Please see https://groups.google.com/forum/#!topic/ansible-devel/ivrpVbLya8g for further info

### Attending in person

We realize that not everybody can attend in person, which is why we’ll again be arranging a video conference and a meeting time on IRC in #ansible-meeting to encourage remote participation. This has worked very well for the past Contributor Summits. We’ll be sending out an email with the information for remote participation about a week before the Contributor Summit. 

If you want to attend in-person please sign up at: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 

After signing up you'll receive an email from Eventbrite with a discount code for AnsibleFest Austin. 


### Attending remotely

Please add your name at the bottom of this etherpad: https://etherpad.openstack.org/p/ansible-summit-october-2018 

### Call to action

1) Add ideas to https://etherpad.openstack.org/p/ansible-summit-october-2018 
2) Attending in person: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 then use discount code to sign up to AnsibleFest
3) Attending in person OR virtually: Add your name to the end of https://etherpad.openstack.org/p/ansible-summit-october-2018 
4) Happy automating!

### Questions?
Thanks for all of your contributions to Ansible, and we hope to see you in Austin! And if you have any questions at all, please let us know. 

Speak to `gundalow` on Freenode, or anyone else in `#ansible-devel`

**Comment by gundalow** [comment]
ios_config fails when creating macro "timeout trying to send command:" https://github.com/ansible/ansible/issues/38420

**Comment by amuraleedhar** [comment]
Please review and merge the following PRs
 ansible/ansible#43862
 ansible/ansible#43868
 ansible/ansible#43876
 ansible/ansible#43923
Thanks

-Anil

**Comment by ganeshrn** [comment]
https://github.com/ansible/ansible/pull/35817

**Comment by Qalthos** [comment]
2018-09-05
========

Team status and updates
--------------------------------

* 2.7 is branched, devel is now 2.8
* 2.7rc1 is tomorrow, by last report
* fixing issues with ios_user
* working on issues related to asa_config/asa_acl/asa_command
* vyos provider role WIP
* configure_user task updates for eos & nxos

Logs
------

Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-09-05/ansible_network_working_group.2018-09-05-15.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-09-05/ansible_network_working_group.2018-09-05-15.59.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-09-05/ansible_network_working_group.2018-09-05-15.59.log.html

**Comment by amuraleedhar** [comment]
Please Merge the following PR
ansible/ansible#45278

CLIs used in cnos_facts, cnos_command,  its UT test modules and few CLI template files are in old format. This is getting corrected to new CLI format. Though we are having backward compatibility for this CLIs, it will get deprecated from 10.9 onwards. So we want to change them all to new CLI. Hence this PR is. 
Please merge this so that Customers will have all latest CLI experience.

Thanks

-Anil

**Comment by amuraleedhar** [comment]
Please Merge the following PR
ansible/ansible#45483

Thanks
-Anil

**Comment by Qalthos** [comment]
[date]
========

Team status and updates
--------------------------------
* 2.7rc1 went out last week, is available in the usual places
* fixed a `nothing to repeat` issue with nxos terminal plugin on Python 2.6
* fixed multiple parents issue for asa
* fixed issues with new firepower modules

Logs
------

Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-09-12/ansible_network_working_group.2018-09-12-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-09-12/ansible_network_working_group.2018-09-12-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-09-12/ansible_network_working_group.2018-09-12-16.00.log.html

**Comment by gundalow** [comment]
**Network session as part of Austin AnsibleFest Contributors Summit**

We will be having a Network session which you can join in person or remotely via IRC/VideoCall

**Network Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018-network
**Zuul Agenda:** https://etherpad.openstack.org/p/ansible-summit-october-2018-zuul

Also there are two Zuul talks at Ansible Fest:
* https://agenda.fest.ansible.com/SessionDetail.aspx?id=482019
* https://agenda.fest.ansible.com/SessionDetail.aspx?id=482140

**Top level Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018

Please feel free to add comments and vote (`+1`) on topics.

**NOTE** time and location of sessions may change

For more information about the Contributors Summit see https://github.com/ansible/community/issues/329#issuecomment-410040811

If you have questions feel free to ask here, in IRC, or ping `gundalow`.

Hope to see you there either in person or online.

**Comment by pabelanger** [comment]
**IRC logs**

Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-09-19/ansible_network_working_group.2018-09-19-16.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-09-19/ansible_network_working_group.2018-09-19-16.02.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-09-19/ansible_network_working_group.2018-09-19-16.02.log.html

**Comment by Qalthos** [comment]
2018-09-26
=========

Team status and updates
--------------------------------

- AnsibleFest is next week
- As such, no IRC meeting next week
- Ansible 2.7rc3 was released last week
- 2.7.0 final should be out next week

Team Updates

- Work in progress for juniper_junos provider role.
- sshkey_fingerprint action plugin for ios provider.
- work on cisco_ios role - bugfixes, plugin for checking dependant role version, test for zuul.
- Other provider role work continues on integration tests and bugs.

Logs
------

 Minutes: https://meetbot.fedoraproject.org/ansible-network/2018-09-26/ansible_network_working_group.2018-09-26-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-network/2018-09-26/ansible_network_working_group.2018-09-26-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-network/2018-09-26/ansible_network_working_group.2018-09-26-16.00.log.html

**Comment by samerd** [comment]
Please welcome @anasbadaha (https://github.com/anasbadaha) a new team member of Mellanox-Onyx
His first PR: ansible/ansible#46218
Please review this PR and merge if OK with you

**Comment by Qalthos** [comment]
Hi, now that 2.7.0 is soon to be out I've created a fresh agenda.

Please subscribe to #363

**Comment by dagwieers** [comment]
As being discussed at AnsibleFest 2018, we would like to learn how we can extend httpapi with (very) specific needs for different connection methods (all different types of REST), for Cisco this is different technologies like IMC, UCS, ACI, MSC, Tetration, ...

One problem is the lack of documentation or code annotations that help understand how we ought to extend it. The second problem is that by extending the httpapi framework you may break the original use-cases without the ability to test.

So the easiest path is everybody does their own implementation, but even for Cisco only there's a benefit of having a single framework.
