### ISSUE TITLE
Set up Core WG pages

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#250]
https://github.com/ansible/community/tree/master/meetings

This page has a nice list of all the meetings and links to the working groups -- but the Core Team meeting isn't technically a working group, so there's not really a direct / obvious place to link to -- but having the link to their standing agenda linked here (so people know where to add any items for that meeting) might be a good idea. 

@gundalow @thaumos any objections? (not sure if this tracking issue gets renewed monthly offhand and if it will likely get forgotten about as needing to be updated on this page)

**Comment by robynbergeron** [comment]
(was looking at @gundalow also since he's done a bunch of work on reorganizing lots of the community documentation and there may be other bits that are better / more useful to point people at that i'm not thinking of off the top of my head)

**Comment by gundalow** [comment]
https://github.com/ansible/community/labels/core is the (always correct) link to core meeting

**Comment by gundalow** [comment]
Core does have an ics and yml https://github.com/ansible/community/blob/master/meetings/core-team.yaml

**Comment by dagwieers** [comment]
And I still have an issue open in order to create a single ical file that combines all ical calendars into one (and also includes one-off events like e.g. ansiblefests, deadlines and sprints. Currently the yaml2ical tool does not support any of that :-(

**Comment by gregdek** [comment]
OK, this is now "set up core WG pages" which can basically just be links to all these things.

**Comment by gundalow** [comment]
I believe this is all done
