### ISSUE TITLE
Create ansible-outreach mailing list

### ISSUE THREAD

**Issue by gregdek** [ansible/community#254]
We've hemmed and hawed about this, and yes, it's Yet Another Mailing List -- but we really do need a way for meetup organizers and other evangelist type people to be able to keep in touch with one another, and ansible-users and ansible-devel are clearly not appropriate for this sort of thing.

**Comment by gregdek** [comment]
Sigh. So, here's the problem with the old list: it was created by greg@ansible.com, and there were no backup admins, and the ansible.com google domain has been inactivated by Red Hat.

So now I get to try getting this enabled by Red Hat IT.

**Comment by gregdek** [comment]
Well, that won't work.

I tried using the "Report This Group" to get a Google admin to respond. We'll see if that works. If it hasn't worked in a day or two, we may be forced to abandon this group and start a new one.

**Comment by gregdek** [comment]
All right, this is now going to be "Outreach mailing list" instead. Sigh.

**Comment by gundalow** [comment]
+1 to mail list.

What does "out reach" mean in this context?

**Comment by gregdek** [comment]
Outreach means meetups, speakers, event activites, cfps, and the like. Anyone who wants to stay informed about those things should be on this list.

The list is now created; I just need to configure it,

**Comment by dmsimard** [comment]
This is created and used :) https://groups.google.com/forum/#!forum/ansible-outreach

**Comment by gregdek** [comment]
Right, we can close this one :)
