### ISSUE TITLE
Ambassadors meetings

### ISSUE THREAD

**Issue by gregdek** [ansible/community#255]
Do we need them? When should they be? Who should we invite?

**Comment by gundalow** [comment]
What's the difference between ambassadors, meetup organisers and outreach?
If they have roughly similar aims maybe we should combine under the outreach umbrella
I wonder if we sub divide too much much we end up with small groups not sharing

@cybette

**Comment by gregdek** [comment]
Ambassadors was the old name for outreach, so yes, closing in favor of #338.
