### ISSUE TITLE
GitHub badges for all communities

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#258]
So now that [my GitHub badge changes](https://github.com/badges/shields/pull/1020) have been approved, we can show open issues and open PRs by label, and I have been adding these badges for each of the related wiki-pages. However, some of the communities (cloudstack, jboss, and some network communities) do not have their own labels and therefore cannot show their own badge counters.

Do we want to fix this ?

**Comment by dagwieers** [comment]
So the process to do this is:
- Add a label to Github (e.g. cloudstack) using existing color-convention (e.g. look at aws color)
- Modify *.github/BOTMETA.yml* like this: https://github.com/ansible/ansible/commit/60db863158b9126c165065c25fa8534d45fc7584

**Comment by dagwieers** [comment]
So I added labels and badges for the remaining communities.
I wonder if we should document somewhere that communities can request this too.

**Comment by gregdek** [comment]
oooh. I didn't even understand this until I read the patch in question.

Still making sure I understand... this means that we can add a label to any module or set of modules in botmeta and any PR that pertains to that file will have that label?

Does it apply to issues as well?

I completely agree that this should be documented in the community guide.

**Comment by dagwieers** [comment]
Right, but it's just a means to an end. We want to see the issues/PRs by label for the different community wiki-pages, so these labels are essential.

**Comment by dagwieers** [comment]
This is done.

**Comment by sm4rk0** [comment]
For those curious about what's been done here, check heading of any working group/community [here](https://github.com/ansible/community/wiki).
