### ISSUE TITLE
Mechanism for identifying unmaintained modules

### ISSUE THREAD

**Issue by gregdek** [ansible/community#261]
If modules are not being properly maintained by their maintainers of record, we need a mechanism to identify them and mark them appropriately. For instance: if a module has open issues and no merged PRs or responses within X amount of time, the module is marked as "unmaintained" somehow, which allows us to advertise it to new maintainers.

This is likely a function of ansibot, but we need to figure out the policies around it.

**Comment by Im0** [comment]
This sounds good.

**Comment by gundalow** [comment]
See also https://github.com/ansible/community/issues/337
