### ISSUE TITLE
Public Ansible Project Meeting Agenda - October 2017

### ISSUE THREAD

**Issue by thaumos** [ansible/community#263]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by thaumos** [comment]
https://github.com/ansible/community/issues/240#issuecomment-333001995

**Comment by thaumos** [comment]
https://github.com/ansible/ansible/issues/16804

**Comment by thaumos** [comment]
2017-10-03 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-03/ansible_core_meeting.2017-10-03-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-03/ansible_core_meeting.2017-10-03-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-03/ansible_core_meeting.2017-10-03-19.00.log.html

**Comment by gundalow** [comment]
Decide on `loop_control`, which blocks https://github.com/ansible/proposals/issues/71

**Comment by thaumos** [comment]
2017-10-05 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-05/ansible_core_meeting.2017-10-05-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-05/ansible_core_meeting.2017-10-05-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-05/ansible_core_meeting.2017-10-05-15.00.log.html

**Comment by thaumos** [comment]
2017-10-10 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-10/ansible_core.2017-10-10-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-10/ansible_core.2017-10-10-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-10/ansible_core.2017-10-10-19.00.log.html

**Comment by sethp-nr** [comment]
I'd like to discuss ansible/ansible#28839 at tomorrow's (10/12) meeting.

**Comment by kustodian** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/31719

Not sure if I will be able to attend the meeting, but I wrote everything I would say in the PR.

**Comment by gundalow** [comment]
Proposal: Refactoring the Ansible Core Docs

https://github.com/ansible/proposals/issues/79

**Comment by thaumos** [comment]
2017-10-17 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-17/ansible_core.2017-10-17-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-17/ansible_core.2017-10-17-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-17/ansible_core.2017-10-17-19.00.log.html

**Comment by thaumos** [comment]
2017-10-19 Meeting


Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-19/ansible_core.2017-10-19-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-19/ansible_core.2017-10-19-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-19/ansible_core.2017-10-19-15.00.log.html

**Comment by BondAnthony** [comment]
I would like to discuss a couple aging pull requests:

https://github.com/ansible/ansible/pull/27269
https://github.com/ansible/ansible/pull/26365

**Comment by jborean93** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/31767#discussion_r145487409 at the 2017-10-24 meeting.

I probably won't be online until the later half of the meeting though.

**Comment by dagwieers** [comment]
Would like to discuss https://github.com/ansible/proposals/issues/74 before the meeting ends :-)

**Comment by thaumos** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-24/ansible_core.2017-10-24-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-24/ansible_core.2017-10-24-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-24/ansible_core.2017-10-24-19.00.log.html

**Comment by thaumos** [comment]
2017-10-27 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-26/ansible_core.2017-10-26-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-26/ansible_core.2017-10-26-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-26/ansible_core.2017-10-26-15.00.log.html

**Comment by cognifloyd** [comment]
Moving from November's agenda #273
@bcoca:
> Are we interested in this feature?:
> ansible/ansible#32304

**Comment by thaumos** [comment]
2017-10-31 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-31/ansible_core.2017-10-31-19.00.html
13:00 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-10-31/ansible_core.2017-10-31-19.00.txt
13:00 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-10-31/ansible_core.2017-10-31-19.00.log.html

**Comment by gundalow** [comment]
Novembers agenda https://github.com/ansible/community/issues/273
