### ISSUE TITLE
Document Galaxy as best practice for creating roles

### ISSUE THREAD

**Issue by gregdek** [ansible/community#267]
In our role docs here:

http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html

We allude to Galaxy, but we don't really mention that ansible-galaxy init will give you a pre-built framework for a role. 

Should we make this more prominent? I think maybe we should.

**Comment by thaumos** [comment]
BIG YES from me!

**Comment by gregdek** [comment]
https://github.com/ansible/ansible/pull/40499

**Comment by gregdek** [comment]
Change is merged.
