### ISSUE TITLE
Have a similar series of events to Microsoft's Azure Red Shirt Dev Tour '17

### ISSUE THREAD

**Issue by mcgonagle** [ansible/community#268]
Community Organizing Idea:

Hello, I was chatting with @gundalow and we both thought it would be a good idea to have a community driven Dev tour similar to Microsoft's https://channel9.msdn.com/Blogs/Azure/Join-us-for-the-Azure-Red-Shirt-Dev-Tour. You can count on @F5networks for support. Who would be the best person at @ansible to discuss this initiative with? Would it be best to loop in Andrius @abenokraitis and Mani @ophiion?

**Comment by gregdek** [comment]
We've already got the Ansible Automates series of events that fit better with this, I think. They're not pure "community-driven" but we don't have the resources to drive such an initiative at present.

**Comment by gregdek** [comment]
@mcgonagle send me an email (gdk@redhat.com) and I'll put you in touch with the right folks.
