### ISSUE TITLE
Copy meetup guidelines from Google Doc to wiki

### ISSUE THREAD

**Issue by gregdek** [ansible/community#271]
We've got a great meetup guide linked in our Outreach section of our wiki, from Haisan Ido. Gonna just pull that content in as a wiki page and give him the attribution.

**Comment by gregdek** [comment]
Basically forking it to add any suggestions we might have.

**Comment by gundalow** [comment]
Done, see revision#2 of https://github.com/ansible/community/wiki/Outreach:-Meetups
