### ISSUE TITLE
Public Ansible Project Meeting Agenda - November 2017

### ISSUE THREAD

**Issue by thaumos** [ansible/community#273]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by bcoca** [comment]
Are we interested in this feature?:
https://github.com/ansible/ansible/pull/32304

**Comment by gundalow** [comment]
We are overloading `--ask-pass`, sometimes it means:
a) Use this password to unlock an encrypted SSH Key
b) Use this for password auth

Do we need a new command line argument that's only used to unlock the SSH Key?

See https://github.com/ansible/ansible/issues/31988

**Comment by pilou-** [comment]
I would like to discuss ansible/ansible#31920 (a fix for `include_role` unit tests which currently don't test anything) at the next meeting.

**Comment by thaumos** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-02/ansible_core.2017-11-02-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-11-02/ansible_core.2017-11-02-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-02/ansible_core.2017-11-02-15.00.log.html

**Comment by abadger** [comment]
@jimi-c @bcoca @sivel: https://github.com/ansible/ansible/pull/32480  We need to talk over the ramifications of doing things like this on our public API and decide whether we want to break backwards compat in a single release, over a deprecation cycle, or come up with a replacement.

**Comment by eikef** [comment]
I would like to discuss ansible/ansible#31716 (a new module named keycloak_client).

**Comment by nitzmahone** [comment]
Now that we have versioned docs, I'm proposing that we only maintain callouts of feature changes for up to two releases in our docs/guide content. It's important to call out changes to existing users, but at some point (especially for fast-moving parts of the project), continuing to document old behavior and call out changes by version makes the docs much harder to grok. 

So this would mean for 2.5, we'd look for any callout reference to 2.2 or lower and remove it (eg, "As of Ansible v2.1 ..." would go), and repeat the process for each major release (minus two versions). Similarly, descriptions of old/deprecated behavior that are no longer applicable to the most recent release and the two prior would be removed.

This would not affect the `version_added` behavior in module docs, though it should probably affect other text in module docs that makes reference to old versions.

**Comment by tima** [comment]
I agree @nitzmahone. I've found the version call outs that have built up over years incredibly noisy and distracting and noisy and just plain annoying. They needed to go and now there is no good reason.

**Comment by dagwieers** [comment]
Would like to discuss ansible/proposals#74 before the meeting ends.

**Comment by thaumos** [comment]
2017-11-07 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-07/ansible_core.2017-11-07-19.00.html
12:13 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-11-07/ansible_core.2017-11-07-19.00.txt
12:13 Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-07/ansible_core.2017-11-07-19.00.log.html

**Comment by sivel** [comment]
https://github.com/ansible/proposals/issues/83

**Comment by sivel** [comment]
https://github.com/ansible/ansible/pull/32079

**Comment by jtyr** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/31938 and https://github.com/ansible/ansible/pull/32706 on the meeting on 9 Nov 2017.

**Comment by aalexmonteiro** [comment]
I have  pull requests open and reviewed by the community for a new module. I'd like some review of my PRs.

https://github.com/ansible/ansible/pull/32701
https://github.com/ansible/ansible/pull/32849

**Comment by sivel** [comment]
https://github.com/ansible/proposals/issues/83

**Comment by thaumos** [comment]
2017-11-16 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-16/core_meeting.2017-11-16-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-11-16/core_meeting.2017-11-16-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-16/core_meeting.2017-11-16-15.00.log.html

**Comment by bcoca** [comment]
https://groups.google.com/forum/#!msg/ansible-project/oRZwBj4XDx8/7IPtbtKFCgAJ

define pattern behaviour on mulitple matches

**Comment by jborean93** [comment]
Looking at options to deprecate `get_md5` from `stat` and `win_stat`. This is tricky because the default option is `yes` so to deprecate it we will need to do it in steps. What I propose to do is

* Add deprecation warning for when `get_md5: yes` is explicitly set and say the functionality and `md5` return value will be removed in 2.9
* Add info to the docs and changelog to say `get_md5: yes` will no longer work in 2.9
* Once 2.9 comes along remove the default option and throw an error if it is set to `true` and display a warning if set to `no` saying it will be removed altogether in the next release
* In the next release, remove the option altogether

This means it will be fully removed in 5 releases time but is designed to allow people who have set `get_md5: no` explicitly 1 release where they can remove the option but still keep the same functionality. Happy to shorten the timeframe if wanted but I've tried to reach a good middle ground.

We can't just add a warning if the option is set as;
* We set `get_md5=False` when an action plugin tries to get a stat from a file so every call will show a warning unless we change the behaviour to True
* People who are setting `get_md5: no` on their tasks because they don't want to get the MD5 hash will be warning until we finally remove the option and then they need to modify their playbooks.

You can still use `get_checksum: yes` and `checksum_algorithm: md5` if you still want the MD5 hash but now the options are unified and simpler.

Have raised a PR for this but it is subject to what we want to move forward with https://github.com/ansible/ansible/pull/33002. I probably won't be online at the next meeting but hopefully this is enough information.

**Comment by eikef** [comment]
I'd like to request a discussion/review and commit of ansible/ansible#31716 (keycloak_client, which was modified according to the last review).

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/32860 <= this returns to previous behaviour but some have pointed out that the 'new behaviour' could be considered a feature.

**Comment by mattclay** [comment]
Do we want to enable the following style related pylint rules?

- len-as-condition
- no-else-return

This was brought up as part of https://github.com/ansible/ansible/pull/30764

**Comment by eikef** [comment]
I'd like to request a review and commit of  ansible/ansible#33184 (zabbix_host integration tests and preparation for more zabbix_*-integration tests).

**Comment by aalexmonteiro** [comment]
I have pull requests open and reviewed by the community and core team for a new module. I'd like some review of my PRs.

https://github.com/ansible/ansible/pull/32798 (already reviewed by core-team - changes requested)
https://github.com/ansible/ansible/pull/32849

**Comment by nitzmahone** [comment]
2017-11-28

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-28/ansible_core.2017-11-28-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-11-28/ansible_core.2017-11-28-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-28/ansible_core.2017-11-28-19.01.log.html

**Comment by sivel** [comment]
Generic API modules...

Recently there have been an influx of generic API modules for services submitted as pull requests. These modules typically accept an arbitrary argument of input data and have no explicitly defined operation other than interacting generically with an API. We have denied some, accepted a few others. We should have an official stance on generic API modules.

**Comment by thaumos** [comment]
# Please Note

For items to be covered starting next week, use the [December 2017 issue](https://github.com/ansible/community/issues/286).

**Comment by thaumos** [comment]
2017-11-30 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-30/ansible_core.2017-11-30-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-11-30/ansible_core.2017-11-30-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-11-30/ansible_core.2017-11-30-15.00.log.html
