### ISSUE TITLE
Hook up zodbot in #ansible-azure

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#275]
The #ansible-azure WG is starting to get a little more organized and planning for meetings in #ansible-azure- can we get zodbot invited and plugged in?

**Comment by mscherer** [comment]
Asked on #fedora-infra: 
```
12:37:01|  misc> for a zodbot request, should a ticket to infra be opened ? (https://github.com/ansible/community/issues/275) 
12:38:53|  puiterwijk> misc: normally, yes. But for ansible community, people can just assign it to me
```

**Comment by puiterwijk** [comment]
In the future, please assign to me and/or create a ticket on https://pagure.io/fedora-infrastructure/.
This channel has been added now.
