### ISSUE TITLE
Add "azure working group" meeting to calendar

### ISSUE THREAD

**Issue by kyliel** [ansible/community#277]
#ansible-azure WG would like to kick off regular weekly meeting through IRC channel #ansible-azure IRC channel on Freenode.net. 

Time: UTC 00:00 on each Wednesday 
Duration: 30 min

How could I add it to Ansible Community Calendar?

**Comment by kyliel** [comment]
@nitzmahone Any idea who own the calendar for Ansible community meetings? Thank you.

**Comment by gundalow** [comment]
Hi, in a single PR
1) Add a new yaml file
2) Run the Makefile to generate the `.ics` file
3) Update `README.md`

in https://github.com/ansible/community/tree/master/meetings

**Comment by kyliel** [comment]
Thank you @gundalow . The pull request for yaml file/ical/update against README.md is created - https://github.com/ansible/community/pull/280. Could you please have a review?

**Comment by dagwieers** [comment]
Already merged. Closing.
