### ISSUE TITLE
We now have a galaxy waffleboard, so where do we talk about it?

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#28]
https://waffle.io/ansible/galaxy-issues

Per #24: "So that we can manage our galaxy issues transparently!" -- not very transparent if nobody knows that it exists to see :) Add to community/readme.md? Add to galaxy/readme.md?

**Comment by gregdek** [comment]
This is out-of-date (although we really should consider a Galaxy WG, which would be a different thing.)
