### ISSUE TITLE
Windows Working Group agenda - 2018

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#294]
----
**This agenda has been migrated to a new location: #420**

----

The Windows Working Group is focused on improving Ansible's management of Windows hosts. The group meets every week on Tuesdays at 20:00 UTC (see [ical](https://raw.githubusercontent.com/ansible/community/master/meetings/ical/windows.ics)) 

More information related to the Windows Working Group is available at:
https://github.com/ansible/community/tree/master/group-windows

**Feel free to add your questions to this ticket to be discussed during the upcoming meeting.**

After being discussed, raised items are being updated, and after a month resolved items are being hidden from view (but remain accessible).

*(Migrated from the previous agenda at #195, actionable items are available at [Windows: action plan](https://github.com/ansible/community/wiki/Windows:-action-list))*

**Comment by dagwieers** [comment]
[New windows modules](https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Awindows+label%3Anew_module) waiting for review/feedback:

- win_whoami: ~https://github.com/ansible/ansible/pull/33295~ *new in v2.5*
- win_disk_facts: https://github.com/ansible/ansible/pull/32935
- win_audit_policy_system: ~https://github.com/ansible/ansible/pull/31046~ *new in v2.5*
- win_audit_rule: ~https://github.com/ansible/ansible/pull/30473~ *new in v2.5*
- win_disk_management: https://github.com/ansible/ansible/pull/27634
- win_xml: https://github.com/ansible/ansible/pull/26404
- win_certificate: https://github.com/ansible/ansible/pull/25837

Please review these tickets on a weekly basis (if there was new progress, otherwise add instructions to the owner how to continue).

Once merged, please add to [CHANGELOG.md](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md) !

**Comment by dagwieers** [comment]
Effort to have [integration tests for all Windows modules](https://github.com/ansible/community/wiki/Windows%3A-progress-tracker#missing-integration-tests). Please review and merge:
- **win_iis_website**  --  @jborean93   --  https://github.com/ansible/ansible/pull/25902

**Comment by dagwieers** [comment]
(@dagwieers) Investigate and recover from "Connection refused" errors in WinRM. ansible/ansible#25532

*Migrated from https://github.com/ansible/community/issues/153#issuecomment-307416504*

**Comment by dagwieers** [comment]
I'd be interested to know if this is something to pursue further, or not: https://github.com/ansible/ansible/pull/34097

**Comment by dagwieers** [comment]
For the upcoming v2.6 maintenance release, it would be nice if we could get all known idempotency/tests/feature parity issues closed from [Windows progress tracker]
 (https://github.com/ansible/community/wiki/Windows:-progress-tracker). Coverage support for Powershell modules would be very useful to get a sense of achievement ;-)

**Comment by dagwieers** [comment]
I would like to revisit ansible/ansible#29170 since the Unix python modules are doing this all over the place, without any framework.

**Comment by jborean93** [comment]
Just a shameless plug to get some tester, but I've finally created a dev release for a Python psexec library which you can find here https://github.com/jborean93/pypsexec. The goal of this library is to give us more boostrapping choices for Windows as this only needs SMB (2+) which should be enabled on most Windows hosts from the get go unlike WinRM on some hosts.

Once I've ironed out some of the nastier bugs and have more confidence in the library, I plan on creating an Ansible module for this. This would mean users can run an adhoc command on a Windows host from the Ansible controller instead of relying on another Windows host and PsExec to be installed. I do have a loftier goal for eventually adding a connection plugin for this in the future but I don't think it is stable enough right now.

If you want to test it, just run `pip install pypsexec` and run the following script;

```
from pypsexec.client import Client

server = "SERVER2016.domain.local"
username = "vagrant"
password = "vagrant"
c = Client(server, username=username, password=password, encrypt=False)
try:
    c.connect()
    c.create_service()
    result = c.run_executable("hostname.exe")
finally:
    c.remove_service()
    c.disconnect()
print(result)
```

Trying out the various permutations would be great as you have access to pretty much any configuration option that comes with psexec like running as the SYSTEM account or in an interactive logon.

Any issues you find, please add it into this ongoing issues list I have for the dev release https://github.com/jborean93/pypsexec/issues/2.

**Comment by jhawkesworth** [comment]
I am curious to know what WWG participants think about whether CI should be testing against the non LTS versions of  Windows Server (of which 1709 is the first example).

**Comment by jborean93** [comment]
Look at adding the win_dsc "parsed" values back in the return JSON https://github.com/ansible/ansible/issues/37882#issuecomment-376002493. Potentially only add this when setting `-vv` or `-vvv` to not pollute the normal output. This is useful for debugging purposes to see how the module parsed the input parameters to DSC parameters but the output can get really complex when it comes to dict/CimInstances.

**Comment by dagwieers** [comment]
@jborean93 This is probably not the right place to discuss, but we shouldn't add returned variables depending on verbosity as this could be confusing. One option is to use the --debug flag, or have a special parameter (e.g. output_level=normal|info|debug) or do both.

**Comment by jhawkesworth** [comment]
I'd like WWG's opinion on whether this PR is worth pursuing.  https://github.com/ansible/ansible/pull/37291 - having worked on it a while its starting to feel like maybe its going in the wrong direction.

**Comment by jhawkesworth** [comment]
Also https://github.com/ansible/ansible/pull/37343 looks good to me but wondered if it fits in with core testing capability plans.

**Comment by jborean93** [comment]
Should we add some checks in `Convert-ToSID` to detect if the input string is already a SID and return that same value, see https://github.com/ansible/ansible/issues/38502#issuecomment-383789687. The only downside of this is if someone (for some weird reason) actually has a local or domain account that is named like a SID, e.g. a local account called `S-1-0-0`. This can still work if the user specifies the domain or hostname/. like `DOMAIN\S-1-0-0` or `.\S-1-0-0` but adds more magic to the whole thing.

**Comment by chopraaa** [comment]
I'd like to discuss addition of dedicated `win_partition`, `win_disk` and `win_volume` modules over the `win_disk_management` module that has a PR going. Also, deprecation of `win_disk_facts` over dedicated modules (again). 

Both `win_disk_management` and `win_disk_facts` are really cluttered, and I think dedicated modules would help us do the same job better.

**Comment by jborean93** [comment]
Whether we want to officially support and document that win_get_url supports FTP sources https://github.com/ansible/ansible/pull/39317#issuecomment-384592630. Testing it isn't the end of the world but whether we want to ensure this stays working in the future needs to be discussed.

**Comment by gyorgynadaban** [comment]
Discuss making PowerShellGet 1.6.0 the default minimum version installing it if necessary. ansible/ansible#39909

**Comment by jhawkesworth** [comment]
I've seen conversations like this come up a few times in the irc channel:

2:04 PM <strfry> hmm, ansible doc says that become: yes should now work on windows hosts. but it complains that there's no sudo available
2:05 PM <agaffney> strfry: you need to set become_method to 'runas', iirc

I am wondering whether a default become method could be associated with a connection type.  
So if connecting via winrm then default become method would be 'runas'.
It would have to be a default as you would still need to be able to select a specific become method elsewhere (and I guess in theory windows could wind up having more than 1 become method - psexec is almost a become method I suppose).

I don't know if this could be achievable as I haven't looked at the internals, so question 1 is, could it be done? and 2/ does anyone think it would be desirable to do so?

**Comment by jborean93** [comment]
Look into https://github.com/ansible/ansible/pull/41127 and discuss whether we want to allow people to specify alternative Chocolatey install sources.

**Comment by jborean93** [comment]
Look at https://github.com/ansible/ansible/issues/41791 and decide whether we should break compatibility of specifying paths with `/` so user's can create keys with `/` in the name. `win_regedit` is a core module so we need to tread carefully here. As a bit of background info here are the types of paths we specify

```
HKLM:\SOFTWARE\Microsoft

# this works and is the same as the example above
HKLM:\SOFTWARE/Microsoft

# this will throw an error
HKLM:/SOFTWARE/Microsoft
```

Because we at least have the check on the root provider and enforce that to be a `\` in the separator I would be surprised if people had a mixture but stranger things have happened.

**Comment by jborean93** [comment]
Currently `creates_version` in `win_package` uses `FileVersion` but this does not match up with File Version shown in Windows Explorer. The latter contains the "private part" which is just the 4th component to the version. We can change win_package to use `FileVersionRaw` which contains the full version string but this is a core module and has the potential to break existing user's playbooks. On the other hand, when we install packages and specify the version we would want to specify the full version and not just a subset.

**Comment by jhawkesworth** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/42056

**Comment by jborean93** [comment]
Also https://github.com/ansible/ansible/pull/42468

**Comment by dagwieers** [comment]
So I would like to propose we hide older comments in the agenda that are resolved (e.g. every new month) and stick as long as possible with the existing agenda (as we are already doing). This enables users to subscribe to the agenda to stay involved without the existing overhead of having to scroll down pages and pages to get to the current stuff. (On top of that we can keep some generic comments visible for all to see, like the new/upcoming modules section).

Add :+1: if you think this is a good idea ?

**Comment by gundalow** [comment]
## Ansible Contributor Summit 6 (Part of AnsibleFest 2018 Austin, Texas)

As part of http://www.ansible.com/ansiblefest

* AnsibleFest Austin will be on both Tuesday 2nd and Wednesday 3rd October 2018
* The Contributor Summit will also be over two days, on Monday 1st and Thursday 4th October, from 9:30am to 4pm (time subject to change).

### This is your event

Ansible succeeds because of its community, and this contributor summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the etherpad. For topics that other had added please vote by adding +1

https://etherpad.openstack.org/p/ansible-summit-october-2018 

Please see https://groups.google.com/forum/#!topic/ansible-devel/ivrpVbLya8g for further info

### Attending in person

We realize that not everybody can attend in person, which is why we’ll again be arranging a video conference and a meeting time on IRC in #ansible-meeting to encourage remote participation. This has worked very well for the past Contributor Summits. We’ll be sending out an email with the information for remote participation about a week before the Contributor Summit. 

If you want to attend in-person please sign up at: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 

After signing up you'll receive an email from Eventbrite with a discount code for AnsibleFest Austin. 


### Attending remotely

Please add your name at the bottom of this etherpad: https://etherpad.openstack.org/p/ansible-summit-october-2018 

### Call to action

1) Add ideas to https://etherpad.openstack.org/p/ansible-summit-october-2018 
2) Attending in person: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 then use discount code to sign up to AnsibleFest
3) Attending in person OR virtually: Add your name to the end of https://etherpad.openstack.org/p/ansible-summit-october-2018 
4) Happy automating!

### Questions?
Thanks for all of your contributions to Ansible, and we hope to see you in Austin! And if you have any questions at all, please let us know. 

Speak to `gundalow` on Freenode, or anyone else in `#ansible-devel`

**Comment by jhawkesworth** [comment]
while revewing #43943 and #43866 I wondered if examples is the best place to show how to install the prerequisites (which can be a multi-step process if not on ps 5) (see test setup steps).

**Comment by dagwieers** [comment]
Wondering if any of the open new windows modules PRs are ready for being merged into v2.7 ? Like [win_wait_for_process](https://github.com/ansible/ansible/pull/40404) or the [win_rds modules](https://github.com/ansible/ansible/pull/43406) ?

**Comment by dagwieers** [comment]
Wondering whether we can do something about [the list of old and irrelevant Windows roles on Ansible Galaxy](https://galaxy.ansible.com/search?tags=windows&order_by=-repository__download_count&page_size=100). I think it helps the signal-to-noise ratio of Ansible Galaxy if we can make an effort to (maybe) contact authors and discuss about retracting roles that e.g. only perform a single task (installing a package) or implement something that is now possible with a single task.

I'd rather prevent Ansible users from thinking that this is the right way to do something (if it isn't).
@gregdek @robynbergeron

**Comment by gregdek** [comment]
I believe, in the long term, that asking contributors to take down roles that we don't think are "good enough" is the wrong approach. Our notion of "good enough" might differ from what others might think.

However, I do think there's a *lot* value in actually codifying what *we think* constitutes a good role (i.e. a good role is tested, issues are addressed in a timely way, aren't single function, and so on) and then reducing signal/noise ratio by filtering for these "good" roles by default  This has been an ongoing discussion for quite a while now, and the Galaxy team is continuing towards tools to help us decide what these best practices should look like. Expecting to drill down into this discussion at the Contributor Summit next month. cc: @tima

**Comment by jborean93** [comment]
Look into offering a create new console flag for win_command/win_shell https://github.com/ansible/ansible/issues/44905#issuecomment-419678238. Not sure if we want to do that or just tell people to use async which removes the main need for doing that.

**Comment by ksubileau** [comment]
Is ansible/ansible#44755 ready to be merged ?
Should we really need to support the "string representing a dict" form for the parameter `app_parameters`, even if this feature doesn't seem to be documented anywhere and doesn't seem to work in any of the existing releases ?

**Comment by ksubileau** [comment]
What next for ansible/ansible#43406 ?

**Comment by gundalow** [comment]
**Windows session as part of Austin AnsibleFest Contributors Summit**

We will be having a Windows session which you can join in person or remotely via IRC/VideoCall

**Windows Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018-Windows

**Top level Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018

feel free to add comments and vote (`+1`) on topics.

**NOTE** time and location of sessions may change

For more information about the Contributors Summit see https://github.com/ansible/community/issues/329#issuecomment-410040811

If you have questions feel free to ask here, in IRC, or ping `gundalow`.

Hope to see you there either in person or online.

**Comment by chopraaa** [comment]
How are integration tests handled for modules that require specific resources? I'm working on `win_partition` (slowly but getting there, haha) and I'm not sure how my tests would do once I submit a PR. 

I can use `ansible-test` fine to run my role but it requires an additional disk to be present on the server.

**Comment by jborean93** [comment]
@chopraaa I'm wondering whether you can create a VHD, mount that and then run the tests around partitioning that. What I've done in the past is add `unsupported` to the test alias https://github.com/ansible/ansible/blob/devel/test/integration/targets/win_domain_group/aliases. This has allowed me to still define the tests to run locally in the proper environment but skip it when it comes to CI.

**Comment by mattclay** [comment]
Partitioning a VHD sounds like a good idea. It should provide consistent results without requiring a special test environment.

**Comment by jborean93** [comment]
Yep, the only downside is it may restrict the tests to Server 2012+ as I believe the ability to mount a VHD was added in that version but I could be wrong. I'm not sure what platforms @chopraaa is targeting but it's something to be mindful off.

**Comment by chopraaa** [comment]
@jborean93 Using a VHD sounds great. Only thing is that the `VHD` cmdlets come with the Hyper-V module, and that requires the Hyper-V role as well, so I'll just go with good ol' diskpart. 

I'm targeting 2012 and above plus - I think the storage cmdlets/`MSFT_Partition` wasn't there before it.

Adding `unsupported` would work for a future `win_disk` module I think.

**Comment by jborean93** [comment]
@chopraaa have a look at https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_disk_image.ps1, it can mount VHDs and doesn't required the Hyper-V modules. I'm sure there are CIM or .NET calls you can make to create an empty VHD and shouldn't requre Hyper-V to be installed.

**Comment by dagwieers** [comment]
We probably need to have a discussion on how to support reboots with outstanding updates, which could cause **win_reboot** to fail (unexpectedly) because the shutdown or reboot takes longer than 600 seconds. See https://github.com/ansible/ansible/pull/46377#issuecomment-426856834

**Comment by jborean93** [comment]
I would like to talk about https://github.com/ansible/ansible/pull/45708, more specifically

* Whether we use a separate module options for this post category filtering
* Whether we should filter all updates in the beginning or whether it should be done later on, like the whitelist/blacklist
* If we don't do the filtering above like we do today, should we return all the other updates missing in that filter like we do with whitelist/blacklist updates
* Should this be added to the whitelist/blacklist instead to allow filtering of the categories based on a whitelist/blacklist

**Comment by dagwieers** [comment]
I would like to discuss making WinRM and PSRP more reliable (#25532). Two PRs have been produced, for WinRM (diyan/pywinrm#174) and PSRP (jborean93/pypsrp#10) that use the python-requests Retry mechanism. This can recover safely from "Connection Refused" issues, or specific HTTP/gateway errors.

**Comment by chopraaa** [comment]
Looking to get https://github.com/ansible/ansible/pull/46292 reviewed to get a general sense of direction so I can make what changes are required.

**Comment by dagwieers** [comment]
We still have a backlog of known issues listed at [our progress tacker](https://github.com/ansible/community/wiki/Windows:-progress-tracker) and I was wondering what we wanted to do with this.
- Maybe first evaluate if the current list is still correct.
- Can we ask the original maintainer to fix some of these issues ?
- Should we somehow add information to the module documentation what the limitations are ?
  - E.g. This module is not idempotent, this module has not integration tests, this module is unmaintained ?
  - And actively ask for contributors to help fix known issues ?
- Can we do some effort to clean this up ourselves ?
  - Or create easy-fixes in the issue-tracker.

**Comment by dagwieers** [comment]
The current [Windows community plan](https://github.com/ansible/community/wiki/Windows:-community-plan) lists various ideas and functionality, some of which we have implemented (and even have removed since).

In order to prepare the new Ansible v2.8 Windows roadmap, it would be nice if we could collectively think about important issues we still have with Ansible/Windows integration. We've come a long way, and a lot of improvements are in the pipeline, but each of us know of issues that are still prevalent and require work/notes.

This could include modules/lookup-plugins/filters that would be of great value. So feel free to discuss on IRC and add them to the Wiki.

**Comment by ksubileau** [comment]
I suggest to talk about ansible/ansible#45693 and the direction to take for the `win_nssm` module, whether we should use native Powershell code rather than relying on NSSM when possible, and if so how to handle the code duplication and feature ovelapping with `win_service`.

Please have a look on [my (long) comment](https://github.com/ansible/ansible/pull/45693#issuecomment-441459358) for more details.

**Comment by it-praktyk** [comment]
I would like to ask all permanent members of the Windows Working Group to consider and discuss how they will be treated pull requests from the new community members.

The last behavior of @jborean93 - please read the last comments for the #48828 - allow me to doubt the inclusivity of the group.

cc: @nitzmahone, @jborean93 ,@jhawkesworth , @trondhindenes , @dagwieers

**Comment by dagwieers** [comment]
@it-praktyk I feel your sentiment and it would be good to discuss this, either in a meeting, or in private. I have had similar experiences, and I think there are lessons to be learned here wrt. Contributor Experience, even if technically, the code would probably end up being the same.

**Comment by jhawkesworth** [comment]
Of the 93 windows modules 33 have now been converted to Ansible.Basic.
Are we confident enough with it now to have a push at converting everything over?

**Comment by nitzmahone** [comment]
**Working group meetings for Dec 18, Dec 25, Jan 1 are cancelled due to holidays**

See everyone in the new year!

**Comment by dagwieers** [comment]
----
**This agenda has been migrated to a new location: #294**

----
