### ISSUE TITLE
Add me to ansible GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [ansible/community#299]
Hey,

I am really excited about the active development and wanted to be a part of the **ansible** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is **YoginthS**

Thanks, [Yoginth](https://yoginth.ml)

**Comment by gundalow** [comment]
Hi,
What in particular would you like to get involved with?
What modules or features are you interested in?
We have a number of "Working Groups" for different areas, each of them have a channel on IRC and a wiki listing current ideas, see https://github.com/ansible/community/wiki

Joining `#ansible-devel` on FreenodeIRC is a good place to see what's going on
