### ISSUE TITLE
Write "thou shalt not" guidelines for committers

### ISSUE THREAD

**Issue by gregdek** [ansible/community#3]
At the Ansible Contributor Summit, it became clear that we don't have good enough social guidelines for what core contributors "should" and "shouldn't" do. We need to write these guidelines, socialize them amongst the team, and get sign off, so that we can start adding more core contributors to ansible/ansible.

**Comment by mckerrj** [comment]
Have you started a doc or anything on this? If not, I'd be happy to get some of it going or work with you on it.  I'd like to get something posted in the next couple of days so we can kick this lose.

**Comment by gregdek** [comment]
mckerrj, jimi-c said you were on this, so I'm assigning to you.

**Comment by gregdek** [comment]
This should probably be a PR in ansible/ansible for the new "docs/proposals" directory or whatever we decide.

**Comment by gregdek** [comment]
In fact, rather than just say "hey whatever we decide," let's go ahead and create docs/proposals in ansible/ansible, with this as the first proposal.

**Comment by robynbergeron** [comment]
Note: The title of this should probably be more specific to "committers" -- not contributors. Happy to edit the issue title to reflect :)

**Comment by gregdek** [comment]
Done.

**Comment by gregdek** [comment]
Robyn and I have both made comments. We should probably circle back to hammer out a final draft together this week if possible.

**Comment by gregdek** [comment]
Still undergoing internal review.

**Comment by gregdek** [comment]
Internal review complete; now waiting on @mckerrj to publish.

**Comment by gregdek** [comment]
Thanks @mckerrj! This is now being debated in the PR itself.
