### ISSUE TITLE
documentation working group

### ISSUE THREAD

**Issue by gregdek** [ansible/community#30]
we have a number of documentation issues that might be best resolved by a team of folks paying attention. for example: generating documentation based on the current released version, not the devel version.

**Comment by gundalow** [comment]
Just linking this in
Versioned documentation is on the way https://hvops.com/newsletters/ansible/64

**Comment by gregdek** [comment]
Copying @docschick and @dharmabumstead on this (old) ticket. Is this a thing you guys want?

**Comment by robynbergeron** [comment]
Labelling for discussion / decisions on where to send this in Community WG meeting today.

**Comment by robynbergeron** [comment]
Holding until next meeting to wait on the pings :)

**Comment by gregdek** [comment]
The answer is no. Docs are integral parts of various working groups, and breaking out a separate group seems to have no benefit.
