### ISSUE TITLE
Servers and Workstation

### ISSUE THREAD

**Issue by CharlesG1** [ansible/community#300]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by CharlesG1** [comment]
I have to update repo files for Server and Workstation: how can I use the playbook and tell the difference between a Linux Server and Workstation? It has always been a problem to Register and use a Variable, because I tried to cat the /etc/redhat-release, but gets ERROR: undefined variable, so cannot go that way.

**Comment by Akasurde** [comment]
@CharlesG1 Thanks for reporting this issue. If you are looking for Ansible then please file a new issue [here](https://github.com/ansible/ansible/issues/new). This repo is used for community interaction.
