### ISSUE TITLE
Public Ansible Project Meeting Agenda - Apr 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#301]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though ~~strike-though~~

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by sieben** [comment]
I would like to discuss this PR: https://github.com/ansible/ansible/pull/38285 There is still debug information on it to help reviewers understand how it works. Feedback is welcomed :)

**Comment by bcoca** [comment]
Meeting ended Thu Apr  5 16:05:26 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-05/ansible_core_irc_meeting.2018-04-05-15.08.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-04-05/ansible_core_irc_meeting.2018-04-05-15.08.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-05/ansible_core_irc_meeting.2018-04-05-15.08.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/36357

**Comment by retr0h** [comment]
#38200

**Comment by bcoca** [comment]
Meeting ended Thu Apr 12 15:19:16 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-12/ansible_core_irc_meeting.2018-04-12-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-04-12/ansible_core_irc_meeting.2018-04-12-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-12/ansible_core_irc_meeting.2018-04-12-15.02.log.html

**Comment by pilou-** [comment]
ansible/ansible#38196: I would like some feedback/reviews

**Comment by bcoca** [comment]
Meeting ended Tue Apr 17 19:50:34 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-17/ansible_public_core_meeting.2018-04-17-19.11.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-04-17/ansible_public_core_meeting.2018-04-17-19.11.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-17/ansible_public_core_meeting.2018-04-17-19.11.log.html

**Comment by chopraaa** [comment]
I'd like to discuss addition of dedicated `win_partition`, `win_disk` and `win_volume` modules over the `win_disk_management` module that has a PR going. Also, deprecation of `win_disk_facts` over dedicated modules (again). 

Both `win_disk_management` and `win_disk_facts` are really cluttered, and I think dedicated modules would help us do the same job better.  Would be bringing this up on Tuesday I guess.

**Comment by Im0** [comment]
Would like any reviews/comments about this filter plugin addition in mathstuff.py: https://github.com/ansible/ansible/pull/39114

**Comment by abadger** [comment]
Proposal to implement tainting of vaulted variables: https://github.com/ansible/proposals/issues/109  I'm putting this on the agenda because I think we should vote not to implement this.  There's simply no way to ever make this better than a leaky sieve.  Advertising it as a security feature would be bad.

**Comment by sieben** [comment]
I would like to have reviews on https://github.com/ansible/ansible/pull/38739 and https://github.com/ansible/ansible/pull/38587

**Comment by bcoca** [comment]
Meeting ended Tue Apr 24 19:43:46 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-24/ansible_core_irc_public_meeting.2018-04-24-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-04-24/ansible_core_irc_public_meeting.2018-04-24-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-24/ansible_core_irc_public_meeting.2018-04-24-19.05.log.html

**Comment by albertomurillo** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/31956
It has been sitting around for too long, fixes an annoying bug and is already reviewed.
IRC: albertom

**Comment by bcoca** [comment]
Meeting ended Thu Apr 26 15:32:11 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-26/core_public_irc_meeting.2018-04-26-15.08.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-04-26/core_public_irc_meeting.2018-04-26-15.08.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-04-26/core_public_irc_meeting.2018-04-26-15.08.log.html

**Comment by sac** [comment]
I'd like to discuss PRs:
https://github.com/ansible/ansible/pull/37822
https://github.com/ansible/ansible/pull/37771
