### ISSUE TITLE
Ansible meetup 21/22 April, Paris (France)

### ISSUE THREAD

**Issue by pilou-** [ansible/community#305]
An Ansible meetup _how to contribute to Ansible_ will take place on 21/22 April in Paris.

This issue is used for counting attendees: attendees are asked to comment there.

Date: Saturday 21 April and Sunday 22 April
Location: Paris (France)

Please, per [host request](https://github.com/ansible/community/issues/305#issuecomment-381920434), if your GitHub public profil doesn't mention your real name, provide it to us there or by [email](pierre-louis.bonicoli@libregerbil.fr).

[Full description](https://annuel2.framapad.org/p/r.578b074c76d55322999cdf5932149542?noColors=true) (in French)

**Comment by pilou-** [comment]
I will be there both days :)

**Comment by Hachebourin** [comment]
Hello :)

Same for me. I will come both days.

**Comment by mscherer** [comment]
I will also be here

**Comment by sieben** [comment]
We will need your name and affiliation to organize it. Be sure to communicate to myself or @pilou- all the required information (name, affiliation)

**Comment by sieben** [comment]
@Hachebourin ^

**Comment by moula** [comment]
Hello,  l'atelier de samedi ou grève :-)

**Comment by pilou-** [comment]
@Hachebourin  @moula: sorry folks, meetup is cancelled :-/ Another one is being planned for later this year.
