### ISSUE TITLE
Network First Gamification Exercise - Earn Ansible Swag!

### ISSUE THREAD

**Issue by gundalow** [ansible/community#311]
# WE WANT PULL REQUESTS FOR ANSIBLE NETWORKING DOCUMENTATION

## 5 pull requests == 1 t-shirt shipped to your house

![t-shirt](https://lf.staplespromotionalproducts.com/lf?set=scale[1200],env[live],output_format[png],sku_number[200284094],sku_dir[200284],view_code[F1]%26call=url[file:san/com/sku.chain])

- keep pull requests simple
- keep pull requests small
- keep pull requests succinct

Documentation pull requests can be a 1-task example... in fact, we encourage very simple 1-task examples!

## RULES

- must be a PR for Ansible Networking modules that are already part of the project: https://docs.ansible.com/ansible/latest/modules/list_of_network_modules.html
- submit PR against this issue-> https://github.com/ansible/community/issues/311
- email ansible-network@redhat.com after you reach 5 pull request with your t-shirt size

## EXAMPLE PULL REQUEST

https://github.com/ansible/ansible/pull/40021

All I did for the [ios_l3_interface](https://docs.ansible.com/ansible/devel/modules/ios_l3_interface_module.html) module was add this example to the documentation after testing it on my own Cisco switch

```
- name: Set interface Vlan1 (SVI) IPv4 address
  ios_l3_interface:
    name: Vlan1
    ipv4: 192.168.0.5/24
```
# Validation
To make sure you're adding a valid new example for the platform you've selected, you must use your new example in a playbook and your pull request must include:
- the output of the playbook
- the output of the relevant show command on the network device so we know the playbook was actually executed

For the example above, here's a playbook: 
```
➜  ansible-napalm-samples git:(master) ✗ ansible-playbook test.yml

PLAY [arista] ********************************************************************************************************************************************************************

TASK [Set interface Vlan1 (SVI) IPv4 address] ************************************************************************************************************************************
changed: [eos]

PLAY RECAP ***********************************************************************************************************************************************************************
eos                        : ok=1    changed=1    unreachable=0    failed=0

```
Here's the proof that it ran properly:
```
eos#sh run int vlan1
interface Vlan1
  ip address 192.168.0.5/24
```

## HOW? HOW DO I DO IT?

1) Create a fork!
Create a fork on your own Github personal space
[GitHub Documentation on Forking a repo](https://help.github.com/articles/fork-a-repo/)

Ensure your fork is up to date https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

2) Configuring Your Remotes
Configure github.com/ansible/ansible as your upstream so you can stay in sync
`git remote add upstream https://github.com/ansible/ansible.git`

3) Rebasing Your Branch
`git pull --rebase upstream master`

## CREATE THE PULL REQUEST

https://help.github.com/articles/creating-a-pull-request/

Please comment here if you have questions or we need more documentation to make this process easy!

**Comment by HimanshuAwasthi95** [comment]
I'm new to ansible .... I'm confused from where to start? 
Should I learn hardcore concepts of ansible for contributing too this?

**Comment by LindsayHill** [comment]
@HimanshuAwasthi95 if you're new to Ansible, then I would suggest just start with learning that first. Come back to this a little later.

You don't need to know a lot about detailed Ansible to contribute to this, but it will be a distraction from learning Ansible up front. Cover that first.

**Comment by gundalow** [comment]
Thanks to everyone that participated, this is now closed.
