### ISSUE TITLE
Identify key EU meetup cities to target in the upcoming year

### ISSUE THREAD

**Issue by gregdek** [ansible/community#314]
Since we'll have some community advocates able to travel to meetups, need to identify key cities in NA+EU that would most benefit from Ansible folks visiting and speaking in the coming year.

**Comment by gundalow** [comment]
Is this about key https://www.meetup.com/topics/ansible/ events, or general events that we should send Ansible people to?

Depending on when/where I should be able to help with EU

**Comment by gregdek** [comment]
Could be either. We'll have some extra folks to help; we need to figure out how to best use their time.

**Comment by cybette** [comment]
I'm focusing on EU meetups for now. Should we separate this into two tasks (NA and EU) or keep it as one?

**Comment by gregdek** [comment]
Let's split it in two. I'll create a separate NA issue.
