### ISSUE TITLE
Organizing for Ansiblefest Contributor Conference 2018

### ISSUE THREAD

**Issue by gregdek** [ansible/community#315]
It's that time again. Will use this as a general tracker for various Ansiblefest tasks until it's time to break them down more. Document here:

https://etherpad.openstack.org/p/ansible-summit-october-2018

**Comment by robynbergeron** [comment]
Okay! So: 

* We've fleshed out the etherpad
* We have discount codes and such
* We have an eventbrite code 
* @gundalow is sending out a mail to the lists 
* https://etherpad.openstack.org/p/ansible-summit-october-2018 is the etherpad in which we'll be collecting details around what folks want to discuss at the contributor Summit

**Comment by robynbergeron** [comment]
@gundalow let's update this when we know what the date is when we're going to make a final call on the agenda -- and we can go from there to (a) do a blog post, (b) do broader announcing of the contributor summit to the ansible-project list, since as of now we'll only have pinged ansible-devel + awx.

**Comment by robynbergeron** [comment]
@gregdek @gundalow may also want to make a issue re:  adding an ansiblefest announce to galaxy in their repo, maybe? Thoughts on how to handle that?

**Comment by gundalow** [comment]
@robynbergeron https://galaxy.ansible.com/home has a big AnsibleFest banner now

**Comment by gundalow** [comment]
Making a note of post-fest actions

- [ ] Feedback - Collect feedback from attendees - in person & remote. Ask for follow up comments to be added to Etherpads by $DATE
- [ ] Review Etherpads, create GH Issues and link back to Etherpads
- [ ] Convert Etherpads to Markdown and move to https://github.com/ansible/community/tree/master/meetings/contributor_summits
- [ ] Replace Etherpads with links to Markdown
- [ ] Write up summary doc - possible blog post, next steps, call to action
