### ISSUE TITLE
Repository of Ansible presentations

### ISSUE THREAD

**Issue by gregdek** [ansible/community#316]
We've now got some folks on the Ansible team committing to putting some prebuilt Ansible presentations into the community repo.

We need to decide where they're gonna live, formatting, and other such questions. We'll use this issue to track that work.

@dfederlein -- I choose you!

**Comment by dfederlein** [comment]
LOL So we should chat, because we're thinking of expanding lightbulb for these as well.  Should these be separate in this repo, or should we build out lightbulb more?

**Comment by gregdek** [comment]
No, it's fine to leave that stuff in lightbulb. We can link to any presos from here. I'll just close this one.

**Comment by gundalow** [comment]
How do we know if a presentation should be stored in `lightbulb` vs elsewhere?

**Comment by gregdek** [comment]
We don't. I don't want to make a policy decision there. Decks live where they live, and we link to them in outreach.
