### ISSUE TITLE
how to move existing vm to specific folder in vcenter?

### ISSUE THREAD

**Issue by llmiell** [ansible/community#323]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by llmiell** [comment]
Could you help on this ?

**Comment by Akasurde** [comment]
@llmiell please report new issue here - https://github.com/ansible/ansible/issues/new with details for playbook and console log?
