### ISSUE TITLE
Public Ansible Project Meeting Agenda - July 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#325]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by maxamillion** [comment]
There was a large rewrite to the `k8s_raw` and `openshift_raw` modules that landed in Ansible 2.6 which maintained backwards compatibility (as far as we know) and also fixed many bugs along the way. The rewrite makes it easier for the maintainer to maintain the code and it also added more test cases for good measure. I was curious if the core dev community would be alright with this being backported to the `stable-2.5` branch even though it is such a large change to the module code.

Also, there's a decent chance I will miss the community meeting but I wanted to notate here for posterity that I'm alright with backporting the changeset so long as the rest of the group is. https://github.com/ansible/ansible/issues/42041#issuecomment-401115508

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/39794 <= allow gpl in module utils (depends on gpl2 code)

**Comment by samdoran** [comment]
ansible/ansible#42033 <= allow more parameter types in the `type:` field in the module docstring

**Comment by bcoca** [comment]
Meeting ended Tue Jul  3 20:11:53 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-03/ansible_core_irc_public_meeting.2018-07-03-19.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-03/ansible_core_irc_public_meeting.2018-07-03-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-03/ansible_core_irc_public_meeting.2018-07-03-19.06.log.html

**Comment by dagwieers** [comment]
Please review:
- ansible/ansible#38325
- ansible/ansible#39526

**Comment by dagwieers** [comment]
I would like to reconsider [the mechanism](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2390) that adds (the last raised, but catched) `exception` (traceback really) to the module's output when the module fails (and debug/verbosity was raised). Almost always is this specific traceback ***not*** related to the actual failure, and as such confusing.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/42044 is this a bug?

**Comment by bcoca** [comment]
Meeting ended Tue Jul 10 19:10:19 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-10/ansible_core_public_irc_meeting.2018-07-10-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-10/ansible_core_public_irc_meeting.2018-07-10-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-10/ansible_core_public_irc_meeting.2018-07-10-19.02.log.html

**Comment by maxamillion** [comment]
There's currently a disagreement about how best to handle retrieving information from an `etcd3` system, either via module or lookup plugin and I would like to get a general consensus from the core development community. https://github.com/ansible/ansible/pull/42127

**Comment by tzurE** [comment]
We'd like to push this PR: https://github.com/ansible/ansible/pull/3996
we added the required changes that the core team asked us to, and want to contribute more code but this issue a blocker.

**Comment by bcoca** [comment]
Meeting ended Thu Jul 12 15:20:16 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-12/ansible_core_public_irc_meeting.2018-07-12-15.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-12/ansible_core_public_irc_meeting.2018-07-12-15.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-12/ansible_core_public_irc_meeting.2018-07-12-15.06.log.html

**Comment by itdependsnetworks** [comment]
Any chance on getting this to the 2.7 agenda? `https://github.com/ansible/community/issues/291#issuecomment-355016399`

**Comment by dagwieers** [comment]
I'd like to have these reviewed (asked a few times on #ansible-devel):
- https://github.com/ansible/ansible/pull/42513
- https://github.com/ansible/ansible/pull/38325

**Comment by bcoca** [comment]
Meeting ended Tue Jul 17 20:04:30 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-17/ansible_core_public_irc_meeting.2018-07-17-19.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-17/ansible_core_public_irc_meeting.2018-07-17-19.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-17/ansible_core_public_irc_meeting.2018-07-17-19.03.log.html

**Comment by fabianvf** [comment]
There are a couple features for the k8s module that went into devel after 2.6 was released, they add quite a bit of functionality for users. 

The first  allows users to pass in a yaml string (including multidocument yaml) and have the module parse it and perform actions on all the resources in the string (the `from_yaml` filter does not support multidocument yaml)
- https://github.com/ansible/ansible/pull/40730

The second allows users to pass in lists of resources and fixes type validation issues from the first.
- https://github.com/ansible/ansible/pull/42377

The third is much higher priority, as it allows a workaround for a bug that prevents any updates on CustomResources (which don't support the strategic merge_patch).
- https://github.com/ansible/ansible/pull/42219

**Comment by bcoca** [comment]
Meeting ended Thu Jul 19 16:01:16 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-19/core_public_irc_meeting.2018-07-19-15.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-19/core_public_irc_meeting.2018-07-19-15.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-19/core_public_irc_meeting.2018-07-19-15.06.log.html

**Comment by dagwieers** [comment]
I'd like to have these reviewed (asked a few times on #ansible-devel):
- ansible/ansible#42513
- ansible/ansible#38325

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/43128

**Comment by abadger** [comment]
Important: Changes to the release schedule to allow for slippage: https://github.com/ansible/ansible/pull/43103

Basically, Freezes will occur two weeks earlier.

**Comment by sylr** [comment]
https://github.com/ansible/ansible/issues/38808

**Comment by bcoca** [comment]
Meeting ended Tue Jul 24 20:05:31 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-24/ansible_core_irc_public_meeting.2018-07-24-19.07.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-24/ansible_core_irc_public_meeting.2018-07-24-19.07.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-24/ansible_core_irc_public_meeting.2018-07-24-19.07.log.html

**Comment by bcoca** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-26/ansible_core_public_irc_meeting.2018-07-26-14.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-26/ansible_core_public_irc_meeting.2018-07-26-14.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-26/ansible_core_public_irc_meeting.2018-07-26-14.01.log.html

**Comment by abadger** [comment]
Voting to allow this bulk style update: https://github.com/ansible/ansible/pull/43401  (reviewed by abadger, So far, +1 from abadger, sivel)

**Comment by jose-delarosa** [comment]
https://github.com/ansible/ansible/pull/43469
https://github.com/ansible/ansible/pull/43470

Need review please.

**Comment by bcoca** [comment]
Meeting ended Tue Jul 31 19:14:06 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-31/ansible_core_public_irc_meeting.2018-07-31-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-07-31/ansible_core_public_irc_meeting.2018-07-31-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-31/ansible_core_public_irc_meeting.2018-07-31-19.00.log.html
