### ISSUE TITLE
Metrics: Which metrics

### ISSUE THREAD

**Issue by gundalow** [ansible/community#335]
- [ ] How can we define success
- [ ] Working Group: Joiners, leavers, duration
- [ ] Metrics: Break down by supported_by:(core,community)
- [ ] Metrics: Clarify moving content out of ansible/ansible is out of scope

**Comment by acozine** [comment]
For documentation, I'd love to know how well our team can keep up with incoming documentation problems/suggestions/ideas. We're currently So I'd like to track:
- [ ] how many open PRs and issues marked `docs` and/or `docsite_pr` do we have, tracked over time
- [ ] with a breakdown of PRs that *only* touch files in `docs/docsite` vs touch docs files *and* other files
- [ ] how long do PRs and issues sit open on average
- [ ] oldest open PR/issue
- [ ] average wait between opening a docs issue/PR and getting a comment/response
We're working through the current backlog, so I expect the current stats to be a little painful, but over time I hope we will improve.

**Comment by gundalow** [comment]
Bot work: https://github.com/ansible/ansibullbot/issues/1047
