### ISSUE TITLE
Which modules are responsive

### ISSUE THREAD

**Issue by gundalow** [ansible/community#337]
For a module to be counted as "certified" we need to ensure the maintainers are responsive to issues & PRs.

For Galaxy Roles there would be a block of dev work needed to collect these stats

**Comment by gregdek** [comment]
Just being able to define what is and isn't "responsive", and then sorting out who meets that bar, is very important.

**Comment by bcoca** [comment]
that varies a lot, if i have an emergency 'unresponsive' means "they didn't answer within 5 mins", if it is anything else 3 weeks .. most people fall somewhere in between and change depending on the urgency on their side.

Considering vacation periods outside US, it is possible and even expected that 4 weeks might go by w/o response, but for 'temporary reasons'.
