### ISSUE TITLE
Public Ansible Project Meeting Agenda - Sept 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#347]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by bcoca** [comment]
Meeting ended Tue Sep  4 19:14:37 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-04/ansible_core_irc_public_meeting.2018-09-04-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-09-04/ansible_core_irc_public_meeting.2018-09-04-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-04/ansible_core_irc_public_meeting.2018-09-04-19.01.log.html

**Comment by sethp-nr** [comment]
I'd like to discuss my PR: https://github.com/ansible/ansible/pull/35636

Meshing the systemd state machine with Ansible's understanding of state is a tricky business.

**Comment by bcoca** [comment]
Meeting ended Thu Sep  6 16:07:24 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-06/ansible_core_irc_meeting.2018-09-06-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-09-06/ansible_core_irc_meeting.2018-09-06-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-06/ansible_core_irc_meeting.2018-09-06-15.03.log.html

**Comment by bcoca** [comment]
finalize decision on future direction of systemd module ... version/implementation quirk DB  or state machine that does independent verification from systemd tools, either needs to translate into 'ansible states'.

**Comment by gundalow** [comment]
**Austin AnsibleFest Contributors Summit**


**Top level Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018
**Core update Agenda**: https://etherpad.openstack.org/p/ansible-summit-october-2018-Core-update

Please feel free to add comments and vote (`+1`) on topics.

**NOTE** time and location of sessions may change

For more information about the Contributors Summit see https://github.com/ansible/community/issues/329#issuecomment-410040811

If you have questions feel free to ask here, in IRC, or ping `gundalow`.

Hope to see you there either in person or online.

**Comment by devyanikota** [comment]
I'd like to discuss my PR: [1].
Added support for remove-brick operation for the existing GlusterFS volume module[2].

[1] https://github.com/ansible/ansible/pull/38269
[2] https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/glusterfs/

**Comment by bcoca** [comment]
Meeting ended Tue Sep 18 19:06:16 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-18/public_core_irc_meeting.2018-09-18-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-09-18/public_core_irc_meeting.2018-09-18-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-18/public_core_irc_meeting.2018-09-18-19.01.log.html

**Comment by dagwieers** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/45853

**Comment by alikins** [comment]
I'd like to point folks to https://github.com/ansible/ansible/pull/44983 (potential impl of https://github.com/ansible/proposals/issues/39) for review/discussion.

**Comment by devyanikota** [comment]
> I'd like to discuss my PR: [1].
> Added support for remove-brick operation for the existing GlusterFS volume module[2].
> 
> [1] [ansible/ansible#38269](https://github.com/ansible/ansible/pull/38269)
> [2] https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/glusterfs/

I'd like to discuss this in today's meeting.
Thank you.

**Comment by lwm** [comment]
*hoping this is the right place ...* - Could I nag some more to get https://github.com/ansible/ansible/pull/45902 seen to? Will turn up to the next meeting. Poked around on #ansible-devel but didn't find anyone who has some experience with the inventory plugin modules.

**Comment by bcoca** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-25/ansible_core_public_irc_meeting.2018-09-25-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-09-25/ansible_core_public_irc_meeting.2018-09-25-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-25/ansible_core_public_irc_meeting.2018-09-25-19.02.log.html

**Comment by ryansb** [comment]
Get your agenda items on the Contributor Summit page: https://etherpad.openstack.org/p/ansible-summit-october-2018

**Comment by bcoca** [comment]
Meeting ended Thu Sep 27 15:54:08 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-27/ansible_core_team_meeting.2018-09-27-15.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-09-27/ansible_core_team_meeting.2018-09-27-15.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-09-27/ansible_core_team_meeting.2018-09-27-15.05.log.html

**Comment by bcoca** [comment]
next issue https://github.com/ansible/community/issues/375
