### ISSUE TITLE
[new_contributor] Speak to them 

### ISSUE THREAD

**Issue by gundalow** [ansible/community#353]
New contributors should be a great source of information, we should speak to them.
Additionally if there PRs have been merged they maybe interested in some ideas of what to look at next.

Rather than a survey I'm thinking open ended discussions/chat so my prejudices don't influence them, there are a few possible topics/questions:

* From what I can see you've just had your first PR merged into the Ansible project, congratulations and thank you for your contribution
* How was the process for you? 
* did it make sense what to do to progress the PR? 
* Did you know you could run `ansible-test` locally?
* What interested you in contributing to Ansible - personas
  * See if they would be interested in possible future maintainer?

https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=label%3Anew_contributor+label%3Abug+-label%3Abackport+merged%3A%3E2018-09-01

**Meta**

* Consider talking to UX

Tracking who we've spoken to as [label:contrib_follow_up](https://github.com/ansible/ansible/issues?q=label%3Acontrib_follow_up+is%3Aclosed)

**Comment by Im0** [comment]
`From what I can see you've just had your first PR merged into the Ansible project, congratulations and thank you for your contribution`.

How about a t-shirt a bit like the network documentation gamification?
