### ISSUE TITLE
Create a Documentation WG

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#358]
It would be nice if we had a documentation WG where we can start listing:
- Nice features for documentation or toolchain
- Cleanup operations in documentation
- Look and feel improvements
- Define standards to documentation writing (so documentation feels consistent)
- Processing docsite_pr and docs PRs.

And have regular meetings to track progress.

**Comment by gundalow** [comment]
Added to https://etherpad.openstack.org/p/ansible-summit-october-2018-documentation for discussion during Contributors Summit

**Comment by gundalow** [comment]
I'll do this, currently updating https://github.com/ansible/community/pull/372 so I document the procedure.

**Comment by gundalow** [comment]
Initial docs added in https://github.com/ansible/community/pull/373

Feel free to raise PR to update that.

**Comment by gundalow** [comment]
So you now have:
* `#ansible-docs`
* https://github.com/ansible/community/wiki/docs - You can create sub paged under that, see how Windows is done
* https://github.com/ansible/community/blob/master/group-docs/README.md

**Comment by gundalow** [comment]
Ansibullbot needs a bit more work as currently it's based on Module categories https://github.com/ansible/ansibullbot/issues/1067

**Comment by gundalow** [comment]
Maybe also worth putting some tips & tricks on https://github.com/ansible/community/wiki/Docs (or at least linked from)

**Comment by gundalow** [comment]
Remaining tasks:

1. Ansibullbot needs a bit more work as currently it's based on Module categories ansible/ansibullbot#1067
2. Initial ideas on https://github.com/ansible/community/wiki/Docs (maybe pull some bits from https://etherpad.openstack.org/p/ansible-summit-october-2018-documentation)?
3. Publicise - `#ansible`, `#ansible-devel`, Google Groups: `ansible-project` & `ansible-devel`

**Comment by dagwieers** [comment]
@gundalow Thanks for driving this !

**Comment by gundalow** [comment]
Agenda for meeting https://github.com/ansible/community/issues/389 please hit `subscribe`

**Comment by dagwieers** [comment]
I guess we can close this, the WG is working :-)
