### ISSUE TITLE
PR Workflow: Should `changelog/fragments` stop automerge?

### ISSUE THREAD

**Issue by gundalow** [ansible/community#361]
Currently if a PR change `changelogs/fragments/` then `support:core` is added, this stopping automerge.

Q: Do we want to allow these to be automerge (update BOTMETA)

**Comment by jborean93** [comment]
I think we should, no reason a changelog should have a special workflow.

**Comment by gundalow** [comment]
https://github.com/ansible/ansibullbot/pull/1089

**Comment by gundalow** [comment]
No longer an issue, closing
