### ISSUE TITLE
IRC - Is it still right & tidyup

### ISSUE THREAD

**Issue by gundalow** [ansible/community#362]
Central place to track all the discussions around IRC

Current list of IRC channels: https://github.com/ansible/community/#groups

## Moving away from IRC

* Where else could we go?
* Are their ways of linking IRC & Slack (we tried something though it was ugly, is there something better)

## Requirements

* CoC
  * https://docs.ansible.com/ansible/latest/community/code_of_conduct.html
  * Ability to kick people that don't follow it
* Ability to run meetings and log

## Improving IRC

* Logging channels?
* Add some other "Group Contacts", 2-3, split timezones, define list internally
* ~~See if we can take ownership of the other `#ansible*` channels~~ DONE
* ~~Network Team to move all discussion to `#ansible-network`~~ DONE

## Where to get feedback

* Ask outreach
* Once we have a short list, do a survey on ansible-project & ansible-devel

**Comment by privateip** [comment]
personally i would like to see us move to Gitter due to its nice integration with Github -- https://gitter.im/

**Comment by rcarrillocruz** [comment]
I'm intrigued by Matrix ( https://matrix.org/docs/projects/try-matrix-now.html ), keep on hearing great things about it, it's open source and great integration.
Haven't said that, I have not used, neither Gitter, so I'll better try a few options before taking a side on one another.

**Comment by privateip** [comment]
i guess if you are going to go there then this should be on the list as well --> https://rocket.chat/

**Comment by bcoca** [comment]
Matrix can integrate several server platforms into one interface for it's clients as well as multiple client protocols.

Rocket also has IRC client integration but I am not aware of a server one.

**Comment by abadger** [comment]
There's also tulip.  that said, just for getting IRC-slack integration back, the tulip devs recommended I try out matrix.  The matrix service seems okay.  However, I've yet to find a great, intuitive matrix client (for my phone... also tried out desktop apps to see if it was just phone apps that weren't doing it for me and they weren't great either.)

I still like straight IRC clients above anything else out there so everything else I've tried has really had the ideal goal of "does this make it easier for me to integrate with IRC?"

**Comment by dagwieers** [comment]
We have a Matrix setup and there are various caveats when you want to use this in production (the quick succession of releases is only one, various implementation problems and a future rewrite only makes this worrisome to build on now). Also, it includes voice/video conferencing and file sharing, and I don't think you can turn some of these off. That said, I like some of the ideas implemented in Matrix and the Android app does work well.

Probably a more reliable alternative is Mattermost, which has all kinds of interfaces (incl. IRC) and is Open Source too. And it reflects Slack to some degree (for the better or worst, depending on your perspective with Slack :-))

**Comment by rcarrillocruz** [comment]
I also heard very good things about Mattermost.

To me, this is my personal criteria:

1. Open Source
2. Integration with IRC
3. Good mobile apps
4. Stable

If it's Mattermost or Matrix or $solution , those are the things I would like them to have.

**Comment by lwm** [comment]
I've opened Gitter chat rooms for my Github projects and had people turn up and chat a lot more than any other platform at all. Some groups are simply deluged by people. It's just so convenient to get in there and start hammering away. #ansible is already pretty noisy and Ansible is like, world scale, on the level of issues and backlog and the like. I suppose you've all realised that maybe you'll get a shock at how many people turn up if you open up the chat space! :) IRC is definitely a barrier if you're looking to maximise the access. I lean towards https://rocket.chat/ now, which I use for multiple projects and find it really good. It has solid integrations (the Jitsi video one is impressive) and access control lists, admin interfaces, extensibility for bots, etc. It's solid software.

**Comment by gundalow** [comment]
Hi everybody,
Lots of great feedback in here.

Any ideas of what the specific pain points are with IRC, that way we maybe able to address them directly to improve IRC in the short->long term

**Comment by jborean93** [comment]
I think the biggest issue for IRC I've seen is lack of history, I use IRCCloud which keeps it for me but not everyone has the luxury (or wants to use another service) for this.

**Comment by mscherer** [comment]
So, on the slack<->irc interaction, I would point people to the ToS of slack, cause they are kinda super sketchy, and putting a lot of requirements that we wouldn't respect with a bridge (like, the part about age verification, etc). I didn't verify if this changed since last years, but I think it didn't.

**Comment by tonk** [comment]
I still think IRC could be a very valid channel. But if you really want code-blocks, emoticons and things like that, I would vote Mattermost.

**Comment by lwm** [comment]
For consideration: https://github.com/thelounge/thelounge

**Comment by maxamillion** [comment]
Big +1 to stick with irc.

However, if there's a large draw to move away from it or somehow supplement it then I'd +1 [matrix](https://matrix.org) with a suggestion of [riot.im](https://riot.im) as the recommended front end. If there's not much desire for that, then [rocket.chat](https://rocket.chat/) is reasonable.

**Comment by gundalow** [comment]
In `#ansible-community` today (2019-02-11) we talked about this and we are looking at `Matrix <---> Freenode` integration which would allow the same channels to be accessed directly via IRC (no change) or via Matrix.

We are working on some docs for this in https://github.com/ansible/community/pull/441 as part of a limited trial to get feedback. 

The Ansible channels have had the channel had the Nickname registration requirement removed, so it Matrix users should be able to join without registering with Nickserver, lowing the bar to entry.

**Comment by blaisep** [comment]
Dunno if this is old news, there's also a telegram to freenode bridge which
the fedora  folks set up:
https://docs.fedoraproject.org/en-US/teleirc-sig/create-new-bot/

HTH
Blaise

**Comment by AJ-Acevedo** [comment]
This post from @GregSutcliffe about Ansible and Matrix is relevant here.

https://ansible.github.io/community/posts/matrix_and_ansible.html
