### ISSUE TITLE
Public Ansible Project Meeting Agenda - Oct 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#375]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by felixfontein** [comment]
I'd like to get some feedback on a lookup plugin: https://github.com/ansible/ansible/pull/42151

**Comment by bcoca** [comment]
Meeting ended Tue Oct  9 20:01:46 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-09/ansible_core_plublic_irc_meeting.2018-10-09-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-09/ansible_core_plublic_irc_meeting.2018-10-09-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-09/ansible_core_plublic_irc_meeting.2018-10-09-19.00.log.html

**Comment by tonk** [comment]
just for the record: My IRC handle is `tkersten`

**Comment by jose-delarosa** [comment]
https://github.com/ansible/ansible/pull/46148
IRC: jdelaros1

**Comment by bcoca** [comment]
Meeting ended Thu Oct 11 15:40:42 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-11/ansible_core_plublic_irc_meeting.2018-10-11-15.07.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-11/ansible_core_plublic_irc_meeting.2018-10-11-15.07.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-11/ansible_core_plublic_irc_meeting.2018-10-11-15.07.log.html

**Comment by pilou-** [comment]
ansible/ansible#45824 bugfix for `uri` (module supported by core team)
ansible/ansible#44428 inventory plugins: `auto`/`ini` order

**Comment by devyanikota** [comment]
I'd like to discuss [1].
Added support for remove-brick operation for the existing GlusterFS volume module[2].
Addressed suggested changes and review comments.

[1] ansible/ansible#38269
[2] https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/glusterfs/

**Comment by bcoca** [comment]
Meeting ended Thu Oct 18 15:42:53 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-18/ansible_core_irc_public_meeting.2018-10-18-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-18/ansible_core_irc_public_meeting.2018-10-18-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-18/ansible_core_irc_public_meeting.2018-10-18-15.02.log.html

**Comment by jamescassell** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/44800 and https://github.com/ansible/ansible/pull/45170

I can be there for the Thursday meeting, Oct 25.

**Comment by kushaldas** [comment]
I would like to discuss https://github.com/ansible/ansible/pull/47034.
My IRC nickname: `kushal`

**Comment by bcoca** [comment]
Meeting ended Tue Oct 23 19:44:09 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-23/ansible_core_public_irc_meeting.2018-10-23-19.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-23/ansible_core_public_irc_meeting.2018-10-23-19.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-23/ansible_core_public_irc_meeting.2018-10-23-19.03.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Oct 25 15:19:13 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-25/ansible_core_irc_public_meeting.2018-10-25-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-25/ansible_core_irc_public_meeting.2018-10-25-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-25/ansible_core_irc_public_meeting.2018-10-25-15.02.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Oct 30 19:59:25 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-30/ansible_core_public_irc_meeting.2018-10-30-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-10-30/ansible_core_public_irc_meeting.2018-10-30-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-10-30/ansible_core_public_irc_meeting.2018-10-30-19.02.log.html
