### ISSUE TITLE
vsphere server connectivity issue: Error :  " Unknown error while connecting to vCenter or ESXi API at 10.10.10.10:443 'NoneType' object has no attribute 'get'" 

### ISSUE THREAD

**Issue by aksdhee** [ansible/community#385]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by aksdhee** [comment]
I am trying to build a new VM using ansible vmware_guest module . 
getting following error while connecting to the vpshere server : 


TASK [Create a virtual machine from a template] *********************************************************************************************************************************************************************************************
task path: /etc/ansible/VM_server_build.yaml:9
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unknown error while connecting to vCenter or ESXi API at 10.10.10.10:443 : 'NoneType' object has no attribute 'get'"}
        to retry, use: --limit @/etc/ansible/VM_server_build.retry

**Comment by sivel** [comment]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
