### ISSUE TITLE
New module review meeting

### ISSUE THREAD

**Issue by gregdek** [ansible/community#39]
We continue to have a not-very-good process for accepting new modules into Extras.

We seemed to agree at the contributor summit that what we needed was a standing meeting to review new modules according to the current guidelines. Now we need to drive that.

**Comment by mckerrj** [comment]
let's meet next week when I'm there? I want to work on this quickly.

**Comment by gregdek** [comment]
Next week is too late. :) Let's meet this week. I really think it's as simple as "pick a time every week, commit one or two core guys for an hour or two, walk through the modules from oldest to newest" to start. It doesn't need to be complicated; we already have clear guidelines. We just need regular predictable review. Once we have a few weeks under our belt, that will give us a velocity, and then we'll be able give contributors a rough idea of how long they can expect to wait.

**Comment by mckerrj** [comment]
ok.  Put something on.  Tuesday afternoon, I'm driving to Boston, but other than that should be ok.

**Comment by gregdek** [comment]
Moving forward. From IRC:

#info newtmckerr will have us a name of a (possibly rotating) facilitator from the core team this week
#info first new module triage meeting will be next week

**Comment by gregdek** [comment]
Still waiting on @mckerrj for a time and a person.

**Comment by gregdek** [comment]
(When we have it, we will update the meeting calendar.)

**Comment by gregdek** [comment]
Meeting will initially be 1700 UTC on Wednesdays. I will add to the calendar and announce to Ansible-devel today.

**Comment by gregdek** [comment]
Changed to 1800 UTC on Wednesdays. In the schedule and announced.
