### ISSUE TITLE
Contributor Experience Agenda

### ISSUE THREAD

**Issue by gundalow** [ansible/community#390]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your GitHub username, leave that as well.

[Big Contributor Project Plan](https://github.com/orgs/ansible/projects/2)

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure contributor_experience and meeting_agenda labels are set

Meeting will be in **#ansible-community** on Libera IRC

**Comment by gundalow** [comment]
Initial topics

* What metrics should we track so we can show progress
* Ansibullbot update: https://etherpad.openstack.org/p/ansibot
* New Contributor feedback https://github.com/ansible/community/issues/353

**Comment by gundalow** [comment]
Update index page of [/community](https://docs.ansible.com/ansible/devel/community/) and [/dev_guide](https://docs.ansible.com/ansible/devel/dev_guide/) so Contributors can find out existing docs.

For minimal effort we can guide people in the right direction.

Welcome your edits & comments via https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#

**Comment by paulvonderhaar** [comment]
Hey, I'm interested in helping development for this project, but I don't have any idea where to begin. Is there a particular place where I can find ongoing issues?

**Comment by gundalow** [comment]
@paulvonderhaar Hi, 
I'd start with an area you already use with Ansible, and then look at

* [label/small_patch](https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asmall_patch+-label%3Abackport+-label%3Aneeds_revision)
* https://ansible.sivel.net/pr/byfile.html
* https://docs.ansible.com/ansible/devel/community/

**Comment by gundalow** [comment]
## [Docs] How to review & test a PR #399

We need (clearer) instructions to so anyone knows how to review and test a PR.
Best type of review is from someone actually using it, rather than just looking at the code

https://github.com/ansible/community/issues/339

https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#heading=h.kzxzqyez5fp5

**Comment by gundalow** [comment]
# 2018-11-08 Minutes

## Purpose

* We define "contributor" as someone that does or should interact with PRs
* s discussed in Contributor Summit in Austin, we'd setup this new group, which I'm (gundalow) working on full time. We are (initially) focusing on PRs, though we are happy to fix other stuff as we go along. It's also expected that some of this work will also improve issues and help the community more generally. 


## Improving Docs: /community and /dev_guide

aka Helping new contributors figure out how to navigate our processes

Update for `/community/` and `/dev_guide/`

[WIP Document](https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#) - updated & comments welcome

* Approach was liked
* Docs about deprecation are always difficult to find, this work helps that
* Lots of updates made to the doc
* Making people aware of updates/changes in the "right" way to do things is an issue
* Writing/reviewing code is only one way to be a contributor **How to sell doing reviews** - Need help with this

Better way to generate modules
* [module-init](https://github.com/jctanner/molecule/blob/MAZER_COLLECTIONS_ANSIBLE_TEST/molecule/command/init/module.py) [proposal#49](https://github.com/ansible/proposals/issues/49)


## [Docs] How to review & test a PR #399

[WIP Document ](https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#) - updated & comments welcome

Before we can attract more reviewers we need to document: 
* How people can review
* What we are looking for in reviews

See [WIP Docs](https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#)
 for current draft. Needs a lot more detail, starting with how to get the code locally to test. Comments welcome in the doc

## Actions

* **acozine/gundalow** to think about changelog for docs, test infrastructure, coding standards
* **gundalow** create issue for tracking ideas on how to motivate reviewers. credit people in changelog, points/badges/stars - watch out for people gaming the system
* **gundalow** needs to document his bigger picture plan (contributor workflow, why we are starting with docs before adding people. Why we improve the SIGs before adding people)
* **gundalow** to do walk though and document how to test a PR

## Full logs

* [Summary](https://meetbot.fedoraproject.org/ansible-community/2018-11-08/ansible_contributor_experience_working_group.2018-11-08-19.00.html)
* [Chat logs](https://meetbot.fedoraproject.org/ansible-community/2018-11-08/ansible_contributor_experience_working_group.2018-11-08-19.00.log.html)

**Comment by ssbarnea** [comment]
Can we do somethign about the DCO check that is currently enabled on ansible/molecule? It makes contributions a PITA, especially as there is no way to use templates when you create PRs using git web interface.

If it is possible to get rid of it would be great for the contrubutor experience https://github.com/ansible/molecule/issues/1548 --- or you can just add me to the team and I will shut up ;)

**Comment by ssbarnea** [comment]
Here is something to think about which I found over the last years about Ansible: because Ansible has a fast release cycle, most users are on an older version on Ansible and they prefer to implement local ugly workarounds for Ansible bugs because they would not be able to benefit from a bugfix anyway (or not in short term).   

If ansible team would have a more related policy about backporting bugfixes to older versions it may be possible to have some extra incentices to improve the product.

Real life example: openstack teams are now using 2.5.x which receives only security fixes. Why would I spend considerable more extra time fixing a bug which I cannot benefit from? Yep, the team will migrate to newer version, but buy thet time this happens, it will again be security-fixes only. 

PS. I have few other examples about people using *now* 2.4.x versions, in production!

**Comment by jamescassell** [comment]
2.4.x I've seen in prod because it comes in RHEL extras

**Comment by gundalow** [comment]
# 2018-11-15 Minutes

## Improving Docs: /community and /dev_guide 
aka Helping new contributors figure out how to navigate our processes

* Review and discussion around https://github.com/ansible/ansible/pull/48734, which was created based on plan from previous meeting.

## Actions
* https://docs.ansible.com/ansible/latest/community/development_process.html refactor should include https://help.github.com/articles/fork-a-repo/# etc for people that are new to GitHub

## Full logs

* [Summary](https://meetbot.fedoraproject.org/ansible-community/2018-11-15/ansible_contributor_experience_working_group.2018-11-15-19.00.html)
* [Chat logs](https://meetbot.fedoraproject.org/ansible-community/2018-11-15/ansible_contributor_experience_working_group.2018-11-15-19.00.log.html)

**Comment by gundalow** [comment]
Modules' `DOCUMENTATION.author` have been checked and 250 modules updated to correctly state the author. CI now enforces the format `author: Name (@handle)`, see https://github.com/ansible/community/issues/406 for background

**Comment by gundalow** [comment]
Details of the big PR review session taking place on Thursday 29th November, see https://github.com/ansible/community/issues/407 for details. Hope to see you there (add a comment if you plan to make it)

**Comment by syncpak** [comment]
I am not sure this is the right IRC but here it goes: If we make a module and import the requests library (which is not installed by default) I understand it is frowned upon, but is it an automatic reason for rejection of the module into the project ? See you next Thursday.

**Comment by gundalow** [comment]
Topics for today's meeting:
* Webinar preparation [How to Make Your Mark: Ansible Community Contributions](https://www.ansible.com/resources/webinars-training/ansible-community-contributions) Wed, Jan 30, 2018 9:30AM EST
  * How to attract new contributors
  * Showing community Progress
  * What do people need to know/motivate to get them contributing
  * Big PR review days
  * What other topics should we cover?
* New Working Groups
  * [AIX](https://github.com/ansible/community/issues/421)
  * [Solaris](https://github.com/ansible/community/issues/422)
* Thoughts on replacing [Working Group email list page](https://docs.ansible.com/ansible/devel/community/communication.html#working-groups) with dedicated page about Working groups
  * Describe the purpose of Working Groups
  * Better links and details of what they are doing
  * Link to docs on how to create a working group

**Comment by gundalow** [comment]
Topics for Thursday's meeting

* Webinar preparation [How to Make Your Mark: Ansible Community Contributions](https://www.ansible.com/resources/webinars-training/ansible-community-contributions) Wed, Jan 30, 2018 9:30AM EST
* Organise and publicize next Big PR review (mid Feb?) https://github.com/ansible/community/issues/407
* Update on Working Groups, inc Molecule [All Working Groups](https://github.com/ansible/community/wiki)
  * Need specific pages for WGs needed

**Comment by gundalow** [comment]
Help needed

It's generally agreed that Working Groups are the secret to scaling challanges with Ansible, so over the next few months I'd like us to focus on them. 

Some initial thoughts:
* Do any of the WG (Working Groups) have anything blocking them? 
* Is it clear how someone just starting out can help? 
* Do we need to highlight `label:$WG + label:bug` items? 
* Does each WG have some guidance/actions in how to increase test coverage 
* If we heavily promoted the WG would it help or drown it? 
* Would they benefit from a WG specific review day, like https://github.com/ansible/community/issues/407

What else? 

Join us at 1900UTC Thursday to discuss this, or add comments in `#ansible-community` or on this GitHub issues.

**Comment by GeoEducator** [comment]
Hello All,
I'm trying to joining the security and Azure meeting and groups so I can be a reviewer and then get to be a contributor.
Thanks,
Dewayne

**Comment by Andersson007** [comment]
Hello @GeoEducator, thanks for your interest and desire to help!
Do you have any issues with joining the meetings and groups?
In case you haven't seen it, we have the [Communication guide](https://docs.ansible.com/ansible/latest/community/communication.html) where you can find all the information on how to join corresponding Matrix/IRC channel.
There you can ask the current maintainers of azure/security collections on how to proceed.
We also have the [Contributor path](https://docs.ansible.com/ansible/devel/community/contributor_path.html) doc that can be useful.

**Comment by Andersson007** [comment]
closed as feels redundant, let's use Community Working Group Meeting Agenda issue instead https://github.com/ansible/community/issues?q=is:open+label:meeting_agenda+label:contributor_experience
