### ISSUE TITLE
Setup IRC Meeting for Contributor Experience

### ISSUE THREAD

**Issue by gundalow** [ansible/community#391]
See when people are available for the Contributor Experience meeting

## What is Contributor Experience, why should I get involved?

* Put together a set of people with a focus on making it easier for good quality code to be merged into Ansible sooner. 
* Collectively we can get bug fixes and features into Ansible which is to everybody's benefit
* Feedback from people new to contributing to Ansible is especially welcome

## When

Weekly at:

* Tuesday 1400 UTC
* Tuesday 1500 UTC
* Wednesday 1900 UTC
* Thursday 1400 UTC

## What if I can't make the meeting

We understand that some people can't make any, or in fact of them. Everything we do will be tracked via GitHub:

 * Agenda: https://github.com/ansible/community/issues/390
* Bigger project plan (needs prioritizing) https://github.com/orgs/ansible/projects/2

Meeting will be in **#ansible-community**

**Comment by gundalow** [comment]
Any of these times work for me

**Comment by gundalow** [comment]
@dagwieers @pilou- @felixfontein @Shaps @agaffney @caphrim007 @emonty @jhawkesworth @mscherer @resmo @Shrews @trondhindenes @willthames @yungezz @geerlingguy @dsoper2

@ansible/ansible-community Would you be interested in this?

**Comment by lwm** [comment]
Yeah, I'd be happy to join this discussion! Any times are probably OK for me too these days.

**Comment by geerlingguy** [comment]
I would be interested, and the times look doable (later is better), so I’d try to make a few meetings for sure.

**Comment by agaffney** [comment]
My availability at 1400 UTC is spotty, and 1500 UTC isn't much better. I'm usually available at 1900 UTC.

**Comment by caphrim007** [comment]
1900 is better for me as well

**Comment by Shaps** [comment]
Wed 1900UTC

**Comment by pilou-** [comment]
Tue 1400 UTC / Tue 1500 UTC / Thu 1400 UTC

**Comment by felixfontein** [comment]
I'd prefer not Thursday, at least thinking long term. For now, all times are equally good/bad ;)

**Comment by rharolde** [comment]
Thursday 1400 UTC  is best for me.
Wednesday 1900 UTC  is second best.

**Comment by gundalow** [comment]
Thanks to all that have replied.
Any other comments before I pick a time?

**Comment by resmo** [comment]
I don't have any preferences, currently.

**Comment by gundalow** [comment]
Hi, so by the numbers **Thursday 1900 UTC** is best, so we will go with that.

That said I know that means we miss some people in EMEA, though as I'm also in EMEA we can look at having something earlier one day. Everything will be tracked online so you can follow what's happening on GitHub and IRC


**Please all join** `#ansible-community` and add-by-URL (don't download and add) `https://raw.githubusercontent.com/ansible/community/master/meetings/ical/ansible_community_meetings.ics`

**Comment by tonk** [comment]
I personally like 19:00 UTC (or 18:00 UTC) because I'n in NL and during
the day I absolutely have no chance to join. (Customer and teaching
stuff).

So, a little later is better.

**Comment by gundalow** [comment]
1) Please add by URL above `.ics`
2) Please join `#ansible-community`
3) Please subscribe to the agenda: https://github.com/ansible/community/issues/390

**Comment by rharolde** [comment]
The calendar URL returns "error 404 not found" for me.
Also, is there a link for where to join "#ansible-community" ?

-- 
Bob Harold

**Comment by gundalow** [comment]
@rharolde I made a typo, correct link is `https://raw.githubusercontent.com/ansible/community/master/meetings/ical/contributor_experience.ics`

All of the Meetings on Freenode IRC, so you'll want an IRC Client or to use a webclient like irccloud.com

For some of the `#ansible-*` IRC channels you need to Register with Freenode to verify your account, see https://freenode.net/kb/answer/registration

**Comment by gundalow** [comment]
Starting in 10 minutes in `'#ansible-community`
