### ISSUE TITLE
Code of Conduct update

### ISSUE THREAD

**Issue by gregdek** [ansible/community#40]
Ours is somewhat outdated. Should consider the Fedora CoC as a base:

https://getfedora.org/code-of-conduct

**Comment by robynbergeron** [comment]
Other examples:
https://www.python.org/psf/codeofconduct/
https://www.openstack.org/legal/community-code-of-conduct/
https://www.elastic.co/community/codeofconduct

Should also consider having an aliased email address that people can report to (not married to this idea one way or the other).

**Comment by gregdek** [comment]
Yeah -- the Fedora CoC is really not that much better. It punts on a lot of important issues.

Of the ones you list, I think the Elastic one is the best one. I'm going to use that as a base to start discussions with stakeholders.

**Comment by gregdek** [comment]
Outreach has started -- waiting on potential PRs.

**Comment by bwlz** [comment]
I have created a pull request for this issue [here](https://github.com/ansible/ansible/pull/15164) - is this the correct thing to do or should I be moving this pull request somewhere else?

**Comment by gregdek** [comment]
Excellent. :) Leaving this open until the PR in ansible/ansible is fully resolved, but the work will happen there.

**Comment by gregdek** [comment]
Sigh. ETA on getting codeofconduct@ansible.com email address is two weeks. But then we'll be ready to go.

**Comment by gregdek** [comment]
Two weeks is up! Going to go get angry at internal Red Hat IT for a while. Will keep folks posted.

**Comment by gregdek** [comment]
No response, and no reason to wait further. I'll work on getting this in immediately with my own email address until we've got something else.

**Comment by gregdek** [comment]
Another update on this: ran into Melanie Chernoff of Red Hat legal at the Tower yesterday, and she agreed to review this and help give sign off (which is what we need to get IT to actually give us the email address "codeofconduct@ansible.com".)  Will follow up with her to keep moving this one along. For now, we're asking forgiveness rather than permission, and we have the new CoC posted with my email address instead.

**Comment by gregdek** [comment]
And this is good enough for now.
