### ISSUE TITLE
[reviewers] Improve/increase

### ISSUE THREAD

**Issue by gundalow** [ansible/community#401]
from @webknjaz 

> Writing/reviewing code is only one way to be a contributor How to sell doing reviews - Need help with this

Add reviewers as Co-authored-by commit trailers to credit the effort to them as well? I really like how Gentoo git workflow guide insists on preserving authorship info :)

@gundalow I'd like to invite you to check out their docs and maybe we could adopt some things from there (it's probably a separate issue though).

Refs
https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Retaining_commit_author_information
https://devmanual.gentoo.org/ebuild-maintenance/git/index.html
https://wiki.gentoo.org/wiki/Gentoo_GitHub#Separate_.28or_.22atomic.22.29_commits
https://www.gentoo.org/glep/glep-0066.html#commit-messages

**Comment by gundalow** [comment]
new_contributors review session
Find people wanting to help review things and focus on new_contributor/small_patch https://github.com/ansible/community/issues/202

**Comment by webknjaz** [comment]
> Add reviewers as Co-authored-by commit trailers to credit the effort to them as well?

https://hynek.me/til/easier-crediting-contributors-github/

**Comment by samccann** [comment]
I believe this is done now. If someone does a suggested edit in github, it shows up in the commit log. Closing this issue since we will be archiving this repo soon.
