### ISSUE TITLE
policy_group is not working in the aci_access_port_to_interface_policy_leaf_profile module

### ISSUE THREAD

**Issue by mupett** [ansible/community#402]
See my config below:
  - name: Associate an access port block (single port) to an interface selector
    aci_access_port_to_interface_policy_leaf_profile:
     hostname: "{{ inventory_hostname }}"
     username: "{{ username }}"
     certificate_name: "{{ certificate_name }}"
     private_key: "{{ private_key }}"
     validate_certs: no
     leaf_interface_profile: "INTPROF_{{ intpol_intprof_name }}"
     access_port_selector: "PORTSEL_{{ attached_device_name }}"
     leaf_port_blk: "{{ item.descr }}"
     leaf_port_blk_description: "{{ item.descr }}"
     from_port: "{{ item.port_id }}"
     to_port: "{{ item.port_id }}"
     policy_group: "INTPOL_{{ intpol_intprof_name }}"
     state: present
    loop: "{{ ports_properties }}"

kind regards,
Luca

**Comment by mupett** [comment]
- name: Associate an access port block (single port) to an interface selector
    aci_access_port_to_interface_policy_leaf_profile:
     hostname: "{{ inventory_hostname }}"
     username: "{{ username }}"
#     password: "{{ password }}"
     certificate_name: "{{ certificate_name }}"
     private_key: "{{ private_key }}"
     validate_certs: no
     leaf_interface_profile: "INTPROF_{{ intpol_intprof_name }}"
     access_port_selector: "PORTSEL_{{ attached_device_name }}"
     leaf_port_blk: "{{ item.descr }}"
     leaf_port_blk_description: "{{ item.descr }}"
     from_port: "{{ item.port_id }}"
     to_port: "{{ item.port_id }}"
     policy_group: "INTPOL_{{ intpol_intprof_name }}"
     state: absent
    loop: "{{ ports_properties }}"

**Comment by gundalow** [comment]
Please raise at github.com/ansible/ansible/issues

**Comment by gundalow** [comment]
This repository is for management of all Ansible community related initiatives, such as meetings.

Ansible Support

Bug reports: https://github.com/ansible/ansible/issues/new
IRC: #ansible on irc.freenode.net * Mailing List: https://groups.google.com/forum/#!forum/ansible-projec
