### ISSUE TITLE
whatcanidoforansible (whatcanidoforfedora)

### ISSUE THREAD

**Issue by gundalow** [ansible/community#405]
Ask not what Ansible can do for you, but what you can do for Ansible.

https://whatcanidoforfedora.org/ looks rather cool.

It flips contributing on it's head by making the (potential) contributor drive the discussion.

I've raised https://github.com/fedora-infra/asknot-ng/issues/92 to see what we can find out

Src: https://github.com/fedora-infra/asknot-ng

**Comment by gundalow** [comment]
https://fedoraproject.org/wiki/Join

**Comment by samccann** [comment]
Moved to https://github.com/ansible-community/community-website/issues/301 so we don't lose the idea. Closing this issue as we'll be archiving this repo soon. See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928 for details.
