### ISSUE TITLE
Reduce needs_maintainer

### ISSUE THREAD

**Issue by gundalow** [ansible/community#406]
Too many modules are listed as having zero maintainers due to bad formatting of `DOCUMENTATION.author` field in the module.

This issue tracks the work to fix that.

Draft scheme.py update: https://gist.github.com/gundalow/a240014769877706e4f46ee9b49a1104

**Comment by dagwieers** [comment]
What do you mean with "Reduce" ? I think it's nice if Github exposes when a module has no maintainer.
But maybe it wouldn't be bad if we could list unmaintained modules, or indicate it in the documentation as well.
