### ISSUE TITLE
Ansible Big PR review days & Office Hours

### ISSUE THREAD

**Issue by gundalow** [ansible/community#407]
Ask not what your community can do for you, ask what you can do for your community!

## What are we doing and why?

Ansible is a very popular project by any metric. Our awesome community contributes lots of Pull Requests (PRs) every month. Unfortunately, the volume of incoming PRs means contributors often have to wait a looong time for PRs to be merged, or even reviewed. We want to change that.

The Core Team and Community at large is starting various initiatives under the [Contributor Experience](https://github.com/ansible/community/issues/390) umbrella to help address some of the root causes that slow down quality PRs from being merged into Ansible. 
We dedicate one day a month to doing a big community review. We hope you can join in!

## What we are trying to achieve

* To give potential new community members a place to learn and experiment with Ansible's review process and get feedback
* Improve the process and documentation by getting feedback from you
  * Feedback from people starting their journey with open source is particularly important to us as it helps to identify and improve complicated processes and documentation.
  * People that have been contributing for a while have already built up this knowledge and have forgotten the "pain of getting started"
* Give PRs some love
* Identify PRs that could be merged or closed
* Help PRs that are not covered by one of the existing [Ansible Working Groups](https://github.com/ansible/community/wiki), and therefore may otherwise fall through the cracks
 
## How

* Using a few (to be defined) GitHub searches we will go through PRs and:
  * Provide feedback, which is useful to the PR author
  * Provide testing feedback, which will help maintainers know if it can be merged
  * Merge if good
  * Close, if not needed

* For collections we will be focusing on 
  * [community.general](https://github.com/ansible-collections/community.general/pulls)
  * [community.network](https://github.com/ansible-collections/community.network/pulls)
  * [community.aws](https://github.com/ansible-collections/community.aws/pulls)

## When

* ~~Thursday 29th November 2018 from 0900 UTC till late~~
* ~~Wednesday 19th December 2018  from 0900 UTC till late~~
* ~~Tuesday 3rd September from 1000UTC til late~~
* ~~Thursday 19th September from 1000UTC til late~~
* ~~Thursday 14th November from 1400UTC til late~~
* ~~Wednesday 17th June from 1400UTC til late~~
* ~~Tuesday 1st December 2020 1500UTC~~
* Thursday 17th December 2020 [In my timezone, and calendar invitation](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible%20PR%20Day+2020&iso=20201217T15)

Add to your calendar by clicking the `Add to Calendar` in the above links
## What do I need

* A [GitHub account](https://github.com/join)
* A bit of spare time
* IRC client to connect to [#ansible-community](https://webchat.freenode.net/?channels=ansible-community) (see note below about registering)
* Add an `I'll be there` comment to this issue
* Before you start:
  * Read Ansible's [Code of Conduct](https://docs.ansible.com/ansible/devel/community/code_of_conduct.html)
* If you have a bit more time, the following guides can help. If not just ask during the meeting.
  * Skim read [Ansible's Contributing Guide](https://docs.ansible.com/ansible/devel/community/) - makes it easier to find content later
  * Read the draft [How to do reviews at Ansible](https://docs.google.com/document/d/1nMevQ0W7MZgJA1tJrJbNHIhTiHYHYUlO3IHXBs_usGE/edit?ts=5be2cd87#heading=h.kzxzqyez5fp5) document - During the session, as a group, this document will be updated.
  * Read [Ansible coding guidelines](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_checklist.html#developing-modules-checklist)
  * Skim read [Ansible's Module guidelines](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_best_practices.html)
  * Want to know more about how to contribute to Ansible, have a look at our on-demand webinar and slides [how to make Ansible community contributions](https://www.ansible.com/resources/webinars-training/how-to-make-ansible-community-contributions).

Even if you are new to contributing to Ansible, this is an excellent opportunity to get involved!

Our IRC channels may require you to register your nickname. If you receive an error when you connect, see [Freenode’s Nickname Registration](https://freenode.net/kb/answer/registration) guide for instructions.

**Comment by gundalow** [comment]
I'll be there!

**Comment by larsks** [comment]
I'll be there.

**Comment by gregdek** [comment]
In.

**Comment by Shaps** [comment]
I'll be there

**Comment by robertdebock** [comment]
I'll be there

**Comment by chopraaa** [comment]
I'll be there

**Comment by apple4ever** [comment]
I'll be there

**Comment by mbhavya** [comment]
I'll be there.

**Comment by barlik** [comment]
I'll be there.

**Comment by felixfontein** [comment]
I'll be there (probably only in the evening though)

**Comment by lemoney** [comment]
I'll be there!

**Comment by alexsaezm** [comment]
And my axe!

**Comment by biohazd** [comment]
I’ll be there

**Comment by acozine** [comment]
I'll be there. Once the sun rises in my timezone and the morning caffeine hits, that is.

**Comment by maxamillion** [comment]
I'll be there. Probably around 1400 UTC because of my local TZ skew.

**Comment by winem** [comment]
I'll be there. But probably not before 1130 as I'm currently in Malaysia (UTC+8).

**Comment by gundalow** [comment]
Great to see so many people signed up, new and familiar faces.

I've updated the [description](https://github.com/ansible/community/issues/407#issue-383223086) to include some more details about what we are trying to achieve, as well as some background reading (`What do I need`) as some people have asked for background on how to review and test content.

**Comment by rajeevarakkal** [comment]
I'll be there

**Comment by richardcs** [comment]
Ill be there

**Comment by gundalow** [comment]
This is happening **right now**. Hope to see you in `#ansible-community` on Freenode. If you get a warning that you need to be registered, see https://freenode.net/kb/answer/registration

**Comment by kbreit** [comment]
> 
> 
> Given the great success of Novembers PR review, planning on having the next PR review on Wednesday 19th December.

Is there a topic or focus?

**Comment by gundalow** [comment]
@kbreit Good question. For the December Review, we will be focusing on PRs that are not part of a Working Group, as these are the PRs that often don't get reviewed.

The [Working Groups](https://docs.ansible.com/ansible/devel/community/communication.html) will perform their own backlog reviews, as they are the subject matter experts. This will start in early 2019.

**Comment by navalkp** [comment]
I will be there.

**Comment by resmo** [comment]
![](https://media.giphy.com/media/xUySTEh41261Ff63NS/giphy.gif)

**Comment by felixfontein** [comment]
I'll be there in the evening. This time earlier than last time :)

**Comment by rajeevarakkal** [comment]
I will be there.

**Comment by Shaps** [comment]
I'll be there

**Comment by maxamillion** [comment]
I'll be there starting at roughly 1400UTC

**Comment by winem** [comment]
I'll be there.

**Comment by hvariant** [comment]
Hopefully I'll be there.

**Comment by gundalow** [comment]
We will be starting in 50 minutes, looking forward to seeing you there :)

**Comment by gundalow** [comment]
Next Big PR review day is **Thursday 21st February 2019** from 1200UTC till late

---
Also, I know people ask "How can I contribute?", well we have a webinar to help you with that
[How to Make Your Mark: Ansible Community Contributions](https://www.ansible.com/resources/webinars-training/ansible-community-contributions) at Wed, Jan 30, 2019 9:30AM EST

Have you ever thought about contributing to the Ansible project? If you’re interested in learning about how you can help Ansible grow, tune in to this webinar to learn things like: 

 * What the Ansible Community is, and what they do 
 * Where contributions are needed the most 
 * The best ways to get your pull requests reviewed and merged 
 * … and much more!

**Comment by gundalow** [comment]
I'll be there from 1200UTC

**Comment by cabral404** [comment]
I'll be there

**Comment by maxamillion** [comment]
I'll be there.

**Comment by alongchamps** [comment]
I'll be there by 1300 UTC.

**Comment by hvtuananh** [comment]
I'll be there.

**Comment by gundalow** [comment]
How to see you all tomorrow, even if you have just a few mins to spare this all really helps.

**Comment by glitchcrab** [comment]
@gundalow: it's not tomorrow, it's thursday.. :stuck_out_tongue:

**Comment by gundalow** [comment]
@glitchcrab Thank you, you passed the test.

Thursday from 1200 UTC

**Comment by gundalow** [comment]
Starting now, if you have some time over the next ~6 hours, join us in  [#ansible-community](https://webchat.freenode.net/?channels=ansible-community)

**Comment by gundalow** [comment]
Given some discussion in `#ansible-devel` today, it was proposed that we should do PR review days **fortnightly** to help get the PR backlog under control.


Looking at the last three months for ansible/ansible:
* 908 PRs created
* 830 PRs merged (or closed without merging)
* Difference: 78/month

So if we can process another 80 PRs/month then we can keep the backlog stead (or better yet decreasing)*

.
* Alternate between different days of the week to give people a reasonable chance of attending
* Publicise the dates well in advance (ie just set the dates for the next n-months)
* Work through different GitHub PR queries each time, so give a reasonable chance of hiting different PRs
* Also advertise this as a dropin place for "can you help review my PR" 
* Flesh this into a blog post to help recruit/promote

To avoid too much email spam, how about people vote on this issues:
:heart: This sounds like a good idea, lets see how it works out
and/or
:+1: I maybe able to attend occasionally to help out.

or
:-1: I don't think this is a good idea

Join the discussion in `'#ansible-community` on Freenode


* Yes, yes, I know it doesn't really work like that, and things very from month to month, though the point is that ~10% increase in merge/close rate will let us breakeven

**Comment by tremble** [comment]
10% may sometimes feel like a lot, but it's also something that's achievable.  Does the core team have any *impressions* about the common mistakes they see that could be easily avoided?

Personally I've seen a number of PRs where someone from core has taken a look, asked for a small change or a test, and then things have ground to a halt because it's not been re-visited.

**Comment by gundalow** [comment]
Next PR days will take place in `#ansible-community' on Freenode:

* **Tuesday 3rd September** from 1000UTC till late
* **Thursday 19th September** from 1000UTC till late

Please :+1: This issue if you can attend one of the above, just so I can get a sense of turnout. As always even just 

I agree with @tremble's comment above that 10% may feed like a lot, though it is possible. If we close/merge an extra 100 PRs a month (so 50/fortnight) then we break even. I think this is possible, especially since there is some low hanging fruit since we've not done a PR review day since the beginning of the year.

**Comment by gundalow** [comment]
Starting in 40 minutes, see you in `#ansible-community` on Freenode IRC

**Comment by gundalow** [comment]
Starting now in `#ansible-community` on Freenode IRC

**Comment by gundalow** [comment]
Next PR review day is **Thursday 14th November from 1400UTC** til late
[What's this in my Timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+PR+Day&iso=20191114T14)

See you in `#ansible-community` on Freenode IRC

**Comment by gundalow** [comment]
Starting in just under 3 hours, see you in `#ansible-community` on Freenode.

**Comment by gundalow** [comment]
A few updates to share:
* As part of the European Contributors Summit we will have two hackathon days. These can be viewed as "Office Hours" if you'd like to get started with Ansible Collections (or anything else related to Ansible on March 30 & 31st
* Regular PR days will resume once the various [Collection repos](https://github.com/ansible-collections/) are up and running, see [docs](https://github.com/ansible-collections/overview/blob/master/README.rst)

**Comment by gundalow** [comment]
Hi all.
The next PR day will be **Wednesday 17th June 2020 from 1400UTC**

### When
Wednesday 17th June 2020 from 1400UTC

[What's this in my Timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+PR+Day&iso=20200617T14)

### Where
 `#ansible-community` on Freenode IRC

### What

This will be our first session focusing on the new Community Collections: 
  * [community.general](https://github.com/ansible-collections/community.general/pulls)
  * [community.network](https://github.com/ansible-collections/community.network/pulls)
  * [community.crypto](https://github.com/ansible-collections/community.crypto/pulls)

**Comment by gundalow** [comment]
Starting now in `#ansible-community`

**Comment by gundalow** [comment]
Next two PR days
* Tuesday 1st December 2020 1500UTC [In my timezone, and calendar invitation](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible%20PR%20Day+2020&iso=20201201T15)
* Thursday 17th December 2020 [In my timezone, and calendar invitation](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible%20PR%20Day+2020&iso=20201217T15)

Please give a :+1: on this issue if you can attend either

**Comment by gundalow** [comment]
Reminder that this is taking place tomorrow, Tuesday 1st December 2020 1500UTC [In my timezone, and calendar invitation](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible%20PR%20Day+2020&iso=20201201T15)

**Comment by gundalow** [comment]
About to start in `#ansible-community` on Freenode IRC

**Comment by prantikb** [comment]
I'll be there

**Comment by prantikb** [comment]
I'll be there

**Comment by ggold7046** [comment]
@maxamillion , could you help me please ?

**Comment by Andersson007** [comment]
@ggold7046 hello, apologies for the late reply (long end-of-year PTOs) and welcome to the project!

Please:
- Join us in a real time chat on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix) at least in [#social:ansible.com](https://matrix.to/#/#social:ansible.com) (say "Hello" there) and [#community:ansible.com](https://matrix.to/#/#community:ansible.com). You can also ask folks there for easyfixes. See the [Communication guide](https://docs.ansible.com/ansible/devel/community/communication.html) for details.
- Take a look at the [Contributor path](https://docs.ansible.com/ansible/devel/community/contributor_path.html).
- When you find the first issue to fix, if it's about code, take a look at the [Quick-start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html).
- Any questions? Feel free to ask (better on Matrix).

Thanks for your interest in contributing to ansible!

**Comment by maxamillion** [comment]
@ggold7046 what @Andersson007 said! (Double apologies for not replying sooner ... I'm still not caught up on email because I took a whole month off for the winter holidays :smile:)

**Comment by ggold7046** [comment]
Hello Adam,

I'm looking for document contribution. I don't have any preference though.
If you could guide me that would be great.

**Comment by Andersson007** [comment]
@ggold7046 you could take a look at easifixes:
- across multiple [collections](https://github.com/search?q=user%3Aansible-collections+label%3Aeasyfix%2C%22good+first+issue%22+state%3Aopen&type=Issues)
- for all [other](https://github.com/search?q=user%3Aansible+user%3Aansible-community+label%3Aeasyfix%2C%22good+first+issue%22+state%3Aopen&type=Issues) Ansible projects
