### ISSUE TITLE
 Remote Management: Task list

### ISSUE THREAD

**Issue by gundalow** [ansible/community#409]
## Remote Management Working Group

Help improve the [Remote Management modules](https://docs.ansible.com/ansible/devel/modules/list_of_remote_management_modules.html)

## How to help

* Firstly, click the `Subscribe` button on the right hand side so you will see update.
* Ansible used GitHub labels to categorize Issues and PRs, therefore everything remote_management related has [/label/remote_management](https://github.com/ansible/ansible/labels/remote_management)
* Reviewing [remote_management PRs](https://github.com/ansible/ansible/pulls?q=is%3Aopen+label%3Aremote_management+is%3Apr) is very useful

  * As a lot of the remote_management modules require hardware, which isn't something we can add into Ansible CI, manual human testing is very important
  * Actually using and testing the PRs is one of the best types of feedback we can get. Add a comment saying what you tested and how it worked: [example of good testing feedback](https://github.com/ansible/ansible/pull/46151#issuecomment-435026764)

## What is expected of me

Help can be anything:

* from spending a few minutes testing an existing PR
* Fixing bugs
* [Improving Documentation](https://docs.ansible.com/ansible/latest/community/documentation_contributions.html)

The only commitment in a community project is what one commits to themselves. When working with volunteers we don't think we can ask for a commitment from anyone. People come and go. But as a community we can try to communicate better, provide easier and more dependable processes, have regular introspective meetings, so that if someone commits to something the community and processes are there to reach those goals. That is the aim of this working group :)

## How to speak to us

* Feel free to add comments on this issue
* Join us in `#ansible-devel` on Freenode - [Ansible IRC channels](https://docs.ansible.com/ansible/latest/community/communication.html)

**Comment by gundalow** [comment]
* https://github.com/ansible/ansible/pull/46675 - DellEMC Install Firmware Modules
* https://github.com/ansible/ansible/pull/46767 - lxca_nodes for Lenovo XClarity Administrator

**Comment by gundalow** [comment]
* https://github.com/ansible/ansible/pull/49075 New `spacewalk_swchannel_facts` (Other Spacewalk modules coming soon)

**Comment by navalkp** [comment]
Can we include remote_management PR in Big PR Review on 21st Feb, 2019

**Comment by gundalow** [comment]
Hi, Do you want `remove_management` to be it's own collection, or are you happy for it to be in `community.general`?
