### ISSUE TITLE
Meetings.MD should probably be information in docs.ansible.com

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#41]
Nobody knows that meetings.md exists because there's no indicator that it exists anywhere else. 

Should probably put something here http://docs.ansible.com/ansible/community.html#other-topics (or just have the entire meeting page there, and then link to the meetinglogs.md from that page)

**Comment by gregdek** [comment]
Yeah, I think we should probably point from that page to the ansible/community repo, since it will be much more dynamic and up-to-date. But yes, we should totally do that.

**Comment by bob-smith** [comment]
See also https://github.com/ansible/community/pull/49 which tidies up MEETINGS.md

**Comment by gregdek** [comment]
Closing here and opening as PR in ansible/ansible: https://github.com/ansible/ansible/pull/15124
