### ISSUE TITLE
Core team ics file only includes Tuesday meeting

### ISSUE THREAD

**Issue by larsks** [ansible/community#412]
The ICS file for the core-team meeting (https://raw.githubusercontent.com/ansible/community/master/meetings/ical/core-team.ics) includes only the Tuesday meeting.  It should include both Tuesday and Thursday, or there should be a separate link for the Thursday meeting.

**Comment by felixfontein** [comment]
But it *does* contain both meetings. The upper entry is the Tuesday meeting, the lower the Thursday meeting.

**Comment by dagwieers** [comment]
It is generated from this YAML file: https://github.com/ansible/community/blob/master/meetings/core-team.yaml

**Comment by larsks** [comment]
Hah, yeah, that's what I get for doing work before coffee.  Neeeeeever mind.
