### ISSUE TITLE
Public Ansible Project Meeting Agenda - December 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#415]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by bcoca** [comment]
updates to async https://github.com/ansible/ansible/pull/28561

**Comment by bcoca** [comment]
allow include_role's tasks_from: to deal with more paths than just `tasks/` https://github.com/ansible/ansible/pull/20078

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/44428 prioritize 'auto' in inventory plugins

**Comment by pilou-** [comment]
create `ansible/ansible-baseline` in order to ease contributions ([see](https://github.com/ansible/ansible/issues/45839#issuecomment-430243355)).

**Comment by ericzolf** [comment]
Is there any interest in merging something like https://github.com/ansible/ansible/pull/46561 (for "Makefile"-alike Playbooks)? It's not the usual Ansible use case but I find it handy and I have a few ideas how to make it better, but no point if it's of no interest to the community.

**Comment by bcoca** [comment]
Meeting ended Thu Dec  6 15:08:21 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-06/ansible_core_irc_meeting.2018-12-06-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-12-06/ansible_core_irc_meeting.2018-12-06-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-06/ansible_core_irc_meeting.2018-12-06-15.02.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Dec 11 19:35:03 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-11/core_public_irc_meeting.2018-12-11-19.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-12-11/core_public_irc_meeting.2018-12-11-19.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-11/core_public_irc_meeting.2018-12-11-19.04.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Dec 13 15:12:58 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-13/core_public_irc_meeting.2018-12-13-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-12-13/core_public_irc_meeting.2018-12-13-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-13/core_public_irc_meeting.2018-12-13-15.02.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Dec 18 19:11:12 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-18/ansible_core_irc_meeting.2018-12-18-19.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-12-18/ansible_core_irc_meeting.2018-12-18-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-18/ansible_core_irc_meeting.2018-12-18-19.06.log.html

**Comment by Akasurde** [comment]
cc @lucastheisen wants to discuss - https://github.com/ansible/ansible/issues/49992

**Comment by bcoca** [comment]
Meeting ended Thu Dec 20 16:04:18 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-20/ansible_core_irc_meeting.2018-12-20-15.07.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-12-20/ansible_core_irc_meeting.2018-12-20-15.07.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-12-20/ansible_core_irc_meeting.2018-12-20-15.07.log.html

**Comment by bcoca** [comment]
Rest of December meetings canceled due to lack of attendance (it is the season). Will resume in January.
