### ISSUE TITLE
Public Ansible Project Meeting Agenda - January 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#418]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by bcoca** [comment]
cc @lucastheisen wants to discuss - ansible/ansible#49992

**Comment by dagwieers** [comment]
I want to discuss the following:
- https://github.com/ansible/ansible/pull/28662 -- New 'required_by' argument_spec option
- https://github.com/ansible/ansible/pull/35462 -- Add option tls_insecure
- https://github.com/ansible/ansible/pull/49719 -- Make (http) method a free text field (uri/win_uri)
- https://github.com/ansible/ansible/pull/50035 -- New type 'mode' for Unix permissions/umask (migrate to strings-only)

**Comment by jamescassell** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/50327 -- regex_escape - added re_type option to enable escaping POSIX BRE chars

**Comment by bcoca** [comment]
Meeting ended Thu Jan  3 15:44:10 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-03/ansible_core_public_irc_meeting.2019-01-03-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-03/ansible_core_public_irc_meeting.2019-01-03-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-03/ansible_core_public_irc_meeting.2019-01-03-15.00.log.html

**Comment by FedericoOlivieri** [comment]
Created new PR with test for ios_ntp module PR #50642

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/50564 might need revert, has far reaching consequences for existing playbooks

**Comment by bcoca** [comment]
Meeting ended Tue Jan  8 19:49:48 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-08/core_public_irc_meeting.2019-01-08-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-08/core_public_irc_meeting.2019-01-08-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-08/core_public_irc_meeting.2019-01-08-19.00.log.html

**Comment by samdoran** [comment]
https://github.com/ansible/ansible/issues/50503

**Comment by Alb0t** [comment]
https://github.com/ansible/ansible/pull/49138 aerospike migrations module to allow choreographing the cluster during deployments/upgrades.

**Comment by bcoca** [comment]
Meeting ended Tue Jan 15 19:56:02 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-15/ansible_core_public_irc_meeting.2019-01-15-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-15/ansible_core_public_irc_meeting.2019-01-15-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-15/ansible_core_public_irc_meeting.2019-01-15-19.01.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Jan 17 15:11:32 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-17/ansible_core_irc_meeting.2019-01-17-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-17/ansible_core_irc_meeting.2019-01-17-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-17/ansible_core_irc_meeting.2019-01-17-15.01.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/51030

**Comment by FedericoOlivieri** [comment]
https://github.com/ansible/ansible/pull/50705

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/35382

**Comment by lwm** [comment]
https://github.com/ansible/proposals/issues/39 and how to help push forward  / split out https://github.com/ansible/ansible/pull/44983.

**Comment by FedericoOlivieri** [comment]
https://github.com/ansible/ansible/pull/50705. Would be possible to merge?

**Comment by bcoca** [comment]
Meeting ended Tue Jan 22 19:58:03 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-22/ansible_core_irc_meeting.2019-01-22-19.11.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-22/ansible_core_irc_meeting.2019-01-22-19.11.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-22/ansible_core_irc_meeting.2019-01-22-19.11.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Jan 24 16:02:37 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-24/core_public_irc_meeting.2019-01-24-15.14.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-24/core_public_irc_meeting.2019-01-24-15.14.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-24/core_public_irc_meeting.2019-01-24-15.14.log.html

**Comment by bcoca** [comment]
#15484

**Comment by bcoca** [comment]
Meeting ended Tue Jan 29 19:55:31 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-29/ansible_core_public_irc_meeting.2019-01-29-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-01-29/ansible_core_public_irc_meeting.2019-01-29-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-01-29/ansible_core_public_irc_meeting.2019-01-29-19.01.log.html
