### ISSUE TITLE
Schedule a ansible phoenix meetup

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#42]
I'll do this. I swear

**Comment by robynbergeron** [comment]
Looks like this will be the week of 6/20. Still nailing down with helpful friend at red hat (will be joint with the phx RHUG) who is coordinating with the meetup host on a date. And I am pinging local folks who might present.

**Comment by robynbergeron** [comment]
So: We had this scheduled for the 22nd, and it is now unscheduled due to a conflict with the facility where the meetup was giong to be. And having to juggle around some scheduling stuff, still sorting out a new date with the RHUG folks.

**Comment by robynbergeron** [comment]
Robyn is repinging the red hat humans. Also mental note to ping chris @ citrix about their nice meetupspace in downtown tempe.

**Comment by gregdek** [comment]
Scheduled and ready to go!
