### ISSUE TITLE
VMware Working Group meeting agenda - Jan'19 - Mar'20

### ISSUE THREAD

**Issue by Akasurde** [ansible/community#423]
The VMware Working Group focuses on delivering modules and features to Ansible to support working with VMware. The group meets every week on Mondays at 16:00 UTC (see [calendar](https://calendar.google.com/calendar/embed?src=ansible.com_pafenslko0e2bqjgujp8f7s0do%40group.calendar.google.com&ctx=UTC)) 

More information related to the VMware Working Group is available [here](https://github.com/ansible/community/tree/master/group-vmware)

**Feel free to add your questions to this ticket to be discussed during the upcoming meeting.**

*(Migrated from the previous agenda at #233, actionable items are available at [VMware: action plan](https://github.com/ansible/community/wiki/VMware:-action-list))*

**Comment by Akasurde** [comment]
* Meeting ended Mon Jan 14 17:06:35 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-01-14/ansible_vmware_working_group_meeting.2019-01-14-16.04.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-01-14/ansible_vmware_working_group_meeting.2019-01-14-16.04.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-01-14/ansible_vmware_working_group_meeting.2019-01-14-16.04.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Jan 21 16:51:26 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-01-21/ansible_vmware_working_group_meeting.2019-01-21-16.03.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-01-21/ansible_vmware_working_group_meeting.2019-01-21-16.03.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-01-21/ansible_vmware_working_group_meeting.2019-01-21-16.03.log.html

**Comment by gundalow** [comment]
Could we please help https://github.com/ansible/ansible/pull/44399 get merged, the PR author @naphta is active

**Comment by dagwieers** [comment]
Maybe we could discuss reviving the VMware pinboard, and using it for review requests to a larger community ? As wider review and testing is usually the showstopper.

**Comment by Akasurde** [comment]
* Meeting ended Mon Feb  4 16:45:36 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-04/ansible_vmware_working_group_meeting.2019-02-04-16.15.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-02-04/ansible_vmware_working_group_meeting.2019-02-04-16.15.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-04/ansible_vmware_working_group_meeting.2019-02-04-16.15.log.html

**No quorum**

**Comment by Akasurde** [comment]
* Meeting ended Mon Feb 11 17:39:51 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-11/ansible_vmware_working_group_meeting.2019-02-11-16.05.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-02-11/ansible_vmware_working_group_meeting.2019-02-11-16.05.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-11/ansible_vmware_working_group_meeting.2019-02-11-16.05.log.html

**Comment by alongchamps** [comment]
I'd like to discuss merging #52125 at the next meeting.

**Comment by adarobin** [comment]
I'd like to discuss https://github.com/ansible/ansible/pull/49800 at the next meeting.  I've never written any tests for Ansible so I could use a little direction.

**Comment by Akasurde** [comment]
* Meeting ended Mon Feb 18 17:05:37 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-18/ansible_vmware_working_group_meeting.2019-02-18-16.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-02-18/ansible_vmware_working_group_meeting.2019-02-18-16.02.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-18/ansible_vmware_working_group_meeting.2019-02-18-16.02.log.html

**Comment by moshloop** [comment]
I would like to discuss the following at the next meeting: 
https://github.com/ansible/ansible/pull/47936
https://github.com/ansible/ansible/pull/47930
https://github.com/ansible/ansible/pull/44885
https://github.com/ansible/ansible/pull/44832

**Comment by Akasurde** [comment]
* Meeting ended Mon Feb 25 17:44:48 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-25/ansible_vmware_working_group_meeting.2019-02-25-16.02.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-02-25/ansible_vmware_working_group_meeting.2019-02-25-16.02.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-02-25/ansible_vmware_working_group_meeting.2019-02-25-16.02.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Mar  4 17:08:31 2019 UTC
 *  Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-04/ansible_vmware_working_group_meeting.2019-03-04-16.01.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-03-04/ansible_vmware_working_group_meeting.2019-03-04-16.01.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-04/ansible_vmware_working_group_meeting.2019-03-04-16.01.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Mar 11 17:07:19 2019 UTC
 *  Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-11/ansible_vmware_working_group_meeting.2019-03-11-16.05.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-03-11/ansible_vmware_working_group_meeting.2019-03-11-16.05.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-11/ansible_vmware_working_group_meeting.2019-03-11-16.05.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Mar 25 16:58:04 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-25/ansible_vmware_working_group_meeting.2019-03-25-16.02.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-03-25/ansible_vmware_working_group_meeting.2019-03-25-16.02.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-03-25/ansible_vmware_working_group_meeting.2019-03-25-16.02.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Apr  8 16:39:49 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-04-08/ansible_vmware_working_group_meeting.2019-04-08-16.02.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-04-08/ansible_vmware_working_group_meeting.2019-04-08-16.02.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-04-08/ansible_vmware_working_group_meeting.2019-04-08-16.02.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Apr 15 17:05:05 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-04-15/ansible_vmware_working_group_meeting.2019-04-15-16.05.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-04-15/ansible_vmware_working_group_meeting.2019-04-15-16.05.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-04-15/ansible_vmware_working_group_meeting.2019-04-15-16.05.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon May  6 16:59:46 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-05-06/ansible_vmware_working_group_meeting.2019-05-06-15.55.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-05-06/ansible_vmware_working_group_meeting.2019-05-06-15.55.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-05-06/ansible_vmware_working_group_meeting.2019-05-06-15.55.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon May 13 17:02:15 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-05-13/ansible_vmware_working_group_meeting.2019-05-13-16.04.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-05-13/ansible_vmware_working_group_meeting.2019-05-13-16.04.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-05-13/ansible_vmware_working_group_meeting.2019-05-13-16.04.log.html

**Comment by alongchamps** [comment]
I'd like to review https://github.com/ansible/ansible/pull/56733 and get it merged if possible at the next meeting.

**Comment by Akasurde** [comment]
* Meeting ended Mon Jun  3 16:44:44 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-03/ansible_vmware_working_group_meeting.2019-06-03-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-06-03/ansible_vmware_working_group_meeting.2019-06-03-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-03/ansible_vmware_working_group_meeting.2019-06-03-16.00.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Jun 10 16:35:11 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-10/ansible_vmware_working_group_meeting.2019-06-10-16.00.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-06-10/ansible_vmware_working_group_meeting.2019-06-10-16.00.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-10/ansible_vmware_working_group_meeting.2019-06-10-16.00.log.html

**Comment by n3pjk** [comment]
-

**Comment by n3pjk** [comment]
- Should a REST API sub group be formed?
- Establish a design reference for new REST API modules. Location of Wiki

**Comment by Akasurde** [comment]
> * Should a REST API sub group be formed?

Please add yourself here, once this PR is merged.
https://github.com/ansible/ansible/pull/57832/files#diff-5baefb0f9c8093094911cec657444e70R1181

> * Establish a design reference for new REST API modules. Location of Wiki

Wiki location = https://github.com/ansible/community/wiki/VMware%3A-HTTPAPI-connection-plugin

**Comment by Akasurde** [comment]
* Meeting ended Mon Jun 17 17:07:46 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-17/ansible_vmware_working_group_meeting.2019-06-17-16.04.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-17/ansible_vmware_working_group_meeting.2019-06-17-16.04.txt
* Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-17/ansible_vmware_working_group_meeting.2019-06-17-16.04.log.html

**Comment by alongchamps** [comment]
I had a discussion with twk on IRC today about storage DRS for placement of machines, e.g. in vmware_vmotion. There is some SDRS code in vmware_guest.py, for placement, but nothing I could see in module_utils/vmware.py. So I wonder if get_recommended_datastores should be moved in there?

**Comment by Akasurde** [comment]
No discussion -

* Meeting ended Mon Jun 24 16:51:20 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-24/ansible_vmware_working_group_meeting.2019-06-24-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-06-24/ansible_vmware_working_group_meeting.2019-06-24-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-06-24/ansible_vmware_working_group_meeting.2019-06-24-16.00.log.html

**Comment by agowa338** [comment]
I'd like to add some PRs of mine to the agenda:
- vmware dynamic inventory naming collision #55137
- VMware: Folder support on dynamic inventory plugin - alternative implementation #55576
- VMware Tools Connector does not support pipelining #57237
- vmware_tools handle connection issues #57661

**Comment by Akasurde** [comment]
* Meeting ended Mon Jul  1 17:14:03 2019 UTC
 * Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-07-01/ansible_vmware_working_group_meeting.2019-07-01-16.20.html
 * Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-07-01/ansible_vmware_working_group_meeting.2019-07-01-16.20.txt
 * Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-07-01/ansible_vmware_working_group_meeting.2019-07-01-16.20.log.html

**Comment by Akasurde** [comment]
**No Discussion**

* Meeting ended Mon Jul 15 16:59:46 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-07-15/ansible_vmware_working_group_meeting.2019-07-15-16.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-07-15/ansible_vmware_working_group_meeting.2019-07-15-16.02.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-07-15/ansible_vmware_working_group_meeting.2019-07-15-16.02.log.html

**Comment by agowa338** [comment]
Hi, I'd like to request a review of these PRs (not necessarily within the meeting):

- vmware_tools handle connection issues #57661
- vmware dynamic inventory naming collision #55137
- VMware: Folder support on dynamic inventory plugin - alternative implementation #55576

**Comment by Akasurde** [comment]
* Meeting ended Mon Aug 12 17:10:11 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-08-12/ansible_vmware_working_group_meeting.2019-08-12-16.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-08-12/ansible_vmware_working_group_meeting.2019-08-12-16.02.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-08-12/ansible_vmware_working_group_meeting.2019-08-12-16.02.log.html

**Comment by Akasurde** [comment]
* Meeting ended Mon Sep  9 16:19:51 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-09-09/ansible_vmware_working_group_meeting.2019-09-09-16.05.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-09-09/ansible_vmware_working_group_meeting.2019-09-09-16.05.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-09-09/ansible_vmware_working_group_meeting.2019-09-09-16.05.log.html

**Comment by gundalow** [comment]
# Ansible Fest: Contributors Summit 

Just a reminder that Contributors Summit is happening on Monday 23rd September and will be streamed online and you can make your voice heard via IRC.

[When is this in my timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+Contributor+Summit&iso=20190923T1250&p1=1440&ah=8&am=10)

To see what we plan to discuss see the [top level Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
From there you can see the various breakout sessions.
A lot of the morning session will be around Collections

## Call to Action!

Even if you can only make a small part of the day, or maybe can't attend at all, there are still ways take part:

* Add your thoughts, ideas and questions to the [Breakout Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
* Vote on what you'd like to be discussed (ie add `+yourname`)


## Background Reading

A large part of Monday Morning will be around "Ansible Collections", to get up to speed on what the current thoughts are, the following links will help you:

[Blog: Thoughts on restructuring the Ansible Project](https://www.ansible.com/blog/thoughts-on-restructuring-the-ansible-project)
[Blog: The future of Ansible Content Delivery](https://www.ansible.com/blog/the-future-of-ansible-content-delivery)
[Webinar: Collections and the future of how Ansible Content is handled](https://www.ansible.com/resources/webinars-training/collections-future-of-how-ansible-content-is-handled)
[Docs: Collections Tech Preview Guide](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html)

# NEW: Community Central (drop in space)

At AnsibleFest 2019 we are excited to launch Community Central, a gathering place and information hub for Ansible contributors. This takes place 10-3pm each day at AnsibeFest.

Community Central builds on the success of Ask an Expert, with a focus on contributors rather than users.

Community Central will host informal talks and coding sessions on the main conference days. Members of the Ansible Engineering team and the various Ansible Working Groups will be there.

It's a great place to discover how you can contribute to Ansible, meet other contributors, or polish your latest Ansible pull request. If you already contribute to Ansible, or would like to find out how to get involved, this is the place for you!

Feel free to come along and say hello, or even bring your laptop and we can help you through any part of the contributor or development process. Keep an eye on the Agenda Builder to see what's happening.

# Questions?

Any questions, feel free to ping me

Email: gundalow@redhat.com
Freenode: `#ansible-community`
Matrix: [ansible-community](https://matrix.to/#/#freenode_#ansible-community:matrix.org)
GitHub: @gundalow 
Twitter: @the_gundalow

**Comment by Akasurde** [comment]
* Meeting ended Mon Sep 16 17:09:40 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-09-16/ansible_vmware_working_group_meeting.2019-09-16-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-09-16/ansible_vmware_working_group_meeting.2019-09-16-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-09-16/ansible_vmware_working_group_meeting.2019-09-16-16.00.log.html

**Comment by goneri** [comment]
2019-09-30: cancel, no attendees

**Comment by samdoran** [comment]
- [ ] https://github.com/ansible/ansible/pull/28552:  vmware: Only add configured network interfaces to facts

**Comment by Akasurde** [comment]
* Meeting ended Mon Oct  7 16:39:07 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-10-07/ansible_vmware_working_group_meeting.2019-10-07-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-10-07/ansible_vmware_working_group_meeting.2019-10-07-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-10-07/ansible_vmware_working_group_meeting.2019-10-07-16.00.log.html

**Comment by Akasurde** [comment]
14 Oct 2019 - No attendees

**Comment by Akasurde** [comment]
* Meeting ended Mon Oct 21 17:04:01 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-10-21/ansible_vmware_working_group.2019-10-21-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-10-21/ansible_vmware_working_group.2019-10-21-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-10-21/ansible_vmware_working_group.2019-10-21-16.00.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Nov  4 16:20:13 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-04/vmware_weekly.2019-11-04-16.06.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-11-04/vmware_weekly.2019-11-04-16.06.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-04/vmware_weekly.2019-11-04-16.06.log.html

**Comment by jtyr** [comment]
I would like to discuss these PRs on Monday Nov 18:

- [ ] https://github.com/ansible/ansible/pull/63741
- [ ] https://github.com/ansible/ansible/pull/63740
- [ ] https://github.com/ansible/ansible/pull/62217
- [ ] https://github.com/ansible/ansible/pull/43435

**Comment by D3DeFi** [comment]
Hey, I would really like to attend today's meeting, but the scheduled meeting time is really not in my favor right now. Can you guys please address this issue (below)? 
- [ ] ansible/ansible#64291

Basically, 2.9 introduced a big game changer for some of us that are depending on Advanced VM Options without communicating it in porting guide or some deprecation warning first. As of right now, _vmware_guest_ module tries to set Custom Attributes for the VM instead, which I believe is wrong.

**Comment by Akasurde** [comment]
* Meeting ended Mon Nov 18 16:45:29 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-18/ansible_vmware_working_group.2019-11-18-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-11-18/ansible_vmware_working_group.2019-11-18-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-18/ansible_vmware_working_group.2019-11-18-16.00.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Nov 25 16:46:39 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-25/ansible_vmware_working_group.2019-11-25-16.04.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-11-25/ansible_vmware_working_group.2019-11-25-16.04.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-11-25/ansible_vmware_working_group.2019-11-25-16.04.log.html

**Comment by jtyr** [comment]
I would like to discuss:

- [ ] ansible/ansible#63741
- [ ] ansible/ansible#63740
- [ ] ansible/ansible#43435
- [ ] ansible/ansible#65429

**Comment by Akasurde** [comment]
* Meeting ended Mon Dec  2 17:26:49 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-02/ansible_vmware_working_group_meeting.2019-12-02-16.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-12-02/ansible_vmware_working_group_meeting.2019-12-02-16.02.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-02/ansible_vmware_working_group_meeting.2019-12-02-16.02.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Dec  9 16:49:05 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-09/vmware_working_group_meeting.2019-12-09-15.59.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-12-09/vmware_working_group_meeting.2019-12-09-15.59.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-09/vmware_working_group_meeting.2019-12-09-15.59.log.html

**Comment by Akasurde** [comment]
- https://github.com/ansible/ansible/pull/65684

**Comment by Akasurde** [comment]
* Meeting ended Mon Dec 16 16:56:33 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-16/ansible_vmware_working_group.2019-12-16-16.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2019-12-16/ansible_vmware_working_group.2019-12-16-16.02.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2019-12-16/ansible_vmware_working_group.2019-12-16-16.02.log.html

**Comment by Akasurde** [comment]
PR to discuss in next meeting - 

- [ ] https://github.com/ansible/ansible/pull/49534
- [ ] https://github.com/ansible/ansible/pull/64087
- [ ] https://github.com/ansible/ansible/pull/47848
- [ ] https://github.com/ansible/ansible/pull/49800

**Comment by goneri** [comment]
2020/01/05: No attends, Meeting cancelled.

**Comment by Akasurde** [comment]
* Meeting ended Mon Jan 13 16:56:53 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-01-13/ansible_vmware_working_group_meeting.2020-01-13-16.08.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-01-13/ansible_vmware_working_group_meeting.2020-01-13-16.08.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-01-13/ansible_vmware_working_group_meeting.2020-01-13-16.08.log.html

**Comment by Akasurde** [comment]
no meeting - 20 Jan 2020

**Comment by Akasurde** [comment]
no meeting - 17 Feb 2020

**Comment by goneri** [comment]
2020-02-24: cancelled, no agenda

**Comment by gundalow** [comment]
## Ansible Contributors Summit EUROPE

## What

Ansible Contributor Summit is a one day event especially for community contributors to meet with each other, as well as Ansible development teams (Core, AWX/Tower, Galaxy) in person, to discuss important issues in the community and help shape the future of Ansible. For those unable to make it to Gothenburg, we welcome you to join virtually for part/all of the day. Online participation and streaming details to follow closer to the summit.

## When
* Contributors Summit: Sunday, 29th March
* Ansible Hackathon: Monday 30th March
* [FOSS-North](https://foss-north.se/2020/): 30 & 31st March

## How

* If you plan to attend **in person**, please register on [Eventbrite](https://www.eventbrite.com/e/ansible-contributor-summit-eu-registration-92039844653)
* If you plan to attend the hackathon or any of FOSS-North please [register](https://foss-north.se/2020/)
* If you plan to attend virtually details will be added to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020) the day before

## Agenda

* Please add suggested topics to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020)
For more info please see the [announcement](https://groups.google.com/forum/#!topic/ansible-devel/o6xnI9g8QqM).

**Comment by Akasurde** [comment]
* Meeting ended Mon Mar  2 16:34:28 2020 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-02/ansible_vmware_working_group.2020-03-02-16.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-03-02/ansible_vmware_working_group.2020-03-02-16.00.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-02/ansible_vmware_working_group.2020-03-02-16.00.log.html

no meeting

**Comment by Akasurde** [comment]
No meeting

* Meeting ended Mon Mar  9 16:07:41 2020 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-09/ansible_vmware_working_group.2020-03-09-16.01.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-03-09/ansible_vmware_working_group.2020-03-09-16.01.txt
* Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-09/ansible_vmware_working_group.2020-03-09-16.01.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Mar 23 17:00:18 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-23/ansible_vmware_working_group.2020-03-23-16.01.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-03-23/ansible_vmware_working_group.2020-03-23-16.01.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-23/ansible_vmware_working_group.2020-03-23-16.01.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Mar 30 16:51:04 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-30/ansible_vmware_working_group.2020-03-30-16.00.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-03-30/ansible_vmware_working_group.2020-03-30-16.00.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-03-30/ansible_vmware_working_group.2020-03-30-16.00.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Apr 20 17:00:20 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-04-20/ansible_vmware_working_group.2020-04-20-16.04.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-04-20/ansible_vmware_working_group.2020-04-20-16.04.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-04-20/ansible_vmware_working_group.2020-04-20-16.04.log.html

**Comment by goneri** [comment]
- Meeting ended Mon Apr 27 16:25:20 2020 UTC.
No agenda, meeting cancelled.

**Comment by goneri** [comment]
- Meeting ended Mon May  4 16:30:07 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
- Minutes: https://meetbot.fedoraproject.org/ansible-vmware/2020-05-04/ansible_vmware_working_group.2020-05-04-16.01.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-vmware/2020-05-04/ansible_vmware_working_group.2020-05-04-16.01.txt
- Log: https://meetbot.fedoraproject.org/ansible-vmware/2020-05-04/ansible_vmware_working_group.2020-05-04-16.01.log.html

**Comment by n3pjk** [comment]
I would like to discuss vmware_content_deploy_template and _ovf_template. I am preparing a PR to fix over a half dozen issues.

**Comment by Akasurde** [comment]
@n3pjk Please create a PR and will discuss things over the PR itself. Thanks for taking the initiative.

**Comment by n3pjk** [comment]
@Akasurde according to the Wiki, I'll need Trello access.

**Comment by Akasurde** [comment]
> @Akasurde according to the Wiki, I'll need Trello access.

We moved from Trello to GitHub Project. I will create an issue and ping you there.

**Comment by Akasurde** [comment]
@n3pjk Please use https://github.com/ansible-collections/community.vmware/issues/738 as a tracking bug and I added this in the project.

**Comment by aaronk1** [comment]
@Akasurde @goneri 
Has there not been a VMware Working Group meeting since May 2020?

**Comment by aaronk1** [comment]
@Akasurde @goneri Was the last meeting in November 2020?
https://meetbot.fedoraproject.org/sresults/?type=channel&group_id=ansible-vmware

**Comment by goneri** [comment]
Hi @aaronk1, we've skipped several meetings because there were no attendee. This being said, you can ping us anytime on #ansible-vmware if you've got a question.
