### ISSUE TITLE
Ansible Molecule Meeting - When

### ISSUE THREAD

**Issue by gundalow** [ansible/community#426]
Looking at setting up a weekly Molecule meeting in `#ansible-molecule`, when would work for you?

Day/UTC
weekly?

**Comment by lwm** [comment]
Weekly could be too much for a band of volunteers? Or how does it normally go with other groups?

I could do a bi-weekly wednesday. 7PM UTC would suit me. 1 hour meeting?

Open to suggestions, of course!

**Comment by ragingpastry** [comment]
I could be pretty flexible. 7pm UTC would work for me as well.

**Comment by gundalow** [comment]
For the other Working Groups we do weekly see the [schedule](https://github.com/ansible/community/tree/master/meetings#schedule), the general thought is having a short meeting is better than people missing a meeting that only occurs twice a month.

That said, this is *your* meeting, so I'm happy to help you with whatever you think is best.
Everything will be tracked via GitHub (and possinly [Etherpad](https://etherpad.openstack.org/p/ansible-molecule) so if meeting times don't work out everything will be recorded (as well as IRC Meeting Logs).

**Comment by gundalow** [comment]
@kireledan @wilmardo @robertdebock @MarkusTeufelberger @dj-wasabi @elliotweiser @themr0c @rgarrigue @saez0pub @dhoppeIT @msheiny @rosstimson @analbeard @fabianvf @skhoroshavin @pilou- @lwilke @shortmann @singuliere @AlexisLessard @loomsen @danihodovic @duck-rh  @mickelmayers @torrentalle @uSpike @f-roscher @Lowess @jonashackt Hi, apologies for the `@mention`, though we are wanting to form a Working Group for Molecule, which is now part of the Ansible by Red Hat family. I've pinged you are you've been a recent contributor to Molecule.

We'd like to form a regular meeting to help drive Molecule's direction and I though you might be interested in that, if so please ad a comment to this issue stating what times would work for you.

If you aren't interested, please hit `unsubscribe` on the right hand of this issue.

**Comment by fabianvf** [comment]
I'm also very flexible, 7PM UTC works fine for me.

**Comment by AlexisLessard** [comment]
Can't say I'd be there everytime, but I think it would be an interesting experience! I'm not sure how regular of a contributor I'll be :P.  Any eastern evening time, or weekends would do for me. If there's anything I could do to make myself useful, I'd be happy to help!

**Comment by shortmann** [comment]
7PM UTC works for me too.

**Comment by loomsen** [comment]
7PM works fine for me as well-

**Comment by robertdebock** [comment]
I have a preference for a weekly meeting at 19:00 UTC on Wednesdays.

Great initiative, looking forward to it!

**Comment by lwm** [comment]
Oh yes, gathering steam. Weekly it is!

**Comment by skhoroshavin** [comment]
For me ideal time looks like 8 PM UTC, but 7 PM UTC is also good.

**Comment by duck-rh** [comment]
I'm in the JST TZ so 04:00 here is going to be difficult for me.
I'm not a real contributor yet, so it's OK.
I'd be happy to read the notes though (RDO folks use a magic bot for this, very handy). Also maybe one could post some question/suggestion in the meeting agenda somewhere.

**Comment by rgarrigue** [comment]
Nice initiative. Sadly I don't have enough free time to be of a real help, and 7PM UTC is 1 hour too late for me. Doesn't matter much since I'm a minor contributor, mostly about doc.

But I'll gladly read logs on my bouncer and/or meeting notes to follow Molecule :-)

**Comment by Shaps** [comment]
weekly 7PM UTC works for me

**Comment by MarkusTeufelberger** [comment]
7 PM UTC is fine for me too.

**Comment by ssbarnea** [comment]
Wednesday 19:00 UTC seems to be ok. I added a calendar links so we can easily add it https://calendar.google.com/event?action=TEMPLATE&tmeid=XzcxMTM4ZHE1NmtyM2liYTQ4b3MzZ2I5azhjcmplYmExNjBvM2NiYTM2MTEzMGMyMzg1MzNpZ3BuNzRfMjAxOTAxMjNUMTkwMDAwWiBzb3Jpbi5zYmFybmVhQG0&tmsrc=sorin.sbarnea%40gmail.com&scp=ALL

**Comment by wilmardo** [comment]
7PM UTC should work for me too, only the earlier mentioned Wednesday isn't free until May. Weekly or bi-weekly doesn't matter for me but I think it is more efficient to do it weekly. Less decisions to make, shorter meetings and thus easier to block in the agenda.
Just my 2 cents! 

I am curious where this goes, cool to be a part of Molecule 👍

**Comment by MarkusTeufelberger** [comment]
Btw. @retr0h should also be mentioned/invited, after all as far as I know he started the project and maintained it for quite a while. :-)

**Comment by lwilke** [comment]
Not sure how much time i am going to have spare, but 1900 UTC is fine with me.

**Comment by gundalow** [comment]
Firstly wow, wasn't expecting such a quick response from so many people :)

So it seems that 1900 UTC Wednesday works for most people.

1) The agenda has been created; please hit subscribe on https://github.com/ansible/community/issues/427
2) The meeting will be **1900 UTC on Wednesdays** in `#ansible-molecule`

    * First meeting will be Wednesday 23rd Jan at 1900UTC
3) All Ansible meetings are recorded thanks to `zobot`.

    * At the end of each meeting the agenda #427 will be updated to include a summary of discussion as links to the summary (actions) and full transcript.

4) In your calendar of choice please "add by URL"  `https://raw.githubusercontent.com/ansible/community/master/meetings/ical/molecule.ics`. This ensure if the meeting time is changed in the futrue you calendar will be updated



Our IRC channels may require you to register your nickname. If you receive an error when you connect, see [Freenode’s Nickname Registration guide](https://freenode.net/kb/answer/registration) for instructions.


So we can consider this issue closes. Thanks everybody!
