### ISSUE TITLE
HP-UX community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#429]
[![Github hpux issues](https://img.shields.io/github/issues/ansible/ansible/hpux.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:hpux) [![Github hpux PRs](https://img.shields.io/github/issues-pr/ansible/ansible/hpux.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:hpux) [![HP-UX pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/429.svg?label=pinboard+update)](https://github.com/ansible/community/issues/429)

We could collectively benefit from forming a Working Group related to HP-UX integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this issue is a wake-up call to potential interested parties (earlier and existing contributors to Ansible). The benefits of having a Working Group is that members of the Working Group can:

- test, review and add shipits to existing HP-UX-related PRs
- work collectively on the HP-UX roadmap
- provide a single-point-of-contact for interested HP-UX contributors
- collaborate on [a HP-UX-specific Wiki](https://github.com/ansible/community/wiki/HP-UX)
- have a $team_hpux in BOTMETA.yml for auto-notifying team members (ansible/ansible#51075)
- implement auto-labeling HP-UX issues and PRs (ansible/ansible#51075)

Since we don't have any HP-UX infrastructure for automated testing, collaborating on modules like this is important for the quality of the modules.

**Comment by dagwieers** [comment]
cc @sdodsley @Akasurde @rgroten @cocampbe @mtkunkel @taksekine @fallencliff @jokurz @pdelared @rik2803 @melodous @tgolly @Logos01
cc @Hr0bar @rpettersen @alikins @davx8342

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, show your support in this ticket ! If we have a few interested people, we can start our own HP-UX Working Group.

I started labeling all the HP-UX related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:hpux (1 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:hpux (5 open issues)

PS If you no longer want to receive any messages from this pinboard, I apologize. Feel free to unsubscribe from this issue ticket.

**Comment by dagwieers** [comment]
I refactored the **swdepot** module and added integration tests, you can find this at: https://github.com/ansible/ansible/pull/51106
Can someone with access to an HP-UX system test the new module and integration tests ?

You need to clone my fork, checkout my branch, then run ansible-test:

    git clone https://github.com/dagwieers/ansible ansible.dagwieers
    cd ansible.dagwieers
    git checkout swdepot-refactor
    ansible-test integration --allow-destructive --allow-unsupported swdepot

You may have to modify the integration test at *test/integration/targets/swdepot/tasks/main.yml* to point the tests to your depot/repository. By default the tests uninstall and reinstall the 'unzip' package.

**Comment by davx8342** [comment]
> If you want to actively lead or are interested to be part of this Working Group, show your support in this ticket ! 

Yeah, this is something that's on my list. Last year there was a re-org at work and, to cut a long story short, automation took a back seat while the new team bedded in.

I've got access to HP-UX 11.11, 11.23, 11.31, 11.33, 11iv1, 11iv2, 11iv3 in house so I should be able to contribute some time to this.

**Comment by dagwieers** [comment]
@davx8342 Welcome to the team ;-) I would really appreciate if you could test the swdepot refactored code and even test/fix the included integration test.
