### ISSUE TITLE
BSD community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#430]
[![Github bsd issues](https://img.shields.io/github/issues/ansible/ansible/bsd.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:bsd) [![Github bsd PRs](https://img.shields.io/github/issues-pr/ansible/ansible/bsd.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:bsd) [![BSD pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/430.svg?label=pinboard+update)](https://github.com/ansible/community/issues/430)

We could collectively benefit from forming a Working Group related to BSD integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this *issue* is a wake-up call to potential interested parties (earlier and existing contributors to Ansible).  The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing BSD PRs
- work collectively on the BSD roadmap
- provide a single-point-of-contact for interested BSD contributors
- collaborate on [a BSD-specific Wiki](https://github.com/ansible/community/wiki/BSD)
- have a $team_bsd in BOTMETA.yml for auto-notifying team members (ansible/ansible#51085)
- implement auto-labeling BSD issues and PRs (ansible/ansible#51085)

Since we have quite some open PRs, reviewing and testing modules and contributions are important for the quality of the modules and helps getting things moving.

**Comment by dagwieers** [comment]
cc @jpdasma @opoplawski @loqutus @padme279 @hc42 @t6n @basarevych @AMDmi3 @thnee @danieljakots @afair @fpracht @tmshn @desnudopenguino @tuxillo @jforman @digitalist @jontow @jcsmith @slohse @eest @toxadx @jasperla @ftigeot @biancalana @quinot @amenonsen @mutermule @verm666 @stemid @jeffrizzo @rpe-github @jpte @landryb @sthen @berenddeboer @dehylton @Mischi @mwpher @faust64 @rgbj @zehome @johanwiren @r-p-e @uggedal @trbs @GuiGui2 @huberteff @rrtj3

**Comment by dagwieers** [comment]
cc @bcoca @samdoran @maxamillion @alikins @mscherer @mkrizek

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, show your support in this ticket ! If we have a large enough group, we can start our own BSD Working Group.

I started labeling all the BSD related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:bsd (25 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:bsd (12 open issues)

PS If you no longer want to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by tuxillo** [comment]
Should we present ourselves in the wiki under "Community" for specific BSD flavours?

**Comment by dagwieers** [comment]
@tuxillo That is a good idea!

**Comment by jasperla** [comment]
I have added myself to the list, thanks for setting this up!

**Comment by mscherer** [comment]
So, my interest is mostly making sure stuff still work for FreeBSD (for my work). I use to be also interested into NetBSD, but we stopped using it in the gluster buildsystem, so I kinda stopped finding issues and testing there.

**Comment by dagwieers** [comment]
So we got a good response for AIX, BSD and Solaris, HP-UX (unsurprisingly) is a bit silent.

How do we proceed ? Having a meeting would probably be best. See my thoughts on this at: https://github.com/ansible/community/issues/421#issuecomment-455200492

In any case, please review open issues and PRs to help close issues. Also help in writing integration tests would be very welcome (and is not hard at all). Since we have FreeBSD in Shippable CI these would be run continuously and find issues with FreeBSD updates as well as changes to the modules.

**Comment by mekanix** [comment]
I added myself. Thank you very much!

**Comment by vbotka** [comment]
I added myself. Thank you very much!
