### ISSUE TITLE
macOS community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#432]
[![Github macos issues](https://img.shields.io/github/issues/ansible/ansible/macos.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:macos) [![Github macos PRs](https://img.shields.io/github/issues-pr/ansible/ansible/macos.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:macos) [![macOS pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/432.svg?label=pinboard+update)](https://github.com/ansible/community/issues/432)

We could collectively benefit from forming a Working Group related to macOS integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this *issue* is a wake-up call to potential interested parties (earlier and existing contributors to Ansible). The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing macOS PRs
- work collectively on the macOS roadmap
- provide a single-point-of-contact for interested macOS contributors
- collaborate on [a macOS-specific Wiki](https://github.com/ansible/community/wiki/macOS)
- have a $team_macos in BOTMETA.yml for auto-notifying team members (ansible/ansible#51255)
- implement auto-labeling macOS issues and PRs (ansible/ansible#51255)

Since we have quite some open PRs, reviewing and testing modules and contributions are important for the quality of the modules and helps getting things moving.

**Comment by dagwieers** [comment]
cc @danieljaouen @kinglouie @indrajitr @kyleabenson @jcftang @enriclluelles 
cc @newtonne @jasontedor @damselem @BadStreff @bjoernalbers @indrajitr @pm5 @rabynlarsen @gbazilio @aluminiumgeek @raul-gracia @jure @y-nk @mjaschen @jxtx @dedalusj @adammenges @vyrak @cchurch @kimausloos @grlee @daghoidahl markmcconachie @stoned @renanivo @andrew-d

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, add your name to [the Wiki page](https://github.com/ansible/community/wiki/macOS) ! If we have a large enough group, we can start our own macOS Working Group.

I started labeling all the Gitlab related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:macos (4 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:macos (13 open issues)

PS If you no longer want to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by jcftang** [comment]
I'm interested in reviewing/watching the outputs of this group should I add myself to this page or just remain part of this ticket?

**Comment by dagwieers** [comment]
@jcftang If you subscribe to this ticket, you only get the updates to this ticket. If you add yourself to the list on the wiki, you will get included in new issues/PRs and can follow the discussion in those tickets.

But it's a good question, we should probably make a distinction between people interested to be notified (notified), and people interested to review (maintainers). So I am going to add a Roles column.

**Comment by gmkey** [comment]
Hey there, I've been checking some issues on the list and I've noticed that most seem already resolved. Got a few hours here and there, so maybe I can assist?

**Comment by y-nk** [comment]
hi @dagwieers :) i'm really flattered to receive this notification but sadly i moved on platform automation. if there's anything i can do in the frontend part of things, let me know.
