### ISSUE TITLE
Public Ansible Project Meeting Agenda - Feb 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#436]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through.

*(Migrated from [a previous agenda](https://github.com/ansible/community/issues?q=label:core+label:meeting_agenda))*

**Comment by bcoca** [comment]
carried over:
@dagwieers :
  - ansible/ansible#50035 -- New type 'mode' for Unix permissions/umask (migrate to strings-only)
@bcoca:
  - ansible/ansible#15484

**Comment by dagwieers** [comment]
I would like to see this added as it solves various use-cases:
- https://github.com/ansible/ansible/pull/42528 -- New forks directive, per-play, per-block, per-task

**Comment by dw** [comment]
I would like to discuss a sensible approach to landing various pieces of the Mitogen work:

- concrete plan for landing pieces of the existing connection layer implementation,
- patches necessary to remove ActionModule monkey-patches
- state of the threading/forking patches
- route for landing a complete strategy implementation that changes the process model

**Comment by jamescassell** [comment]
https://github.com/ansible/ansible/issues/51757

**Comment by tgadiev** [comment]
Can we add this one to discussion?
https://github.com/ansible/ansible/pull/49953

**Comment by gundalow** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-05/ansible_core_irc_meeting.2019-02-05-19.00.html
20:52 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-05/ansible_core_irc_meeting.2019-02-05-19.00.txt
20:52 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-05/ansible_core_irc_meeting.2019-02-05-19.00.log.html

**Comment by vutkin** [comment]
Hello, could you kindly advise me who is a contact person for aws group? I have not found any meeting aganda or smth like this. I have a PR but I can't find anubody to review it. https://github.com/ansible/ansible/pull/51535
TIA.

**Comment by dw** [comment]
- [ ] followup discussion about possibly doing SSH-like-only connection method first, in order to flush out the `ansible_python_interpreter` task_vars issue

**Comment by dagwieers** [comment]
I like to discuss @agaffney's proposal for inclusion:
- https://github.com/ansible/ansible/pull/51768 -- *Custom jinja Undefined class for handling nested undefined attributes*

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/46687 ansible_parent_role_name/path variables for when a role is being included by another role

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/51499 Add warning to use reboot module with command/shell
aka Should we be adding items to `command-warnings`?

**Comment by dagwieers** [comment]
@gundalow We discussed this once in a meeting (see https://github.com/ansible/ansible/pull/25089#issuecomment-322585638), not sure if we want to come back on this. Did anything change?

**Comment by samdoran** [comment]
Meeting ended Tue Feb 12 20:00:04 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
15:00 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-12/ansible_core_irc_meeting.2019-02-12-19.00.html
15:00 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-12/ansible_core_irc_meeting.2019-02-12-19.00.txt
15:00 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-12/ansible_core_irc_meeting.2019-02-12-19.00.log.html

**Comment by madonius** [comment]
Can we add https://github.com/ansible/ansible/pull/38121 to the agenda?

**Comment by maxamillion** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-14/ansible_core_public_meeting.2019-02-14-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-14/ansible_core_public_meeting.2019-02-14-15.01.log.html

**Comment by marcjay** [comment]
Please could we add this one by @AlanCoding to the discussion?:

- [ ] ansible/ansible#44067 Support deterministic host ordering from group ancestors

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/issues/52506 (standardize TLS connection properties)

**Comment by felixfontein** [comment]
ansible/ansible#52518: deprecate returned facts for `docker_container`, `docker_network`, `docker_volume` and `docker_compose modules`

**Comment by AlanCoding** [comment]
https://github.com/ansible/ansible/pull/52045: add a toggle to allow unsafe group names so users can migrate from inventory scripts to inventory plugins

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/155

**Comment by bcoca** [comment]
Meeting ended Tue Feb 19 20:19:09 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[15:19] <zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-19/ansible_core_meeting.2019-02-19-19.03.html
[15:19] <zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-19/ansible_core_meeting.2019-02-19-19.03.txt
[15:19] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-19/ansible_core_meeting.2019-02-19-19.03.log.html

**Comment by c-edw** [comment]
https://github.com/ansible/ansible/issues/52354#issue-410909935: Adopt the XDG Base Directory Specification. My IRC name is `cedwards`.

**Comment by nitzmahone** [comment]
(for Feb 26) Should module args with `choices` always be lowercase? Currently, the match is case-sensitive on Python, and has historically been case-insensitive for Powershell. Do we really want `absent` and `AbSeNt` to mean different things on a module with specific enumerated choices?

If we choose to make it case-insensitive (`type='str'` with `choices` specified), we'd probably need a deprecation warning to fire on any module that specifies `choices` with an uppercase value. We can fix all the ones we ship, but there may be modules in the wild that expect specific-cased values. There are a number of other ways we could address it as well, but they'd probably require a lot more changes to the existing modules (eg the introduction of a `lowerstr` type).

**Comment by bcoca** [comment]
Meeting ended Thu Feb 21 15:22:15 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-21/ansible_core_public_irc_meeting.2019-02-21-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-21/ansible_core_public_irc_meeting.2019-02-21-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-21/ansible_core_public_irc_meeting.2019-02-21-15.00.log.html

**Comment by felixfontein** [comment]
ansible/ansible#52825: add `quiet` option to `assert` module (to prevent automatic default to dump full `item`s etc.)

**Comment by akatch** [comment]
For 26 February:
[ansible/ansible#32810](https://github.com/ansible/ansible/pull/32810): Unixy stdout callback plugin - display name of play and list of play hosts
[ansible/ansible#46728](https://github.com/ansible/ansible/pull/46728): Add Unixy option to display only changed output

My IRC nick is raktajino.

**Comment by Akasurde** [comment]
For 26 February: 

I would like to discuss this - https://github.com/ansible/ansible/pull/32214 - irc @akasurde

**Comment by bcoca** [comment]
Meeting ended Tue Feb 26 19:58:12 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-26/ansible_core_irc_public_meeting.2019-02-26-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-26/ansible_core_irc_public_meeting.2019-02-26-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-26/ansible_core_irc_public_meeting.2019-02-26-19.02.log.html

**Comment by devyanikota** [comment]
I would like to discuss this https://github.com/ansible/ansible/pull/45997
IRC nick: devyani7
Thanks.

**Comment by bcoca** [comment]
Meeting ended Thu Feb 28 16:18:41 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-28/ansbile_core_irc_public_meeting.2019-02-28-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-02-28/ansbile_core_irc_public_meeting.2019-02-28-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-02-28/ansbile_core_irc_public_meeting.2019-02-28-15.03.log.html
