### ISSUE TITLE
Crypto community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#438]
[![Github crypto issues](https://img.shields.io/github/issues/ansible/ansible/crypto.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:crypto) [![Github crypto PRs](https://img.shields.io/github/issues-pr/ansible/ansible/crypto.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:crypto) [![Crypto pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/438.svg?label=pinboard+update)](https://github.com/ansible/community/issues/438)

We could collectively benefit from forming a Working Group related to Crypto integration. We have quite some contributors and users that are interested in improving this integration.

So this *issue* is a call to potential interested parties (earlier and existing contributors to Ansible).  The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing Crypto PRs
- work collectively on a Crypto roadmap
- provide a single-point-of-contact for interested Crypto contributors
- collaborate on [a Crypto-specific Wiki](https://github.com/ansible/community/wiki/Crypto)
- have a $team_crypto in BOTMETA.yml for auto-notifying team members (ansible/ansible#52057)
- implement auto-labeling Crypto issues and PRs (ansible/ansible#52057)

**Comment by dagwieers** [comment]
cc @ldx @puiterwijk @rouge8 @spredzy @manicai @fagaillard @kgottholm @kkjang @psykotox @hsoft @equinox0815 @MarkusTeufelberger @cpointner @gdelpierre @drzraf @danielllek @thomwiggers @bverschueren @tiggi @ksnavely @Xyon @john-westcott-iv @lolcube @s3lph @endorama @saito-hideki 
cc @abadger @jimi-c @resmo @felixfontein @mscherer @jborean93

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, add your name to [the Wiki page](https://github.com/ansible/community/wiki/Crypto) ! If we have a large enough group, we can start our own Crypto Working Group.

I started labeling all the Crypto related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:crypto (6 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:crypto (21 open issues)

PS If you no longer want to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by felixfontein** [comment]
cc @japokorn @saito-hideki

**Comment by Xyon** [comment]
@dagwieers how many is sufficient for a working group?

**Comment by Shaps** [comment]
@Xyon I don't think there's an exact minimum number as long as it > 1 :)

**Comment by dagwieers** [comment]
@Xyon @Shaps I guess it depends mostly on the involvement of the members. But it helps if more people are actually involved to discuss, review and test. Being able to reflect on things as a group is really useful. The crypto-stuff is already managed well in Ansible, hence the low number of open PRs, but the number of issues is relatively high so this WG will have to work on that issues backlog mostly.

The plan is to add a list of (general) actions to the Wiki so that Working Groups can assess themselves what they do well and where they may be lacking. And I'd also like to detail the different tools a WG could be using for communication and decision-making. We do not want to impose any rules, and leave it up to the WG Leads to use what works best. The minimum requirements currently are a Wiki (overview) and a Pinboard (general peer communication).

Obviously most communication among WG members happen in the issue tickets and PRs.

**Comment by dagwieers** [comment]
I would like to thank @Spredzy and @felixfontain for accepting the role as lead in the Crypto Working Group. This will reduce my role to helping out in the background when needed.

We are still learning how these communities can help improve contributors and users. I started to write down how I envision [the different roles in Working Groups](https://github.com/ansible/community/wiki/Roles). Feedback and ideas are always welcome.

There is room for more people taking up the Lead role, so if you think you have some extra cycles to spare to help grow this community, let me know.

The Ansible v2.8 freeze is nearing and we have about a month to get as much as possible reviewed and fixed. Feel free to reach out to @felixfontein, @Spredzy, @gundalow and me if you need any help. Let's make the upcoming release the best one ever!

**Comment by dericcrago** [comment]
The crypto community pinboard has moved here https://github.com/ansible-collections/community.crypto/issues/24
