### ISSUE TITLE
MySQL community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#439]
[![Github mysql issues](https://img.shields.io/github/issues/ansible/ansible/mysql.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:mysql) [![Github mysql PRs](https://img.shields.io/github/issues-pr/ansible/ansible/mysql.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:mysql) [![MySQL pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/439.svg?label=pinboard+update)](https://github.com/ansible/community/issues/439)

We could collectively benefit from forming a Working Group related to MySQL and MariaDB integration. We have quite some contributors and users that are interested in improving this integration.

So this *issue* is a call to potential interested parties (earlier and existing contributors to Ansible).  The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing MySQL PRs
- work collectively on a MySQL roadmap
- provide a single-point-of-contact for interested MySQL contributors
- collaborate on [a MySQL-specific Wiki](https://github.com/ansible/community/wiki/MySQL)
- have a $team_mysql in BOTMETA.yml for auto-notifying team members (ansible/ansible#52212)
- implement auto-labeling MySQL issues and PRs (ansible/ansible#52212)

**Comment by dagwieers** [comment]
cc @marktheunissen @lorin @Ernest0x @gottwald @mavimo @abondis @stijnopheide @blair @tyll @asad-at-srt @candeira @jochu @aquach @stintel @banyek @adq @bradleyy @jpmens @stoned @johnhamelink @thirty3 @tomdymond @damianmoore @pileofrogs @jhoekx @mmoya @jkleckner @Oneiroi @kustodian @ospii @gkoller @muffl0n @amree @jazmit @Jmainguy @pilou- @PierrePaul @mistaka0s @hansbaer @abeverley @adamchainz @webmat @himyouten @evgorchakov @escaped @scottbrown @caphrim007 @isegal @ghjm @wrosario

**Comment by dagwieers** [comment]
cc @georgeOsdDev @mpeters @jsmartin @jlaska @zytek @chrismeyersfsu @sbktrifork @mvgrimes @skalfyfan @bjne @megamisan @jonathonwalz @alustenberg @bobuss @computersalat @mklassen @sergey-trukhin @cdalbergue @ghost @dramaley @ilsken @willthames @zaenk @kenichi-ogawa-1988 @cosmix @MagikSquirrel @jappievw @iredmail @michalmedvecky @tolland @genofire @ChristopherGAndrews @sbktrifork @plumbeo @DSpeichert @kucuny @Xyon @Alexander198961 @chrnie @jw34 @zikalino @Uwila @oposicioncuba @oadiazp @tomaszkiewicz @bmalynovytch @mikeSimonson @diegobill @AndrewGEvans95 @timorunge @maxamillion

**Comment by dagwieers** [comment]
@commx @richlv @bpennypacker @uncertaintyP @MrStrix

cc: @gundalow

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, add your name to [the Wiki page](https://github.com/ansible/community/wiki/MySQL) ! If we have a large enough group, we can start our own MySQL Working Group.

I started labeling all the MySQL related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:mysql (33 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:mysql (62 open issues)

PS If you no longer want to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by genofire** [comment]
Hi, thank you to try to improve the mysql support.
I only have one problem ATM - for this i have created a PR https://github.com/ansible/ansible/pull/37400 .
I really like improve this PR if somebody take a look/review and say, what i have to do (after 11 months).

Keep calm and please accept, that i do not spent more time in developing at this project.
I wish u good luck and thank you for the initiative.

**Comment by dagwieers** [comment]
I was made aware that the ProxySQL modules made use of the MySQL module_utils. So it seems best that we add ProxySQL to the responsibility of the MySQL Working Group.

**Comment by bmalynovytch** [comment]
Thank you @dagwieers for the effort.
Right now, MySQL modules suffer from many bugs, some of them required complete rewrite of the modules or libs.
We first need to determine which PRs need to be merges first and check which issues remain, as many might be closed after a couple of PRs will be merged.
Where should we talk about it ? (best place for this ?)

**Comment by Oneiroi** [comment]
@bmalynovytch https://gitter.im/ansible-mysql-wg/community I've just created this gitter room; note my BW is limited at this time I'll seek to coordinate on reviews etc as soon as I have some BW available to do so.

**Comment by bmalynovytch** [comment]
Thx @Oneiroi 
If this room is fine, we should add it to the Wiki page of the WG (@dagwieers)

**Comment by dagwieers** [comment]
We are actually setting up Matrix bridges for IRC channels, so I would prefer use existing solutions for all WGs rather than individual solutions. cc @gundalow

**Comment by dagwieers** [comment]
@bmalynovytch I wouldn't mind merging all new modules as-is, if we agree to fix all issues before the Ansible 2.8 release. Which includes writing integration tests for all MySQL modules to ensure they work correctly.

**Comment by bmalynovytch** [comment]
The trouble is that most PRs will have heavy conflicts I bet.
Many of them were done based on old codebase.
I'll do my best to help but can't guarantee I'll have enough bandwidth to fix/test every module.

Couldn't we do a first review of the PRs awaiting and pick the most urgents / well reworked ?

**Comment by dagwieers** [comment]
Sure, but having integration tests helps ensure the behavior is as it was before.

PS I was only talking about new modules, not about PR's to existing modules. Those actually require integration tests beforehand IMO.

**Comment by dagwieers** [comment]
Reviewing is already possible, you don't need my approval for those ;-) (My role is a supporting one really)

**Comment by bmalynovytch** [comment]
Oh sorry, I read too quickly.
I'll give it a quick eye (Kubernetes baremetal currently deploying ^^ )

**Comment by bmalynovytch** [comment]
@dagwieers I'm unable to find PRs adding modules related to MySQL.
How do you search them ?

**Comment by gundalow** [comment]
@bmalynovytch https://github.com/ansible/ansible/labels/mysql

**Comment by bmalynovytch** [comment]
@gundalow 🤔 
This search gives all issues related to MySQL, not PRs adding **new** modules related to MySQL.

**Comment by gundalow** [comment]
Ah, set the query to `label:mysql label:new_module is:open`

**Comment by timorunge** [comment]
My 2cents: KISS. 
- Start with PRs which have passed checks / tests
- Start with PRs which are are easy to understand / merge, e.g.:
  - https://github.com/ansible/ansible/pull/19123 (Dec 2016)
  - https://github.com/ansible/ansible/pull/40183 (May 2018)
  - https://github.com/ansible/ansible/pull/47809 (mine and I really need it 😋)
- Move on, write the integration tests if they are required, prioritise the existing PRs and start to create tickets and some cleanup afterwards.

**Comment by dagwieers** [comment]
> * Start with PRs which have passed checks / tests
> * Start with PRs which are are easy to understand / merge, e.g.:

We don't have any real tests without integration tests, so I would really urge to start writing integration tests first. Anyone contributing to existing modules benefits from writing integration tests first to ensure/prove their changes are not breaking existing modules.

**Comment by dagwieers** [comment]
All members that signed up now have **shipit** rights and can use them to merge PRs when reviewing and testing. Use it wisely (and only after reviewing *and* testing).

As a result of becoming co-maintainer of the MySQL modules you will be notified by @ansibot for each open issue and PR.

We are still looking for one or more [leads](https://github.com/ansible/community/wiki/Roles#lead) to manage this WG.

**Comment by bmalynovytch** [comment]
Thx @gundalow, I was missing the `new_module` label.
@dagwieers I'll give a look at the tests ASAP (but certainly not before a couple of days).
@timorunge I'll give them a look as well ASAP.

**Comment by bmalynovytch** [comment]
Ready for review PR (`label:mysql -label:needs_rebase -label:backport status:success`) : https://github.com/ansible/ansible/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Amysql+-label%3Aneeds_rebase+-label%3Abackport+status%3Asuccess

**Comment by Andersson007** [comment]
FYI: All the modules and related stuff have been recently moved to https://github.com/ansible-collections/community.mysql

**Comment by Andersson007** [comment]
FYI: pinboard and wiki have been created https://github.com/ansible-collections/community.mysql/issues/12 and https://github.com/ansible-collections/community.mysql/wiki/MySQL-Working-Group
