### ISSUE TITLE
Idea: reviewer recruiting

### ISSUE THREAD

**Issue by gregdek** [ansible/community#44]
So here's an idea for discussion at our next cwg meeting:

Put a module reviewer solicitation directly in boilerplate for modules that are in core review. 

e.g. "Hi submitter! Thanks for this PR. This module is currently maintained by the Ansible Core team, which means it might take a while. But if you'd be willing to take over maintainership, we might be able to move your PR through more quickly! Just respond to this with "new_maintainer" and we'll follow up with next steps to make you a maintainer of this module."

Or something like that. It's pretty clear that the people who are most likely to want to maintain a module are the people who are willing to submit a PR for the module, and we should leverage that.

**Comment by robynbergeron** [comment]
Was discussed in IRC meeting on March 11 -- https://meetbot.fedoraproject.org/ansible-meeting/2016-03-11/community-working-group.2016-03-11-19.04.html & some actions assigned to Greg.

Re-discussed in 3/16 meeting as well.

**Comment by gregdek** [comment]
Yep. Next step is to open a PR for this against ansible/ansibullbot. Once I've done that, I'll close this one.

**Comment by gregdek** [comment]
https://github.com/ansible/ansibullbot/issues/51
