### ISSUE TITLE
Request for hcloud WG

### ISSUE THREAD

**Issue by LKaemmerling** [ansible/community#446]
WORKING GROUP NAME:  hcloud

WORKING GROUP PURPOSE:
Maintaining and review all Hetzner Cloud (hcloud) modules and the hcloud inventory plugin

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
IRC: LukasKaemmerling Github: @lkaemmerling
IRC: cschmitt-hcloud  Github: @cschmitt-hcloud

**Comment by dagwieers** [comment]
I wonder if `hetzner` is not a better name for the Working Group as it is more recognizable to most users. In any case, I will already start making the labels and make the PR for a $team to BOTMETA.yml.

**Comment by LKaemmerling** [comment]
I guess `hetzner` wouldn't fit for us directly, because we will only maintain all Hetzner Cloud specific modules. All our other tools are named with `hcloud` too.(https://github.com/hetznercloud/hcloud-go, https://github.com/hetznercloud/hcloud-python, https://github.com/terraform-providers/terraform-provider-hcloud).

**Comment by dagwieers** [comment]
I understand, but a name is also about recognition, and I would expect people to recognize hetzner more than hcloud. Besides are there any other hetzner-related modules ? I don't think so.

But if you prefer hcloud, that's fine :-)

**Comment by LKaemmerling** [comment]
Of course it could be also named `hetzner_cloud`.

**Comment by dagwieers** [comment]
Whatever you think helps your cause...

**Comment by dagwieers** [comment]
- The wiki has been created at https://github.com/ansible/community/wiki/hcloud
- I also added the label and labeled the only PR that was relevant :-)

**Comment by LKaemmerling** [comment]
Thank you!
