### ISSUE TITLE
AnsibleFest Contributor Conference 2019

### ISSUE THREAD

**Issue by gundalow** [ansible/community#449]
[AnsibleFest Atlanta](https://www.ansible.com/ansiblefest)
* Mon 23rd September: Contributors Summit
* Tue & Wed 24-26 September: Main Fest

We are starting to collect ideas for topics in the [Etherpad](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)

### This is your event

Ansible succeeds because of its Community, and this Contributor Summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the Etherpad. For topics that others had added please vote by adding +1

**Comment by geerlingguy** [comment]
@gundalow - Will the notes/materials from this year be added to https://github.com/ansible/community/tree/master/meetings/contributor_summits? Or where could I point people to as the source of truth after today?

**Comment by gundalow** [comment]
@geerlingguy Link to videos and meeting notes will be added in the next 2-3 week
