### ISSUE TITLE
Clarify PR labels and process

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#45]
We have labels, some used by ansibullbot, some just applied by committers, in various repositories, that sometimes are not well documented or at least documented in an obvious place. 

We should do that.

**Comment by robynbergeron** [comment]
From meeting on March 16

#action rbergeron to figure out some label definitions and re-review workflow
#action rbergeron to figure out better place for that documentation of those 
                   things to go. 
13:00 <@gregdek> Should prolly change this issue to reflect that we're talking pr labels
13:01 <@rbergeron> #info note: the above is really related to PR labels, and not issue labels, as 
                   that was a previous topic in meeting.
13:02 <@rbergeron> #action rbergeron to maybe list out other things that may be affected / come to 
                   mind while going through this -- stuff relating to PR bot, etc.
13:02 <@rbergeron> I think that's it.

**Comment by robynbergeron** [comment]
Have started (just a wee little bit) fleshing this out. 

Will probably just take care of PR labels and issue labels all at the same time -- most of them overlap, and only a few differ in context (for example, needs_revision means "fix the code" in a PR, in a label as defined currently it is "fix your issue with the right issue type or module name"). 

Not sure what to do about ansible/ansible just yet, but many of those labels also overlap, so may try to catch it all at once. Still investigating.

https://github.com/robynbergeron/thingsandstuff/blob/master/labeldefinitions

**Comment by robynbergeron** [comment]
Robyn to move this list over to ansibullbot -- then reassign to gdk for ... refinement.

**Comment by gregdek** [comment]
This is done: https://github.com/ansible/community/blob/master/PR-FLOW.md
