### ISSUE TITLE
Public Ansible Project Meeting Agenda - Apr 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#456]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

*(Migrated from [a previous agenda](https://github.com/ansible/community/issues?q=label:core+label:meeting_agenda))*

**Comment by bcoca** [comment]
- [ ] Allow exception to azure_*_facts modules new in 2.8 that don't return facts (schedule for rename/deprecation in 2.9) @nitzmahone

**Comment by bcoca** [comment]
Meeting ended Tue Apr  2 19:55:01 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-02/ansible_plublic_core_irc_meeting.2019-04-02-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-02/ansible_plublic_core_irc_meeting.2019-04-02-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-02/ansible_plublic_core_irc_meeting.2019-04-02-19.05.log.html

**Comment by sivel** [comment]
https://github.com/ansible/ansible/issues/54131

Document behavior or deprecate the INI facts.d functionality.

**Comment by bcoca** [comment]
Meeting ended Thu Apr  4 15:37:20 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-04/ansbile_core_irc_public_meeting.2019-04-04-15.10.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-04/ansbile_core_irc_public_meeting.2019-04-04-15.10.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-04/ansbile_core_irc_public_meeting.2019-04-04-15.10.log.html

**Comment by bcoca** [comment]
- [ ] https://github.com/ansible/proposals/issues/160 by @gundalow

**Comment by bcoca** [comment]
Meeting ended Tue Apr  9 19:07:32 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-09/ansible_core_public_irc_meeting.2019-04-09-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-09/ansible_core_public_irc_meeting.2019-04-09-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-09/ansible_core_public_irc_meeting.2019-04-09-19.00.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/54412

**Comment by gundalow** [comment]
Agree where Plugin metadata should come from
https://github.com/ansible/ansibullbot/issues/1183#issuecomment-478001863

**Comment by bcoca** [comment]
Meeting ended Thu Apr 11 15:35:14 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-11/ansible_core_public_irc_meeting.2019-04-11-15.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-11/ansible_core_public_irc_meeting.2019-04-11-15.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-11/ansible_core_public_irc_meeting.2019-04-11-15.06.log.html

**Comment by jamescassell** [comment]
- [ ] TRANSFORM_INVALID_GROUP_CHARS 

[13:24] <cyberpear> "The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on deprecation"
[13:25] <cyberpear> looks like there's 'never', 'always', and 'silent' -- can we add a 'never-silent' option?
[13:25] <cyberpear> since it seems that I will be able to use '-' in my group names indefinitely as long as I set this config flag appropriately?

**Comment by felixfontein** [comment]
@jamescassell the code knows another option which isn't documented but *mostly* does what you want: `ignore`. See https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/group.py#L38-L52

**Comment by bcoca** [comment]
Meeting ended Tue Apr 16 20:00:26 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-16/ansible_core_public_irc_meeting.2019-04-16-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-16/ansible_core_public_irc_meeting.2019-04-16-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-16/ansible_core_public_irc_meeting.2019-04-16-19.01.log.html

**Comment by bcoca** [comment]
No items discussed, but here are logs anyways:

Meeting ended Thu Apr 18 15:31:56 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-18/ansible_core_public_irc_meeting.2019-04-18-15.13.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-18/ansible_core_public_irc_meeting.2019-04-18-15.13.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-18/ansible_core_public_irc_meeting.2019-04-18-15.13.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Apr 23 19:53:49 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-23/ansible_core_public_irc_meeting.2019-04-23-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-04-23/ansible_core_public_irc_meeting.2019-04-23-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-04-23/ansible_core_public_irc_meeting.2019-04-23-19.00.log.html

**Comment by nalsaber** [comment]
Oracle cloud modules use the GPL 3.0 license. Oracle legal approved to use this license for all of the files. It is not possible to get BSD approval for Oracle module_utils. 
We are requesting an exception to use GPL 3.0 license for module_utils.
