### ISSUE TITLE
win_copy azure ansible module not working

### ISSUE THREAD

**Issue by Srija2495** [ansible/community#457]
Hi Team,

We are trying to automate the installation of tools in azure using ansible. VM spin up is successful and we are trying to invoke the powershell script(code for tools installation) so the files has to be installed on the server.

Tried number of ways using **win_copy** command for copying the files to remote server but no luck.

Here is the code snippet we are using:
- name: Create virtual machine to setup MicroFocus and WIE tools
    azure_rm_virtualmachine:
        resource_group: rg
        name: WinServer
        os_type: Windows
        vm_size: Standard_D1
        storage_account: azure
        admin_username: admin
        admin_password: admin
        image:
         # user_data: "{{ lookup('file', 'userdata-dbsetup.ps1')}}"
           offer: WindowsServer
           publisher: MicrosoftWindowsServer
           sku: '2016-Datacenter'
           version: latest
    register: instance_winout
  **- name: Copy script from local to remote server
    win_copy:
       src: files
       dest: C:\
       register: myfile
  - debug: var=myfile
  - win_command: powershell.exe -ExecutionPolicy ByPass -File C:/userdata-winsetup.ps1**

_**Below is the error while executing the playbook:
fatal: [localhost]: FAILED! => {
    "changed": false,
    "dest": "C:\\",
    "module_stderr": "",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "operation": "folder_copy",
    "rc": 0,**_

PS: Not able to execute the code highlighted in Bold Text.
We are using ansible 2.7.9 and Python 3.5.2 versions.
Tried using ansible_winrm_transport module as well, but no luck.

Note: we are not explicitly giving connection details except localhost

**Comment by gundalow** [comment]
Hi,
Please raise the issue at https://github.com/ansible/ansible/issues/new/choose
