### ISSUE TITLE
Ansible playbook not reading all the values in the LIST provided through extra variable

### ISSUE THREAD

**Issue by vijayakrishnarg1** [ansible/community#459]
Local Machine:

Ansible version: 2.4.1.0
python version = 2.7.10

Remote Redhat Machine:

Ansible version: 2.7.7
Python: 2.7.5

i have ansible running on my local machine(MAC), when i pass extra variable as LIST it's reading all the values in the map and giving proper results.

If i run same task on remote machine which Redhat vm, it's always reading last value in the LIST, please look at the issue and suggest me, is it Playbook issue or ansible version issue?

Here is the Playbook:  

ansible-playbook values_files.yml -i localhost  --extra-vars "@values_files_variable.yml" '--extra-vars={"MICROSERVICE_NAMES":["processor-create","processor-update"]}'  '--extra-vars={"MICROSERVICE_ENV_MAP":{}}'

if i execute above playbook on my local machine it's reading both the values in the MICROSERVICE_NAMES map : processor-create and processor-update

same playbook execute on Redhat remote machine, it's reading only what ever defined at the end in the LIST (processor-update), please suggest me , Thanks.

Gist for reference: https://gist.github.com/vijayakrishnarg1/fc0a037b82cb212708c65ba0b9010631

**Comment by gundalow** [comment]
Hi,
Please use the https://groups.google.com/forum/#!forum/ansible-project for user questions.
