### ISSUE TITLE
Fix "if you'd like to file a bug" documentation-related spots

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#46]
Right now this reads "please copy the issue template" -- we should not need to copy it now, it should be there automagically. 

"If you'd like to file a bug
Read the community page above, but in particular, make sure you copy this issue template into your ticket description. We have a friendly neighborhood bot that will remind you if you forget :) "

**Comment by gregdek** [comment]
@robynbergeron is this still an issue? If you can confirm and assign back to me or close?
