### ISSUE TITLE
Unable to copy files from local to remote server

### ISSUE THREAD

**Issue by Srija2495** [ansible/community#463]
Hi Team,

This topic is in reference to the content mentioned in the below link:
https://groups.google.com/forum/#!topic/ansible-project/DlqdnWXIoBA

Here I'm going to attach the files(playbook, filecopy and inventory).

Please help us solve this issue.

Here is some information related to the versions we are using:
ANSIBLE VERSION:

ansible 2.7.9

  config file = None

  ansible python module location = /opt/ansible/local/lib/python2.7/site-packages/ansible

  executable location = /opt/ansible/bin/ansible

  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
[inventory1.txt](https://github.com/ansible/community/files/3110578/inventory1.txt)
[vmspinup1.txt](https://github.com/ansible/community/files/3110579/vmspinup1.txt)
[wincopy1.txt](https://github.com/ansible/community/files/3110580/wincopy1.txt)

Tried adding add_host to the vmspinup file, but not able to execute the playbook successfully.

- name: wait for the WinRM port to come online
    wait_for:
      port: 5986
      host: WinServer
      timeout: 60

  - name: add new Azure VM as a Windows host
    add_host:
      name: WinServer
      groups: windows
      ansible_user: admin
      ansible_password: admin

    - name: invoke setup script
    script: userdata-winsetup.ps1

**Comment by Akasurde** [comment]
@Srija2495 This is repo is meant for community related activities. Please open a new issue in ansible/ansible repo. Thanks.
