### ISSUE TITLE
2FA enabled on github/ansible-community

### ISSUE THREAD

**Issue by gundalow** [ansible/community#464]
There were only three people without two-factor enabled on github.com/ansible-community so I've enabled it as we now have project code in here (ARA, bender) and not just meetup planning.

@atsaloli ansible-losangeles-meetup
@chrisweaver ansible-richmond-meetup
@keithresar ansible-minneapolis-meetup

If you [enable 2FA for your GitHub](https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa) account I'll give you admin back on the above repos.

**Please comment on this ticket once you have and I'll add you back**

For the London meetup group we've found https://github.com/ansible-community/ansible-london-meetup/ works well.

For outreach discussion, including Meetups feel free to use [ansible-outreach email list](https://groups.google.com/forum/#!forum/ansible-outreach)

**Comment by gundalow** [comment]
@jairojunior @mikedlr Can you please enable 2FA (see https://github.com/ansible/community/issues/464#issue-440433861 for details) otherwise you will lose your extra powers on https://github.com/ansible/community (ability to update issues and merge PRs) thanks in advance

**Comment by keithresar** [comment]
2FA enabled @gundalow

**Comment by decentral1se** [comment]
@gundalow can I be re-added to the organisation? I got locked out of my account (:man_facepalming:) and was removed but 2FA is re-enabled now and I need to be manually re-added. Thanks and sorry for noise.

**Comment by gundalow** [comment]
2FA has been a requirement on github/ansible-community for a while, I just forgot to close this issue.
Thank you to all then enabled 2FA.
