### ISSUE TITLE
How to create dynamic inventory group by  private ip address in ansible-playbooks using ansible aws_ec2 plugin 

### ISSUE THREAD

**Issue by ljzlegendice** [ansible/community#467]
How to create dynamic inventory group by  private ip address in ansible-playbooks using ansible aws_ec2 plugin?

**Comment by willthames** [comment]
This question is probably better asked on the ansible mailing list

https://www.ansible.com/community

or on the ansible-aws IRC channel. 

This repository is for issues relating to the community itself.
