### ISSUE TITLE
How can I modify or add tags on the existing ec2_customer_gateway? 

### ISSUE THREAD

**Issue by antarmy07** [ansible/community#469]
I can't seem to find any solution to create the tags for ec2_customer_gateway. I am able t create for ec2_vpc_vgw and ec2_vpc_vpn but for ec2_customer_gateway always give the following error:

```
TASK [XXXX : modify CGW connection tags] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ec2_customer_gateway) module: customer_gateway_id, tags Supported parameters include: aws_access_key, aws_secret_key, bgp_asn, ec2_url, ip_address, name, profile, region, routing, security_token, state, validate_certs"}
```

Playbook:

     - name: Create a new cgw
       ec2_customer_gateway:
        bgp_asn: 65000
        ip_address: xxx
        name: "xxx"
        region: "{{ region }}"
       register: local_cgw_result

     - name: modify CGW connection tags
       ec2_customer_gateway:
        state: present
        region: "{{ region }}"
        customer_gateway_id: "{{ ds_cgw_result.gateway.customer_gateway.customer_gateway_id }}"
        name: "xxx"
        region: "{{ region }}"
        tags:
          Environment: "{{ env }}"
          Type: "customer gateaway"
          Service: "xxx"
          Component: "Networking"
          Department: "xxx"
       register: local_cgw_mod_result 

Please help?

This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Akasurde** [comment]
@antarmy07 This repo is meant for community related stuff. Please fill issue under `ansible/ansible` repo.
