### ISSUE TITLE
Testing Working Group

### ISSUE THREAD

**Issue by gundalow** [ansible/community#47]
As agreed in Community Working Group 2016-05-25 we are using this to track test related work. It will be the bases for the Test Working Group.

This has grown into a "top level (parent)" ticket that tracks a number of issues. Feel free to add comments for other items you believe may be worth investigating.

# Travis-ci

### a) Travis Plan - gundalow - With Core Team DONE
Quotes for increasing Travis pool are with the Core Team for review

Ansible Core Team have reviewed and decision has been moved to pay for Shippable. We can now run 30 concurrent jobs (compaired to 5 on Travis)

### b) Collect stats on duration and variance - gundalow DONE
data is now being collected WIP
http://buildtimetrend.herokuapp.com/dashboard/ansible/ansible/index.html 

This will allow to see changes in test speed, such as improvements made by this work. It will also allow us to identify if a PR has caused a sudden increase 

# Test Framework

### c) Splitting tests into separate Travis jobs - scrapped gundalow
https://github.com/ansible/ansible/pull/15176 proved we can chop the tests into smaller shorter section. However as Travis only allocates a small number of jobslots per repo we this actually slows down the process.
If we change/move CI frameworks to allow us to better split things up

### g) Remove duplicate Travis jobs 

https://github.com/grosser/travis_dedup

> < Qalthos> would something like https://github.com/grosser/travis_dedup be helpful here? I know I'm in the "push and push and rebase and push" camp, and I                    try to cancel stale builds when it's crowded, but I'm not sure how much of the problem is of that sort
> [20:03] < Joel> time to work on speeding those up :)
> [20:04] <@bcoca> Qalthos: that is rarely the problem, but does help sometimes, the issue is just massive number of daily PRs and fixes to PRs
> [20:04] <@bcoca> ^ non overlapping
> [20:05] < Qalthos> bcoca: that was more or less what I expected
> [20:05] <@jimi|ansible> yeah, it's rare that repeated pushes cause new builds (i do that more than anyone in the community i think)
> [20:07] <@bcoca> its rare we give feedback in same day to same ticket and several iterations at that
> 

# Test Improvements

To find out what tests take the longest `callback_whitelist = profile_tasks` in `ansible.cfg` can be used

### d) Tests installing packages - gundalow DONE

Docker images have been updated. This will save us time till the packages get updated and will have to be installed due to `state=latest`, this shouldn't happen much on older OS images

```
TASK: setup_mysql_db : install mysqldb_test debian dependencies ------- 134.92s
TASK: setup_postgresql_db : install dpkg dependencies for postgresql test -- 39.58s
TASK: test_unarchive : Ensure zip is present to create test archive (apt) -- 29.42s
TASK: test_apache2_module : install apache via apt --------------------- 17.47s
```

The above timings are from Docker 14.04 on SSD, I expect Travis to be slower

This will be fixed as part of @gundalow's other Docker changes, see https://github.com/ansible/ansible/pull/15692

Also there is:
`TASK: test_apt : install netcat build-dep with apt --------------------- 37.90s`

However the purpose if that test is to exercise apt. There may be some improvements to be made

### e) test_git number and size of git checkouts
We do 8 checkouts taking a total of 112 seconds 

We may be able to reduce this a bit

Now that we have sivels docker is running we could move more tests to use that. We should also see of we can reduce the size of the git repos at the same time. 

### f) Investigate other tests

Once devel is green again I'll do a run in Travis with  `callback_whitelist = profile_tasks` in `ansible.cfg` enabled to see if their is anything that's particularly worse on Travis compared to local runs.

### h) test_binary_module - downloads golang and combiles code.

See if we can test using something

  * Quicker to compile
  * Using a language that we already have buildtools in the Docker image

**Comment by bob-smith** [comment]
[21:30]  * mattclay wishes Travis didn't take so long to start build jobs

**Comment by bob-smith** [comment]
3) See if we can speed up Travis's performance when running jobs. 

[13:18] <@jimi|ansible> F/OSS actually gets a pretty good setup, it just depends on availability, but we often get more workers than the paid subscriptions would
[13:18] <@jimi|ansible> but when 3-4 PRs come in at once they back up because it still takes 10-20 for each one to go through, so that limits us to 3-6 commits per hour


"To speed up a test suite, you can break it up into several parts using Travis CI’s build matrix feature.

Say you want to split up your unit tests and your integration tests into two different build jobs. They’ll run in parallel and fully utilize the available build capacity for your account."

Looks like the unit tests take 10 minutes to run. 

We could maybe split that into multiple blocks.

**Comment by gregdek** [comment]
Agreed that @bob-smith will dig in with the folks at Travis to get more data about the nature of the problem.

**Comment by gregdek** [comment]
Will check in again on 28 march

**Comment by bob-smith** [comment]
May need to look at apt/yum proxy

**Comment by bob-smith** [comment]
It was agreed that although https://github.com/ansible/ansible/pull/15176 was interesting data point it wasn't the way forward.

As per discussion on Wed 30th April, the general agreement was

  * It doesn't matter (as much) how long a run take, 
  * It does matter how long it takes a Travis job to start


Currently with the version of Travis we have we can only have 4 (sub?)jobs running at once. This means we quickly end up with a backlog.

I'll contact Travis and see if they have any statistics to show how busy Travis is for our three repos.

There was some discussion (@jimi-c) about having a second Jenkins instance so that every PR can be run as soon as it comes in, and every sub-job in parallel.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/15708 enables http://buildtimetrend.github.io/ on ansible/ansible, which a single line, gives us a load of extra data. I'd hope that with some analysis I can find some ways to improve the performance.

This should allow us to see if a particular change or Operating System has a sudden increase in runtime

Once the next few builds start happening we should start seeing data at http://buildtimetrend.herokuapp.com/dashboard/ansible/ansible/index.html

There are two PRs WIP to add 16.04 and OpenSUSE

https://github.com/ansible/ansible/issues/15704

https://github.com/ansible/ansible/issues/15650

**Comment by gundalow** [comment]
Travis queue load can be seen here https://www.traviscistatus.com/#week

**Comment by robinro** [comment]
another suggestion for speeding up travis: The `test_git` role clone several external repositories, some of them quite sizeable. 2 or 3 external clones should be enough, the rest could be local copies, which would safe a lot of time

**Comment by robinro** [comment]
in general I would try to minimize external dependencies of the tests, eiither move those repos to some ansible-* namespace or make them local

**Comment by robinro** [comment]
the same is true for some of the http tests, which often fail because they call (unreliable) external urls

**Comment by gundalow** [comment]
Some excellent ideas,  I haven't looked into the individual test durations yet. I know about external http,but I didn't know about git repos sizes. I'll get that sorted.

**Comment by robinro** [comment]
I did a run of the testsuite in the docker14.04 container with the plugin profile_tasks enabled. The machine has really poor io, so this might be off. Attached the output. Maybe someone can parse it and make nice plots?

Short Summary (in minutes:seconds):
Total time: 19:50
test_subversion: 0:30
test_git: 3:40
test_unarchive: 0:50
test_apt: 3:00
test_apt_repository: 2:30
test_postgresql*: 1:15
test_mysql*: 2:00
test_apache2_module (installs apache, should probably be moved to the dockerfile as well): 0:45

So the number of tests to clean up and make fast is rather small. Use smaller repos/packages/testdatasets for the tests, cache/reuse more of them locally.

**Comment by robinro** [comment]
This also explains why the discussion comes up now, test_git grew a lot lately...

**Comment by gundalow** [comment]
@robinro I'l update the docker images to have apache now (I've got a PR in flight for them at the moment, so I'll add it to that and notify the people working on the new images for 16.04 and OpenSUSE)

So it easier to track what the issues are I'll edit the ticket description to track the specific actions (which I'll assign to myself)

**Comment by gundalow** [comment]
@robinro is this the plugin you used https://github.com/jlafon/ansible-profile?

**Comment by gundalow** [comment]
On a high spec laptop I get

TASK: test_unarchive : Ensure zip is present to create test archive (apt) -- 29.42s
TASK: setup_mysql_db : install mysqldb_test debian dependencies ------- 134.92s
TASK: test_apache2_module : install apache via apt --------------------- 17.47s

Travis will no doubt be slower. I'll get the above added into the Docker images. That's a saving of at least three minutes, less the few seconds for the increased docker image that will need to be transfered.

**Comment by robinro** [comment]
the plugin is part of ansible already, just add `callback_whitelist = profile_tasks` in ansible.cfg to activate it

**Comment by gundalow** [comment]
Travis responded, with very scary statistics. No wonder we often see stuff getting queued up


> We don't have extended per-repo statistics about readily available but I did some analysis for the whole Ansible organization based on your usage in the last 15 days. You can have a look at the results in the following spreadsheet:
> 
> https://docs.google.com/spreadsheets/d/1VzUPNN_KseqySj5CFRUjU1okgXQN6he57ZHrOwyQRGc/edit?usp=sharing
> 
> In brief, each line shows a line from our logs indicating the number of queued builds at the specified time. When you see a gap in the listed times, it means there wasn't a queued build at that time.
> 
> Here are the basic statistics I could gather from the data of the last 15 days (copied from the spreadsheet):
> 
> Max: 245 queued builds
> Min: 1 queued build
> Average: 67.94 queued builds
> Mode: 6 queued builds
> Median: 44 queued builds

**Comment by gregdek** [comment]
IT LIVES

https://github.com/ansible/community/issues/114
