### ISSUE TITLE
Public Ansible Project Meeting Agenda - Jul 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#475]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by agowa338** [comment]
Support omit within lists [#58587](https://github.com/ansible/ansible/issues/58587)

**Comment by bcoca** [comment]
- [ ] Conflicting doc standards, some defaults are required present while others are required to be omitted.

**Comment by bcoca** [comment]
Meeting ended Tue Jul  2 20:09:39 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-02/core_public_irc_meeting.2019-07-02-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-02/core_public_irc_meeting.2019-07-02-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-02/core_public_irc_meeting.2019-07-02-19.01.log.html

**Comment by ShachafGoldstein** [comment]
ansible/ansible#53402

**Comment by tchernomax** [comment]
- [ ] combine filter: fine list handling (option a) #58798
- [ ] combine filter: fine list handling (option b) #57894

**Comment by bcoca** [comment]
Meeting ended Tue Jul  9 19:50:08 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-09/ansible_core_irc_plublic_meeting.2019-07-09-19.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-09/ansible_core_irc_plublic_meeting.2019-07-09-19.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-09/ansible_core_irc_plublic_meeting.2019-07-09-19.04.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Jul 16 19:59:56 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-16/ansible_core_public_irc_meeting.2019-07-16-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-16/ansible_core_public_irc_meeting.2019-07-16-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-16/ansible_core_public_irc_meeting.2019-07-16-19.00.log.html

**Comment by basos9** [comment]
- [ ] Discuss approval of check mode markers feature https://github.com/ansible/ansible/pull/49432 (nick: zer0_her0)

**Comment by rmahique** [comment]
Discuss approval of 'remount' option for mount module  https://github.com/ansible/ansible/pull/52649 (nick: rmahique)

**Comment by bcoca** [comment]
http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-18/ansible_core_public_irc_meeting.2019-07-18-15.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-18/ansible_core_public_irc_meeting.2019-07-18-15.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-18/ansible_core_public_irc_meeting.2019-07-18-15.05.log.html

**Comment by bcoca** [comment]
- [ ] https://github.com/ansible/ansible/pull/58646, previous vote tied check changes to always display type (which makes `type: string` the default), concerns were brought up that the display will now show 'incorrect types explicitly' vs  the current 'incorrect implicit type'. Want vote to separate check changes from display changes to allow correcting underlying modules between applying both.

**Comment by bcoca** [comment]
Meeting ended Tue Jul 23 19:32:56 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-23/ansible_core_public_irc_meeting.2019-07-23-19.12.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-23/ansible_core_public_irc_meeting.2019-07-23-19.12.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-23/ansible_core_public_irc_meeting.2019-07-23-19.12.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Jul 25 15:13:57 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-25/ansible_core_public_irc_meeting.2019-07-25-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-25/ansible_core_public_irc_meeting.2019-07-25-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-25/ansible_core_public_irc_meeting.2019-07-25-15.00.log.html

^ nothing happened, but keeping logs to demonstrate that statement

**Comment by bcoca** [comment]
crickets

Meeting ended Tue Jul 30 19:11:43 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-30/ansible_core_public_irc_meeting.2019-07-30-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-07-30/ansible_core_public_irc_meeting.2019-07-30-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-07-30/ansible_core_public_irc_meeting.2019-07-30-19.00.log.html
