### ISSUE TITLE
Security Automation Community Meeting Agenda - Oct 2019

### ISSUE THREAD

**Issue by maxamillion** [ansible/community#491]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

For other ongoing discussion around Security Automation, please visit the #ansible-security irc channel on freenode.

**Comment by jamescassell** [comment]
Maybe title should include Security WG?

**Comment by justjais** [comment]
Closing this as we have new issue (ref: https://github.com/ansible/community/issues/510) for tracking Security WG meeting agenda
