### ISSUE TITLE
Grafana Working group

### ISSUE THREAD

**Issue by rrey** [ansible/community#494]
WORKING GROUP NAME:    GRAFANA

WORKING GROUP PURPOSE:
Create an effort for writing and maintaining Grafana related modules and plugins.

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
IRC: rrey GitHub: @rrey 
GitHub: @Seuf

**Comment by seuf** [comment]
Hi !
Yes, why not :)
But i'm not doing as much ansible as I was before (when I've developed grafana ansible modules). 
Not sure if I will have the time to help you very much.. (It's already difficult to find time to review PR on existing grafana modules..)

**Comment by rrey** [comment]
@seuf do you have an IRC login ?

**Comment by seuf** [comment]
IRC ? I'm not on IRC since a few years.

**Comment by gundalow** [comment]
IRC is useful to chat, though not required.

All open Grafana issues and PRs: https://github.com/ansible/ansible/labels/grafana

I'll get the working group

**Comment by gundalow** [comment]
pinboard for discussion: https://github.com/ansible/community/issues/498
Wiki: https://github.com/ansible/community/wiki/Grafana (which anyone has edit powers on.

Thanks for this!
