### ISSUE TITLE
Public Ansible Project Meeting Agenda - October 2019

### ISSUE THREAD

**Issue by samdoran** [ansible/community#495]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by samdoran** [comment]
(moved from #486)
@jamescassell
- [x] https://github.com/ansible/ansible/pull/59958
- [x] I was removed from ansible-lockdown repo because "You were removed from Ansible organization because you do not have two-factor authentication enabled." I've since enable 2FA.  Please re-add me to ansible-lockdown repo. (also, would be good to send a notice to folks who will be removed ahead of time, and/or auto re-add once they've enabled 2FA.)
- [ ] dict filter https://github.com/ansible/ansible/pull/53488

**Comment by samdoran** [comment]
Meeting ended Tue Oct  1 20:04:36 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
16:04 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-01/ansible_core_irc_meeting_https:github.comansiblecommunityissues486.2019-10-01-19.15.html
16:04 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-01/ansible_core_irc_meeting_https:github.comansiblecommunityissues486.2019-10-01-19.15.txt
16:04 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-01/ansible_core_irc_meeting_https:github.comansiblecommunityissues486.2019-10-01-19.15.log.html

**Comment by jillr** [comment]
Meeting ended Tue Oct  8 19:18:58 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-08/ansible_core_irc_public_meeting.2019-10-08-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-08/ansible_core_irc_public_meeting.2019-10-08-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-08/ansible_core_irc_public_meeting.2019-10-08-19.02.log.html

**Comment by s-hertel** [comment]
Meeting ended Thu Oct 10 15:34:39 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:35 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-10/ansible_core_irc_public_meeting.2019-10-10-15.21.html
11:35 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-10/ansible_core_irc_public_meeting.2019-10-10-15.21.txt
11:35 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-10/ansible_core_irc_public_meeting.2019-10-10-15.21.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#63411: validate `contains:` in module return values

**Comment by jillr** [comment]
Meeting ended Tue Oct 15 19:12:54 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot.
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-15/ansible_core_irc_public_meeting.2019-10-15-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-15/ansible_core_irc_public_meeting.2019-10-15-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-15/ansible_core_irc_public_meeting.2019-10-15-19.01.log.html

**Comment by jillr** [comment]
Meeting ended Tue Oct 22 19:11:04 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot 
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-22/ansible_core_irc_public_meeting.2019-10-22-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-22/ansible_core_irc_public_meeting.2019-10-22-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-22/ansible_core_irc_public_meeting.2019-10-22-19.02.log.html

**Comment by jillr** [comment]
Meeting ended Tue Oct 29 19:10:52 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-29/ansible_core_irc_public_meeting.2019-10-29-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-29/ansible_core_irc_public_meeting.2019-10-29-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-29/ansible_core_irc_public_meeting.2019-10-29-19.01.log.html

**Comment by samdoran** [comment]
Meeting ended Thu Oct 31 15:30:50 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:30 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues495.2019-10-31-15.15.html
11:30 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-10-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues495.2019-10-31-15.15.txt
11:30 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-10-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues495.2019-10-31-15.15.log.html

**Comment by drybjed** [comment]
### Concensus regarding a custom `params` option in LDAP modules

The existing `ldap_entry` module has a `params` option which lets Ansible users override any of the module parameters via a YAML dictionary. I included the same `params` option for feature parity in the [proposed `ldap_attrs` Ansible module](https://github.com/ansible/ansible/pull/62701), however @felixfontein [brought up some issues with its implementation](https://github.com/ansible/ansible/pull/62701#discussion_r326883651).

What would be the correct way to solve this? I think that because the `ldap_entry` feature is already used, `ldap_attrs` module could be merged in Ansible 2.10 and then an improved solution could be developed for both modules. An alternative would be to change how `ldap_entry` module works first, so that the `ldap_attrs` module can then implement the same solution before merging.

I'll be available on the `#ansible-meeting` IRC channel on Tuesday 5th at the planned time to discuss this issue further.

**Comment by sivel** [comment]
`TaskExecutor` unsafe loop behavior change:

https://github.com/ansible/ansible/issues/64169
https://github.com/ansible/ansible/issues/64379
