### ISSUE TITLE
Promote Ansible Best Tools

### ISSUE THREAD

**Issue by gregdek** [ansible/community#5]
At the contributor summit, it was widely agreed that there are many great tools for helping with Ansible that are not "part of" Ansible. We want a way to endorse and promote these tools.
- https://ansible.sivel.net/pr/byfile.html
- https://github.com/willthames/ansible-lint
- https://github.com/sivel/ansible-testing (ansible-validate-modules)

(EDIT: gundalow added links, feel free to edit comment0 to add items to the list)

**Comment by ksatirli** [comment]
I'm curious; has the upstream position regarding Ansible Lint changed? 

Remembering the [initial reaction|https://groups.google.com/d/msg/ansible-project/AlfMYo5RzIM/LJOWhxgL6G8J] on Ansible Lint, there was feedback given that 

Please note: I like the idea of a linter a lot; I don't find languages that have a linter available to be overly complicated _by definition_, so more recognition for `ansible-lint` is a great thing, to me!

**Comment by gregdek** [comment]
In discussion about this issue at the contributor summit, we came to the
conclusion that it's an extremely effective tool that is best managed
independently, but given more visibility in the Ansible community. That's
in large part what this issue is about.

On Fri, Feb 26, 2016 at 6:06 AM, Kerim Satirli <notifications@github.com>
wrote:

> I'm curious; has the upstream position regarding Ansible Lint changed?
>
> Remembering the [initial reaction|
> https://groups.google.com/d/msg/ansible-project/AlfMYo5RzIM/LJOWhxgL6G8J]
> on Ansible Lint, there was feedback given that
>
> Please note: I like the idea of a linter a lot; I don't find languages
> that have a linter available to be overly complicated *by definition*, so
> more recognition for ansible-lint is a great thing, to me!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ansible/community/issues/5#issuecomment-189223017>.
>



-- 
Greg DeKoenigsberg
Ansible Community Guy

**Comment by gundalow** [comment]
@willthames has created ansible-review http://willthames.github.io/2016/06/28/announcing-ansible-review.html

**Comment by gundalow** [comment]
https://github.com/ansible/ansible-doctor

**Comment by jctanner** [comment]
https://github.com/jctanner/ansible-tools

**Comment by jctanner** [comment]
https://github.com/seantis/suitable

**Comment by thaumos** [comment]
So do we like the idea of creating a page on docs for this?

**Comment by gundalow** [comment]
@dharmabumstead Do you have a suggestion of what this page should be called and what should link to it?

**Comment by gundalow** [comment]
https://github.com/nickjj/ansigenome though may currently be Ansible v1 only

**Comment by gregdek** [comment]
We still don't have what I would call a "good" answer for this. 

Option 1: put it in the developer's guide.
Option 2: put it on some other page.

Either way, my concerns are:

a. How do we keep this content current?
b. How do we get people to use it?

It's important, though. Turns out we've got a bunch of customers using ansible-lint. These are important tools in our ecosystem.

**Comment by gregdek** [comment]
@gundalow maybe you should just make this part of the developer guide and own it?

**Comment by dharmabumstead** [comment]
The developer guide might be problematic because not all of the tools appear to be targeted at the module/plugin/etc developers that the dev guide is aimed at.

**Comment by dharmabumstead** [comment]
How about we create an appendix that's visible in the main TOC that we call "Community Supported Tools"?

**Comment by gundalow** [comment]
-1 to `dev_guide`, as Scott says this is more than just developers


I wonder if this should go under the new community section on `docs.ansible.com` perhaps

`docs/docsite/rst/community/other_tools_and_programs.rst`

Welcome a better suggestion than `other_tools_and_programs.rst`

**Comment by robynbergeron** [comment]
Labelling for discussion in Community WG meeting today.

**Comment by gregdek** [comment]
Make sure to add this: https://github.com/jdauphant/awesome-ansible

**Comment by gregdek** [comment]
Closed by https://github.com/ansible/ansible/pull/28138
