### ISSUE TITLE
Public Ansible Project Meeting Agenda - November 2019

### ISSUE THREAD

**Issue by jillr** [ansible/community#500]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by jillr** [comment]
Opem items remaining from Oct issue:

- [ ] https://github.com/ansible/community/issues/495#issuecomment-549267833 Concensus regarding a custom params option in LDAP modules
- [ ] https://github.com/ansible/community/issues/495#issuecomment-549382052 TaskExecutor unsafe loop behavior change

**Comment by samdoran** [comment]
Meeting ended Tue Nov  5 19:47:38 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
14:47 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-05/ansible_core_meeting_https:github.comansiblecommunityissues500.2019-11-05-19.02.html
14:47 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-11-05/ansible_core_meeting_https:github.comansiblecommunityissues500.2019-11-05-19.02.txt
14:47 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-05/ansible_core_meeting_https:github.comansiblecommunityissues500.2019-11-05-19.02.log.html

**Comment by samdoran** [comment]
Meeting ended Tue Nov 12 20:03:06 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
15:03 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-12/ansible_core_public_irc_meeting.2019-11-12-19.12.html
15:03 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-11-12/ansible_core_public_irc_meeting.2019-11-12-19.12.txt
15:03 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-12/ansible_core_public_irc_meeting.2019-11-12-19.12.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#65014

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#59060

**Comment by Miouge1** [comment]
- [ ] https://github.com/ansible/ansible/pull/55989
- [ ] https://github.com/ansible/ansible/pull/55965

My IRC nick: miouge

**Comment by jillr** [comment]
Low attendance, 2019-11-19 cancelled.
Meeting ended Tue Nov 19 19:13:34 2019 UTC. Information about MeetBot at  http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-19/ansible_core_public_irc_meeting.2019-11-19-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-11-19/ansible_core_public_irc_meeting.2019-11-19-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-19/ansible_core_public_irc_meeting.2019-11-19-19.01.log.html

**Comment by bidord** [comment]
Hi, I'd like to discuss the following PR:
https://github.com/ansible/ansible/pull/64959

**Comment by samdoran** [comment]
Meeting ended Thu Nov 21 16:03:30 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:03 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-21/ansible_core_public_irc_meeting_https:github.comansibleansibleissues64564.2019-11-21-15.09.html
11:03 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-11-21/ansible_core_public_irc_meeting_https:github.comansibleansibleissues64564.2019-11-21-15.09.txt
11:03 Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-11-21/ansible_core_public_irc_meeting_https:github.comansibleansibleissues64564.2019-11-21-15.09.log.html

**Comment by jillr** [comment]
Today's meeting and the one on 2019-11-28 are cancelled due to US holiday/low attendance.
