### ISSUE TITLE
vmware AttributeError: 'NoneType' object has no attribute 'template' when creating vm is in progress

### ISSUE THREAD

**Issue by lxuzhang** [ansible/community#502]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project .  

When the vm creation is in progress I try to query the existing vm and template information whenever by using pyVmomi vim or vmware_guest_facts in playbook, I get below error:

AttributeError: 'NoneType' object has no attribute 'template'

However if no vm creation is in progress, both code and vmware_guest_facts work fine when I query the vm and template information. If you could point the right direction I could investigate then will be highly appreciated.

Detailed information: https://github.com/ansible/ansible/issues/64590

**Comment by mkrizek** [comment]
Closing in favor of https://github.com/ansible/ansible/issues/64590.
