### ISSUE TITLE
Maintenance of ansible-lint project

### ISSUE THREAD

**Issue by ssbarnea** [ansible/community#506]
Since [ansible-lint](https://github.com/ansible/ansible-lint) was adopted by ansible organization it did not receive a lot of attention, there were always other more important priorities. Open PRs from users were lingering for very long time, CI went broken and there was not a lot of active work on making it green. 

I was kinda lucky to know to ping @webknjaz on irc and get a number of hotfixes reviewed and merged but that was not the average contributor experience (i would ignore raised bugs, PRs are those that really matter here as they sign that user already spend some effort trying to address an issue)

As I do care a lot about the project and because it became a critical part of the projects I am working with, I want to assure that we do our best to avoid further deterioriation of the codebase. 

The reality is that any piece of code rots and active maintenance needs to be performed to keep it relevant (newer platforms used by users, newer version of dependencies, newer ansible/python,...).  

So far @webknjaz helped with such tasks in his spare time but at the same time he is a single person and I am sure he cannot be 24/7 available to fix any breakage, review, merge and release patches. The project needs a **team of stewards** (or maintainers), so the load is spread across them and even more important: they can cross review their patches. With only one maintainer there is a risk of self-reviews, biased decisions, delays or burn-out. This is why I think we need at least 3 people, if one is in vacation/unavailable we can expect that one of the others should be available to help with a review and a release.

Another aspect that needs to be addressed is releases because I seen often seen people asking in on irc (i monitor ansilble-lint keyword) about bugs that were fixed on master weeks or months ago. This is because no release was made February 2019, which is a very long time in Ansible ecosystem. As far as I understood from @webknjaz he is not empowered to make releases and @awcrosby needs to be consulted on that.

Can we please enlarge the number of core contributors on ansible-lint in order to assure its future development? I am sure that there are lots of users that do have an interest around ansible-lint.

**Comment by willthames** [comment]
This has my full support (for what that's worth) @ssbarnea 

cc'ing @tima as he had a lot to do with the transfer of the project so hopefully he can help here.

**Comment by gundalow** [comment]
Thank you for raising this.

**Comment by ssbarnea** [comment]
Merging https://github.com/ansible/ansible-lint/pull/633 would be a good start because that is blocking CI from reporting green on other patches. Once that merges one core should close/reopen the recent PRs that were affected by it.
