### ISSUE TITLE
Security Working Group Meeting Agenda - Dec 2019 - Jan 2020

### ISSUE THREAD

**Issue by justjais** [ansible/community#510]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/tree/master/group-security for the schedule

Security Working Group: https://github.com/ansible/community/tree/master/group-network

#ansible-security on Freenode IRC

**Comment by Akasurde** [comment]
* Meeting ended Mon Dec  9 15:30:25 2019 UTC
* Minutes: https://meetbot.fedoraproject.org/ansible-security/2019-12-09/ansible_security_working_group.2019-12-09-15.01.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2019-12-09/ansible_security_working_group.2019-12-09-15.01.txt
* Log: https://meetbot.fedoraproject.org/ansible-security/2019-12-09/ansible_security_working_group.2019-12-09-15.01.log.html

**Comment by maxamillion** [comment]
Meeting ended Mon Dec 16 15:28:15 2019 UTC.
* Minutes: https://meetbot.fedoraproject.org/ansible-security/2019-12-16/ansible_security_working_group.2019-12-16-15.00.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2019-12-16/ansible_security_working_group.2019-12-16-15.00.txt
*  Log: https://meetbot.fedoraproject.org/ansible-security/2019-12-16/ansible_security_working_group.2019-12-16-15.00.log.html

**Comment by Akasurde** [comment]
pfsense modules needs attention - https://github.com/ansible/ansible/pull/50390

**Comment by maxamillion** [comment]
Meeting ended Mon Jan 13 15:26:37 2020 UTC.

* Minutes: https://meetbot.fedoraproject.org/ansible-security/2020-01-13/ansible_security_automation_working_group.2020-01-13-15.03.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2020-01-13/ansible_security_automation_working_group.2020-01-13-15.03.txt
* Log: https://meetbot.fedoraproject.org/ansible-security/2020-01-13/ansible_security_automation_working_group.2020-01-13-15.03.log.html

**Comment by justjais** [comment]
Meeting ended Mon Jan 20 15:30:20 2020 UTC. 
-  Minutes: https://meetbot.fedoraproject.org/ansible-security/2020-01-20/ansible_security_automation_working_group.2020-01-20-15.01.html
-  Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2020-01-20/ansible_security_automation_working_group.2020-01-20-15.01.txt
-  Log: https://meetbot.fedoraproject.org/ansible-security/2020-01-20/ansible_security_automation_working_group.2020-01-20-15.01.log.html

**Comment by justjais** [comment]
Meeting ended Mon Jan 27 15:28:36 2020 UTC. 

-  Minutes: https://meetbot.fedoraproject.org/ansible-security/2020-01-27/ansible_security_automation_working_group.2020-01-27-15.00.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2020-01-27/ansible_security_automation_working_group.2020-01-27-15.00.txt
-  Log: https://meetbot.fedoraproject.org/ansible-security/2020-01-27/ansible_security_automation_working_group.2020-01-27-15.00.log.html

**Comment by maxamillion** [comment]
Moving to Feb 2020 tracker -> https://github.com/ansible/community/issues/520
