### ISSUE TITLE
Setting loop in Ansible for doing vMotion of multiple VMs on different ESXi host

### ISSUE THREAD

**Issue by yogesh918** [ansible/community#514]
Hi All,

I want to create a playbook which will do vMotion of multiple VMs same time, The issue here is while doing vMotion I want to put the different VMs on different ESXi Host
Eg. I have VM1, VM2, VM3 and I want to vMotion VM1 on ESXi1, VM2 on ESXi2 and so on.

Could you please help in this, I am doing some search on this but no luck.

**Comment by sivel** [comment]
This repository is not intended for support.

Instead, please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
