### ISSUE TITLE
Kubernetes Pinboard

### ISSUE THREAD

**Issue by geerlingguy** [ansible/community#515]
[![kubernetes issues](https://img.shields.io/github/issues/ansible-collections/kubernetes.svg?label=issues)](https://github.com/ansible-collections/kubernetes/issues) [![Github kubernetes PRs](https://img.shields.io/github/issues-pr/ansible-collections/kubernetes.svg?label=pull+requests)](https://github.com/ansible-collections/kubernetes/pulls) [![Kubernetes pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/515.svg?label=pinboard+update)](https://github.com/ansible/community/issues/515)

This issue is a call for potential interested parties to subscribe to updates from the [Kubernetes Working Group](https://github.com/ansible/community/wiki/Kubernetes). Working Group members can:

* test, review and add shipits to existing Kubernetes PRs
* work collectively on the Kubernetes/OpenShift roadmap
* provide a single-point-of-contact for interested Kubernetes contributors
* collaborate on the Kubernetes Wiki
* have a $team_kubernetes in BOTMETA.yml for auto-notifying team members
* implement auto-labeling kubernetes issues and PRs

Please see the [Kubernetes Working Group](https://github.com/ansible/community/wiki/Kubernetes) page for more details about Ansible's Kubernetes/OpenShift integration and roadmap.

**Comment by geerlingguy** [comment]
@gundalow - Two quick questions:

  1. How can I get a 'pinboard update' badge like you have on #498?
  2. Can I get two labels added, 'Kubernetes' and 'pinboard'?

**Comment by geerlingguy** [comment]
A few open action items:

  - [ ] Currently there are a number of `k8s` and `kubernetes` sections in [BOTMETA.yml](https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml), but no `team_kubernetes` macro. Do we want to merge lists into a macro for all the k8s-related components?
  - [ ] I'm working on a first draft of the [Kubernetes Working Group Wiki page](https://github.com/ansible/community/wiki/Kubernetes). Please review!
  - [ ] We have not yet decided where new work (starting soon™, not necessarily right now or by Ansible 2.10) will go—should we still go straight to Ansible core? Should we go to a new community 'kitchen sink' repository (I believe most non-core modules will eventually be put there)? Should we pick up the [ansible-kubernetes-modules](https://github.com/ansible/ansible-kubernetes-modules) repository and develop a new collection there?
  - [ ] Should we try to meet (maybe via IRC) monthly? Quarterly?
  - [ ] Does someone want to work on updating the [Kubernetes and OpenShift Guide](https://docs.ansible.com/ansible/latest/scenario_guides/guide_kubernetes.html), which is a little outdated currently?

**Comment by gundalow** [comment]
@geerlingguy labels added

**Comment by geerlingguy** [comment]
The Kubernetes Collection for Ansible is out, and version 0.9.0 includes the content that was in Ansible as of 2.9. There are already some new modules being merged in which will be in the 1.0.0 release.

I wrote a blog post more formally introducing the collection: [The Kubernetes Collection for Ansible](https://www.jeffgeerling.com/blog/2020/kubernetes-collection-ansible).

**Comment by Akasurde** [comment]
Hey folks, can someone please review this https://github.com/ansible/ansible/pull/62450

**Comment by geerlingguy** [comment]
FYI, today I renamed the Kubernetes collection repository on GitHub from https://github.com/ansible-collections/kubernetes to https://github.com/ansible-collections/community.kubernetes

If you have a fork or clone, those should still work fine, as will downloads from Ansible Galaxy, it's mostly a backend change to conform to the pattern of other community collections—see https://github.com/ansible-collections/kubernetes/issues/76 for more details.

Also, we are very close to merging this PR (https://github.com/ansible-collections/kubernetes/pull/61) which adds new Helm modules to the Kubernetes collection; these will be available in an upcoming 0.11.0 release.

**Comment by geerlingguy** [comment]
Today, following the [precedent](https://github.com/ansible-collections/overview/issues/83) in the other Ansible Collection repositories, we switched the default branch for the `community.kubernetes` collection from `master` to `main`.

If you have an active fork of the repository, please make sure to update your own branches. Instructions for doing so can be found [in this comment](https://github.com/ansible-collections/community.kubernetes/issues/148#issuecomment-660124657).

**Comment by geerlingguy** [comment]
For anyone using the `community.kubernetes` collection with OpenShift or OKD clusters, please note that we are working on moving the few OpenShift-specific features in the kubernetes collection into a new, dedicated `community.okd` collection.

See the reasoning for and motivation behind this decision here: [Proposal: Establish a separate collection for OpenShift (OKD) Content](https://github.com/ansible-collections/community.kubernetes/issues/175).

The new collection is already under active development here: https://github.com/ansible-collections/community.okd

An initial version (0.1.0) will be released with the OpenShift-specific content that was in the `community.kubernetes` collection, as well as the `oc` connection plugin that is currently in `community.general`. A future 1.0.0 release may be included in Ansible's community distribution and will include more functionality specific to OpenShift clusters.

**Comment by samccann** [comment]
@geerlingguy - we will be moving most of the content of ansible/community to the ansible-community repo. Are you still using this issue or should I close it out?

**Comment by geerlingguy** [comment]
Closing it is fine! Thanks :)
