### ISSUE TITLE
How to get next available ip in DHCP Range

### ISSUE THREAD

**Issue by Bahu2016** [ansible/community#518]
Hello,

Greetings,

Question: how to get next available ip in DHCP range.

I have subnet 167.93.24.0/25 in this subnet, i created ipv4 DHCP Range (167,93,24.89-168.94.24.123). how to get ip from DHCP Range. Is that possible with the below module? Let me know which ansible module will i need to use.

And i want to reserve the IP for future use.

#- name: Add host record over DHCP next available ip

nios_host_record:

Sorry if i posted in wrong group, please direct me into correct group if am wrong.

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
