### ISSUE TITLE
Security Working Group Meeting Agenda - Feb 2020

### ISSUE THREAD

**Issue by maxamillion** [ansible/community#520]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/tree/master/group-security for the schedule

Security Working Group: https://github.com/ansible/community/tree/master/group-network

#ansible-security on Freenode IRC

**Comment by maxamillion** [comment]
Meeting ended Mon Feb  3 15:44:10 2020 UTC

* Minutes: https://meetbot.fedoraproject.org/ansible-security/2020-02-03/ansible_security_automation_working_group.2020-02-03-15.02.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2020-02-03/ansible_security_automation_working_group.2020-02-03-15.02.txt
09:44:11 
* Log: https://meetbot.fedoraproject.org/ansible-security/2020-02-03/ansible_security_automation_working_group.2020-02-03-15.02.log.html

**Comment by justjais** [comment]
Meeting ended Mon Feb 17 15:30:06 2020 UTC.

- 9:00 PM Minutes: https://meetbot.fedoraproject.org/ansible-security/2020-02-17/ansible_security_working_group.2020-02-17-15.08.html
- 9:00 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-security/2020-02-17/ansible_security_working_group.2020-02-17-15.08.txt
- 9:00 PM Log: https://meetbot.fedoraproject.org/ansible-security/2020-02-17/ansible_security_working_group.2020-02-17-15.08.log.html

**Comment by justjais** [comment]
Closing and opening new one for March'20: #530 530
