### ISSUE TITLE
Where do people discuss Ansible

### ISSUE THREAD

**Issue by gundalow** [ansible/community#525]
Previously we've been focusing on Freenode and the Google Groups.

While both of these have good people in, we feel we are only talking to a subset of Ansible users and Contributors

We need to find all the other placed that people talk about Ansible and promote them,

For example [r/ansible](https://www.reddit.com/r/ansible/) on Reddit is very active

Whatever we find should be linked from https://docs.ansible.com/ansible/devel/community/communication.html making it clear which are external places that we (Ansible) don't control.

## Places
* IRC
* google-groups (announce, project, devel)
* Slack: [Ansible Network](https://join.slack.com/t/ansiblenetwork/shared_invite/zt-74pwlyv8-i71yzR35fLMXfkeJmaddCw)
* Slack: Network to code
* Gitter: https://gitter.im/ansible/ansible
* reddit r/ansible 
* bullhorn

**Comment by daemenseth** [comment]
Irc is not always the easy tool for communicating.
My frustrating from IRC is that I cannot search back if a topic or issue already discussed.
I think the ansible community can grow if there is a easier platform the communicate

**Comment by gundalow** [comment]
gitter: https://gitter.im/ansible/ansible
matrix:  #ansible:matrix.org

**Comment by jillr** [comment]
Everything I was going to link is already on https://devopsnewsletters.com/ (thanks @chris-short!)

**Comment by humadmin** [comment]
guys, need help, I am running command module in ansible playbook. this command is running remote server, however playbook is getting tuck at command task. 

The command is to just start one process of tcpdump. Please advise if anyone has went through this challenge.

**Comment by bmillemathias** [comment]
> guys, need help, I am running command module in ansible playbook. this command is running remote server, however playbook is getting tuck at command task.

Hello

this is not the correct medium for asking support on ansible.
Please go to https://groups.google.com/g/ansible-project for such request.

Best.
