### ISSUE TITLE
Proxmox Working Group

### ISSUE THREAD

**Issue by apple4ever** [ansible/community#527]
WORKING GROUP NAME:   Proxmox

WORKING GROUP PURPOSE:
To review all Proxmox modules

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
Matt Butch- IRC: apple4ver / GitHub: @apple4ever
Karim Boumedhel- GitHub: @karmab
Josha Inglis- @joshainglis

**Comment by apple4ever** [comment]
@karmab @joshainglis @MartinLesser We need two maintainers and love for all of you to join me. Let me know if that's okay and if you have an IRC login. Thanks!

**Comment by gundalow** [comment]
Currently the proxmox modules will go into the `community.general` collection.

**Comment by apple4ever** [comment]
@gundalow Does that impact this request?

**Comment by gundalow** [comment]
No impact and I'm happy for the content to stay in community.general (either short or medium term)

**Comment by MartinLesser** [comment]
Thank you for your offering. But I have no interest.

**Comment by apple4ever** [comment]
Thanks for the update Martin. I removed you.

**Comment by apple4ever** [comment]
Doesn't seem like this is going to happen.

**Comment by blaisep** [comment]
There's a lot of proxmox discussion on the r/homelab sub reddit and I bet
you may get some interest if you bring this up with them.
