### ISSUE TITLE
IRC channel for Kubernetes Working Group?

### ISSUE THREAD

**Issue by geerlingguy** [ansible/community#529]
The [Kubernetes Working Group](https://github.com/ansible/community/wiki/Kubernetes) would like to have an official IRC channel **#ansible-kubernetes** so we can have WG meetings and also have a place to gather for informal discussion outside of GitHub. Is there any official process for kicking off a new IRC channel?

**Comment by geerlingguy** [comment]
cc @gundalow

**Comment by gundalow** [comment]
It lives
Could you please 
1) Update Community wiki
2) Add to https://docs.ansible.com/ansible/devel/community/communication.html

**Comment by geerlingguy** [comment]
@gundalow - Finished:

  - https://github.com/ansible/ansible/pull/68028 for the docs
  - Updated the wiki: https://github.com/ansible/community/wiki/Kubernetes

Thanks for the quick assist! The docs PR will likely take some time to be merged since devel is frozen this month.
