### ISSUE TITLE
telnet issue

### ISSUE THREAD

**Issue by zaldyb2001** [ansible/community#533]
Hi Experts,

I am just new with this one. I am trying to connect using telnet (ssh has no issue) to my IOS devices, but I am getting error when I run my playbook:

---
- name: Telnet do show version for IOS
  hosts: telnet_device
  gather_facts: false
  connection: local

  tasks:
    - name: show version
      telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - show version

Error:
PLAY [Telnet do show version for IOS] ***********************************************************************************************************************

TASK [show version] *****************************************************************************************************************************************
fatal: [telnet_device]: FAILED! => {"changed": true, "msg": "Telnet action failed: telnet connection closed", "output": []}

PLAY RECAP **************************************************************************************************************************************************
telnet_device           : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Any suggestions/comments is much appreciated.

**Comment by felixfontein** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

 - IRC: #ansible on irc.freenode.net
 - mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
