### ISSUE TITLE
Multiple Data Center Names within a single vCenter

### ISSUE THREAD

**Issue by dfoley84** [ansible/community#534]
Hi, I'm currently Trying to Deploy from Template within a  vCenter which it has two Datacenters with the Same name within two different Folder paths:

I'm seen the Issue with unable to find Cluster: 

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unable to find cluster \"CORP-A\""}
Is there a way to Loop untill the Cluster is found  ?

**Comment by Akasurde** [comment]
This repo is used for community-related issues. Please file an issue against https://github.com/ansible-collections/vmware. Thanks,.
