### ISSUE TITLE
sros_command not working with TiMOS-B-19.10.R1 SAR-7705-SR-HM -- HELP ME !!!!

### ISSUE THREAD

**Issue by ddedda** [ansible/community#535]
**OS in my PC**:
   Static hostname: ubuntu
   Icon name: computer-vm
   Chassis: vm
   Machine ID: 1d838c1e31ea4fa4ae17f88f206b983f
    Boot ID: 577109fdb230450c9e31b16e2ce3a32d
    Virtualization: vmware
   Operating System: Ubuntu 20.04 LTS
    Kernel: Linux 5.4.0-28-generic
    Architecture: x86-64

**Ansible Version**:

ansible 2.9.6
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/daniele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
executable location = /usr/bin/ansible
 python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

**My File .yml**

cat prova.yml 
---
- hosts: nokia
  gather_facts: false
  connection: local
  vars:
    cli:
      host: “{{ inventory_hostname }}”
      username: admin
      password: admin

  tasks:
  - name: run show version on remote devices
    sros_command:
      commands: 
             - show version
      provider: "{{ cli }}" 
    register: results

  - debug: msg="{{ results }}"

*******ISSUE**********

Daniele@ubuntu:~/Scrivania/ansible/7705$ ansible-playbook -i inventory.yml prova.yml -vvvv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/daniele/Scrivania/ansible/7705/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/daniele/Scrivania/ansible/7705/inventory.yml as it did not pass its verify_file() method
Parsed /home/daniele/Scrivania/ansible/7705/inventory.yml inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: prova.yml ******************************************************************************************************************
Positional arguments: prova.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/daniele/Scrivania/ansible/7705/inventory.yml',)
forks: 5
1 plays in prova.yml

PLAY [nokia] *************************************************************************************************************************
META: ran handlers

TASK [run show version on remote devices] ********************************************************************************************
task path: /home/daniele/Scrivania/ansible/7705prova.yml:12
<“ra5062”> using connection plugin network_cli (was local)
<“ra5062”> starting connection from persistent connection plugin
<“ra5062”> local domain socket does not exist, starting it
<“ra5062”> control socket path is /home/daniele/.ansible/pc/43b50428dd
<“ra5062”> local domain socket listeners started successfully
<“ra5062”> unable to load cliconf for network_os sros
<“ra5062”> 
<“ra5062”> local domain socket path is /home/daniele/.ansible/pc/43b50428dd
<“ra5062”> socket_path: /home/daniele/.ansible/pc/43b50428dd
<ra5062> ESTABLISH LOCAL CONNECTION FOR USER: daniele
<ra5062> EXEC /bin/sh -c 'echo ~daniele && sleep 0'
<ra5062> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116 `" && echo ansible-tmp-1588668154.257663-78677595018116="` echo /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116 `" ) && sleep 0'
<ra5062> Attempting python interpreter discovery
<ra5062> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<ra5062> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/network/sros/sros_command.py
<ra5062> PUT /home/daniele/.ansible/tmp/ansible-local-5264te0fqfrz/tmpz2or8__e TO /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116/AnsiballZ_sros_command.py
<ra5062> EXEC /bin/sh -c 'chmod u+x /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116/ /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116/AnsiballZ_sros_command.py && sleep 0'
<ra5062> EXEC /bin/sh -c '/usr/bin/python3 /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116/AnsiballZ_sros_command.py && sleep 0'
<ra5062> EXEC /bin/sh -c 'rm -f -r /home/daniele/.ansible/tmp/ansible-tmp-1588668154.257663-78677595018116/ > /dev/null 2>&1 && sleep 0'
fatal: [ra5062]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show version"
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": {
                "host": "“ra5062”",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": null
        }
    },
    "msg": "Unable to decode JSON from response to exec_command({\"command\": \"show version\", \"prompt\": null, \"answer\": null}). Received 'None'.",
    "rc": 1
}

PLAY RECAP ***************************************************************************************************************************
ra5062                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

**SOLUTION**

### does anyone know the problem and how to solve it? Thanks

**Comment by Akasurde** [comment]
@ddedda This repo is used for community-related issues. Please use https://github.com/ansible-collections/community.network for network specific issue.
