### ISSUE TITLE
Public Ansible Project Meeting Agenda - July 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#543]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by gundalow** [comment]
[`ansible-galaxy collection list` vs site-packages](https://github.com/ansible/ansible/issues/70147)

**Comment by samdoran** [comment]
Meeting ended Thu Jul  2 16:00:24 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-02/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues543.2020-07-02-15.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-07-02/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues543.2020-07-02-15.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-02/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues543.2020-07-02-15.05.log.html

**Comment by apollo13** [comment]
I'd like to put up

- [ ] https://github.com/ansible/proposals/issues/181 (Simplification of galaxy installation workflows)

onto the agenda for the meeting on Tuesday, July 7th. My IRC nick is apollo13

**Comment by bcoca** [comment]
Meeting ended Tue Jul  7 19:59:39 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-07/core_public_irc_meeting.2020-07-07-19.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-07-07/core_public_irc_meeting.2020-07-07-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-07/core_public_irc_meeting.2020-07-07-19.06.log.html

**Comment by tchernomax** [comment]
* [ ] [add state absent/present to action template](https://github.com/ansible/ansible/pull/70724)

**Comment by caleb15** [comment]
https://github.com/ansible/ansible/pull/43128

small PR waiting on reviewer that could be very beneficial

**Comment by bcoca** [comment]
Meeting ended Tue Jul 21 19:53:52 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-21/ansible_core_public_irc_meeting.2020-07-21-19.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-07-21/ansible_core_public_irc_meeting.2020-07-21-19.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-21/ansible_core_public_irc_meeting.2020-07-21-19.04.log.html

**Comment by bcoca** [comment]
no one showed up.

Meeting ended Thu Jul 23 15:10:17 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-23/ansible_core_public_irc_meeting.2020-07-23-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-07-23/ansible_core_public_irc_meeting.2020-07-23-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-23/ansible_core_public_irc_meeting.2020-07-23-15.00.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Jul 28 19:14:25 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-28/ansible_core_public_irc_meeting.2020-07-28-19.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-07-28/ansible_core_public_irc_meeting.2020-07-28-19.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-07-28/ansible_core_public_irc_meeting.2020-07-28-19.03.log.html
