### ISSUE TITLE
I dont think this is the right place for asking questions but I am trying to find the best place to ask them. Specifically towards managing windows boxes. Can some one guide me to a form or a place to get help?

### ISSUE THREAD

**Issue by AlanW5510** [ansible/community#544]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Akasurde** [comment]
Hi @AlanW5510!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
