### ISSUE TITLE
Login Linux server with Challenge Response based authentication using ansible

### ISSUE THREAD

**Issue by akshayrathod1** [ansible/community#545]
Hi,
I want to maintain linux servers with challenge response based authentication. I have no idea how this can be achieved with ansible.
Please help me with any useful document.
**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by bmillemathias** [comment]
Hello,

This is project is not for support but for working on community issue around ansible, so unlikely to be helpful for you.
I think such question should be asked on google group you mentioned.

Best
