### ISSUE TITLE
Decision on new module "wrappers"

### ISSUE THREAD

**Issue by gregdek** [ansible/community#55]
@bcoca asserts that new modules should be more than just wrappers of APIs/CLIs. To be accepted, new modules must add some kind of value. His examples:

"must have added value on top of existing tool, checkmode/change management/detection, options instead of passing existing configs"

If there is broad agreement from the core team that this a requirement, we need to agree to it and document it in our module guidelines.

Thanks @mckerrj for taking this one on.

**Comment by mckerrj** [comment]
OK, the new docs are done.  And the other modules are getting worked on.  So I am FINALLY marking this as done.  Sorry it took so long.
