### ISSUE TITLE
Help First Code Contributors

### ISSUE THREAD

**Issue by imjoseangel** [ansible/community#553]
I think it could be good to help new contributions adding the `beginner` tag to the issues as well as we are doing with the `waiting_on_contributor` tag.

What do you think?

**Comment by Akasurde** [comment]
@imjoseangel @bmillemathias We have newbie pinboard as well - https://github.com/ansible/community/issues/437

Let me know if you are willing to work on something, I can ping you both.

**Comment by imjoseangel** [comment]
@Akasurde  Yes!!

I have a 15 mins track on the DevOps World 2020 and I want to inspire collaboration with this nice project. If we can start from there, to me is perfect!!!

Thank you!!!

**Comment by imjoseangel** [comment]
Closing.  #437 is already managing this request.
