### ISSUE TITLE
Public Ansible Project Meeting Agenda - August 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#554]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by agowa338** [comment]
I'd like to know what the status of #45839 is. It's stalle for 8 Months now and I would like to see mitogen upstream.

**Comment by bcoca** [comment]
Meeting ended Tue Aug  4 19:29:17 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-08-04/ansible_core_public_irc_meeting.2020-08-04-19.09.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-08-04/ansible_core_public_irc_meeting.2020-08-04-19.09.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-08-04/ansible_core_public_irc_meeting.2020-08-04-19.09.log.html
