### ISSUE TITLE
Hacktoberfest meetup 2020

### ISSUE THREAD

**Issue by Akasurde** [ansible/community#555]
Plan for Hacktoberfest online meetup 

https://hacktoberfest.digitalocean.com/eventkit

**Comment by Akasurde** [comment]
cc @gundalow

**Comment by gundalow** [comment]
Excellent idea

I see this year it's all virtual, so makes it a bit easier. I've created a draft event on https://organize.mlh.io/

### Questions
1. Date: This is October, so maybe a few weeks *after* AnsibleFest
2. Timezone: Do we want a large window, maybe with some repeating getting started sessions through the day?

### Promotion

- [ ] Reddit
- [ ] Bullhorn
- [ ] Twitter
- [ ] Collection working Groups
- [ ] AnsibleFest
- [ ] AnsibleFest Contributors Summit

- [ ]

**Comment by cybette** [comment]
Event: https://organize.mlh.io/participants/events/3936-ansible-hacktoberfest-2020-virtual

Etherpad: https://etherpad.opendev.org/p/ansible-hacktoberfest-2020

**Comment by cybette** [comment]
Event completed.
