### ISSUE TITLE
ACI MSO site specific deployments if first deployment -- mso_schema_site_bd_l3out #504 - not resolved

### ISSUE THREAD

**Issue by ajsiroin** [ansible/community#557]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

If I add it manually and then run the script it will work.  If I delete it manually and then add it via Ansible script and it works.  Any new BD not manually added l3out, it will not work.

fatal: [cisco-dc1-mso-1]: FAILED! => {"changed": false, "current": {}, "msg": "Provided BD 'whatever_bd' does not exist. Existing BDs: /schemas/5e2f149c100000c9da37d87b/templates/prod/bds/whatever_bd"}

**Comment by felixfontein** [comment]
Please ask support questions in #ansible on irc.freenode.net, or on the mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by ajsiroin** [comment]
I don’t know what that means???

A.J. Siroin
Network Engineer, Enterprise Technology
aj.siroin@securian.com<mailto:aj.siroin@securian.com>
400 Robert Street North, Mail Stop 9-4653, St. Paul, MN 55101-2098
651-395-1736 (mobile)
[Securian Financial]
Securian Financial Group, Inc.
securian.com
