### ISSUE TITLE
Rename the master branch to main.

### ISSUE THREAD

**Issue by abadger** [ansible/community#558]
We've been working towards renaming master branches in all repositories to main instead.

I'm not sure what the repository for this github project is used for or who the stakeholders are so need to figure that out before migrating it.

I'll put this on the meeting agenda so it gets talked about.

**Comment by felixfontein** [comment]
- There are multiple links from the Ansible docs to the master branch of this repo (grep for `ansible/community/tree/master` and `ansible/community/blob/master` in ansible/ansible's docs/)
- This repo contains three links to itself using master
- The ansibullbot repo contains a link to this repo using master
- The wiki of this repo has links (https://github.com/ansible/community/wiki/Windows:-sprints, https://github.com/ansible/community/wiki/Testing:-progress-tracker)

**Comment by felixfontein** [comment]
@gundalow do you know who is all involved in this repo?

**Comment by gundalow** [comment]
Default branch has been changed (master has been deleted)

GitHub Links for unknown branches will now automatically redirect to the default branch ie
