### ISSUE TITLE
Ansible vmware module add PCI device

### ISSUE THREAD

**Issue by Ravi-Virmani** [ansible/community#559]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support** 
Ansible vmware module (vmware_guest) does not have parameters to add PCI device in virtual machine. While adding parameters with any name or keyword like pci_address, pci_controller, pci_device etc. in playbook, but during execution ansible is not bothering/reading these parameters and moved on without any error or warning or changes.

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by felixfontein** [comment]
This repository is not for support questions. Please check out the places which you conveniently inserted in this issue. Thanks.

(The vmware_guest issue tracker is here: https://github.com/ansible-collections/vmware/issues)
