### ISSUE TITLE
Public Ansible Project Meeting Agenda - September 2020

### ISSUE THREAD

**Issue by samdoran** [ansible/community#560]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by samdoran** [comment]
- [ ] Discuss changes to the [module/plugin deprecation documentation](https://docs.ansible.com/ansible/devel/dev_guide/module_lifecycle.html#deprecating-modules)

Somewhat related to https://github.com/ansible/ansible/issues/71459. That issue mainly brought to light the fact that the documentation should be updated since `ANSIBLE_METADATA` is no longer a thing. What should the recommended deprecation process be fore modules/plugins in the new collections-based world?

**Comment by felixfontein** [comment]
@samdoran deprecation of plugins/modules is done by deprecating them both in the module docs and in meta/runtime.yml. For modules, this is already validated by validate-modules.

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#70319

**Comment by nitzmahone** [comment]
- [ ] Should we kill `ansible-galaxy login`? Discussion at ansible/ansible#71628

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#71679

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#71734 Extend validate-modules to also validate plugins. Questions to discuss for standardizing plugin schemas:
  - [ ] what's with `name:` next to `description:` in option descriptions? (see default_callback docs_fragment for extensive usage)
  - [ ] which plugin types must have / can have / cannot have examples?
  - [ ] author: required with same conditions as for modules, or optional, or other conditions?
  - [ ] `<plugin_type>: <name>` vs. `plugin_type: <plugin_type>` and `name: <name>`
  - [ ] option type: should long forms `boolean`, `string`, `integer` etc. be allowed?
  - [ ] return value `type`: required or not for plugins?

**Comment by felixfontein** [comment]
- ansible/ansible#71928 add validation for `type: dict` for plugin options

**Comment by felixfontein** [comment]
- [ ] should `ansible -version` etc. also show the Ansible version? (For example, antsibull-build could add a Python module to the pypi package called `ansible_collections/ansible_version.py`, which if found would provide the Ansible version)

**Comment by bcoca** [comment]
Meeting ended Tue Sep 29 20:10:36 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-09-29/ansbile_core_irc_public_meeting.2020-09-29-18.58.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-09-29/ansbile_core_irc_public_meeting.2020-09-29-18.58.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-09-29/ansbile_core_irc_public_meeting.2020-09-29-18.58.log.html
