### ISSUE TITLE
Extend rds module to allow copying of rds snaphots cross region.

### ISSUE THREAD

**Issue by dreaddesign** [ansible/community#561]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

### SUMMARY
Extend to allow module to copy an rds snapshot to another region.

### ISSUE TYPE
Feature Idea

### COMPONENT NAME
rds_instance or rds

### ADDITIONAL INFORMATION
During automated backups of databases, copy rds snapshot to different region for backup redundancy and ensure availability of rds instance.

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
