### ISSUE TITLE
Help with IDE local linting.

### ISSUE THREAD

**Issue by pm98zz-c** [ansible/community#564]
Hi there,

I'm new to Ansible devel, and started making changes to an existing module, but quickly realized my default linting/auto-formatting setup (pylint) kept on messing up with Ansible coding-standards.

Typically, pylint/.pycodestyle would move import to the top, contrary to guidelines indicating to leave them below the doc block, for example.

I realize I can catch those after the fact with `ansible-test sanity`, but I'd rather have them auto-fixed and/or flagged on the fly in my IDE (like on most projects).

Not sure if I'm missing something obvious here, but I cannot find anywhere any such configuration (.editorconfig, .pycodestyle, etc...) to drop in my project.

Is this something I've just been unable to find, and if not, would it not be useful for the wider community to have such linter standards easily available?

**Comment by imjoseangel** [comment]
@pm98zz-c We can have a chat in the IRC if you want some help. I personally use VSCode following these steps:

From [Ansible Developing Testing](https://docs.ansible.com/ansible/latest/dev_guide/testing.html#developing-testing). You can read:

```sh
ansible-test sanity --test pep8
ansible-test sanity --test validate-modules
```

From here I can assume you have to use pep8. With VSCode:

* Use autopep8
* Use pycodestyle for linting. Help on this [URL](https://code.visualstudio.com/docs/python/linting#_pycodestyle-pep8)

Setup your exceptions:

```json
    "python.linting.pylintEnabled": false,
    "python.linting.pycodestyleEnabled": true,
    "python.linting.pycodestyleArgs": [
        "--ignore=E402"
    ]
```

Hope it helps

**Comment by pm98zz-c** [comment]
Hi, thanks a lot for the tip.
The title of my issue probably was misleading, in that I wasn't only seeking for "help" for myself. What I wanted to point out was, as a first time contributor, that it could be a good thing to have those preset available (hence posting it under the community project, and not asking directly in IRC).

When you contribute to various projects, potentially in various languages, each with their own slightly different standards, you feel more welcome if the repo already provides you with presets so you don't have to think too much about it or fiddle around from one project to the other. 
Usually, it consists of 
- an .editorconfig file for generic formatting (indentation, line-length, quotes, etc)
- one or more language and project specific linting config (.tslint, .rubocop.yml). So in the case of Ansible, probably at least a .pycodestyle with the needed exceptions. The more of https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/index.html can be covered, the better.

Those settings must already exist "somewhere" as they're in use in ansible-test sanity --test pep8 and in the "shippable" tests, but I couldn't find them anywhere.

Thoughts about having them directly in the ansible repo, or at least added to the documentation?

**Comment by imjoseangel** [comment]
Fully agree with it. 

Besides the `.editorconfig` that I think is a great idea and I use it everywhere; I think having specific documentation about this matter could be great with recommended linting and techniques for Ansible development.

**Comment by tremble** [comment]
For what it's worth the configurations used by ansible-test can be found in the main ansible repo:

[pylint](https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_internal/sanity/pylint.py#L231):
- https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/sanity/pylint/config/collection.cfg

[pycodestyle (formerly known as pep8)](https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_internal/sanity/pep8.py#L63):  (ignored messages)
- https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/sanity/pep8/current-ignore.txt

With the migration over to 'collections' I think it's going to be much harder to coordinate getting the various .<something> files in place, but I do like the idea of making it as easy as possible to run any of the tests.

There's also a lot of custom code (validate-modules) which is specific to Ansible, for which I think ansible-test is probably the best wrapper.

**Comment by pm98zz-c** [comment]
Thanks a ton. For some reason I was expecting to find them under the "hacking" dir, I should have thought of the tests one...
