### ISSUE TITLE
 Public Ansible Project Meeting Agenda - Oct 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#568]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#71736 how can we complete the "just need to verify we don't have any code relying on the old structures" part? (except merging and seeing what breaks, that is :) )
- [ ] ansible/ansible#71824
  - [ ] where should `_add_builtin_fqcn` go (and under which name)?
  - [ ] should used `_add_builtin_fqcn` results be cached somewhere (in constants.py maybe) instead of always being computed on the fly?

**Comment by bcoca** [comment]
for the week of 12-15th we won't be holding any meetings due to AnsibleFest https://www.ansible.com/ansiblefest

**Comment by aminvakil** [comment]
- [ ] https://github.com/ansible/ansible/pull/71172

**Comment by bcoca** [comment]
Meeting ended Tue Oct  6 19:38:18 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-06/ansible_core_public_irc_meeting.2020-10-06-19.06.html
 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-10-06/ansible_core_public_irc_meeting.2020-10-06-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-06/ansible_core_public_irc_meeting.2020-10-06-19.06.log.html

**Comment by yoctozepto** [comment]
(hoped for) Thu 2020-10-08 core meeting

yoctozepto:
- [ansible/ansible#71118] Only notify handlers for loop items that changed - OpenStack Kolla-Ansible relies on such assumption

**Comment by bcoca** [comment]
logs here

**Comment by bcoca** [comment]
for the week of 12-15th we won't be holding any meetings due to AnsibleFest https://www.ansible.com/ansiblefest

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#72248
- [ ] ansible/ansible#71824
- [ ] ansible/ansible#71734

**Comment by bcoca** [comment]
Meeting ended Thu Oct 20 1. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-20/ansible_core_public_irc_meeting.2020-10-20-18.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-10-08/ansible_core_public_irc_meeting.2020-10-20-18.59.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-20/ansible_core_public_irc_meeting.2020-10-20-18.59.log.html

**Comment by mkrizek** [comment]
Meeting ended Thu Oct 22 15:14:10 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-22/ansible_core_public_irc_meeting.2020-10-22-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-10-22/ansible_core_public_irc_meeting.2020-10-22-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-22/ansible_core_public_irc_meeting.2020-10-22-15.00.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#72336

**Comment by nitzmahone** [comment]
Meeting ended Tue Oct 27 19:47:27 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
12:47 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-27/ansible_core_public_irc_meeting.2020-10-27-19.01.html
12:47 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-10-27/ansible_core_public_irc_meeting.2020-10-27-19.01.txt
12:47 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-27/ansible_core_public_irc_meeting.2020-10-27-19.01.log.html

**Comment by nitzmahone** [comment]
- [ ] opinions on `fallible` or `ansiboom` for the canary branch formerly known as `ansible_chaos`, last call for other ideas?

**Comment by samdoran** [comment]
Meeting ended Thu Oct 29 15:50:08 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:50 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-29/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues568.2020-10-29-15.00.html
11:50 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-10-29/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues568.2020-10-29-15.00.txt
11:50 Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-10-29/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues568.2020-10-29-15.00.log.html
