### ISSUE TITLE
ansible running really slowly on AWS ec2 when bootstrapped.

### ISSUE THREAD

**Issue by skomm-cap1** [ansible/community#571]
I am using ansible to automate provisioning of binaries/artifacts when a ec2 is launched. This is part of the userdata in Cloudformation used to create that stack. The script down loads the ansible play books and executes them locally. Now, when run through automation...the play books are executed really slowly. There is a pause for every task and this takes almost 30 minutes to complete.

However, if I execute the play books manually by logging to the instance at command prompt...it files and completes in under 5 minutes.

What could be going on here ? Any idea ?

TIA

**Comment by gundalow** [comment]
Please use the email list https://docs.ansible.com/ansible/latest/community/communication.html
