### ISSUE TITLE
Diversity Working Group Meeting Agenda - 2021

### ISSUE THREAD

**Issue by jillr** [ansible/community#577]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

Meetings are every other Thursday (e.g; 2021/01/07, 2021/01/21) on IRC at 19:00 UTC.

Diversity Working Group: https://github.com/ansible/community/wiki/Diversity

#ansible-diversity on Libera Chat IRC

**Comment by cybette** [comment]
In the [Community Working Group Meeting on 2020-12-16](https://github.com/ansible/community/issues/539#issuecomment-747034900) we agreed on updating the CoC criteria for Ansible Collections as follows:

- Collections MUST have a Code of Conduct (CoC)
- The collection's CoC MUST be compatible with the Ansible CoC
- Collections SHOULD consider using the Ansible CoC if they do not have a CoC that they consider better
- The Diversity and Inclusion working group may evaluate all CoCs and object to a collection's inclusion based on the CoCs contents

Let's discuss how the D&I team should evaluate the CoCs - responsibilities, procedure, criteria for what should be in a good CoC, a list of approved standard CoCs etc.

[How to code of conduct](https://hackmd.io/HqDFvkRXQBq28urikxtlCg?view) - notes from discussions by @abadger @jillr @samccann

**Comment by cybette** [comment]
**Java, Ansible, Openshift expertise needed.** Join the Hack-a-thon to support the Southern Coalition for Social Justice. As part of the MLK Day of Service, the Red Hat Social Innovation Program is looking for 50-100 participants to support a development effort for the Southern Coalition for Social Justice’s [Open Data Policing project](https://southerncoalition.org/resources/open-data-policing-website-manual/). (There's a sign up link for hatters but I'm not sure if community members who are interested can participate).

**Comment by cybette** [comment]
## Meeting 2021-01-07

### how the D&I team should evaluate the CoC
- https://github.com/sensu/sensu-go-ansible/blob/master/CODE_OF_CONDUCT.md
- add your thoughts and CoCs you find to this note so we can start evaluating them https://hackmd.io/vkslzOv0Raqx1QwaHzVEow

### Review the sensu-go-ansible collection CoC 
- https://github.com/sensu/sensu-go-ansible/blob/master/CODE_OF_CONDUCT.md 

### Hack-a-thon to support the Southern Coalition for Social Justice. 
- https://southerncoalition.org/resources/open-data-policing-website-manual/ 

## Logs
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-01-07/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-07-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-01-07/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-07-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-01-07/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-07-19.01.log.html

**Comment by felixfontein** [comment]
- [ ] need to discuss / vote on Sensu CoC (https://github.com/ansible-collections/ansible-inclusion/discussions/6)
- [ ] need to discuss / vote on Contributor Covenant Code of Conduct v1.4 (https://github.com/dell/dellemc-openmanage-ansible-modules/blob/devel/CODE_OF_CONDUCT.md, https://github.com/ansible-collections/ansible-inclusion/discussions/3)

**Comment by jillr** [comment]
The Contributor Covenent CoC v1.4 has changed over time without being version incremented.  We've voted today to approve the latest version of the text, which maps to this commit:  https://github.com/ContributorCovenant/contributor_covenant/blob/207d47805029f4029494f404182f67733f509399/content/version/1/4/code-of-conduct.md

**Comment by jillr** [comment]
19:59 <@zodbot> Meeting ended Thu Jan 21 19:59:37 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
19:59 <@zodbot> Minutes:  https://meetbot.fedoraproject.org/ansible-diversity/2021-01-21/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-21-19.00.html
19:59 <@zodbot> Minutes (text):  https://meetbot.fedoraproject.org/ansible-diversity/2021-01-21/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-21-19.00.txt
19:59 <@zodbot> Log:  https://meetbot.fedoraproject.org/ansible-diversity/2021-01-21/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-01-21-19.00.log.html

**Comment by cybette** [comment]
Action Item: everyone to review contributor covenant CoC 2.0 for next time
https://www.contributor-covenant.org/version/2/0/code_of_conduct/

**Comment by samccann** [comment]
- [ ] ways we can encourage communities/collections to audit/change problematic language aka - https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by jillr** [comment]
- [ ] New AWX logo: https://groups.google.com/g/awx-project/c/4gCe1NSVuu4/m/-yYbQkpkAgAJ

**Comment by gundalow** [comment]
## Screen readers

Do we have any guidance for writing wrt screen readers? abadger1999 made the point that we should use "please click `here`" for links. Not something I'd considered before?

Also I'm working on using the new (limited Alpha) GitHub issue templates, which should not only be easier for people to complete, I hope would be easier for screen readers.

**Comment by ssbarnea** [comment]
I stopped using "click" in general even without considering accessibility issue, as I found it to be more of a boilerplate on the web. If the link is correctly produced, it should be visible to the user even without telling user to click it.

I am quite curious about the upcoming new issue templates, do they finally add fields?

**Comment by cybette** [comment]
I've found this collection of how to design for accessibility quite interesting and useful, including for screenreaders: https://ukhomeoffice.github.io/accessibility-posters/

Here's the repo: https://github.com/UKHomeOffice/posters

**Comment by jillr** [comment]
Meeting summary
Announcement: New AWX logo (jillr, 19:04:35)
https://groups.google.com/g/awx-project/c/4gCe1NSVuu4/m/-yYbQkpkAgAJ (jillr, 19:04:59)
https://github.com/ansible/awx/pull/9203 (jillr, 19:05:07)

ways we can encourage communities/collections to audit/change problematic language (jillr, 19:07:01)
https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language (jillr, 19:07:45)
https://inclusivenaming.org/ (jillr, 19:09:47)
https://tools.ietf.org/id/draft-knodel-terminology-00.html (jillr, 19:10:38)
https://github.com/ansible/community/wiki/Diversity (jillr, 19:15:30)
ACTION: samccann and jillr to add an inclusive language section to the Diversity wiki with links to resources (jillr, 19:17:13)

Ansible media and assistive technologies (jillr, 19:17:56)
https://github.com/UKHomeOffice/posters (jillr, 19:19:27)
ACTION: jill to add a call for participation in the bullhorn (jillr, 19:26:34)

Contributor covenant CoC 2.0 for collections (jillr, 19:32:46)
https://www.contributor-covenant.org/version/2/0/code_of_conduct/ (jillr, 19:36:39)
https://meetbot.fedoraproject.org/ansible-community/2020-12-16/ansible_community_meeting.2020-12-16-19.01.log.html is the one I think where things started. (tadeboro, 19:59:17)
AGREED: - we will leave the Contributor Covenant CoC 2.0 unapproved, and will revisit as needed (jillr, 20:02:45)

Meeting ended Thu Feb  4 20:07:42 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-02-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-04-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-02-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-04-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-02-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-04-19.00.log.html

**Comment by jillr** [comment]
Meeting ended Thu Feb 18 20:06:31 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes:  https://meetbot.fedoraproject.org/ansible-diversity/2021-02-18/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-18-19.02.html
Minutes (text):  https://meetbot.fedoraproject.org/ansible-diversity/2021-02-18/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-18-19.02.txt
Log:  https://meetbot.fedoraproject.org/ansible-diversity/2021-02-18/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-18-19.02.log.html

**Comment by cybette** [comment]
- [ ] Recipient list for codeofconduct@ emails

**Comment by jillr** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-03-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-03-04-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-03-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-03-04-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-03-04/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-03-04-19.01.log.html

**Comment by jillr** [comment]
- [ ]  update on CoC recipient list
- [ ]  update on CoC response training

**Comment by jillr** [comment]
We agreed that the Ansible Community will sponsor the PyLadies auction at PyCon US 2021
https://us.pycon.org/2021/events/auction/

Meeting ended Thu Mar 18 19:59:08 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-03-18/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-03-18-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-03-18/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-03-18-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-03-18/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-03-18-19.00.log.html

**Comment by jillr** [comment]
Meetbot went away at some point, so irc log from today: https://gist.github.com/jillr/d799c14e05c57017af330466bd70f2cb

**Comment by cybette** [comment]
- [ ] D&I at PyCon US 2021

**Comment by jillr** [comment]
Meeting ended Thu Apr 15 19:49:43 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-04-15/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-15-19.00.html
Minutes (text):  https://meetbot.fedoraproject.org/ansible-diversity/2021-04-15/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-15-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-04-15/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-15-19.00.log.html

**Comment by jillr** [comment]
- [ ] Triage / update project board https://github.com/ansible/community/projects/2

**Comment by jillr** [comment]
Meeting ended Thu Apr 29 20:05:34 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-04-29/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-29-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-04-29/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-29-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-04-29/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-04-29-19.00.log.html

**Comment by mscherer** [comment]
Meeting ended Thu May 13 19:33:47 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-05-13/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-05-13-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-05-13/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-05-13-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-05-13/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-05-13-19.00.log.html

**Comment by jillr** [comment]
We didn't have zodbot yet (until the last few minutes, hehe) so meeting log from libera.chat:
https://gist.github.com/jillr/77ef2603cd4e8cecf233636bcbb5f139

**Comment by jillr** [comment]
- [ ] D&I working group Docs Hackfest for inclusive language https://gist.github.com/jillr/77ef2603cd4e8cecf233636bcbb5f139

**Comment by jillr** [comment]
<@zodbot> Meeting ended Thu Jun 10 19:29:22 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
<@zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-06-10/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-10-19.00.html
<@zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-06-10/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-10-19.00.txt
<@zodbot> Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-06-10/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-10-19.00.log.html

**Comment by jillr** [comment]
Meeting ended Thu Jun 24 20:01:39 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-06-24/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-24-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-06-24/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-24-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-06-24/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-06-24-19.01.log.html

**Comment by jillr** [comment]
Meeting ended Thu Jul  8 19:14:15 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes:  https://meetbot.fedoraproject.org/ansible-diversity/2021-07-08/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-08-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-07-08/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-08-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-07-08/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-08-19.00.log.html

**Comment by mscherer** [comment]
- [x] try more to deploy CLC http://test-test-clc.apps.ospo-osci.z3b1.p1.openshiftapps.com/ and https://github.com/mscherer/clc-openshift

**Comment by jillr** [comment]
Meeting ended Thu Jul 22 19:11:18 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-07-22/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-22-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-07-22/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-22-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-07-22/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-07-22-19.02.log.html

**Comment by jillr** [comment]
Meeting ended Thu Aug  5 19:17:33 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-08-05/ansible_diversity_working_group_|_agenda:.2021-08-05-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-08-05/ansible_diversity_working_group_|_agenda:.2021-08-05-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-08-05/ansible_diversity_working_group_|_agenda:.2021-08-05-19.00.log.html

**Comment by jillr** [comment]
Meeting ended Thu Sep  2 19:22:17 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021/ansible-diversity.2021-09-02-19.02.html
Minutes (text): https://meetbot.fedorparoject.org/ansible-diversity/2021/ansible-diversity.2021-09-02-19.02.txt
Log: ansible-diversity/2021/ansible-diversity.2021-09-02-19.02.log.html

**Comment by tadeboro** [comment]
* [ ] discuss/vote on [Nautobot CoC](https://github.com/nautobot/nautobot-ansible/blob/develop/CODE_OF_CONDUCT) for [inclusion in Ansible 5](https://github.com/ansible-collections/ansible-inclusion/discussions/28)

**Comment by mscherer** [comment]
Meeting ended Thu Sep 16 19:37:35 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-diversity/2021-09-16/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-09-16-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-diversity/2021-09-16/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-09-16-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-diversity/2021-09-16/ansible_diversity_working_group_|_agenda:_https:github.comansiblecommunityissues577.2021-09-16-19.05.log.html
