### ISSUE TITLE
Link to Ansible 95 ACI and ACI Multi-Site broken

### ISSUE THREAD

**Issue by jkary** [ansible/community#578]
The link in the link 'A total of 95 ACI and ACI Multi-Site modules ship with Ansible v2.8 !' is giving a 404 from ansible.

**Comment by felixfontein** [comment]
Could you please point to the page which contains this text / link? I assume you're refering to this wiki page: https://github.com/ansible/community/wiki/Network%3A-ACI ?

**Comment by felixfontein** [comment]
I assume the correct link should point to https://docs.ansible.com/ansible/stable-2.8/modules/list_of_network_modules.html#aci, but that always (incorrectly) redirects to https://docs.ansible.com/ansible/latest/stable-2.8/modules/list_of_network_modules.html#aci

**Comment by gundalow** [comment]
@jkary could you please respond to the above comment so we can get this fixed. Thanks for helping.

**Comment by jkary** [comment]
Looks good now.

Thanks
Jason

**Comment by Akasurde** [comment]
Closing this as per the above comment. Please feel free to open a new issue if the problem persists. Thanks.
