### ISSUE TITLE
How to test Ansible modules

### ISSUE THREAD

**Issue by gregdek** [ansible/community#58]
2:22 PM <•gregdek> Actually we can improve #2 by writing a good "how to test Ansible modules" guide.
2:22 PM <•gregdek> Which looks suspiciously similar to the Github "how to fork and test a branch in a PR" process.

**Comment by gregdek** [comment]
<bcoca> actually modules are MUCH easier, mkdir library; cd library; wget github.com/module/pr/raw

**Comment by bob-smith** [comment]
I'm happy to review (gundalow)

**Comment by gregdek** [comment]
Moving this to the top of the list; now that we're sending out a weekly report on new modules, we really want to make the call to action *very* obvious for our helpful potential contributors.

**Comment by gregdek** [comment]
Current docs here are decent, looking to expand these:

http://docs.ansible.com/ansible/developing_test_pr.html

**Comment by gregdek** [comment]
This is actually likely as good as it's going to get for now. Closing.
