### ISSUE TITLE
Windows Working Group agenda - 2021

### ISSUE THREAD

**Issue by jborean93** [ansible/community#581]
[![Github windows issues](https://img.shields.io/github/issues/ansible/ansible/windows.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:windows) [![Github windows PRs](https://img.shields.io/github/issues-pr/ansible/ansible/windows.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:windows) [![Windows agenda](https://img.shields.io/github/issues/detail/last-update/ansible/community/517.svg?label=agenda+update)](https://github.com/ansible/community/issues/420) [![Windows pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/208.svg?label=pinboard+update)](https://github.com/ansible/community/issues/208)

The Windows Working Group is focused on improving Ansible's management of Windows hosts. [We meet every week](https://github.com/ansible/community/wiki/Windows#meetings) on Tuesdays at 20:00 UTC (see [ical](https://raw.githubusercontent.com/ansible/community/master/meetings/ical/windows.ics)) 

More information related to the Windows Working Group is available at:
https://github.com/ansible/community/wiki/Windows

**Feel free to add your questions to this ticket to be discussed during the upcoming meeting.**

After being discussed, raised items are being updated, and after a month resolved items are being hidden from view (but remain accessible).

(migrated from 2020 agenda #517)

**Comment by jborean93** [comment]
How should `win_package` handle check mode when the path specified does not exist. Currently it fails like it would if it ran normally but it may have a previous step that copied/downloaded the file. Should we just ignore this error and report a change if possible or is a failure a desired outcome https://github.com/ansible-collections/ansible.windows/issues/208.

**Comment by MKletz** [comment]
I'd like to meet and discuss https://github.com/ansible-collections/ansible.windows/issues/15 if possible

**Comment by briantist** [comment]
The text in https://github.com/ansible/community/wiki/Windows needs updating, and that link is where the IRC channel topic points.

**Comment by jborean93** [comment]
Talk about https://github.com/ansible/ansible/pull/76256, in particular

* If we agree on enabling [UseConsistentIndentation](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/UseConsistentIndentation.md) with the proposed settings (4 spaces, indent on first pipeline)
* If we wish to also enable [AvoidLongLines](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/AvoidLongLines.md) and if so how long

**Comment by MKletz** [comment]
hey all sorry for the delays but I'd be interested in discussing https://github.com/ansible-collections/ansible.windows/issues/15

**Comment by briantist** [comment]
@MKletz sounds good! take note the meeting time is in UTC, so if you're in a location that observes DST, the meeting time may be different than last time you checked/attended. For example for me in US Eastern, it used to be 4pm, now it's 3pm.

**Comment by MKletz** [comment]
If we're still meeting on 11/23 I'd like to discuss the missing package the CI is looking for on https://github.com/ansible-collections/ansible.windows/pull/313
