### ISSUE TITLE
Public Ansible Project Meeting Agenda - January 2021

### ISSUE THREAD

**Issue by bcoca** [ansible/community#584]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by bcoca** [comment]
Carry over from https://github.com/ansible/community/issues/570#issuecomment-752807306
@jerryc

- [ ] Please address the hash_behaviour=merge deprecation issues:
* https://github.com/ansible/ansible/issues/73089
* https://github.com/ansible/ansible/issues/72669
* https://github.com/ansible/ansible/issues/72421
* https://groups.google.com/g/ansible-project/c/9eSApACKTks/m/8ghiXHFHAQAJ

**Comment by mkrizek** [comment]
Meeting ended Thu Jan  7 15:53:12 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-07/ansible_core_public_irc_meeting.2021-01-07-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-07/ansible_core_public_irc_meeting.2021-01-07-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-07/ansible_core_public_irc_meeting.2021-01-07-15.00.log.html

**Comment by mkrizek** [comment]
@jerrac Will you be able to attend the next meeting which is on Tuesday 19:00 UTC?

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#73058 Don't forget plugin deprecations after CLI init; include collection name in plugin deprecations
- [ ] ansible/ansible#73059 Always mention the name of the deprecated plugin in routing deprecation messages

**Comment by jerrac** [comment]
I will be there today. #ansible-meeting right?

**Comment by felixfontein** [comment]
@jerrac yes, #ansible-meeting. It will start in 24 minutes :)

**Comment by felixfontein** [comment]
- [ ] would it be possible if the core team makes sure that for every change (after initial release) in a stable branch that adds things to the porting guide has a changelog fragment that has one of the porting guide sections (`breaking_changes`, `major_changes`, `deprecated_features`, `removed_features`)? That would allow the automatically generated Ansible porting guide to pick these changes up. This is relevant for Ansible 3.0.0, which continues to use ansible-base 2.10, and thus shouldn't include the full ansible-base 2.10 porting guide (most of that has been covered in the Ansible 2.10 porting guide, which includes the ansible-base 2.10 porting guide).

     Unfortunately some entries were added later to the ansible-base 2.10 porting guide which should be covered in the Ansible 3.0.0 porting guide that have no corresponding changelog entry with one of the porting guide categories (for example https://github.com/ansible/ansible/commit/7a38c470bad6195ec29f1701f4a1ce91d34f9a06 corresponds to changelog fragment https://github.com/ansible/ansible/pull/71537/files#diff-e55c39740eaca5f9c694670e5cc05b6f5ccb038844385a5aac1d87c411c2e4d2 which does not show up in the porting guide, since it is not marked as a breaking change).

     It would be great if we could avoid this in the future :)

**Comment by samdoran** [comment]
Meeting ended Tue Jan 12 20:00:40 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-12/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues584.2021-01-12-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-12/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues584.2021-01-12-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-12/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues584.2021-01-12-19.00.log.html

**Comment by mkrizek** [comment]
Meeting ended Thu Jan 14 16:10:46 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-14/ansible_core_public_irc_meeting.2021-01-14-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-14/ansible_core_public_irc_meeting.2021-01-14-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-14/ansible_core_public_irc_meeting.2021-01-14-15.00.log.html

**Comment by rwagnergit** [comment]
Please add https://github.com/ansible/ansible/pull/72419 to next meeting agenda.  I'm especially interested as it relates to my bug (https://github.com/ansible/ansible/issues/72776) but there are others.

**Comment by nitzmahone** [comment]
Meeting ended Tue Jan 19 19:16:06 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-19/ansible_core_public_irc_meeting.2021-01-19-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-19/ansible_core_public_irc_meeting.2021-01-19-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-19/ansible_core_public_irc_meeting.2021-01-19-19.01.log.html

**Comment by Shrews** [comment]
Meeting ended Thu Jan 21 16:25:34 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:25 AM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-21/ansible_core_public_irc_meeting.2021-01-21-15.01.html
11:25 AM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-21/ansible_core_public_irc_meeting.2021-01-21-15.01.txt
11:25 AM Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-21/ansible_core_public_irc_meeting.2021-01-21-15.01.log.html

**Comment by bcoca** [comment]
Nothing substantive really discussed, but you can check logs to verify my statement.

Meeting ended Tue Jan 26 19:14:01 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-26/ansible_core_public_irc_meeting.2021-01-26-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-26/ansible_core_public_irc_meeting.2021-01-26-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-26/ansible_core_public_irc_meeting.2021-01-26-19.02.log.html

**Comment by Shrews** [comment]
Nothing was discussed today.

Meeting ended Thu Jan 28 15:10:30 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
10:10 AM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-28/ansible_core_public_irc_meeting.2021-01-28-15.00.html
10:10 AM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-28/ansible_core_public_irc_meeting.2021-01-28-15.00.txt
10:10 AM Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-28/ansible_core_public_irc_meeting.2021-01-28-15.00.log.html
