### ISSUE TITLE
Public Ansible Project Meeting Agenda - February 2021

### ISSUE THREAD

**Issue by Shrews** [ansible/community#585]
This repository is for management of all Ansible community related initiatives, such as meetings.

Ansible Support

Bug reports: https://github.com/ansible/ansible/issues/new
IRC: #ansible on irc.freenode.net * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by Shrews** [comment]
From the 2-Feb-2021 meeting:

Meeting ended Tue Feb  2 19:25:17 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
2:25 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-02/ansible_core_public_irc_meeting.2021-02-02-19.00.html
2:25 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-02/ansible_core_public_irc_meeting.2021-02-02-19.00.txt
2:25 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-02/ansible_core_public_irc_meeting.2021-02-02-19.00.log.html

**Comment by Shrews** [comment]
Nothing discussed today.

Meeting ended Thu Feb  4 15:12:08 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
10:12 AM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-04/ansible_core_public_irc_meeting.2021-02-04-15.01.html
10:12 AM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-04/ansible_core_public_irc_meeting.2021-02-04-15.01.txt
10:12 AM Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-04/ansible_core_public_irc_meeting.2021-02-04-15.01.log.html

**Comment by Shrews** [comment]
Nothing discussed today.

Meeting ended Tue Feb  9 19:16:36 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
2:16 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-09/ansible_core_public_irc_meeting.2021-02-09-19.04.html
2:16 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-09/ansible_core_public_irc_meeting.2021-02-09-19.04.txt
2:16 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-09/ansible_core_public_irc_meeting.2021-02-09-19.04.log.html

**Comment by samdoran** [comment]
Nothing discussed today.

Meeting ended Thu Feb 11 15:16:41 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-11/ansible_core_public_irc_meeting.2021-02-11-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-11/ansible_core_public_irc_meeting.2021-02-11-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-11/ansible_core_public_irc_meeting.2021-02-11-15.02.log.html

**Comment by mattclay** [comment]
Nothing discussed today.

Meeting ended Tue Feb 16 19:10:12 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-16/ansible_core_public_irc_meeting.2021-02-16-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-16/ansible_core_public_irc_meeting.2021-02-16-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-16/ansible_core_public_irc_meeting.2021-02-16-19.00.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Feb 18 15:20:33 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-18/ansible_core_public_irc_meeting.2021-02-18-15.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-18/ansible_core_public_irc_meeting.2021-02-18-15.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-18/ansible_core_public_irc_meeting.2021-02-18-15.04.log.html

**Comment by bcoca** [comment]
- [ ] Revise meeting schedule:
    - Alternate Tuesday/Thrusday meetings to every other week.
    - Consolidate on Tuesday or Thrusday but alternate the times every other week. (note they conflict with internal core triage meetings)
    - Alternate both times but on Wednesdays

**Comment by mattclay** [comment]
In today's meeting there were 4 proposals for a revised meeting schedule. I will post each one in a comment here. Before the next meeting (Thursday), please upvote and/or comment on the proposals.

**Comment by mattclay** [comment]
### Revised Meeting Schedule - Option 1

Alternate Tuesday/Thursday meetings every other week.

This means meetings on Tuesday and Thursday one week, then no meetings the next week.

**Comment by mattclay** [comment]
### Revised Meeting Schedule - Option 2

Consolidate on Tuesday meetings, but alternate the times every other week.

NOTE: They conflict with internal core triage meetings.

**Comment by mattclay** [comment]
### Revised Meeting Schedule - Option 3

Consolidate on Thursday meetings, but alternate the times every other week.

NOTE: They conflict with internal core triage meetings.

**Comment by mattclay** [comment]
### Revised Meeting Schedule - Option 4

Alternate both times but on Wednesdays.

**Comment by mattclay** [comment]
### Revised Meeting Schedule - Option 5

Alternate Tuesday one week, Thursday the next week.

**Comment by mattclay** [comment]
Meeting ended Tue Feb 23 19:47:50 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-23/ansible_core_public_irc_meeting.2021-02-23-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-23/ansible_core_public_irc_meeting.2021-02-23-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-23/ansible_core_public_irc_meeting.2021-02-23-19.00.log.html

**Comment by samdoran** [comment]
Meeting ended Thu Feb 25 15:37:06 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-25/ansible_core_public_irc_meeting.2021-02-25-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-02-25/ansible_core_public_irc_meeting.2021-02-25-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-02-25/ansible_core_public_irc_meeting.2021-02-25-15.03.log.html
