### ISSUE TITLE
Meetup Organizer CoC Survey - D&I WG

### ISSUE THREAD

**Issue by jillr** [ansible/community#588]
We'd like to survey our existing meetup organizers to check in and make sure they're familiar with the Ansible Code of Conduct, if they feel comfortable/confident with how to enforce the CoC or address violations, if there have been any incidents, and if there's anything we can do to better support them in this area.

We could use assistance crafting this survey from @GregSutcliffe

**Comment by mscherer** [comment]
Related meeting:
 https://meetbot.fedoraproject.org/ansible-diversity/2021-02-18/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-18-19.02.log.html 
and 
https://meetbot.fedoraproject.org/ansible-diversity/2021-02-18/ansible_d&i_wg_agenda:_https:github.comansiblecommunityissues577.2021-02-18-19.02.html

**Comment by GregSutcliffe** [comment]
Oh hai! Thanks for the ego boost :D

So that sounds fine in principle, I'm happy to help out. What's your preference for getting started? Perhaps @jillr & I can schedule a call, draft something up, and then report the draft here for critique?

Also, reading the logs, it's worth knowing that I collect a lot of Meetup data via the Meetup API, so if you need to look at something across all our meetups, I may be able to help there too.

**Comment by cybette** [comment]
I'd be interested to join the call!

**Comment by GregSutcliffe** [comment]
Sure! Not trying to exclude people, just aware that many are suffering meeting fatigue at the moment :)

**Comment by jillr** [comment]
@cybette @GregSutcliffe Looking at what I can see of all of our calendars it looks like the first time we all have overlapping availability might be March 4.  Would it be worth starting a hackmd.io doc or something in the interim and we can review it then?

**Comment by cybette** [comment]
@jillr sounds good! added you to the community team hackmd group so you can create a doc there if you wish.

**Comment by jillr** [comment]
https://hackmd.io/YiBvALjKSFqtVTXzoY-I7A

**Comment by GregSutcliffe** [comment]
I can potentially do an evening meeting sooner if that's preferable. I'm generally available after 8pm GMT.

**Comment by jillr** [comment]
@GregSutcliffe Do we need to provide you anything else to create the survey?

**Comment by GregSutcliffe** [comment]
@jillr I don't think so. Apologies if you've been waiting on me, my recollection was that some wording and such was still being finalised. If you're happy with the  contents of the HackMd doc, I can turn that into a simple survey later this week.

**Comment by jillr** [comment]
@GregSutcliffe no worries, I think we reviewed it at a meeting then didn't properly update you but I wasn't certain. Thanks much!

**Comment by GregSutcliffe** [comment]
@jillr here's a link to test it out https://www.surveymonkey.co.uk/r/6HDQMSW

I can create as many links as places you'd like to share it, so just let me know your needs. I'll delete *this* link once we're happy so that we don't have test replies in out dataset :)

**Comment by samccann** [comment]
We are in the process of archiving the ansible/community repository. See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928 for details.

Consider opening a forum topic to continue this discussion.
