### ISSUE TITLE
Move ticket_stubs out of ansible/ansible into another repository

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#59]
I am concerned about the number of entries in the root directory of the project.

We already moved the Github templates out of the way, and there is a request ansible/ansible#14932 to also get rid of the _samples/_ directory (we already have a dedicated _examples/_ and _test/_ directory).

In this case, I don't think the _ticket_stubs/_ belongs in the project's root directory since it is related to processes and not the product. End-users have no need for them and I guess ansibull-bot is making it redundant as well.

**Comment by dagwieers** [comment]
Similarly, some of the other entries in the root-folder are not special/important enough to earn a place in the root-directory.

 - ansible-core-sitemap.xml
 - RELEASES.txt
 - ROADMAP.md *(this is a difficult one)*
 - docsite/ *(could move to docs/site/)*

In fact the official tarball releases do not ship all these entries, so one could question why they have to live in the root directory anyhow.

It is also unfortunate that some tools require files to exist in the project's root directory:

 - .coverage
 - .coveragerc
 - tox.ini
 - .travis.yml

**Comment by dagwieers** [comment]
With Ansibot and the GitHub "Saved Replies" feature in use, do we still need these ticket_stubs today ? Maybe we can simply get rid of them altogether ?

**Comment by gregdek** [comment]
We're about to do some reorg of what's left here. If you still find this to be an issue in a few weeks, re-file it against ansible/ansible.

**Comment by gregdek** [comment]
Nope, changed my mind. I'll leave this open for now.

**Comment by gregdek** [comment]
Actually, @dagwieers, I'm going to guess that this was closed as part of https://github.com/ansible/ansible/pull/14932. So I'm closing for real now. If it's not handled, please open a new issue. :)

**Comment by dagwieers** [comment]
It's still here: https://github.com/ansible/ansible/tree/devel/ticket_stubs

So I would prefer to see it remove from this repository, as well as remove as many root-level files and directories. The more stuff that's in there, the harder it is for people to find the essential stuff IMO.

**Comment by gregdek** [comment]
@jimi-c are you still using these stubs? Or are other people on the core team?
