### ISSUE TITLE
Public Ansible Project Meeting Agenda - March 2021

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#590]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   
* Mailing List: https://groups.google.com/forum/#!forum/ansible-project

Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by nitzmahone** [comment]
Meeting ended Tue Mar  2 19:19:26 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-02/ansible_core_public_irc_meeting.2021-03-02-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-03-02/ansible_core_public_irc_meeting.2021-03-02-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-02/ansible_core_public_irc_meeting.2021-03-02-19.02.log.html

**Comment by nitzmahone** [comment]
**NO MEETING MARCH 9 due to [Ansible Contributor Summit](https://www.eventbrite.com/e/ansible-contributor-summit-202103-registration-141735886853)**

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#73707, which implements ansible/proposals#68 (by @bcoca)

**Comment by bcoca** [comment]
Meeting ended Thu Mar  4 15:55:05 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-04/ansible_core_public_irc_meeting.2021-03-04-15.08.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-03-04/ansible_core_public_irc_meeting.2021-03-04-15.08.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-04/ansible_core_public_irc_meeting.2021-03-04-15.08.log.html

**Comment by bcoca** [comment]
Nothing discussed

Meeting ended Thu Mar 11 15:16:19 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-11/ansible_core_public_irc_meeting.2021-03-11-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-03-11/ansible_core_public_irc_meeting.2021-03-11-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-11/ansible_core_public_irc_meeting.2021-03-11-15.00.log.html

**Comment by mkrizek** [comment]
Nothing discussed.

Meeting ended Thu Mar 18 15:09:02 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-18/ansible_core_public_irc_meeting.2021-03-18-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-03-18/ansible_core_public_irc_meeting.2021-03-18-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-18/ansible_core_public_irc_meeting.2021-03-18-15.00.log.html

**Comment by jborean93** [comment]
Nothing discussed (apart from some PR reviews)

Meeting ended Tue Mar 23 19:15:57 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
05:15 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-23/ansible_core_public_irc_meeting.2021-03-23-19.01.html
05:15 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-03-23/ansible_core_public_irc_meeting.2021-03-23-19.01.txt
05:15 Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-03-23/ansible_core_public_irc_meeting.2021-03-23-19.01.log.html

**Comment by bcoca** [comment]
No real discussion (one bad joke and a couple of questions about feature/stable branch creation dates)

 Meeting ended Thu Apr  1 15:19:54 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.log.html
