### ISSUE TITLE
Many duplicate new module submissions

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/community#60]
Today a third new module pull request was submitted that duplicates the functionality of two previously submitted new modules
https://github.com/ansible/ansible-modules-extras/pull/1939
https://github.com/ansible/ansible-modules-extras/pull/1908
https://github.com/ansible/ansible-modules-extras/pull/1352

Two ideas that could help:
Review/approve/merge new modules faster
Add language to the new module guidelines to look for duplicate pending merge requests

**Comment by gregdek** [comment]
Some discussion about this on IRC today:

12:33 PM <alikins> re dup prs etc... The bot could potentially compare a pr's diff (mainly which files changed) against existing prs and show them as potential dupes. Likely wouldn't catch new features/modules though...
12:34 PM <alikins> afaict the github api doesn't have a great way to find pr's that change a particular file though. It's doable with local git against a checkout with the pull refs fetched though.
12:35 PM <sivel> PRs list the files that are changed
12:35 PM <sivel> I was debating writing a bot that would hold all files PRs are changing, so it could do cross referencing
12:35 PM <alikins> the bot and triage.py seem to iterate all the prs and compare their changed files against the mantainers date.
12:36 PM <sivel> I had though about using levenshtein distance to calculate similarity of changes...
12:39 PM <sivel> though would be nice then when creating a PR, github listed all other PRs for files that are common
12:40 PM <sivel> one problem with the way the bot works now, is that it chews up a lot of API requests.  Would be better if it were a webhook instead.
12:41 PM <sivel> so the more you try to do, the more likely you are to run out of API requests
12:46 PM <alikins> I have some code that takes the diffs from prs and figures out the which lines would be changed when applied (without checking out the merge). prs could be compared for overlapping lines changed.

**Comment by MichaelBaydoun** [comment]
Perhaps a note in module guidelines or contributions suggesting searching the existing pull requests to see if someone is already working on the module you are considering writing.

**Comment by gundalow** [comment]
https://ansible.sivel.net/pr/byfile.html 
or
https://github.com/ansible/ansible-modules-extras/labels/new_plugin and https://github.com/ansible/ansible-modules-core/labels/new_plugin

**Comment by gregdek** [comment]
This is something we should put into the contributor guide. @gundalow do we have something like this?

**Comment by gundalow** [comment]
* Idea for `ansibullbot` to tell people about other PRs in flight https://github.com/ansible/ansibullbot/issues/563

* Make it cleared in the docs to look at existing PRs https://github.com/ansible/ansible/pull/26287

* New `rst/community/development_process.rst`
as outlines in https://github.com/ansible/community/issues/169 states we should have:

> PR flow chart
> Do I need to raise a PR LINK: sivel's prbyfile LINK: How to review

**Comment by robynbergeron** [comment]
Labelling for discussion in Community WG meeting today.

**Comment by gregdek** [comment]
Now that we've cleaned up our contributing guidelines, we should be able to add this to the new documentation. I'll take this one. The simplest thing: "Add language to the new module guidelines to look for duplicate pending merge requests."

**Comment by gregdek** [comment]
This language now exists here: 

http://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html
