### ISSUE TITLE
Error reading config file (/etc/ansible/ansible.cfg): Source contains parsing errors: '<string>'         [line  4]: '    3 \n'

### ISSUE THREAD

**Issue by momoni33** [ansible/community#601]
Hi Guys 

I am learning Ansible as a newbie so that i can get into the industry of IT, I am learning everything from scratch
I have two hosts - hosts 1 and 2 
i am trying to create a file from host 1 to host 2 - using ansible when i do this i get the following 

Error reading config file (/etc/ansible/ansible.cfg): Source contains parsing errors: '<string>'
        [line  4]: '    3 \n'
        [line  5]: '    4 # nearly all parameters can be overridden in ansible-playbook\n'
        [line  6]: '    5 # or with command line flags. ansible will read ANSIBLE_CONFIG,\n'
        [line  7]: '    6 # ansible.cfg in the current working directory, .ansible.cfg in\n'
        [line  8]: '    7 # the home directory or /etc/ansible/ansible.cfg, whichever it\n'
        [line  9]: '    8 # finds first\n'

**Comment by bmillemathias** [comment]
Hello

This project is for discussing project related decision, for user support please use the Google group https://groups.google.com/g/ansible-project 

Best

**Comment by florenciohugo** [comment]
hi @momoni33 I´m having the same error, did you find out what is wrong??
