### ISSUE TITLE
Public Ansible Project Meeting Agenda - April 2021

### ISSUE THREAD

**Issue by bcoca** [ansible/community#605]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.freenode.net   
* Mailing List: https://groups.google.com/forum/#!forum/ansible-project

Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by bcoca** [comment]
No real discussion (one bad joke and a couple of questions about feature/stable branch creation dates)

 Meeting ended Thu Apr  1 15:19:54 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-01/ansible_core_public_irc_meeting.2021-04-01-15.00.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/32379 <= should we contemplate delegated host failures as special case or just leave current behavior as is?

**Comment by nitzmahone** [comment]
Meeting ended Tue Apr  6 19:18:33 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-06/ansible_core_public_irc_meeting.2021-04-06-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-04-06/ansible_core_public_irc_meeting.2021-04-06-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-06/ansible_core_public_irc_meeting.2021-04-06-19.00.log.html

**Comment by nitzmahone** [comment]
- [ ] interpreter discovery fallback on old "listed" distros (https://github.com/ansible/ansible/pull/74152)

**Comment by ollofx** [comment]
- [ ] Please reconsider deprecating hash_behaviour=merge #74215

**Comment by Shrews** [comment]
[11:21:40] zodbot changed the topic to Scheduled Ansible community meetings - check https://github.com/ansible/community for schedule and to add items to the agenda
[11:21:40]  <@zodbot> Meeting ended Thu Apr 15 15:21:40 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
[11:21:40]  <@zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-15/ansible_core_public_irc_meeting.2021-04-15-15.00.html
[11:21:40]  <@zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-04-15/ansible_core_public_irc_meeting.2021-04-15-15.00.txt
[11:21:40]  <@zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-15/ansible_core_public_irc_meeting.2021-04-15-15.00.log.html

@ollofx was not around to discuss the hash_behaviour topic, but meeting notes should show this was already resolved.

@nitzmahone was not around to discuss his topic, so will add for next meeting.

**Comment by Shrews** [comment]
- [ ] per @nitzmahone: interpreter discovery fallback on old "listed" distros (ansible/ansible#74152)

**Comment by nkakouros** [comment]
- [ ] support collection playbooks in subdirs (https://github.com/ansible/ansible/pull/74284)

**Comment by mattclay** [comment]
Meeting ended Tue Apr 20 19:48:23 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-20/ansible_core_public_irc_meeting.2021-04-20-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-04-20/ansible_core_public_irc_meeting.2021-04-20-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-04-20/ansible_core_public_irc_meeting.2021-04-20-19.00.log.html
