### ISSUE TITLE
Public Ansible Core Meeting Agenda - May 2021

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#606]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by tadeboro** [comment]
Ansible Core 2.11 added support for role argument specification. Unfortunately, roles that include the argument specification are currently not usable on still-supported ansible-2.9 and ansible-base-2.10. See https://github.com/ansible/ansible/issues/74525 for more details about the error and how to replicate it.

Since this makes it impossible to start using new features of Ansible Core without breaking the compatibility with older Ansible releases, maybe older releases should be updated just enough to ignore the unknown metadata?

**Comment by nitzmahone** [comment]
Meeting ended Tue May  4 19:58:23 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-04/ansible_core_public_irc_meeting.2021-05-04-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-05-04/ansible_core_public_irc_meeting.2021-05-04-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-04/ansible_core_public_irc_meeting.2021-05-04-19.00.log.html

**Comment by gundalow** [comment]
[#74558 ansible-test: Error if non-standard dirs exist under plugins/ ](https://github.com/ansible/ansible/issues/74558)

https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#modules-plugins

Are there any cases where we'd want someone to add a new plugins subdirectory that isn't fully defined in ansible-core?

**Comment by bcoca** [comment]
Meeting ended Thu May 13 15:47:05 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-13/core_public_irc_meeting.2021-05-13-15.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-05-13/core_public_irc_meeting.2021-05-13-15.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-13/core_public_irc_meeting.2021-05-13-15.05.log.html

**Comment by samdoran** [comment]
Meeting ended Thu May 27 16:01:06 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-27/ansible_core_public_irc_meeting.2021-05-27-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-05-27/ansible_core_public_irc_meeting.2021-05-27-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-05-27/ansible_core_public_irc_meeting.2021-05-27-15.02.log.html
