### ISSUE TITLE
Moving to libera.chat

### ISSUE THREAD

**Issue by gundalow** [ansible/community#613]
This is to track the actions needed when we move IRC.

This is a todo list  **assuming** we do libera.chat + matrix bridge. That hasn't been confirmed yet. That is tracked as https://github.com/ansible-community/community-topics/issues/19

### libera.chat
- [x] Create & register project
- [x] Create and register all channels
- [x] `FLAGS` set for all channels
- [ ] Set some channels to redirect to others (ansiblezh,ansibleu, ansible-zh -> ansible-eu ) (ansible-news -> ansible-community)
- [X] Set initial `/topics`
- [x] Update docs to point to new location: https://github.com/ansible/ansible/pull/74775
- [x] invite meeting bot (and drop existing rooms)
- [X] Ops for Core Team - Don't assume names match
- [ ] Matrix Bridge - [Matrix Plan](https://hackmd.io/FnpIUIrrRuec-gT3lrv-rQ)
- [ ] Clear how to join docs, steal [Zuuls's Matrix Docs?]|(https://zuul-ci.org/docs/zuul/howtos/matrix.html)
- [x] GitHub Bot to post in new channels (community-topics, lint, molecule)
- [ ] Internal onboarding docs - Sign up to Libera.chat + Matrix
- [ ] Ansible release procedure 

#### Other links
- [ ] [d.a.c/ansible](https://github.com/ansible/ansible/pull/747750)
- [ ] Backport 747750
- [ ] [ansibullbot](https://github.com/ansible/ansibullbot/pull/1577)
- [ ] [collection_bot](FIXME)
- [ ] Update https://github.com/ansible/community: https://github.com/ansible/community/pull/614
- [ ] Update https://github.com/ansible/community/wiki -> abadger will take this (needs backporting)
- [ ] AWX docs https://github.com/ansible/awx/pull/10295
- [ ] collection_template
- [ ] Each collection repo
- [ ] Release process to update topic in libera.chat

### Matrix

- [ ] Redirect/combine existing channels
- [ ] Review who has ops
- [ ] `Spaces` - Can we link to this in the main docs?

### Freenode

- [ ] Once the channels quieten down, possibly redirect them so only `#ansible` and `#ansible-devel` exist.
- [ ] Update channels topic to point to 

### Questions
1. Require registered users to talk (anyone can join?) Allow Matrix (non NickServ joins)

For general discussion about what we should do, please use https://github.com/ansible-community/community-topics/issues/19

### Permissions

```
/msg ChanServ CLAIM #ansible
/msg ChanServ FLAGS #ansible *!*@ansible/owner/*           +AORefiorstv
/msg ChanServ FLAGS #ansible *!*@ansible/staff/*           +Oo
/msg ChanServ FLAGS #ansible *!*@redhat/ansible.staff.*    +Oo
/msg ChanServ FLAGS #ansible zodbot                        +Oo
```
`zodbot` entry allows meeting bot to set the `/topic`

### Channel modes
FIXME
* Only Ops can set topic
* Registered to *talk*
  * Anyone authed with `NickServ`
  * Anyone using Matrix - configuring IRC for Matrix voice - I think the +q is the main line (quiets all (~a) with a regex exception for Matrix)
* Colour allowed
* In channel to post
### Group Contacts

Community Team are the Group Contact for `ansible` on Libera.chat (On Freenode it was Gundalow + Jimi)

These are the only people that can
*  `CLAIM` any channel starting `#ansible-`
* Assign cloaks to other Ansible staff

- [x] gundalow
- [x] abadger
- [x] cybette
- [x] dericcrago
- [x] dmsimard
- [ ] gwmngilfen
- [x] ompragash
- [ ] andersson007_

**Comment by mscherer** [comment]
Should this issue also lists the communication needed ? (like send mails, post on reddit, etc)

I also know that on Freenode, I requested a special access to be on more than X channels long time ago (and by long time ago, I do not mean "just before the pandemics", more like 10 years ago), maybe this is worth checking as well for some of the most heavier channel users (I think X was quite lowe, like 15 or 20).

**Comment by mscherer** [comment]
I think freenode also have a way to add messages when you join a channel, it might be useful to use that along /topic ?

**Comment by mscherer** [comment]
For the record, here is the instructions written by the Wikipedia community for a migration:
https://meta.wikimedia.org/wiki/IRC/Migrating_to_Libera_Chat

Can be useful to cut and paste or see if we missed anything on Freenode irc channel closing, or as a inspiration for our own docs. 

They also took the time to rename some channels, not sure if we have the same issue, but maybe this would be the right time to look (not sure if that's the 4th point of the list or not)

**Comment by mscherer** [comment]
Also, one more task missing, transfer of bans (or decide to drop them). I am not aware of any long term IRC ban, but me not being aware do not mean it doesn't exist :)

**Comment by GregSutcliffe** [comment]
> Anyone using Matrix - configuring IRC for Matrix voice - I think the +q is the main line (quiets all (~a) with a regex exception for Matrix)

https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users gives the possible things you can do. `+q ... +e ...` is what I did in #foreman(-dev)

**Comment by mscherer** [comment]
If we move, we might have to pay attention to the topic, per new freenode policies: https://news.ycombinator.com/item?id=27286628

**Comment by felixfontein** [comment]
@mscherer this is already extremely important for the discussion at the meeting today, if someone uses `#topic` with [Ll]ibera in it during the meeting, zodbot will set the channel topic and that mechanism will take over the channel, effectively ending the meeting. @gundalow @abadger @dmsimard I guess one of you will lead the meeting, please make sure to avoid mentioning [Ll]ibera (and maybe also OFTC) in `#topic`!

(See also https://mastodon.sdf.org/@kline/106299403921451814)

**Comment by felixfontein** [comment]
We should probably create a page (here, or docs.ansible.com) which mentions the move to the new network, and only link to that one in the channel topic when moving, to avoid this automatic takeover. I guess sooner or later they will also use that as a reason, but it's a bit harder to automate :)

**Comment by mscherer** [comment]
Also, update the calendar (inspired from https://pagure.io/fedora-infrastructure/issue/9980 )

**Comment by wenottingham** [comment]
>  Update docs to point to new location: ansible/ansible#74775

related: https://github.com/ansible/awx/pull/10295/

**Comment by felixfontein** [comment]
There are also some collection README.md files which mention Freenode, like community.network, community.aws and amazon.aws (CC @dericcrago @jillr).

**Comment by felixfontein** [comment]
Since the collection template's GHA script refers to Freenode, some collections instantiated from it might have that too (https://github.com/ansible-collections/collection_template/pull/23).

**Comment by mscherer** [comment]
We also have the agenda item for meeting, like:
https://github.com/ansible/community/issues/577

Should we create a new ticket, or change the existing one ?

**Comment by gundalow** [comment]
> We also have the agenda item for meeting, like:
> https://github.com/ansible/community/issues/577
> 
> Should we create a new ticket, or change the existing one ?

@mscherer if you have powers to change the existing ones that would be great. Zodbot has moved.

**Comment by Andersson007** [comment]
Fixed `freenode` to `libera.chat` everywhere across the collections were found, though not all the PRs are already merged

**Comment by mscherer** [comment]
On #ansible, bmorg signaled that https://www.ansible.com/community still list freenode.

**Comment by cybette** [comment]
https://www.ansible.com/community has been updated to reflect libera.chat

**Comment by Andersson007** [comment]
Fixed all the wiki pages under https://github.com/ansible/community/wiki

**Comment by mscherer** [comment]
I made a quick pass using search on the ansible org, but there is also the new translated documentation:
https://github.com/ansible/ansible/blob/36287e98108b2d53f4813770bfe93630026c86b9/docs/docsite/rst/locales/ja/LC_MESSAGES/plugins.po

Not sure if that's already deployed.

**Comment by gundalow** [comment]
> I made a quick pass using search on the ansible org, but there is also the new translated documentation:
> https://github.com/ansible/ansible/blob/36287e98108b2d53f4813770bfe93630026c86b9/docs/docsite/rst/locales/ja/LC_MESSAGES/plugins.po
> 
> Not sure if that's already deployed.


Good spot, this will get updated next time we send a batch of docs for translation

**Comment by mscherer** [comment]
So while we can't exclude archived repositories from code search ([feature request](https://github.community/t/feature-request-search-code-for-not-archived-repositories/2135)), we can exclude them one by one manually, so here is a shorter [list of repositories](https://github.com/search?p=3&q=org%3Aansible+freenode+-repo%3Aansible%2Fansible-azp+-repo%3Aansible%2Fzuul-test-repo+-repo%3Aansible%2Fansible-container&type=Code) to fix. Some already have PR, some incomplete PR (I have done that before noticing the web client), and some don't.

Also related, a [list](https://github.com/ansible-community/community-topics/issues/25) of repositories to archive.

**Comment by mscherer** [comment]
Not sure where to report but https://www.ansible.com/community/awx-project still list freenode

**Comment by cybette** [comment]
> Not sure where to report but https://www.ansible.com/community/awx-project still list freenode

This is the place to report! I'll take care of this, thanks!

**Comment by gundalow** [comment]
This was completed last year, so closing the issue.
Thank you to everybody that helped with this fire drill.
