### ISSUE TITLE
 Public Ansible Core Meeting Agenda - June 2021 

### ISSUE THREAD

**Issue by bcoca** [ansible/community#615]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by bcoca** [comment]
just emoji practice
Meeting ended Thu Jun 10 15:15:32 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-10/ansible_core_public_irc_meeting.2021-06-10-15.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-06-10/ansible_core_public_irc_meeting.2021-06-10-15.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-10/ansible_core_public_irc_meeting.2021-06-10-15.05.log.html

**Comment by nitzmahone** [comment]
Meeting ended Tue Jun 15 19:07:50 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-15/ansible_core_public_irc_meeting.2021-06-15-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-06-15/ansible_core_public_irc_meeting.2021-06-15-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-15/ansible_core_public_irc_meeting.2021-06-15-19.00.log.html

**Comment by Shrews** [comment]
Meeting ended Thu Jun 24 15:09:18 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-24/ansible_core_public_irc_meeting.2021-06-24-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-06-24/ansible_core_public_irc_meeting.2021-06-24-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-24/ansible_core_public_irc_meeting.2021-06-24-15.00.log.html

**Comment by s-hertel** [comment]
Meeting ended Tue Jun 29 19:35:21 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-29/ansible_core_public_irc_meeting.2021-06-29-19.00.html 
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-06-29/ansible_core_public_irc_meeting.2021-06-29-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-06-29/ansible_core_public_irc_meeting.2021-06-29-19.00.log.html
