### ISSUE TITLE
Ansible multiple command output to a single file.

### ISSUE THREAD

**Issue by dheerajwadhw** [ansible/community#617]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

Hi This is tge script that  i am running, i need to capture all 3 command in the commands section 
in one single hostname file, instead of 3 different file, currently this is only saving outout of the 2nd command and if i chnage tghe print_output.stdout to 0 it will print the 1st command but it will not write the output of all command to a single file, 
Pls advise.
 - name: Name servers  
      ios_command: 
        authorize: yes
        provider: "{{ cli }}"
        commands: 
          - show ip name-servers
          - show ip int brief
          - show logging | in host 
          
      register: print_output
      
    - name: save output to a file
      copy: content="{{ print_output.stdout[1] }}" dest="/opt/ansible/dev/Dheeraj/verf/adnan/NTP/{{ inventory_hostname }}.txt"

**Comment by felixfontein** [comment]
Please **read** the issue template which forms the first few lines of your question. Thanks.
