### ISSUE TITLE
How can we get translations of Ansible docs?  

### ISSUE THREAD

**Issue by jillr** [ansible/community#619]
They are currently only available in English.  Most Red Hat product docs are available in English, Japanese, Simplified Chinese, Korean, German, French, Spanish, Italian, Portuguese, Russian, and Taiwanese.

The community team is looking into this
https://meetbot.fedoraproject.org/ansible-community/2021-06-09/ansible_community_meeting.2021-06-09-18.03.log.html#l-56

**Comment by samccann** [comment]
We'll be archiving this repository soon so closing out the open issues. See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928 for details.

for this issue, consider opening up a discussion on the forum.
