### ISSUE TITLE
vmware_guest doesn't poweroff VMs or perform hardware changes

### ISSUE THREAD

**Issue by RobotScience** [ansible/community#620]
Module: [vmware_guest](https://docs.ansible.com/ansible/2.9/modules/vmware_guest_module.html#requirements)

1. Can get VM info from vSphere fine
2. When I attempt to set state to 'shutdownguest' the task executes ok but fails to do anything to the VM (nothing shows in vSphere as happening)
3. When I attempt to set state to 'poweredoff' it states: "Folder is required parameter while deploying new virtual machine" (?)
4. When I manually power down the VM and try to change hardware on the VM it thinks I'm trying to deploy a new VM and tells me: 

![image](https://user-images.githubusercontent.com/15388715/121745621-94017b00-cad2-11eb-8c04-6234950ae317.png)

vSphere: 6.7.0 Build: 18010599

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

**Comment by felixfontein** [comment]
This repository is not for support. Please read the bottom of your question, it includes the part of the issue template which tells you where you can ask for support.
