### ISSUE TITLE
Replacing RSA Keys on ASA

### ISSUE THREAD

**Issue by chuckjamm2001** [ansible/community#622]
I apologize if this is the wrong place to post this.  I'm new to ansible and so I'm looking for help on how to perform a configuration task on a ASA using Ansible.

Below is my playbook:

# This file is used to create RSA Keys and learn how to configure the yaml file to act when the ASA prompts the admin for a response.
# without some type of parameterto permit the admin's input, the play will fail with a timeout message
# ciscoasa# config t
# ciscoasa(config)# crypto key generate rsa modulus 4096
# WARNING: You have a RSA keypair already defined named <Default-RSA-Key>.
# 
# Do you really want to replace them? [yes/no]: yes
# Keypair generation process begin. Please wait...
# ciscoasa(config)# 
---
- name: Generate RSA keys
  hosts: ciscoasa.corp.macstadium.com
  gather_facts: false

  tasks:
    - name: Generate New SSL RSA Keys
      cisco.asa.asa_config:
        lines:
          - crypto key generate rsa label SSL2_VPN modulus 4096
          - crypto key generate rsa modulus 4096
        prompt: Do you really want to replace them?
        answer: yes

Line 0 creates a brand new RSA key while Line 1 is meant to replace the key.  The above comments show how the command would work along with the prompt you have to answer.  My first attempt resulted in my playbook timing out.  All my remaining attempts was trying to use any method I could find to answer the prompt that I know the ASA is asking.  All of my attempts resulted in a 'Unsupported parameter method'.  Right now, I believe that I'm simply using the wrong module for the command that I want to run.  Anyone ever tried the above and was successful?

**Comment by felixfontein** [comment]
Please read the contents of the "New Issue" template:

-----

This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat
* Mailing List: https://groups.google.com/forum/#!forum/ansible-project

-----

Your issue looks like a request for support, so please check out IRC and mailing list specified above. Thanks.
