### ISSUE TITLE
Public Ansible Core Meeting Agenda - July 2021

### ISSUE THREAD

**Issue by s-hertel** [ansible/community#623]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by Shrews** [comment]
zodbot changed the topic to Scheduled Ansible community meetings - check https://github.com/ansible/community for schedule and to add items to the agenda
<@zodbot> Meeting ended Thu Jul  8 16:08:18 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
<@zodbot> Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-07-08/ansible_core_public_irc_meeting.2021-07-08-15.30.html
<@zodbot> Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-07-08/ansible_core_public_irc_meeting.2021-07-08-15.30.txt
<@zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-07-08/ansible_core_public_irc_meeting.2021-07-08-15.30.log.html

**Comment by jborean93** [comment]
[ ] https://github.com/ansible/ansible/pull/75247 - Talk about whether this behaviour is the desired behaviour going forward or whether the docs should just be updated to match the existing behaviour.

**Comment by samdoran** [comment]
Meeting ended Thu Jul 22 15:50:17 2021 UTC.
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-07-22/ansible_core_public_irc_meeting.2021-07-22-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-07-22/ansible_core_public_irc_meeting.2021-07-22-15.03.log.html

**Comment by jborean93** [comment]
Meeting ended Tue Jul 27 19:10:32 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-07-27/ansible_core_public_irc_meeting.2021-07-27-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-07-27/ansible_core_public_irc_meeting.2021-07-27-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-07-27/ansible_core_public_irc_meeting.2021-07-27-19.00.log.html
