### ISSUE TITLE
Public Ansible Core Meeting Agenda - August 2021

### ISSUE THREAD

**Issue by jborean93** [ansible/community#626]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by s-hertel** [comment]
Meeting ended Thu Aug  5 15:13:37 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-05/ansible_core_public_irc_meeting.2021-08-05-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-08-05/ansible_core_public_irc_meeting.2021-08-05-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-05/ansible_core_public_irc_meeting.2021-08-05-15.00.log.html

**Comment by nitzmahone** [comment]
Meeting ended Tue Aug 10 19:07:55 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-10/ansible_core_public_irc_meeting.2021-08-10-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-08-10/ansible_core_public_irc_meeting.2021-08-10-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-10/ansible_core_public_irc_meeting.2021-08-10-19.00.log.html

**Comment by bcoca** [comment]
no items

Meeting ended Thu Aug 19 15:09:35 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-19/ansible_core_public_irc_meeting.2021-08-19-14.57.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-08-19/ansible_core_public_irc_meeting.2021-08-19-14.57.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-08-19/ansible_core_public_irc_meeting.2021-08-19-14.57.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Aug 24 19:31:05 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021/ansible-meeting.2021-08-24-19.02.html
Minutes (text): https://meetbot.fedorparoject.org/ansible-meeting/2021/ansible-meeting.2021-08-24-19.02.txt
Log: ansible-meeting/2021/ansible-meeting.2021-08-24-19.02.log.html

**Comment by s-hertel** [comment]
- [ ] https://github.com/ansible/ansible/pull/75468

Too noisy? Any objections to handling non-HTTPError exceptions more flexibly?
