### ISSUE TITLE
Error reading config file (/etc/ansible/ansible.cfg): File contains parsing errors: <???>

### ISSUE THREAD

**Issue by thegaintserver** [ansible/community#627]
ansible is my user on server, when I'm running the below command then I'm getting this error
[ansible@ip-172-31-**-*** ~]$ **ansible demo --list-hosts**

Error reading config file (/etc/ansible/ansible.cfg): File contains parsing errors: <???>
        [line 14]: u' inventory      = /etc/ansible/hosts\n'
        [line 22]: u' sudo_user      = root\n'

Can anybody ansible user help me on this?

**Comment by felixfontein** [comment]
Please read the issue template before posting here:


This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
