### ISSUE TITLE
Public Ansible Core Meeting Agenda - September 2021

### ISSUE THREAD

**Issue by mkrizek** [ansible/community#628]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by mkrizek** [comment]
- [ ] https://github.com/ansible/ansible/pull/75468

Too noisy? Any objections to handling non-HTTPError exceptions more flexibly?

_Originally posted by @s-hertel in https://github.com/ansible/community/issues/626#issuecomment-910508676_

**Comment by s-hertel** [comment]
Meeting ended Thu Sep  2 15:24:01 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021/ansible-meeting.2021-09-02-15.00.html
Minutes (text): https://meetbot.fedorparoject.org/ansible-meeting/2021/ansible-meeting.2021-09-02-15.00.txt
Log: ansible-meeting/2021/ansible-meeting.2021-09-02-15.00.log.html

**Comment by jborean93** [comment]
Meeting ended Tue Sep  7 19:07:44 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-09-07/ansible_core_public_irc_meeting.2021-09-07-19.00.html
Minutes (text): https://meetbot.fedorparoject.org/ansible-meeting/2021-09-07/ansible_core_public_irc_meeting.2021-09-07-19.00.txt
Log: https://meetbot.fedorparoject.org/ansible-meeting/2021-09-07/ansible_core_public_irc_meeting.2021-09-07-19.00.log.html

**Comment by mkrizek** [comment]
Meeting ended Thu Sep 16 15:07:38 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-09-16/ansible_core_public_irc_meeting.2021-09-16-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-09-16/ansible_core_public_irc_meeting.2021-09-16-15.00.txt
 Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-09-16/ansible_core_public_irc_meeting.2021-09-16-15.00.log.html
