### ISSUE TITLE
Public Ansible Core Meeting Agenda - October 2021

### ISSUE THREAD

**Issue by jborean93** [ansible/community#631]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by jborean93** [comment]
Meeting ended Tue Oct  5 19:09:13 2021 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-10-05/ansible_core_public_irc_meeting.2021-10-05-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-10-05/ansible_core_public_irc_meeting.2021-10-05-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-10-05/ansible_core_public_irc_meeting.2021-10-05-19.00.log.html

**Comment by felixfontein** [comment]
- [ ] Add similar plugins to the `a_module` test (https://github.com/ansible-collections/community.general/pull/3628) and the `collection_version` lookup (https://github.com/ansible-collections/community.general/pull/3633) to ansible-core.

**Comment by bcoca** [comment]
Meeting ended Tue Nov  2 19:33:52 2021 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-11-02/core_public_irc_meeting.2021-11-02-19.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-11-02/core_public_irc_meeting.2021-11-02-19.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-11-02/core_public_irc_meeting.2021-11-02-19.03.log.html
