### ISSUE TITLE
Devtools working group IRC community meeting

### ISSUE THREAD

**Issue by ganeshrn** [ansible/community#633]
The issue is created to discuss starting a new ansible community meeting focussed toward [Ansible devtools](https://github.com/ansible/community/wiki/Ansible-developer-tools). We are looking for feedback on points like
*  Is a new community meeting required in first place? :-)
* Frequency of the meeting (weekly/bi-weekly/monthly)
* Timing of the meeting
* Location (irc channel) for the meeting

**Comment by samccann** [comment]
As a reminder, we will archive this repository and close out all open issues on January 5, 2024.   Working groups are forming in the [Ansible forum](https://forum.ansible.com/t/requesting-a-forum-group/503).
