### ISSUE TITLE
Public Ansible Core Meeting Agenda - Decembre 2021

### ISSUE THREAD

**Issue by bcoca** [ansible/community#637]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by bcoca** [comment]
- [ ] Type hinting in core https://github.com/ansible/community/issues/635#issuecomment-966636254

**Comment by bcoca** [comment]
- [ ] validate-modules add plugins https://github.com/ansible/ansible/pull/71734 (felixfontain)

**Comment by bcoca** [comment]
- [ ] should we normalize passing lists to lookups? https://github.com/ansible/ansible/pull/76388

**Comment by rabin-io** [comment]
I would like to add this [issue](https://github.com/ansible/ansible/issues/16305) to the agenda:
> https://github.com/ansible/ansible/issues/16305
