### ISSUE TITLE
Public Ansible Core Meeting Agenda - March 2022

### ISSUE THREAD

**Issue by s-hertel** [ansible/community#649]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by s-hertel** [comment]
* [ ] Should we add a generic alias for `hosts`? https://github.com/ansible/ansible/issues/50181

**Comment by felixfontein** [comment]
- [ ] Handle errors during ansible-doc --metadata-dump more gracefully https://github.com/ansible/ansible/pull/77035
- [ ] validate-modules for plugins: do some more schema validations so that some issues that are currently reported for modules are also reported for plugins https://github.com/ansible/ansible/pull/77268

**Comment by s-hertel** [comment]
Meeting ended Tue Mar 22 19:54:18 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-03-22/ansible_core_public_irc_meeting.2022-03-22-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-03-22/ansible_core_public_irc_meeting.2022-03-22-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-03-22/ansible_core_public_irc_meeting.2022-03-22-19.05.log.html
