### ISSUE TITLE
Add module testing info to new_module boilerplate

### ISSUE THREAD

**Issue by gregdek** [ansible/community#65]
So people who look at the PR know how to test it.

**Comment by gregdek** [comment]
Still useful.

**Comment by gundalow** [comment]
For 2.3 I'll be refactoring most of developing_modules.html once that's done it will be easier for people to find things, and to link to specific parts of the process. 

I link the idea of the Bot linking to relevant information.

**Comment by gregdek** [comment]
@gundalow is this now part of developing_modules or its successors?

**Comment by gundalow** [comment]
tracked else where
