### ISSUE TITLE
Amazon Web Services Working Group Agenda - 2022

### ISSUE THREAD

**Issue by alinabuzachis** [ansible/community#654]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution join us on:
- IRC Channel: `#ansible-aws`
- Matrix Room: [#aws:ansible.com](https://matrix.to/#/#aws:ansible.com)

**Comment by marknet15** [comment]
**Possible discussion points:**
- Clarity on update path for module_utils in say amazon.aws and then modules consuming it in community.aws. Probably this will be less of an issue soon when a chunk of the modules get promoted to amazon.aws. But either way it might be a good thing to document.
- Tests stability, currently it's quite a regular occurance to have to run `recheck` / `regate` that slows things down, is there anything we could do to improve either through hardening of the tests themselves and or making the retries automatic ?

**PRs for next community release ?**
- https://github.com/ansible-collections/community.aws/pull/973
- https://github.com/ansible-collections/community.aws/pull/972
- https://github.com/ansible-collections/community.aws/pull/963
- https://github.com/ansible-collections/community.aws/pull/940

Possible also:
- https://github.com/ansible-collections/community.aws/pull/827

**Comment by markuman** [comment]
Unfortunately I probably won't be able to attend on our first meeting. It's week 1 after our quarantine and we have to find our rhythm here first.

**Comment by markuman** [comment]
#### backporting lifetime

How long long do we maintain backport releases?  
`stable-1` for example seems to be dead for me.

**Comment by jillr** [comment]
> #### backporting lifetime
> How long do we maintain backport releases? `stable-1` for example seems to be dead for me.

I probably won't make the next meeting.  for community.aws we can set any support cycle we like, for amazon.aws though we need to have the branches for anything that we still provide downstream Red Hat support for. stable-1 is still eligible for security fixes (but not feature backports).

**Comment by markuman** [comment]
### purge_tags default value

> Let's undo this breaking change, but also look at how we want to do this. About 3 quarters of our modules that support managing tags default to purge_tags=True behaviour today (some even nuke tags if you don't set the tags parameter)  

https://github.com/ansible-collections/community.aws/pull/1064

**Comment by tremble** [comment]
@jillr Is 1.x eligible?  I thought Ansible 2.9 had the modules still in ansible/ansible, so while we might need to backport over to the old repo but not necessarily into a 1.x release.

Which supported release has 1.x rather than 2.x+ ?

**Comment by tremble** [comment]
- [ ] 4.0.0 Release schedule - We have various deprecations slated for 2022-06-01, pull them in and release in June?

**Comment by tremble** [comment]
- [ ] 4.0.0 Release planning - Once we have a schedule let's decide on significant features (if any)

**Comment by jillr** [comment]
@tremble 
> Which supported release has 1.x rather than 2.x+ ?

AAP 2.1 included supported Execution Environment version 1.1, with amazon.aws 1.5

**Comment by mandar242** [comment]
- [ ] route53_info returns CamelCase, should have consistency along modules to use snake_case that can be used as a input to other modules directly, but modifying this might break existing playbooks for route53_info

**Comment by markuman** [comment]
> * [ ]  route53_info returns CamelCase, should have consistency along modules to use snake_case that can be used as a input to other modules directly, but modifying this might break existing playbooks for route53_info

does it break backwards compatibility, when the return values are not documentated yet? :)

imo it must be a general compliance that _info modules returns snake_case.  
and a follow up discussion: shall `_info` module output parameter names match the input parameter names?

* anti-example: `ec2_group` and `ec2_group_info`
* positive example: `wafv2_ip_set` and `wafv2_ip_set_info`

**Comment by tremble** [comment]
> does it break backwards compatibility, when the return values are not documentated yet? :)

IMO, yes.  Our docs have historically been rather lacking in completeness and accuracy when it comes to the return values, so consumers of modules have had no choice but to rely on what's been historically returned.  One work around can be to add a new return value and return the new data structure in there.

**Comment by jatorcasso** [comment]
[ ] lambda_info returns a dict of dicts as opposed to list of dicts. Should probably return list of dicts for consistency, but that would be a breaking change. Short term fix could be to add new return value representing the list, and deprecating the old

**Comment by tremble** [comment]
- [ ] Sanity checks now that Ansible 2.9 and 2.10 support has been dropped upstream...

**Comment by tremble** [comment]
Minutes from the May meeting:

Minutes (text): https://meetbot.fedoraproject.org/ansible-aws/2022-05-26/ansible_aws_community_meeting.2022-05-26-17.33.txt
21:15
Log: https://meetbot.fedoraproject.org/ansible-aws/2022-05-26/ansible_aws_community_meeting.2022-05-26-17.33.log.html

All topics up to this point were covered.

**Comment by jillr** [comment]
- [ ] ADR proposal
We've started using [Architectural Decision Records](https://adr.github.io/) in the Cloud Control API code generator (https://github.com/ansible-collections/amazon_cloud_code_generator/tree/main/docs/adr)

As we make decisions that effect the amazon.aws and community.aws repos, we could adopt ADRs (or something similar) in these repos too.  Things like the recent conversations about returns values, in addition to being recorded in the documentation, could also be codified as ADRs in the repo.
Questions:
1. Should we do this?
2. Where should ADRs be kept (ie; all in amazon.aws? in both repos? something else?) 
3. Should we try to backfill previous decisions that have been made in irc, PR discussions, etc?

**Comment by tremble** [comment]
> * Should we do this?

I'm a generally +1

> * Where should ADRs be kept (ie; all in amazon.aws? in both repos? something else?)

In general I'd suggest either amazon.aws or something separate, and we move the WG agenda there too.
 
> * Should we try to backfill previous decisions that have been made in irc, PR discussions, etc?

I think it would be valuable to try and capture the decisions we've made in the past, so at least some of the background is recorded "somewhere".

**Comment by tremble** [comment]
- [ ] Proposed module naming guidelines https://github.com/ansible-collections/amazon.aws/pull/881

**Comment by mandar242** [comment]
> * [ ]  route53_info returns CamelCase, should have consistency along modules to use snake_case that can be used as a input to other modules directly, but modifying this might break existing playbooks for route53_info

Fixed by https://github.com/ansible-collections/community.aws/pull/1236

**Comment by tremble** [comment]
- [] Tentative release dates for 6.0.0.  We have a number of deprecations slated for "a release after 2022-12-01".  I suggest we pencil in a 6.0.0 release date of 2022-12-06 (as a gift from St Nicholas, and ~ quarterly) or 2023-03-02 as an "~6 monthly" release schedule.

**Comment by alinabuzachis** [comment]
This is continued in https://github.com/ansible/community/issues/687. From now on we will have one issue per year.
