### ISSUE TITLE
Public Ansible Core Meeting Agenda - April 2022

### ISSUE THREAD

**Issue by bcoca** [ansible/community#657]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by bcoca** [comment]
note: nothing discussed, no agenda/no attendees with requests

Meeting ended Thu Apr 14 15:17:33 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-04-14/ansible_core_public_irc_meeting.2022-04-14-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-04-14/ansible_core_public_irc_meeting.2022-04-14-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-04-14/ansible_core_public_irc_meeting.2022-04-14-15.01.log.html

**Comment by s-hertel** [comment]
Meeting ended Tue May  3 19:19:46 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-05-03/ansible_core_public_irc_meeting.2022-05-03-19.12.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-05-03/ansible_core_public_irc_meeting.2022-05-03-19.12.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-05-03/ansible_core_public_irc_meeting.2022-05-03-19.12.log.html
