### ISSUE TITLE
PostgreSQL Working Group request

### ISSUE THREAD

**Issue by hunleyd** [ansible/community#659]
WORKING GROUP NAME:    [ PostgreSQL Working Group ]

WORKING GROUP PURPOSE:
[ This working group is to review  ]
[ all PostgreSQL-related modules   ]

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
[ Matrix: andersson007_ / GitHub: @Andersson007 ]
[ Matrix: hunleyd / GitHub: @hunleyd ]
[ Matrix: jchancojr / GitHub: @jchancojr ]

**Comment by Andersson007** [comment]
i think our WG page is https://github.com/ansible-collections/community.postgresql/wiki/PostgreSQL-Working-Group (oh, we need to update it).
You can add our room and WG info to https://docs.ansible.com/ansible/latest/community/communication.html#working-groups which lives in the https://github.com/ansible/ansible repo and submit a PR
