### ISSUE TITLE
Public Ansible Core Meeting Agenda

### ISSUE THREAD

**Issue by bcoca** [ansible/community#661]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on libera.chat

**Comment by mikedlr** [comment]
I'm not sure what the current correct forum would be (community?) however I'd like to discuss Ansible Galaxy and what it's future is. As far as I can tell it officially remains the primary location for ansible content (roles/collections etc) but at the same time it's not practically working for new users since [they can't sign up to it](https://github.com/ansible/galaxy/issues/2775#issuecomment-1147821960). 

Is Galaxy now considered to be replaced by some other core feature? If so, how could the documentation be updated? If not, how could we get attention to Galaxy to make it work?

**Comment by s-hertel** [comment]
@mikedlr That seems like it may be a bug, but this is the first I've heard of it. You may want to ask in the #ansible-galaxy IRC channel.

**Comment by nkakouros** [comment]
- https://github.com/ansible/ansible/issues/77664
- https://github.com/ansible/ansible/issues/77765

**Comment by nikaro** [comment]
Can this backport PR be merge for the next release?
https://github.com/ansible/ansible/pull/78261

**Comment by bcoca** [comment]
Meeting ended Thu Jul 14 16:18:49 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-07-14/ansible_core_public_irc_meeting.2022-07-14-16.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-07-14/ansible_core_public_irc_meeting.2022-07-14-16.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-07-14/ansible_core_public_irc_meeting.2022-07-14-16.02.log.html

**Comment by ssbarnea** [comment]
Addressing the 6+ years old complaint about enforced-wrapping of text output. I happened to create a PR that should fix it, https://github.com/ansible/ansible/pull/78515 so maybe now there is a chance to address it.

**Comment by s-hertel** [comment]
Meeting ended Thu Aug 11 16:21:43 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-08-11/ansible_core_public_irc_meeting.2022-08-11-15.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-08-11/ansible_core_public_irc_meeting.2022-08-11-15.59.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-08-11/ansible_core_public_irc_meeting.2022-08-11-15.59.log.html

**Comment by felixfontein** [comment]
- [ ] https://github.com/ansible/ansible/pull/79218 (ref: https://github.com/ansible-community/community-topics/issues/154)

**Comment by s-hertel** [comment]
Meeting ended Thu Nov 10 16:10:48 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-11-10/ansible_core_public_irc_meeting.2022-11-10-16.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-11-10/ansible_core_public_irc_meeting.2022-11-10-16.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-11-10/ansible_core_public_irc_meeting.2022-11-10-16.01.log.html

**Comment by s-hertel** [comment]
Meeting ended Thu Dec  8 16:06:07 2022 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
11:06 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2022-12-08/ansible_core_public_irc_meeting.2022-12-08-16.00.html
11:06 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2022-12-08/ansible_core_public_irc_meeting.2022-12-08-16.00.txt
11:06 Log: https://meetbot.fedoraproject.org/ansible-meeting/2022-12-08/ansible_core_public_irc_meeting.2022-12-08-16.00.log.html

**Comment by felixfontein** [comment]
- [ ] https://github.com/ansible/ansible/pull/79370
- [ ] https://github.com/ansible/ansible/pull/77737
- [ ] https://github.com/ansible/ansible/pull/79471

**Comment by s-hertel** [comment]
Meeting ended Thu Jan 12 17:00:34 2023 UTC. Information about Zodbot's MeetBot at https://fedoraproject.org/wiki/Zodbot#Meeting_Functions .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2023-01-12/ansible_core_public_irc_meeting.2023-01-12-16.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2023-01-12/ansible_core_public_irc_meeting.2023-01-12-16.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2023-01-12/ansible_core_public_irc_meeting.2023-01-12-16.00.log.html

**Comment by felixfontein** [comment]
Discuss whether to have this meeting in a more async form. This was suggested by @bcoca on IRC and I fully support this. Since I very likely won't be around for the next meeting, I'm writing this here ;-)

**Comment by sivel** [comment]
The Core team has decided to end the scheduled IRC meetings.  Please come see us in #ansible-devel for adhoc discussions.
