### ISSUE TITLE
ansible 2.4.2.0 PLAY RECAP How to show : ok=38   changed=12   unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

### ISSUE THREAD

**Issue by kenzero3** [ansible/community#663]
my ansible playbook  PLAY RECAP:
192.168.50.219                      : ok=2    changed=1    unreachable=0    failed=1   
192.168.50.218                     : ok=2    changed=1    unreachable=0    failed=1 

I support it show :
192.168.50.219             : ok=38   changed=12   unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

**Comment by Andersson007** [comment]
@kenzero3 hello, thanks for reaching out to the community

- If you have any user-side questions, you can ask them on Matrix in the `#users:ansible.com` channel. See the [communication guide](https://docs.ansible.com/ansible/devel/community/communication.html) to learn how to join.
- If you'd like to submit a bug report, see the [contributor guide](https://docs.ansible.com/ansible/devel/community/reporting_bugs_and_features.html).

This repository is for a different purpose as written in its [README](https://github.com/ansible/community/blob/main/README.md) file.
