### ISSUE TITLE
Is it possible to store a playbook execution time in a variable?

### ISSUE THREAD

**Issue by naveenkumar-j** [ansible/community#666]
Is it possible to store a playbook execution time in a variable?

In AWX while running a playbook we can able to see the execution time. In which variable that execution time will be stored?

Thanks in advance!

**Comment by felixfontein** [comment]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
