### ISSUE TITLE
Ansible Edge Automation Working Group Agenda - Nov 2022

### ISSUE THREAD

**Issue by maxamillion** [ansible/community#667]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your Matrix nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/tree/master/group-edge for the schedule

Meetings are held in the [#edge:ansible.com](https://matrix.to/#/#edge:ansible.com) Matrix Channel.

**Comment by samccann** [comment]
As a reminder, we will archive this repository and close out all open issues on January 5, 2024.   Working groups are forming in the [Ansible forum](https://forum.ansible.com/t/requesting-a-forum-group/503).
