### ISSUE TITLE
Storage Working Group request

### ISSUE THREAD

**Issue by sdodsley** [ansible/community#670]
WORKING GROUP NAME: [ Storage Working Group ]

WORKING GROUP PURPOSE:
[ This working group is to review ]
[ all external storage-related modules ]

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
[ Matrix: sdodsley / GitHub: @sdodsley ]
[ Matrix: coreywan / GitHub: @coreywan]

**Comment by Andersson007** [comment]
@sdodsley hello, thanks for opening the ticket!
How exactly can we help?

**Comment by Andersson007** [comment]
@sdodsley sorry for the late reply, was on a sick leave yesterday.
1. We usually specify WGs in corresponding repositories' wikis, e.g. https://github.com/ansible-collections/community.postgresql/wiki/PostgreSQL-Working-Group. If it doesn't belong to a single repo, I think we could create the WG wiki page here.
2. You don't need any addition permissions to create a Matrix room. If there are no [appropriate room](https://docs.ansible.com/ansible/devel/community/communication.html#working-groups) already, you can create a new one following the steps from the [Matrix FAQ](https://hackmd.io/@ansible-community/community-matrix-faq#How-do-I-create-a-public-community-room).

If the area of the WG is narrow enough (for example, if it relates to certain appliances, etc.) I would suggest reflecting this in the Matrix channel name as well. Just in case in future there will be a need for a general storage Matrix room, there will be no collisions.

@gundalow have I missed anything?

**Comment by sdodsley** [comment]
@Andersson007 I don't have permissions in Matrix/Element to create a new room.
I wondered if we could use something like https://github.com/ansible/community/group-storage as our home page

**Comment by Andersson007** [comment]
> @Andersson007 I don't have permissions in Matrix/Element to create a new room. I wondered if we could use something like https://github.com/ansible/community/group-storage as our home page

@sdodsley we noticed that https://github.com/ansible/community/blob/main/WORKING-GROUPS.md#requesting-a-working-group (and another content in this repo like README) is outdated and needs to be revised. We'll do it ASAP.

AFAIK we don't need any special permissions to create rooms under the `matrix.org` space (you probably tried to do it under `ansible.com`). But I can create the room for you, no problem, how it should be named?

Thanks

**Comment by sdodsley** [comment]
@Andersson007 can you name the room `ansible-storage`?

**Comment by Andersson007** [comment]
> @Andersson007 can you name the room `ansible-storage`?

@sdodsley ok, if it's available on matrix org it'll be `ansible-storage:matrix.org`
How about adding the alias `storage:ansible.com`? it'll be like its official name (including on docs.ansible.com)

**Comment by sdodsley** [comment]
sounds good

**Comment by Andersson007** [comment]
- [ ] Created https://matrix.to/#/#storage:ansible.com , invited you
- [ ] Created https://github.com/ansible/community/wiki/Storage , you should be able to edit it (let me know if you can't). You could use any other WGs there as an example to fill up the page. See the list in https://docs.ansible.com/ansible/devel/community/communication.html
- [ ] Created a PR https://github.com/ansible/ansible/pull/79359 to add the WG info to docs.ansible.com

@sdodsley waiting for your feedback

**Comment by sdodsley** [comment]
@Andersson007 thanks for setting these up.
I'd like to bridge the matrix room with the #ansible-storage IRC channel in Libera.Chat and also with a Slack channel Pure has for Ansible. How do I get these set up?
I'd also like a `storage` label added to the Ansible GitHub repos if possible.

**Comment by sdodsley** [comment]
Yes, this is a vendor agnostic working group.
Is there a limit to the number of Slack channel we can bridge?
There is an active community in the Pure Slack channel, hence why I'd like to bridge to it, but I was hoping that other vendors could bridge in as well, assuming they have equivalent channels.

**Comment by Andersson007** [comment]
bridged #ansible-storage:libera.chat with #ansible-storage:ansible.com

**Comment by GregSutcliffe** [comment]
> There is an active community in the Pure Slack channel, hence why I'd like to bridge to it

How active are we talking here? There is a cost to us for Slack bridges, so we need to make sure we're able to cover it. The mapping is channel-to-room, so you'd want to identify the best room on their workspace for bridging into the Matrix room, and if you had an idea of the number of active users / month (roughly is fine, no need to go digging deep), that would be very useful.

>  Is there a limit to the number of Slack channel we can bridge?

We've not tried multiple Slack Workspaces in a single room, so that would have to be investigated. Worst case we could create more than one room, but that's obviously not ideal. We can test it out as/when we have a second vendor to add in.

**Comment by Andersson007** [comment]
>I'd also like a storage label added to the Ansible GitHub repos if possible.

I would avoid adding the label globally across the ansible-collections org as, afaik, most of the repos there aren't storage related (i think other maintainers can be not happy with it)
You can add the labels to repos you have write access in. If there are some storage-related ones you haven't permissions in, please give me a list.

**Comment by sdodsley** [comment]
@GregSutcliffe There are currently 154 registered users in the Pure Ansible Slack channel.

**Comment by GregSutcliffe** [comment]
Thanks. I'm interested in the number of active users, which I know is harder to answer - but we can obviously assume it's less than 154 :stuck_out_tongue: 

I'll check and see if we can fund the bridge, stay tuned :)

**Comment by carchi8py** [comment]
Is it possible to have both slack and discord mapped? Though for our discord link it specific to Netapp ansible collection and not a general storage channel.  RIght now I don't know if we would want it mapped, this is more of a, if we do in the future, question.

we have this many online at the moment. [![Discord](https://img.shields.io/discord/855068651522490400)](https://discord.gg/NetApp)

**Comment by GregSutcliffe** [comment]
Yes, that should work, although again the bridge has a cost associated. What makes it hard to calculate is that the cost is per Remote Active User - that is, the number of people that actually *say* something (or use reactions) in a period. Just being online doesn't trigger it (fortunately).

**Comment by Andersson007** [comment]
Dear WG leaders, please consider [requesting](https://forum.ansible.com/t/requesting-a-forum-group/503) a forum group and use it instead of wiki pages (if you didn't do it yet).
after that:
- consider replacing the wiki page's content with a link to forum
- raise a PR against the [Communication guide](https://docs.ansible.com/ansible/devel/community/communication.html) to change a corresponding reference
- announce and invite people to join your new shiny forum group on Matrix and via [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn)

**Comment by samccann** [comment]
We are in the process of archiving the ansible/community repository. See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928 for details. As in the prior comment, consider using the forum to conintu the discussions in this issue.
