### ISSUE TITLE
aap_config_as_code Working group

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/community#671]
WORKING GROUP NAME:    [ aap_config_as_code   ]

WORKING GROUP PURPOSE:
[ Example: This working group is to review  ]
[ all configuration as code modules ]
[such as controller_configuration and ah_configuration ]

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
[ IRC: @ssulliva:[matrix.org](http://matrix.org/) / GitHub: @ sean-m-sullivan ]
[ IRC: @djdanielsson:[matrix.org](http://matrix.org/) / GitHub: @djdanielsson   ]

After AnsibleFest feedback thought it might be good to create a working group around the redhat_cop collections, that deal with configuring aap, using the existing infrastructure around community.

**Comment by Andersson007** [comment]
@sean-m-sullivan hello, thanks for creating the issue!

A couple of questions:
1. If we create a Matrix room called `#aap_configuration:ansible.com`, will it be OK? Maybe you have anything better on your mind?
2. Is there any repository related to stuff the WG is working on? If yes, I suggest creating a corresponding wiki page there. Then we will add the link to it to docs.ansible.com. If there's no main repo, we can create WG's page here, no problem. Let me know.

Thanks

**Comment by sean-m-sullivan** [comment]
We've created a wiki here to link to, that lists the repos that we maintain. Going to work on fleshing that out as well.

**Comment by djdanielsson** [comment]
@Andersson007 I think we decided that aap_config_as_code is a more accurate name. and Sean just created a wiki page https://github.com/redhat-cop/controller_configuration/wiki/AAP-Configuration-as-Code that you can link to.

**Comment by Andersson007** [comment]
For myself:
- [ ] Create https://matrix.to/#/#ansible_aap_config_as_code:ansible.com
- [ ] Add it + WG link to docs.ansible.com
- [ ] Announce the room in Bullhorn

**Comment by Andersson007** [comment]
UPDATE: changed main alias to https://matrix.to/#/#aap_config_as_code:ansible.com

**Comment by Andersson007** [comment]
@sean-m-sullivan @djdanielsson would you like to announce the new room in [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn)? If no time or whatever, let me know, I'll do it, np

**Comment by sean-m-sullivan** [comment]
I am working on a multipart announcement for this week, will take care of it, just realized we were to late for last week so wanted to put some things in it.

**Comment by Andersson007** [comment]
> I am working on a multipart announcement for this week, will take care of it, just realized we were to late for last week so wanted to put some things in it.

SGTM thanks! We should not forget to close this issue after that

**Comment by sean-m-sullivan** [comment]
Closing as that task is done, we put it in social and alerted the bot.

**Comment by Andersson007** [comment]
Dear WG leaders, please consider [requesting](https://forum.ansible.com/t/requesting-a-forum-group/503) a forum group and use it instead of wiki pages (if you didn't do it yet).
after that:
- consider replacing the wiki page's content with a link to forum
- raise a PR against the [Communication guide](https://docs.ansible.com/ansible/devel/community/communication.html) to change a corresponding reference
- announce and invite people to join your new shiny forum group on Matrix and via [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn)
