### ISSUE TITLE
Ansible Storage Working Group Agenda - Dec 2022

### ISSUE THREAD

**Issue by sdodsley** [ansible/community#675]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your Matrix nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/tree/master/group-storage for the schedule

Meetings are held in the [#storage:ansible.com](https://matrix.to/#/#storage:ansible.com) Matrix Channel.

**Comment by samccann** [comment]
As a reminder, we will archive this repository and close out all open issues on January 5, 2024.
