### ISSUE TITLE
Irc contact not provided on Docs

### ISSUE THREAD

**Issue by ggold7046** [ansible/community#677]
This repository is for management of all Ansible *community* related initiatives, such as meetings.

**Ansible Support**

* Bug reports: https://github.com/ansible/ansible/issues/new
* IRC: #ansible on irc.libera.chat   * Mailing List: https://groups.google.com/forum/#!forum/ansible-project

I see no IRC contact is provided on this https://github.com/ansible/community/wiki/Docs link. It would be convenient if we could provide the IRC contact along with the Matrix.

**Comment by samccann** [comment]
@ggold7046  - thanks for the catch! updated to add IRC contact.
