### ISSUE TITLE
Figure out how to make amazon or other specialized module guidelines more prominent

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#69]
Per irc discussion today in new module meeting re: boto2-using new modules:

11:29 @rbergeron MichaelBaydoun: did you read the amazon guidelines, or just the regular 
                   guidelines? 
11:29 @rbergeron just curious if you knew they existed or not
11:30 @rbergeron that way we know if we need to more prominently show that information 
                   somewhere
11:30 < MichaelBaydoun> Module guidelines first, then stumbled on the cloud/amazon guidelines 
                        by accident

Others are making the same mistakes, so probably need to fix this.

**Comment by robynbergeron** [comment]
(not really mistakes, just not following guidelines as written because they aren't seeing them possibly)

**Comment by gregdek** [comment]
This will be a part of SIG governance.
