### ISSUE TITLE
Requesting for new working group for Release Management 

### ISSUE THREAD

**Issue by anweshadas** [ansible/community#700]
WORKING GROUP NAME:    Release Management 

WORKING GROUP PURPOSE:

To discuss, improve and carry on the release process of the Release Management in Ansible Ecosystem. We initiating the discussion in the group with invite only.

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
[ Matrix/Libera.Chat IRC: / GitHub: @gotmax23          ]
[ Matrix/Libera.Chat IRC: / GitHub: @felixfontein  ]
[ Matrix/Libera.Chat IRC: / GitHub: @webknjaz  ]
[ Matrix/Libera.Chat IRC: / GitHub: @mariolenz  ]
[ Matrix/Libera.Chat IRC: anwesha / GitHub: @anweshadas  ]
[ Matrix/Libera.Chat IRC: chadams / GitHub: @rooftopcellist  ]

REAL-TIME CHAT CHANNEL: Matrix: #release-management:ansible.com | Libera.Chat IRC: #ansible-release-management 
( they need to be created)

**Comment by gotmax23** [comment]
Thanks for filing this @anweshadas! I'm excited about the new group, and I'll do my best to contribute when I have time.

**Comment by felixfontein** [comment]
I can only second @gotmax23: thank you very much @anweshadas!

My Libera.Chat IRC nick is `felixfontein` BTW.

**Comment by Andersson007** [comment]
working on this

**Comment by Andersson007** [comment]
Question: is irc really necessary here? We have several other active rooms w/o IRC and it works well.
Let's be modern and start with Matrix?

**Comment by Andersson007** [comment]
I've created the Matrix room and invited you all, fyi
@anweshadas please create a wiki page for the WG here (you can use existing ones as examples) or anywhere else and give me its URL so that i'll put it on docs.ansible.com together with the matrix room link

**Comment by Andersson007** [comment]
The group has been created https://forum.ansible.com/g/release-managers
I'll update the communication guide
