### ISSUE TITLE
Delete or archive community.lbry collection

### ISSUE THREAD

**Issue by rhysmeister** [ansible/community#702]
Hi All,

Would it be possible for the community.lbry repo to be deleted or archived? For a number of reasons it's not going to go anywhere.

https://github.com/ansible-collections/community.lbry

Cheers,

Rhys

**Comment by felixfontein** [comment]
Archiving makes more sense than deleting, especially since it has already been released: https://galaxy.ansible.com/ui/repo/published/community/lbry/

It should also be deprecated on Galaxy, though I have no idea on how to do that, or if it's even possible...

**Comment by rhysmeister** [comment]
Deprecation seems possible: one example https://galaxy.ansible.com/ui/repo/published/joe_opensrc/percona_mongodb_col/

**Comment by Andersson007** [comment]
yes, it's just appeared. Closing the issue, thanks
