### ISSUE TITLE
Move the ansible/community repository to the ansible-community GitHub org

### ISSUE THREAD

**Issue by samccann** [ansible/community#707]
The goal is to move the content to the ansible-community GitHub organization that is under community control and archive or otherwise freeze the ansible/community repository for any future changes.

See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928/7 for details of the move.

**Comment by Andersson007** [comment]
Great idea, thanks! If there's anything else to close, i think it might be worth mentioning the forum along the way.

**Comment by samccann** [comment]
Goal is to archive this repo at the end of this year as that will match when most working groups start a new agenda (and can thus start in the Forum instead of here).

**Comment by samccann** [comment]
All items have been moved. See the forum discussion linked in the description for complete details. This repository will be archived tomorrow, Jan 5th 2024.
