### ISSUE TITLE
"adoptme" report

### ISSUE THREAD

**Issue by gregdek** [ansible/community#72]
Send a weekly email with a list of all modules that are core_review and could benefit from at least one community maintainer.

**Comment by MichaelBaydoun** [comment]
Which email list?

**Comment by gregdek** [comment]
Actually, I'm going to close this because I don't think it's the right approach. The right approach is to recruit people who offer PRs to become maintainers -- because if they care enough to submit a PR for a module, that means they're using that module actively enough to care about its upkeep. And since we've already got a PR for ansibullbot in the works, I'm closing this one.
