### ISSUE TITLE
"Welcome to the Ansible's mailing list / forum!"

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#74]
Oh, this is making me cringe. 

https://groups.google.com/forum/#!forum/ansible-project

Can we fix this grammar? I have no idea who manages (I might even be able to but not digging this second)

**Comment by mckerrj** [comment]
I think Jimi has control of this. @jimi-c

**Comment by jimi-c** [comment]
Fixed:
<pre>
Welcome to Ansible's mailing list / forum!
</pre>
If that's all you wanted cleaned up?
