### ISSUE TITLE
Module Maintainer Guidelines

### ISSUE THREAD

**Issue by gregdek** [ansible/community#81]
https://ansible.sivel.net/pr/byfile.html

**Comment by gundalow** [comment]
See also #5

**Comment by gregdek** [comment]
3:04 PM <gundalow> What's #81 for?
3:04 PM <•gregdek> Anyway.
3:04 PM <•gregdek> #topic community/81
3:04 PM •zodbot set the topic: community/81 (Meeting topic: community)
3:04 PM <•gregdek> It's a great tool that sivel set up. Check it:
3:04 PM <•gregdek> https://ansible.sivel.net/pr/byfile.html
3:04 PM <•gregdek> We *really* should be encouraging its use.
3:04 PM <•rbergeron> 81 is linking sivel's tool in the packaging guidelines. :)
3:05 PM <gundalow> It's a great tool. What's it got to do with packaging though?
3:05 PM <gundalow> I wonder if it should be referended in CONTRIBUTING/I've found a bug (maybe it's fixed already) type docs
3:05 PM <sivel> maybe packaging guidelines is the wrong word
3:05 PM <sivel> s
3:05 PM <•gregdek> Right. That's part of the problem. Where does it live?
3:05 PM <gundalow> hey sivel :)
3:06 PM <•rbergeron> err
3:06 PM <•rbergeron> packaging?
3:06 PM <•rbergeron> did isay packaging?
3:06 PM <gundalow> hey rbergeron
3:06 PM <•gregdek> It's this great... thing, that is sorta sitting off to the side and useful for many things and not known.
3:06 PM <•gregdek> How do we make it better known?
3:06 PM <•gregdek> And i keep going "well, maybe doesn't belong there, hmm lemme THINK ABOUT IT SOME MORE FOREVER"
3:06 PM <•rbergeron> oh, that's what it says in the issue... gregdek, is this really "packaging"?
3:06 PM <•rbergeron> or just contributing?
3:06 PM <•gregdek> It's a great place for contributors to see All Their Things!
3:07 PM <•gregdek> "Hey, I'm a Foo Maintainer. What things are open against Foo right now?"
3:07 PM <•rbergeron> i guess the question is... do we even have packaging guidelines?
3:07 PM <•gregdek> Module guidelines is what that should say.
New messages
3:07 PM <•gregdek> And now it does.
3:07 PM <gundalow> I think it would be useful to link from
3:07 PM <•gregdek> BUT: I'm not even sure that's where it goes!
3:07 PM <gundalow> 1) http://docs.ansible.com/ansible/community.html#i-d-like-to-report-a-bug - See if there is a PR for the module
3:08 PM <•rbergeron> okay. thank you. (sorry, i just glaze over "packaging guidelines" at this point in my life post-fedora, so used to seeing that set of words together)
3:08 PM <•rbergeron> contributor and maintainer tools?
3:08 PM <gundalow> 2) http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes Before you start coding see if their is a similar fix/update in flight
3:08 PM <•rbergeron> we have talked about having a place to link to other things as well (ansible-lint, etc)
3:08 PM <•rbergeron> useful tools for maintainers, contributors, and users?
3:08 PM <gundalow> 3) #5 what rbergeron just said
3:09 PM <•rbergeron> it is useful and maybe there is a better place for it as part of ... the maintainership life cycle
3:09 PM <•rbergeron> but just having more word about it out there would probably be useful in figuring out ultimately how it fits in :)
3:09 PM <•gregdek> We don't really have a Maintainer FAQ, do we?
3:09 PM <•gregdek> We just have Module Guidelines.
3:09 PM <•rbergeron> not really.
3:10 PM <•gregdek> But not really a "this is what being a Maintainer entails".
3:10 PM <•rbergeron> i mean, having something at least setting out "what you should expect when you are expecting... to be a maintainer"
3:10 PM <•gregdek> So MAYBE...
3:10 PM <•gregdek> ...that's what this PR actually is.
3:10 PM <•rbergeron> seems like it might be helpful or at least set expectations
3:10 PM <•gregdek> And has been all along.
3:10 PM <•gregdek> And sivel's tool goes in it.
3:10 PM <•gregdek> And links to the module guidelines.
3:11 PM <•rbergeron> and might be a useful thing to link to as well in (a) new module template, (b) maybe the first ping back from ansibot after someone submits a pr, (c) "remember this, it's helpful" when the module is actually merged
3:11 PM <•rbergeron> gregdek: this seems like a good idea.
3:11 PM <•gregdek> Yes Yes Yes
3:11 PM <•gregdek> Yes.
3:11 PM <•gregdek> OK, gonna rename this issue and copypasta all of this into it.
3:12 PM <•rbergeron> gregdek: seems like someone making a rough cut or outline and putting it in an issue and then mailing the -devel list to see "what else do maintainers think would be useful to know about" could be a thing.
3:12 PM <•rbergeron> like, i'm sure they have all sorts of stuff.
3:13 PM <•rbergeron> like knowing that amazon modules have their own additional guidelines, stuff like that
3:13 PM <•gregdek> Yep.

**Comment by robynbergeron** [comment]
Also, link amazon guidelines, other magic in here.

**Comment by robynbergeron** [comment]
Also useful to note in such things, maybe: "give your new module PR a clear title, since people may see it in the weekly new module report and if it's a thing that interests them, they may be more inclined to test it if what it's for is super clear"

**Comment by gregdek** [comment]
First draft ETA... soonish. :)

**Comment by alikins** [comment]
The 'by file' page would be super useful to link to in boilerplate comments to prs. The bot can extract the touched files and find the module and maintainers already. Can't tell if there are anchor links available for https://ansible.sivel.net/pr/byfile.html, but if there are, the comment could point to other prs that touch the same files.

(ditto for issuebot, once it has some filename/module/maintainer capabilities...)

**Comment by robynbergeron** [comment]
https://github.com/robynbergeron/thingsandstuff/blob/master/MODULEMAINTAINERS.md

Okay, here's a rough first cut (making sure i'm on the right track here).

**Comment by gregdek** [comment]
Yes. Definitely the right track.

**Comment by gregdek** [comment]
OK, so we now have this:

https://github.com/ansible/ansible-modules-extras/blob/devel/MAINTAINERS.md

And next we should:

* Review REVIEWERS.md in same repo;
* Make sure that we're referring to this new MAINTAINERS file in all the appropriate places (boilerplate maybe?)

**Comment by gregdek** [comment]
Add this somehow: https://github.com/ansible/community/blob/master/PR-FLOW.md

**Comment by robynbergeron** [comment]
https://github.com/alikins/ansible-modules-extras/commit/c87795da5b0c95c67fea1608a5a2a4ec54cb3905 <-- useful / good

**Comment by robynbergeron** [comment]
Okay, I've updated this -- albeit in my repo, before merging it to extras/maintainers.md. 

https://github.com/robynbergeron/thingsandstuff/blob/master/MODULEMAINTAINERS.md

I think I've covered the aforementioned needed updates -- the lone question I have outstanding is whether or not we want to update Contributing.MD with the suggested forked version linked by Adrian in the previous comment (https://github.com/alikins/ansible-modules-extras/commit/c87795da5b0c95c67fea1608a5a2a4ec54cb3905) and simply link to that from Maintainers.md -- or if we want to just merge that part into maintainers.md

IMO: Probably better to merge it into contributors.md -- since we do have lots of PRs for modules from folks who are not maintainers, but still need to adhere to those guidelines in order for their PRs to be merged. But I'm open to suggestions, as always. :)

**Comment by gregdek** [comment]
Next steps:

1. Submit a PR for extras/MODULE-MAINTAINERS.md with @rbergeron latest content
2. Ask @alikins to submit a PR with his changes to extras/CONTRIBUTING.md

**Comment by gregdek** [comment]
To be clear:

1. In general, GUIDELINES.md is the right thing to call it.
2. In general, GUIDELINES.md should have a sort of inheritance. Any directory with directory-specific guidelines should live in that directory's GUIDELINES.md.
3. What Robyn has as the current MODULEMAINTAINERS.md is a good start for the top-level GUIDELINES.md in Extras.

So that's what we'll do. And then we'll get rid of "extras/MAINTAINERS.md".

**Comment by robynbergeron** [comment]
Need to: 

* Add link to Contributing.md in section about "If you'd like to contribute a new module" that points to GUIDELINES.md. 

* Delete maintainers.md.

* Need to update guidelines.md with any new info re: automation of PRs / issues. 

* Adrian's list should probably go into docs? This is the last detail I think.  I just do'nt want to have 45 places where various module guidelines are at.

**Comment by gregdek** [comment]
We'll check in the latest and keep iterating according to your latest.

**Comment by robynbergeron** [comment]
Added to our little hackfest time plan for tomorrow (thurs. 9/8)

**Comment by gregdek** [comment]
I think we're finally done with this one, hooray!
