### ISSUE TITLE
Need a good way to advertise CFPs to the wider community

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#89]
Related to #35.

**Comment by gregdek** [comment]
Thinking this should be a question asked of a particular SIG.

**Comment by robynbergeron** [comment]
I think it can at least be covered by #175 -- but might also be a thing useful to / covered by Ambassadors, or other content / info distribution mechanisms. 

I wonder if just having a simple wiki page of known CFPs (upcoming at the top, past ones towards the bottom so we can remember the following year to maybe go looking for them again) that various groups can pull from might be "good enough" for now, and just make sure one of the WGs has it on their plate to periodically check / update (or validate if it's useful). Because then we could:

* Include those links in a newsletter
* Someone could do a monthly blog post about upcoming CFPs
* Meetups could check the list for upcoming events in their area that they might encourage meetup attendees to submit to (could even be a pre-made / suggested slide for Ambassador decks, with a note to "visit link to find CFPs for events in your area and add them here" that points to the CFP list)

**Comment by gregdek** [comment]
This is a job for ambassadors! https://github.com/ansible/community/issues/168

**Comment by gregdek** [comment]
OK, discussed this week. Here's the gist:

* Have an ambassadors wiki page where we keep the list.
* Have a simple google form that people can fill out.
* Tweet from @ansible on a regular basis, talk to @ansible marketing team for help here.

**Comment by gregdek** [comment]
Here's a perfect test case for cfgmgmtcamp:

https://docs.google.com/forms/d/e/1FAIpQLSfTRTVNqS2uSFYhS-c086vEy6JTQacJVzA29iCsbNdHGZWp5Q/viewform
