### ISSUE TITLE
Create the Testing Working Group

### ISSUE THREAD

**Issue by gregdek** [ansible/community#9]
We need some kind of Testing Working Group and figure out how it works.

**Comment by gregdek** [comment]
So here's how we're going to do working groups:

* Starts as a ticket in community working group
* Ticket contains "here's what we want to do"
* Add yourself by comment if you're interested in joining
* At Some Indeterminate Point, we create the working group as a Waffle Board / Github Repo / whatever
* And we will use the Testing Working Group as the example of this

**Comment by gregdek** [comment]
And I'll kick it off!

**Comment by gregdek** [comment]
gundalow (@bob-smith on github) on irc has offered to participate. Thanks @bob-smith!

**Comment by gundalow** [comment]
IT LIVES https://github.com/ansible/community/issues/114
