### ISSUE TITLE
Standing Agenda, New Modules Meeting

### ISSUE THREAD

**Issue by gregdek** [ansible/community#92]
This is the standing agenda for New Module review.

PLEASE DO NOT ADD YOUR MODULE TO THIS AGENDA YOURSELF. This meeting is only for final review of modules that have already been reviewed by other community members, and only Ansible team members should be adding modules to this list.

**Comment by gregdek** [comment]
extras/1987

**Comment by gregdek** [comment]
extras/1988

**Comment by gregdek** [comment]
extras/1765

**Comment by gregdek** [comment]
extras/1574 -- one shipit

**Comment by ryansb** [comment]
Closing, meeting has finished.

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1690

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1942

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1434

**Comment by chouseknecht** [comment]
docker_network module: ansible/ansible-modules-core#3728

**Comment by Spredzy** [comment]
openssl_privatekey module: https://github.com/ansible/ansible-modules-extras/pull/2326

**Comment by MichaelBaydoun** [comment]
ec2 virtual private gateway module: https://github.com/ansible/ansible-modules-extras/pull/1709 looks ready to merge

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1775

**Comment by gundalow** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2209 looks ready to merge

**Comment by jgrowl** [comment]
I haven't created a proper PR yet, but I made an issue for a docker_machine module that I've worked on:

https://github.com/ansible/ansible/issues/16318

**Comment by gundalow** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1862 looks ready to merge (only one shipit, but it's good)

**Comment by gregdek** [comment]
ansible/ansible-modules-extras#1882

**Comment by gregdek** [comment]
ansible/ansible-modules-extras#1687

**Comment by Spredzy** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2326

**Comment by ryansb** [comment]
https://github.com/ansible/ansible/pull/16606 (a redux of https://github.com/ansible/ansible/pull/16203)

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2442

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2271

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2208

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1901

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1775

**Comment by ryansb** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2558

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/662#issuecomment-225850022

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1765

**Comment by gregdek** [comment]
ansible/ansible-modules-extras#1882

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2381

**Comment by abadger** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2323 Archive module; marked shipit by dagwiers who is the maintianer of the unarchive module.

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2588

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1023

**Comment by tima** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1902

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1730

**Comment by abadger** [comment]
1902 and 1730 reviewed and marked needs_revision in the tickets.  1902 is much closer to being ready than 1730.

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2305

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2329

**Comment by tima** [comment]
A module PR for review, but not a new one....

https://github.com/ansible/ansible-modules-core/pull/4054

**Comment by tima** [comment]
Came across this one that looks ready for core review again...

https://github.com/ansible/ansible-modules-extras/pull/2521

**Comment by tima** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2305

**Comment by ryansb** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2829

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-core/pull/4469

**Comment by gregdek** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2917

**Comment by mikeoutland** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2977
https://github.com/ansible/ansible-modules-extras/pull/2978
https://github.com/ansible/ansible-modules-extras/pull/2979
https://github.com/ansible/ansible-modules-extras/pull/2981
https://github.com/ansible/ansible-modules-extras/pull/2982
https://github.com/ansible/ansible-modules-extras/pull/2983
https://github.com/ansible/ansible-modules-extras/pull/2984
https://github.com/ansible/ansible-modules-extras/pull/2985

**Comment by gregdek** [comment]
@mikeoutland I've removed your last request. The goal of the new modules review meeting is to review those modules that have already received some degree of community review already.

**Comment by sundeep-co-in** [comment]
https://github.com/ansible/ansible-modules-extras/pull/3045

**Comment by grastogi23** [comment]
I have pull request for a new module Avi Vantage. Please review the PR and any feedback community may have on it.
https://github.com/ansible/ansible-modules-extras/pull/2891

**Comment by mikeoutland** [comment]
@gregdek is this a question for me? ^^

**Comment by gregdek** [comment]
@mikeoutland This agenda is intended for final review of modules that have already been vetted by community members. There are occasional exceptions and Ansible team members will ask someone to submit directly, which is what I'm asking, from you or from anyone on the @ansible/core team.

We're not having this meeting for a few weeks anyway because 2.2 is frozen.

**Comment by ryansb** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2917 discussed, some nonblocking comments added.

**Comment by shaharmor** [comment]
There are 2 new modules for AWS:
Application ELB: https://github.com/ansible/ansible-modules-extras/pull/2946
Target group: https://github.com/ansible/ansible-modules-extras/pull/2947

There are more updates to those PRs here as well:
https://github.com/wimnat/ansible-modules-extras/pull/3
https://github.com/wimnat/ansible-modules-extras/pull/4

They are working, but there are a few bugs still (that I have fixed locally).

My question is what is the correct way to go with this in order for them to get merged into ansible?
1. Should i wait for all those PRs to get all their fixes ready
2. Create a new PR myself with all the fixes in other PRs + my fixes instead?

Also, I think the naming of the new modules is not good and suggest to rename them to:
`ec2_elb_application` & `ec2_target_group` instead.

**Comment by Spredzy** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2341

**Comment by wimnat** [comment]
@shaharmor 
> Also, I think the naming of the new modules is not good and suggest to rename them to:
ec2_elb_application & ec2_target_group instead.

I disagree with the above statement.

The module naming should follow boto3 api naming where possible.  ELB API is not part of EC2 hence why they are named differently.  I think the current ELB module ec2_elb_lb should also be renamed.

**Comment by gundalow** [comment]
The New Modules meetings have been rolled into the existing "Public Core Meetings"

Please see https://github.com/ansible/community/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Ameeting_agenda%20 for those agenda tickets

and https://github.com/ansible/community/blob/master/MEETINGS.md for a link to the `.ics` file that you can import by URL to your calendar.
