### ISSUE TITLE
Planning for Contributor Conference SF

### ISSUE THREAD

**Issue by gregdek** [ansible/community#93]
We will be having another Ansiblefest in San Francisco on July 28th. Need to work out details for Contributor Conference on the 27th.

**Comment by gregdek** [comment]
https://public.etherpad-mozilla.org/p/ansible-summit-june-2016

**Comment by gregdek** [comment]
Registration page is up: https://www.eventbrite.com/e/ansible-contributor-conference-tickets-25729111465

**Comment by gregdek** [comment]
Next step: figure out key list of people and give them first right of refusal for attendance in person. At that point we'll advertise the eventbrite page more broadly.

**Comment by gregdek** [comment]
(ETA on this next bit: Friday June 10)

**Comment by gregdek** [comment]
Still not enough votes on the Etherpad, @robynbergeron will send out another update today. On track for disseminating agenda and meeting info next Friday 7/22.

**Comment by gundalow** [comment]
I guess this is a deadline for me adding the stuff from the Google Doc that's our for review.

**Comment by gregdek** [comment]
All done! @gregdek needs to send out the update and videos.

**Comment by gregdek** [comment]
And @gundalow needs to review the etherpad and create issues as needed.
