### ISSUE TITLE
Consider modifying new module approval requirements

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/community#95]
Consider switching away from the two shipits peer review and instead require:
- One passes_guidelines comment, when someone has reviewed the module and confirmed all guidelines where followed
- One worksforme comment, when someone has thoroughly tested the modules functions.

This has been discussed a few times in the new module review meetings.

**Comment by gundalow** [comment]
+1

**Comment by MichaelBaydoun** [comment]
Discussed in core meeting today.
nitzmahone> #accepted - we will use tested_working and meets_guidelines as comment tags
