### ISSUE TITLE
Agenda for New Modules Meeting -- 2016-05-18 @ 18:00 UTC

### ISSUE THREAD

**Issue by ryansb** [ansible/community#96]

**Comment by gundalow** [comment]
In the previous meeting 2016-05-18 we said if there are any PRs that we believe are close to completion we should add a link to them here so they can be helped through the final parts of the process

**Comment by gundalow** [comment]
Ready for merge https://github.com/ansible/ansible-modules-extras/pull/1987

**Comment by gundalow** [comment]
Very close https://github.com/ansible/ansible-modules-extras/pull/1988

**Comment by gundalow** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2208 lxd_container. Need a functional test/2nd shipit

**Comment by gundalow** [comment]
Enforce pep8 for new modules

We have talked about this a little bit before, but I don't believe we formally signed off on it.

Generally (as documented) we don't allow allow ad-hock change that improve pep8 as it breaks git blame.

That isn't an issue for new modules, as their isn't any history to destroy. I'd like to propose that we enforce (I can update ansible-validate-modules for new modules) to require this.

If agreed I'll update the documentation to make this this case clearer

**Comment by gregdek** [comment]
Agenda is done.

**Comment by gundalow** [comment]
It was agreed that new modules would be pep8ish compliant, which is define as

  * ansible/Makefile
  * 160 char limit
  * E402 should be enforced for new modules as stated by @abadger
