### ISSUE TITLE
Clean up https://releases.ansible.com/ansible/

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#98]
Can we clean up the list of releases from https://releases.ansible.com/ansible/ ?

I would move all the release candidates to its own directory, you may want to symlink/hardlink the latest release candidate in the main directory (just to draw the needed attention to an upcoming release).

But there is little need to keep older release candidates in the main directory, since it makes it harder to determine the latest stable releases...

**Comment by gregdek** [comment]
Is the directory structure the right thing to clean up?

I understand the need for something like "here's a list of the latest things" but I wonder if that list of "cleaned up release" belongs someplace else.  I'm supposing there's a whole lot of workflow around this because it's basically just a dumb repository.

**Comment by gregdek** [comment]
(And sorry I haven't commented on this in a year, LOL, sigh)

**Comment by dagwieers** [comment]
Why not have a separate directory for the release candidates ?

I am not arguing to remove official releases from this list, just to not mingle the release candidates with the actual releases.

Another improvement would be to allow for longer names in that index, that would be very helpful to users as well.

**Comment by gregdek** [comment]
@jimi-c can you weigh in here?

**Comment by gregdek** [comment]
@thaumos could you weigh in on this?

**Comment by gregdek** [comment]
My take: it certainly isn't pretty, but it's functional, and people know how it works. Feels like it falls into the "not too broken, 'fixing' could have unexpected effects that end up making work", but I'll defer to @thaumos or someone from the core team.

**Comment by thaumos** [comment]
sure!  our current page is definitely a catch all for sure...  there are things in the background we're doing in support of the Engine product that will ultimately affect this page.  stay tuned

**Comment by gregdek** [comment]
It's your ball now @thaumos -- thanks :)

**Comment by dagwieers** [comment]
Come on guys, it doesn't take a lot of work to improve this.
5 minutes to change the default Apache DirectoryIndex to get a much improved user experience.

Please do at least the following:
- Allow for longer filenames
- Sort by date ?

http://releases.ansible.com/ansible/
![screenshot from 2018-03-07 14-13-13](https://user-images.githubusercontent.com/388198/37094018-b9c2241a-2211-11e8-92cf-04555e935a45.png)

**Comment by gregdek** [comment]
@dagwieers is right about an Apache DirectoryIndex tweak. At least, I hope he is. 

We could at least turn on FancyIndexing.

https://docstore.mik.ua/orelly/linux/apache/ch07_01.htm

http://httpd.apache.org/docs/trunk/mod/mod_autoindex.html#indexoptions

**Comment by ghjm** [comment]
I have turned on FancyIndexing for releases.ansible.com.
